# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sent', 'Message Sent'), ('read', 'Message Read'), ('deleted', 'Message Deleted'), ('disabled_thread', 'Messaging Disabled for Order'), ('enabled_thread', 'Messaging Enabled by Admin'), ('flagged', 'Message Flagged for Review'), ('unblocked', 'Message Unblocked by Admin'), ('resolved_dispute', 'Dispute Resolved'), ('escalated_dispute', 'Dispute Escalated'), ('created_thread', 'Thread Created'), ('updated_thread', 'Thread Updated'), ('deleted_thread', 'Thread Deleted'), ('notification_sent', 'Notification Sent'), ('read_receipt', 'Read Receipt Created'), ('notification_created', 'Notification Created'), ('other', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer'), ('admin', 'Admin'), ('support', 'Support'), ('editor', 'Editor'), ('superadmin', 'Super Admin')], max_length=10)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File Attachment'), ('link', 'Link'), ('image', 'Image'), ('system', 'System Message'), ('video', 'Video'), ('audio', 'Audio'), ('note', 'Internal Note'), ('other', 'Other')], default='text', max_length=20)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('contains_link', models.BooleanField(default=False)),
                ('is_link_approved', models.BooleanField(default=False)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('link_preview_text', models.TextField(blank=True, null=True)),
                ('preview_failed_at', models.DateTimeField(blank=True, null=True)),
                ('link_preview_json', models.JSONField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Message disabled by admin or system.')),
                ('is_archived', models.BooleanField(default=False, help_text='Message archived by user or admin.')),
                ('created_by_admin', models.BooleanField(default=False)),
                ('visible_to_roles', models.JSONField(default=list, help_text='List of roles allowed to see this message.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('system_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_unblocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('client_writer', 'Client ↔ Writer'), ('order', 'Order'), ('internal', 'Internal'), ('special', 'Special Order'), ('dispute', 'Dispute'), ('general', 'General Inquiry'), ('revision', 'Revision Request'), ('feedback', 'Feedback'), ('clarification', 'Clarification'), ('complaint', 'Complaint'), ('request', 'Request'), ('escalation', 'Escalation'), ('announcement', 'Announcement'), ('class_bundle', 'Class Bundle'), ('support', 'Support'), ('account', 'Account'), ('custom', 'Custom'), ('other', 'Other')], default='client_writer', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_role', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer'), ('admin', 'Admin'), ('support', 'Support'), ('editor', 'Editor'), ('superadmin', 'Super Admin')], max_length=50)),
                ('recipient_role', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer'), ('admin', 'Admin'), ('support', 'Support'), ('editor', 'Editor'), ('superadmin', 'Super Admin')], max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('mute', models.BooleanField(default=False, help_text='Mute notifications for this thread.')),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_messaging', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer'), ('admin', 'Admin'), ('support', 'Support'), ('editor', 'Editor'), ('superadmin', 'Super Admin')], max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('category', models.CharField(choices=[('clarification', 'Clarification'), ('complaint', 'Complaint'), ('request', 'Request'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=20)),
                ('resolution_comment', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_reason', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('is_unblocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSocketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
