# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0003_initial'),
        ('orders', '0001_initial'),
        ('special_orders', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communications.communicationmessage'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationnotification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communications.communicationmessage'),
        ),
        migrations.AddField(
            model_name='communicationnotification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationreadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='communications.communicationmessage'),
        ),
        migrations.AddField(
            model_name='communicationreadreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_thread', to='orders.order'),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='participants',
            field=models.ManyToManyField(help_text='Users involved in this thread.', related_name='message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='website',
            field=models.ForeignKey(help_text='Website associated with this order thread.', on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='websites.website'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.communicationthread'),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_message', to='communications.communicationmessage'),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='resolution_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_message', to='communications.communicationmessage'),
        ),
        migrations.AddField(
            model_name='flaggedmessage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communicationmessage'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', through='communications.MessageReadReceipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websocketauditlog',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationthread'),
        ),
        migrations.AddField(
            model_name='websocketauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='communicationreadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationmessage',
            unique_together={('visible_to_roles', 'is_deleted')},
        ),
    ]
