# Generated by Django 5.0.14 on 2025-10-30 10:53

import django.db.models.deletion
import refunds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_payments_management', '0003_alter_paymentrecord_amount'),
        ('orders', '0002_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=10)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('external_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_method', models.CharField(choices=[('wallet', 'Wallet'), ('external', 'External')], default='wallet', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_refunds', to=settings.AUTH_USER_MODEL)),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order_payments_management.orderpayment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_for_client', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount refunded', max_digits=10)),
                ('source', models.CharField(help_text='Origin of the refund (manual, stripe-webhook, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], help_text='Refund status', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Any additional metadata associated with the refund')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the refund action')),
                ('client', models.ForeignKey(help_text='The client who initiated the refund', on_delete=django.db.models.deletion.CASCADE, related_name='refund_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The order related to the refund', on_delete=django.db.models.deletion.CASCADE, related_name='refund_logs', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_processed_logs', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(help_text='The refund associated with this log', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='refunds.refund')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_logs', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='RefundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount refunded', max_digits=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for the refund', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reference_code', models.CharField(blank=True, default=refunds.models.generate_reference_code, max_length=64, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_receipts', to=settings.AUTH_USER_MODEL)),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_receipt', to='order_payments_management.orderpayment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_receipts', to=settings.AUTH_USER_MODEL)),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='refunds.refund')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_receipt', to='websites.website')),
            ],
        ),
    ]
