# Generated by Django 6.0.5 on 2026-05-28 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=120)),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('worker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('retry_count', models.PositiveIntegerField(blank=True, null=True)),
                ('event_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('domain', models.CharField(db_index=True, max_length=60)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('routing_key', models.CharField(db_index=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored'), ('dead_letter', 'Dead Letter')], db_index=True, default='pending', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ignored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'event_type'], name='event_syste_domain_27a386_idx'), models.Index(fields=['status', 'created_at'], name='event_syste_status_8b8aa0_idx'), models.Index(fields=['routing_key'], name='event_syste_routing_fe2163_idx')],
            },
        ),
    ]
