# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(blank=True, db_index=True, help_text='Original AuditEvent ID if available', null=True)),
                ('event_payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_dead_letters', to='websites.website')),
            ],
            options={
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['is_resolved', 'failed_at'], name='audit_loggi_is_reso_3d2c37_idx'), models.Index(fields=['website', 'is_resolved'], name='audit_loggi_website_022d8e_idx'), models.Index(fields=['retry_count', 'max_retries'], name='audit_loggi_retry_c_71e355_idx'), models.Index(fields=['event_id'], name='audit_loggi_event_i_ff50c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('discarded', 'Discarded')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('span_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('is_sensitive', models.BooleanField(db_index=True, default=False)),
                ('sensitivity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('service_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='websites.website')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['website', 'occurred_at'], name='audit_loggi_website_7bf547_idx'), models.Index(fields=['website', 'action'], name='audit_loggi_website_70ca1a_idx'), models.Index(fields=['website', 'actor_id'], name='audit_loggi_website_1ba630_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_loggi_object__ca9625_idx'), models.Index(fields=['correlation_id'], name='audit_loggi_correla_145212_idx'), models.Index(fields=['span_id'], name='audit_loggi_span_id_41ce08_idx'), models.Index(fields=['status', 'processed_at'], name='audit_loggi_status_b5a1fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('website', 'idempotency_key'), name='uniq_audit_event_idempotency_per_website')],
            },
        ),
    ]
