"""
Comprehensive paper type lists for all academic levels.
Based on typical assignments students write from high school to post-graduate.
"""

# ==================== COMPREHENSIVE PAPER TYPES ====================
# All paper types from high school to post-graduate level

COMPREHENSIVE_PAPER_TYPES = [
    # ========== ESSAYS (All Levels) ==========
    'Essay',
    'Argumentative Essay',
    'Persuasive Essay',
    'Expository Essay',
    'Descriptive Essay',
    'Narrative Essay',
    'Compare and Contrast Essay',
    'Cause and Effect Essay',
    'Process Essay',
    'Definition Essay',
    'Classification Essay',
    'Evaluation Essay',
    'Analysis Essay',
    'Critical Essay',
    'Reflective Essay',
    'Personal Essay',
    'Admission Essay',
    'College Application Essay',
    'Scholarship Essay',
    'Graduate School Essay',
    'Statement of Purpose',
    'Personal Statement',
    'Cover Letter',
    'Motivation Letter',
    
    # ========== RESEARCH PAPERS (All Levels) ==========
    'Research Paper',
    'Term Paper',
    'Research Proposal',
    'Research Report',
    'Literature Review',
    'Systematic Review',
    'Meta-Analysis',
    'Annotated Bibliography',
    'Research Summary',
    'Research Abstract',
    
    # ========== THESIS & DISSERTATION (Graduate Level) ==========
    'Thesis',
    'Master\'s Thesis',
    'PhD Thesis',
    'Dissertation',
    'Doctoral Dissertation',
    'Thesis Proposal',
    'Dissertation Proposal',
    'Thesis Chapter',
    'Dissertation Chapter',
    'Thesis Abstract',
    'Dissertation Abstract',
    
    # ========== ACADEMIC PAPERS (All Levels) ==========
    'Academic Paper',
    'Scholarly Paper',
    'Academic Article',
    'Journal Article',
    'Conference Paper',
    'Position Paper',
    'Policy Paper',
    'White Paper',
    'Discussion Paper',
    'Working Paper',
    
    # ========== REPORTS (All Levels) ==========
    'Report',
    'Lab Report',
    'Science Lab Report',
    'Chemistry Lab Report',
    'Biology Lab Report',
    'Physics Lab Report',
    'Engineering Lab Report',
    'Technical Report',
    'Business Report',
    'Case Study Report',
    'Progress Report',
    'Final Report',
    'Project Report',
    'Feasibility Report',
    'Analytical Report',
    'Informational Report',
    'Recommendation Report',
    'Incident Report',
    'Book Report',
    'Book Review',
    'Article Review',
    'Movie Review',
    'Film Review',
    
    # ========== CASE STUDIES (All Levels) ==========
    'Case Study',
    'Business Case Study',
    'Clinical Case Study',
    'Nursing Case Study',
    'Medical Case Study',
    'Legal Case Study',
    'Case Analysis',
    'Case Brief',
    
    # ========== COURSEWORK (All Levels) ==========
    'Coursework',
    'Assignment',
    'Homework',
    'Classwork',
    'Take-Home Exam',
    'Take-Home Test',
    'Online Exam',
    'Online Test',
    'Quiz',
    'Worksheet',
    'Problem Set',
    'Math Problem',
    'Statistics Problem',
    'Physics Problem',
    'Chemistry Problem',
    
    # ========== PRESENTATIONS (All Levels) ==========
    'Presentation',
    'PowerPoint Presentation',
    'Slides',
    'Presentation Slides',
    'Oral Presentation',
    'Poster Presentation',
    'Conference Presentation',
    'Business Presentation',
    'Pitch Deck',
    
    # ========== PROJECTS (All Levels) ==========
    'Project',
    'Capstone Project',
    'Senior Project',
    'Final Project',
    'Group Project',
    'Research Project',
    'Science Project',
    'Engineering Project',
    'Design Project',
    'Portfolio',
    'Project Proposal',
    'Project Plan',
    
    # ========== SPECIALIZED ASSIGNMENTS ==========
    'Article Review',
    'Literature Review',
    'Annotated Bibliography',
    'Summary',
    'Abstract',
    'Synopsis',
    'Outline',
    'Thesis Statement',
    'Research Question',
    'Hypothesis',
    'Methodology',
    'Data Analysis',
    'Statistical Analysis',
    'Qualitative Analysis',
    'Quantitative Analysis',
    
    # ========== BUSINESS & PROFESSIONAL ==========
    'Business Plan',
    'Marketing Plan',
    'Strategic Plan',
    'Business Proposal',
    'Project Proposal',
    'Grant Proposal',
    'Funding Proposal',
    'Business Case',
    'Executive Summary',
    'SWOT Analysis',
    'Market Analysis',
    'Financial Analysis',
    'Cost-Benefit Analysis',
    'Risk Analysis',
    'Feasibility Study',
    'Business Report',
    'Annual Report',
    'Memos',
    'Memo',
    'Business Letter',
    'Email',
    'Press Release',
    'Newsletter',
    
    # ========== NURSING & HEALTHCARE ==========
    'Nursing Care Plan',
    'Patient Care Plan',
    'Nursing Assessment',
    'Nursing Diagnosis',
    'Nursing Intervention',
    'Clinical Case Study',
    'Evidence-Based Practice Paper',
    'Nursing Research Paper',
    'Nursing Reflection',
    'Clinical Reflection',
    'SOAP Note',
    'Progress Note',
    'Discharge Summary',
    'Quality Improvement Project',
    'Patient Education Material',
    
    # ========== LEGAL ==========
    'Legal Brief',
    'Case Brief',
    'Legal Memorandum',
    'Legal Opinion',
    'Contract Analysis',
    'Legal Research Paper',
    'Court Brief',
    'Motion',
    'Legal Argument',
    
    # ========== TECHNICAL & ENGINEERING ==========
    'Technical Writing',
    'Technical Report',
    'Engineering Report',
    'Design Document',
    'System Design',
    'Software Design',
    'Database Design',
    'Architecture Design',
    'Technical Specification',
    'User Manual',
    'Technical Manual',
    'API Documentation',
    'Code Documentation',
    'Programming Assignment',
    'Coding Assignment',
    'Code Review',
    'Algorithm Design',
    'System Analysis',
    'Requirements Analysis',
    'Test Plan',
    'Test Report',
    
    # ========== CREATIVE WRITING ==========
    'Creative Writing',
    'Short Story',
    'Poem',
    'Poetry',
    'Play',
    'Screenplay',
    'Script',
    'Novel Chapter',
    'Fiction',
    'Non-Fiction',
    'Memoir',
    'Autobiography',
    'Biography',
    
    # ========== ONLINE & DISCUSSION ==========
    'Discussion Post',
    'Forum Post',
    'Blog Post',
    'Discussion Board Post',
    'Response Paper',
    'Discussion Response',
    'Peer Review',
    'Online Discussion',
    
    # ========== OTHER ACADEMIC ==========
    'Q&A',
    'Question and Answer',
    'Exam Questions',
    'Study Guide',
    'Study Notes',
    'Lecture Notes',
    'Note Taking',
    'Transcription',
    'Translation',
    'Paraphrasing',
    'Proofreading',
    'Editing',
    'Rewriting',
    
    # ========== HIGH SCHOOL SPECIFIC ==========
    'Book Report',
    'Book Review',
    'Book Summary',
    'Reading Response',
    'Journal Entry',
    'Diary Entry',
    'Letter Writing',
    'Essay Writing',
    'Five Paragraph Essay',
    'Short Answer',
    'Fill in the Blank',
    'Multiple Choice',
    'True/False',
    
    # ========== GRADUATE LEVEL SPECIFIC ==========
    'Comprehensive Exam',
    'Qualifying Exam',
    'Preliminary Exam',
    'Defense Presentation',
    'Thesis Defense',
    'Dissertation Defense',
    'Prospectus',
    'Grant Application',
    'Fellowship Application',
    'Postdoctoral Proposal',
]

