"""
Comprehensive subject lists for all academic levels.
Based on typical offerings from academic writing services.
All subjects categorized as technical (True) or non-technical (False).
"""

# ==================== COMPREHENSIVE SUBJECT LIST ====================
# All subjects from high school to post-graduate level
# Format: (subject_name, is_technical)

COMPREHENSIVE_SUBJECTS = [
    # ========== HUMANITIES ==========
    ('English', False),
    ('English Literature', False),
    ('American Literature', False),
    ('British Literature', False),
    ('World Literature', False),
    ('Comparative Literature', False),
    ('Creative Writing', False),
    ('Poetry', False),
    ('Drama', False),
    ('Shakespeare', False),
    ('History', False),
    ('World History', False),
    ('American History', False),
    ('European History', False),
    ('Ancient History', False),
    ('Medieval History', False),
    ('Modern History', False),
    ('Military History', False),
    ('Art History', False),
    ('Philosophy', False),
    ('Ethics', False),
    ('Logic', False),
    ('Metaphysics', False),
    ('Epistemology', False),
    ('Aesthetics', False),
    ('Religion', False),
    ('Theology', False),
    ('Biblical Studies', False),
    ('Comparative Religion', False),
    ('Art', False),
    ('Fine Arts', False),
    ('Visual Arts', False),
    ('Painting', False),
    ('Sculpture', False),
    ('Photography', False),
    ('Music', False),
    ('Music Theory', False),
    ('Music History', False),
    ('Composition', False),
    ('Theater', False),
    ('Drama Studies', False),
    ('Theater Arts', False),
    ('Film Studies', False),
    ('Cinema Studies', False),
    ('Media Studies', False),
    ('Linguistics', False),
    ('Applied Linguistics', False),
    ('Sociolinguistics', False),
    ('Psycholinguistics', False),
    ('Languages', False),
    ('Spanish', False),
    ('French', False),
    ('German', False),
    ('Italian', False),
    ('Portuguese', False),
    ('Russian', False),
    ('Chinese', False),
    ('Japanese', False),
    ('Korean', False),
    ('Arabic', False),
    ('Latin', False),
    ('Greek', False),
    ('Classical Studies', False),
    
    # ========== SOCIAL SCIENCES ==========
    ('Psychology', False),
    ('Clinical Psychology', False),
    ('Cognitive Psychology', False),
    ('Developmental Psychology', False),
    ('Social Psychology', False),
    ('Experimental Psychology', False),
    ('Forensic Psychology', False),
    ('Educational Psychology', False),
    ('Industrial Psychology', False),
    ('Sociology', False),
    ('Criminology', False),
    ('Anthropology', False),
    ('Cultural Anthropology', False),
    ('Physical Anthropology', False),
    ('Archaeology', False),
    ('Political Science', False),
    ('International Relations', False),
    ('Public Policy', False),
    ('Public Administration', False),
    ('Economics', False),
    ('Microeconomics', False),
    ('Macroeconomics', False),
    ('Econometrics', False),
    ('International Economics', False),
    ('Geography', False),
    ('Human Geography', False),
    ('Physical Geography', False),
    ('Criminal Justice', False),
    ('Law', False),
    ('Constitutional Law', False),
    ('Criminal Law', False),
    ('Civil Law', False),
    ('Business Law', False),
    ('International Law', False),
    ('Environmental Law', False),
    ('Social Work', False),
    ('Urban Studies', False),
    ('Gender Studies', False),
    ('Women\'s Studies', False),
    ('Ethnic Studies', False),
    ('African American Studies', False),
    ('Asian American Studies', False),
    ('Latin American Studies', False),
    ('Middle Eastern Studies', False),
    
    # ========== NATURAL SCIENCES (Technical) ==========
    ('Biology', True),
    ('Molecular Biology', True),
    ('Cell Biology', True),
    ('Genetics', True),
    ('Microbiology', True),
    ('Botany', True),
    ('Zoology', True),
    ('Marine Biology', True),
    ('Ecology', True),
    ('Environmental Biology', True),
    ('Neuroscience', True),
    ('Biochemistry', True),
    ('Biophysics', True),
    ('Chemistry', True),
    ('Organic Chemistry', True),
    ('Inorganic Chemistry', True),
    ('Physical Chemistry', True),
    ('Analytical Chemistry', True),
    ('Biochemistry', True),
    ('Environmental Chemistry', True),
    ('Physics', True),
    ('Classical Mechanics', True),
    ('Quantum Physics', True),
    ('Thermodynamics', True),
    ('Electromagnetism', True),
    ('Optics', True),
    ('Astrophysics', True),
    ('Astronomy', True),
    ('Geology', True),
    ('Geophysics', True),
    ('Paleontology', True),
    ('Meteorology', True),
    ('Oceanography', True),
    ('Atmospheric Science', True),
    ('Earth Science', True),
    ('Environmental Science', True),
    
    # ========== MATHEMATICS & STATISTICS (Technical) ==========
    ('Mathematics', True),
    ('Algebra', True),
    ('Calculus', True),
    ('Differential Equations', True),
    ('Linear Algebra', True),
    ('Discrete Mathematics', True),
    ('Geometry', True),
    ('Trigonometry', True),
    ('Number Theory', True),
    ('Topology', True),
    ('Statistics', True),
    ('Applied Statistics', True),
    ('Biostatistics', True),
    ('Probability', True),
    ('Mathematical Statistics', True),
    ('Actuarial Science', True),
    
    # ========== COMPUTER SCIENCE & IT (Technical) ==========
    ('Computer Science', True),
    ('Information Technology', True),
    ('Information Systems', True),
    ('Software Engineering', True),
    ('Computer Engineering', True),
    ('Programming', True),
    ('Web Development', True),
    ('Frontend Development', True),
    ('Backend Development', True),
    ('Full Stack Development', True),
    ('Mobile Development', True),
    ('iOS Development', True),
    ('Android Development', True),
    ('Game Development', True),
    ('Database Management', True),
    ('Database Design', True),
    ('SQL', True),
    ('Network Administration', True),
    ('Cybersecurity', True),
    ('Information Security', True),
    ('Cloud Computing', True),
    ('DevOps', True),
    ('Data Science', True),
    ('Data Analytics', True),
    ('Big Data', True),
    ('Machine Learning', True),
    ('Artificial Intelligence', True),
    ('Deep Learning', True),
    ('Natural Language Processing', True),
    ('Computer Vision', True),
    ('Blockchain', True),
    ('Cryptography', True),
    ('Operating Systems', True),
    ('Computer Architecture', True),
    ('Algorithms', True),
    ('Data Structures', True),
    
    # ========== ENGINEERING (Technical) ==========
    ('Engineering', True),
    ('Mechanical Engineering', True),
    ('Electrical Engineering', True),
    ('Civil Engineering', True),
    ('Chemical Engineering', True),
    ('Biomedical Engineering', True),
    ('Aerospace Engineering', True),
    ('Aeronautical Engineering', True),
    ('Automotive Engineering', True),
    ('Industrial Engineering', True),
    ('Environmental Engineering', True),
    ('Structural Engineering', True),
    ('Materials Engineering', True),
    ('Nuclear Engineering', True),
    ('Petroleum Engineering', True),
    ('Systems Engineering', True),
    ('Software Engineering', True),
    ('Computer Engineering', True),
    ('Telecommunications Engineering', True),
    ('Marine Engineering', True),
    ('Agricultural Engineering', True),
    
    # ========== HEALTH SCIENCES ==========
    ('Nursing', False),
    ('Nursing Practice', False),
    ('Nursing Theory', False),
    ('Medical-Surgical Nursing', False),
    ('Pediatric Nursing', False),
    ('Maternal-Child Nursing', False),
    ('Psychiatric Nursing', False),
    ('Community Health Nursing', False),
    ('Critical Care Nursing', False),
    ('Emergency Nursing', False),
    ('Oncology Nursing', False),
    ('Geriatric Nursing', False),
    ('Public Health', False),
    ('Epidemiology', False),
    ('Health Administration', False),
    ('Health Policy', False),
    ('Health Promotion', False),
    ('Health Education', False),
    ('Global Health', False),
    ('Medicine', True),
    ('Internal Medicine', True),
    ('Surgery', True),
    ('Pediatrics', True),
    ('Psychiatry', True),
    ('Cardiology', True),
    ('Oncology', True),
    ('Neurology', True),
    ('Dermatology', True),
    ('Orthopedics', True),
    ('Radiology', True),
    ('Pathology', True),
    ('Pharmacology', True),
    ('Pharmacy', True),
    ('Pharmaceutical Sciences', True),
    ('Physical Therapy', False),
    ('Occupational Therapy', False),
    ('Speech Therapy', False),
    ('Respiratory Therapy', False),
    ('Nutrition', False),
    ('Dietetics', False),
    ('Food Science', False),
    ('Kinesiology', False),
    ('Exercise Science', False),
    ('Sports Medicine', False),
    ('Athletic Training', False),
    ('Veterinary Medicine', True),
    ('Veterinary Science', True),
    ('Dentistry', True),
    ('Dental Hygiene', False),
    ('Optometry', True),
    ('Audiology', False),
    ('Medical Laboratory Science', True),
    ('Biomedical Science', True),
    ('Health Informatics', True),
    
    # ========== BUSINESS ==========
    ('Business', False),
    ('Business Administration', False),
    ('Management', False),
    ('Strategic Management', False),
    ('Operations Management', False),
    ('Project Management', False),
    ('Supply Chain Management', False),
    ('Quality Management', False),
    ('Change Management', False),
    ('Marketing', False),
    ('Digital Marketing', False),
    ('Marketing Communications', False),
    ('Brand Management', False),
    ('Advertising', False),
    ('Public Relations', False),
    ('Finance', False),
    ('Corporate Finance', False),
    ('Investment Banking', False),
    ('Financial Planning', False),
    ('Risk Management', False),
    ('Accounting', False),
    ('Financial Accounting', False),
    ('Managerial Accounting', False),
    ('Auditing', False),
    ('Taxation', False),
    ('Entrepreneurship', False),
    ('Small Business Management', False),
    ('Human Resources', False),
    ('Organizational Behavior', False),
    ('Leadership', False),
    ('International Business', False),
    ('Global Business', False),
    ('Real Estate', False),
    ('Hospitality Management', False),
    ('Hotel Management', False),
    ('Restaurant Management', False),
    ('Tourism', False),
    ('Event Management', False),
    ('Sports Management', False),
    ('Retail Management', False),
    
    # ========== EDUCATION ==========
    ('Education', False),
    ('Teaching', False),
    ('Curriculum Development', False),
    ('Instructional Design', False),
    ('Educational Technology', False),
    ('E-Learning', False),
    ('Special Education', False),
    ('Early Childhood Education', False),
    ('Elementary Education', False),
    ('Secondary Education', False),
    ('Higher Education', False),
    ('Adult Education', False),
    ('Educational Leadership', False),
    ('Educational Administration', False),
    ('Educational Psychology', False),
    ('Learning Sciences', False),
    
    # ========== COMMUNICATIONS ==========
    ('Communications', False),
    ('Mass Communications', False),
    ('Journalism', False),
    ('Broadcast Journalism', False),
    ('Digital Journalism', False),
    ('Public Relations', False),
    ('Corporate Communications', False),
    ('Media Studies', False),
    ('Digital Media', False),
    ('Social Media', False),
    ('Broadcasting', False),
    ('Radio', False),
    ('Television', False),
    ('Film Production', False),
    ('Video Production', False),
    
    # ========== AVIATION & TRANSPORTATION ==========
    ('Aviation', False),
    ('Aeronautics', True),
    ('Aerospace', True),
    ('Air Traffic Control', False),
    ('Aviation Management', False),
    ('Pilot Training', False),
    ('Aircraft Maintenance', True),
    ('Maritime Studies', False),
    ('Marine Science', True),
    ('Maritime Law', False),
    ('Transportation', False),
    ('Logistics', False),
    ('Supply Chain', False),
    
    # ========== ARCHITECTURE & DESIGN ==========
    ('Architecture', False),
    ('Urban Planning', False),
    ('Landscape Architecture', False),
    ('Interior Design', False),
    ('Graphic Design', False),
    ('Web Design', False),
    ('Industrial Design', False),
    ('Fashion Design', False),
    
    # ========== AGRICULTURE & ENVIRONMENT ==========
    ('Agriculture', False),
    ('Agricultural Science', True),
    ('Agronomy', True),
    ('Animal Science', True),
    ('Plant Science', True),
    ('Forestry', False),
    ('Environmental Studies', False),
    ('Environmental Science', True),
    ('Sustainability', False),
    ('Renewable Energy', True),
    ('Climate Science', True),
    ('Conservation', False),
    
    # ========== MILITARY & SECURITY ==========
    ('Military Science', False),
    ('Security Studies', False),
    ('Homeland Security', False),
    ('Intelligence Studies', False),
    ('Criminal Justice', False),
    ('Forensics', True),
    ('Criminal Investigation', False),
    
    # ========== OTHER PROFESSIONAL ==========
    ('Library Science', False),
    ('Information Science', False),
    ('Museum Studies', False),
    ('Sports Science', False),
    ('Recreation Management', False),
    ('Theology', False),
    ('Divinity', False),
]

