# Generated by Django 6.0.5 on 2026-05-28 08:40

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_authors', '0001_initial'),
        ('cms_core', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary for listings and social sharing (max 300 chars)', max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('list', 11), ('quote', 13), ('callout', 15), ('faq', 18), ('cta', 22), ('internal_link', 26), ('attachment', 31), ('divider', 32), ('video', 34), ('sources', 39), ('related_posts', 43), ('code', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('cms_core.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Required for accessibility and SEO (max 125 chars)', 'max_length': 125, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bulleted', 'Bulleted'), ('numbered', 'Numbered')]}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.ListBlock', (9,), {'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('style', 8), ('items', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 13: ('wagtail.blocks.StructBlock', [[('text', 12), ('attribution', 6)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning'), ('important', 'Important')]}), 15: ('wagtail.blocks.StructBlock', [[('style', 14), ('text', 9)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 500}), 17: ('wagtail.blocks.RichTextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('question', 16), ('answer', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 20: ('wagtail.blocks.URLBlock', (), {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 22: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('style', 21)]], {}), 23: ('wagtail.blocks.PageChooserBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': "Override the page's title for this link", 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('page', 23), ('custom_title', 24), ('custom_description', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms_attachments.Attachment',), {}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('card', 'Card with preview'), ('list', 'Compact list item'), ('hero', 'Large hero card'), ('button', 'Simple download button')]}), 29: ('wagtail.blocks.CharBlock', (), {'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Download Now', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('attachment', 27), ('display_style', 28), ('custom_title', 29), ('custom_cta_text', 30)]], {}), 32: ('cms_core.blocks.DividerBlock', (), {}), 33: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo URL'}), 34: ('wagtail.blocks.StructBlock', [[('url', 33), ('caption', 6)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Articles Consulted', 'max_length': 100}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 16), ('url', 20), ('author', 6), ('publication', 6), ('year', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'max_num': 30, 'min_num': 1}), 39: ('wagtail.blocks.StructBlock', [[('heading', 35), ('sources', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'default': 'Related Articles', 'max_length': 100}), 41: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cms_blog.BlogPostPage']}), 42: ('wagtail.blocks.ListBlock', (41,), {'max_num': 5}), 43: ('wagtail.blocks.StructBlock', [[('heading', 40), ('posts', 42)]], {}), 44: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('apa', 'APA Citation Sample')]}), 45: ('wagtail.blocks.TextBlock', (), {}), 46: ('wagtail.blocks.StructBlock', [[('language', 44), ('code', 45), ('caption', 6)]], {})})),
                ('citation_mode', models.CharField(choices=[('sources_list', 'Simple sources list (default)'), ('formal_apa7', 'Formal citations — APA 7'), ('formal_mla9', 'Formal citations — MLA 9'), ('formal_chicago', 'Formal citations — Chicago'), ('none', 'No sources / references')], default='sources_list', help_text='How references are displayed at the bottom of the post', max_length=20)),
                ('last_substantive_update', models.DateTimeField(blank=True, help_text='Updated only when content substance changes, not metadata. Drives Schema.org dateModified and freshness alerts.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='cms_core.blogcategory')),
                ('contributing_authors', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributed_posts', to='cms_authors.author')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Primary image for listings, social sharing, and Schema.org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('primary_author', models.ForeignKey(help_text='Required. The named, credentialed author of this post.', on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='cms_authors.author')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='blog_posts', to='cms_core.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
            bases=('wagtailcore.page',),
        ),
    ]
