# Generated by Django 5.2.2 on 2026-06-09 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_authors', '0001_initial'),
        ('cms_blog', '0003_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Expert who reviewed this post for accuracy — shown in editorial transparency section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to='cms_authors.author'),
        ),
    ]
