# Generated by Django 5.2.2 on 2026-06-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0004_add_reviewer_to_blogpostpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='original_published_at',
            field=models.DateTimeField(blank=True, help_text="Fill this in ONLY when migrating content from another site. Overrides Wagtail's first_published_at for display and Schema.org. Leave blank for new content — Wagtail sets the date automatically.", null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='original_source_url',
            field=models.URLField(blank=True, help_text='The canonical URL of this article on the source site (for records only — not displayed publicly).', max_length=500),
        ),
    ]
