# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_audit_events_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_audit_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_profiles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='account_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.accountprofile'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='account_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.accountprofile'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_account_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='accountstatushistory',
            name='account_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.accountprofile'),
        ),
        migrations.AddField(
            model_name='accountstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_account_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountstatushistory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_status_history', to='websites.website'),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='account_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to='accounts.accountprofile'),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='portalaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_portal_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalaccess',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='accounts.portaldefinition'),
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_definitions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to='accounts.roledefinition'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_roles', to='accounts.roledefinition'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permissiondefinition'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.roledefinition'),
        ),
        migrations.AddField(
            model_name='tenantaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_tenant_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantaccess',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='websites.website'),
        ),
        migrations.AddConstraint(
            model_name='accountprofile',
            constraint=models.UniqueConstraint(fields=('website', 'user'), name='unique_account_profile_per_website_user'),
        ),
        migrations.AlterUniqueTogether(
            name='portalaccess',
            unique_together={('user', 'portal')},
        ),
        migrations.AddConstraint(
            model_name='roledefinition',
            constraint=models.UniqueConstraint(fields=('website', 'key'), name='unique_role_definition_per_website_key'),
        ),
        migrations.AddConstraint(
            model_name='accountrole',
            constraint=models.UniqueConstraint(fields=('account_profile', 'role'), name='unique_role_per_account_profile'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantaccess',
            unique_together={('user', 'website')},
        ),
    ]
