# Generated by Django 5.2.2 on 2026-06-03 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('websites', '0005_payment_disclosure_acknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, default='', help_text='e.g. facebook, google, newsletter, organic', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', help_text='e.g. cpc, email, social, referral', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, default='', help_text='e.g. spring_sale_2026, nursing_essay_fb', max_length=255)),
                ('utm_content', models.CharField(blank=True, default='', help_text='e.g. banner_v2, cta_button_blue', max_length=255)),
                ('utm_term', models.CharField(blank=True, default='', help_text='Paid keyword, e.g. nursing essay help', max_length=255)),
                ('referrer', models.TextField(blank=True, default='', help_text='HTTP Referer header on the first tracked page load.')),
                ('landing_page', models.TextField(blank=True, default='', help_text='Full URL (path + query) of the first page the user visited.')),
                ('channel', models.CharField(blank=True, default='', help_text='Human-readable channel: organic_search, paid_social, email, direct, referral…', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_acquisitions', to='websites.website')),
            ],
            options={
                'verbose_name': 'User Acquisition',
                'indexes': [models.Index(fields=['website', 'utm_source'], name='accounts_us_website_b4287c_idx'), models.Index(fields=['website', 'channel'], name='accounts_us_website_c02e47_idx'), models.Index(fields=['created_at'], name='accounts_us_created_9e6236_idx')],
            },
        ),
    ]
