# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReferralInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_email', models.EmailField(help_text="Email address of the person being referred (they don't have an account yet).", max_length=254)),
                ('referral_code', models.CharField(help_text='Referral code to be used when they sign up.', max_length=50)),
                ('referral_link', models.URLField(help_text='Full referral link sent to the referee.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False, help_text='True when the invitation has been converted to a Referral (user signed up).')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, help_text='Unique referral code used by the referee.', max_length=50, null=True)),
                ('referral_source', models.CharField(blank=True, help_text='Optional: how the referral came in (manual, auto, promo code, etc)', max_length=30, null=True)),
                ('referrer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('referee_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_awarded', models.BooleanField(default=False)),
                ('registration_bonus_credited', models.BooleanField(default=False)),
                ('first_order_bonus_credited', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False, help_text='Whether this referral has been flagged for abuse.')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason for flagging this referral.', null=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Whether this referral has been voided due to abuse.')),
                ('voided_at', models.DateTimeField(blank=True, help_text='When this referral was voided.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralAbuseFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abuse_type', models.CharField(choices=[('self_referral', 'Self Referral'), ('multiple_accounts', 'Multiple Accounts'), ('suspicious_ip', 'Suspicious IP Pattern'), ('rapid_referrals', 'Rapid Referrals'), ('fake_accounts', 'Fake Accounts'), ('other', 'Other')], help_text='Type of suspected abuse.', max_length=30)),
                ('reason', models.TextField(help_text='Detailed reason for flagging this referral.')),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When this abuse was detected.')),
                ('detected_by', models.CharField(default='system', help_text='Who/what detected this (system, admin username, etc).', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='pending', help_text='Current status of this abuse flag.', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this flag was reviewed.', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer.', null=True)),
                ('action_taken', models.TextField(blank=True, help_text='Action taken (e.g., referral voided, bonus revoked).', null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_bonus', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus amount when a referee places their first order.', max_digits=10)),
                ('award_wallet_bonus', models.BooleanField(default=True, help_text="Credit the referrer's wallet when a referral qualifies.")),
                ('award_loyalty_points', models.BooleanField(default=True, help_text='Award loyalty points when a referral qualifies.')),
                ('referrer_loyalty_points', models.PositiveIntegerField(default=0, help_text='Loyalty points awarded to the referrer. If 0, points are derived from the wallet bonus amount.')),
                ('referee_loyalty_points', models.PositiveIntegerField(default=0, help_text='Optional loyalty points awarded to the referred client.')),
                ('qualifying_order_status', models.CharField(default='approved', help_text='Order milestone that qualifies the referral reward.', max_length=32)),
                ('first_order_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='fixed', max_length=10)),
                ('first_order_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_expiry_days', models.IntegerField(default=30)),
                ('max_referrals_per_month', models.PositiveIntegerField(default=10, help_text='Max number of referrals a user can make in a month.')),
                ('max_referral_bonus_per_month', models.DecimalField(decimal_places=2, default=100.0, help_text='Max referral bonus a user can earn in a month.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralBonusDecay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decay_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Decay percentage per month.', max_digits=5)),
                ('decay_start_at', models.DateTimeField(help_text='When the decay starts applying.')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralBonusUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique referral code.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('successful_referrals', models.PositiveIntegerField(default=0)),
                ('referral_bonus_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_referral_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
