# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreferralinvitation',
            name='referrer',
            field=models.ForeignKey(help_text='The user who sent the referral invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_referral_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingreferralinvitation',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_referral_invitations', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(help_text='User who was referred.', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(help_text='The user who made the referral.', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='voided_by',
            field=models.ForeignKey(blank=True, help_text='Admin who voided this referral.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralabuseflag',
            name='referral',
            field=models.ForeignKey(help_text='The referral that was flagged.', on_delete=django.db.models.deletion.CASCADE, related_name='abuse_flags', to='referrals.referral'),
        ),
        migrations.AddField(
            model_name='referralabuseflag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/superadmin who reviewed this flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_abuse_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralbonusconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
    ]
