# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReferralInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_email', models.EmailField(help_text="Email address of the person being referred (they don't have an account yet).", max_length=254)),
                ('referral_code', models.CharField(help_text='Referral code to be used when they sign up.', max_length=50)),
                ('referral_link', models.URLField(help_text='Full referral link sent to the referee.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False, help_text='True when the invitation has been converted to a Referral (user signed up).')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.ForeignKey(help_text='The user who sent the referral invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_referral_invitations', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_referral_invitations', to='websites.website')),
            ],
            options={
                'indexes': [models.Index(fields=['referee_email', 'website'], name='referrals_p_referee_4b3ef8_idx'), models.Index(fields=['referral_code'], name='referrals_p_referra_b620e0_idx')],
                'unique_together': {('referrer', 'referee_email', 'website')},
            },
        ),
    ]
