# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('payments_processor', '0003_initial'),
        ('referrals', '0002_initial'),
        ('wallets', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralbonusdecay',
            name='wallet_transaction',
            field=models.OneToOneField(help_text='The wallet transaction associated with the bonus.', on_delete=django.db.models.deletion.CASCADE, related_name='decay', to='wallets.walletentry'),
        ),
        migrations.AddField(
            model_name='referralbonusdecay',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_decay', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments_processor.paymentintent'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_usage', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this referral code.', on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralstats',
            name='user',
            field=models.OneToOneField(help_text='The user whose referral stats are tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='referral_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pendingreferralinvitation',
            index=models.Index(fields=['referee_email', 'website'], name='referrals_p_referee_4b3ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingreferralinvitation',
            index=models.Index(fields=['referral_code'], name='referrals_p_referra_b620e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pendingreferralinvitation',
            unique_together={('referrer', 'referee_email', 'website')},
        ),
        migrations.AddIndex(
            model_name='referralabuseflag',
            index=models.Index(fields=['status', 'abuse_type'], name='referrals_r_status_36f2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='referralabuseflag',
            index=models.Index(fields=['referral'], name='referrals_r_referra_2c0974_idx'),
        ),
    ]
