# Generated by Django 5.0.14 on 2025-11-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_add_abuse_detection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralabuseflag',
            new_name='referrals_r_status_36f2aa_idx',
            old_name='referrals_r_status_abuse_idx',
        ),
        migrations.RenameIndex(
            model_name='referralabuseflag',
            new_name='referrals_r_referra_2c0974_idx',
            old_name='referrals_r_referra_idx',
        ),
    ]
