# Generated by Django 5.2.2 on 2026-06-01 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='helparticle',
            new_name='legal_pages_website_fc63a0_idx',
            old_name='help_article_site_pub_aud_idx',
        ),
        migrations.RenameIndex(
            model_name='helparticle',
            new_name='legal_pages_website_0c5718_idx',
            old_name='help_article_site_cat_order_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='legal_pages_website_6708ec_idx',
            old_name='legal_doc_website_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='legal_pages_website_5dbe89_idx',
            old_name='legal_doc_website_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='useragreement',
            new_name='legal_pages_user_id_feef4b_idx',
            old_name='legal_agreement_user_date_idx',
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='content',
            field=models.TextField(help_text='Full HTML content of the article. Use headings (h2/h3), paragraphs, ordered/unordered lists, and <strong>/<em> for emphasis.'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured articles appear on the help center home page.'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='summary',
            field=models.CharField(blank=True, help_text='One-line summary shown in category listings.', max_length=300),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Lucide icon name (e.g. 'book-open', 'credit-card', 'users').", max_length=50),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='content',
            field=models.TextField(help_text='Full HTML content of the document. Use the rich editor or paste HTML directly.'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date from which this version is in effect.'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Only one version per document type may be active. Activating this version automatically deactivates the previous one.'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='requires_re_acceptance',
            field=models.BooleanField(default=False, help_text='When True, existing users are prompted to re-accept this version on their next login.'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='version',
            field=models.CharField(default='1.0', help_text='Version label shown to users (e.g. 1.0, 2.1).', max_length=20),
        ),
    ]
