# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('retained', 'Retained'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('purged', 'Purged')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('retained_until', models.DateTimeField(blank=True, help_text='When the retained-deleted window ends.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, help_text='When data was permanently purged.', null=True)),
                ('undo_token_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('undo_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False, help_text='Whether account is currently suspended')),
                ('suspension_type', models.CharField(choices=[('user_initiated', 'User Initiated'), ('admin', 'Admin'), ('security', 'Security')], default='user_initiated', max_length=30)),
                ('suspension_reason', models.TextField(blank=True, help_text='Reason for suspension (user-provided)')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When account was suspended', null=True)),
                ('scheduled_reactivation_at', models.DateTimeField(blank=True, help_text='Scheduled reactivation date (optional)', null=True)),
                ('reactivated_at', models.DateTimeField(blank=True, help_text='When account was reactivated', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('email_verified', 'Email Verified'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_reset', 'MFA Reset'), ('mfa_verified', 'MFA Verified'), ('mfa_challenge_requested', 'MFA Challenge Requested'), ('mfa_challenge_verified', 'MFA Challenge Verified'), ('mfa_challenge_failed', 'MFA Challenge Failed'), ('mfa_recovery_requested', 'MFA Recovery Requested'), ('mfa_recovery_completed', 'MFA Recovery Completed'), ('magic_link_requested', 'Magic Link Requested'), ('magic_link_used', 'Magic Link Used'), ('account_updated', 'Account Updated'), ('account_locked', 'Account Locked'), ('qr_code_generated', 'QR Code Generated'), ('qr_code_scanned', 'QR Code Scanned'), ('device_deleted', 'Device Deleted'), ('session_revoked', 'Session Revoked'), ('suspicious_login', 'Suspicious Login')], max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auth Security Event',
                'verbose_name_plural': 'Auth Security Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the backup code.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the code was used.', null=True)),
            ],
            options={
                'verbose_name': 'Backup Code',
                'verbose_name_plural': 'Backup Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Blocked IP address.')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the IP was blocked.')),
                ('blocked_until', models.DateTimeField(help_text='Timestamp until which the IP remains blocked.')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_until'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(help_text='Hash of the device fingerprint, such as one generated by a browser fingerprinting library.', max_length=255)),
                ('user_agent', models.TextField(help_text='Full user agent string for the client device.')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address associated with this fingerprint.', null=True)),
                ('is_trusted', models.BooleanField(default=False, help_text='Whether this fingerprint is currently trusted.')),
                ('trust_score', models.FloatField(default=0.0, help_text='Computed trust score for this fingerprint.')),
                ('device_name', models.TextField(help_text='The name of device being fingerprinted.', null=True)),
                ('login_count', models.PositiveIntegerField(default=0, help_text='Number of successful logins associated with this fingerprint.')),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this fingerprint was last observed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this fingerprint was first recorded.')),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_email', models.EmailField(help_text='Current email address', max_length=254)),
                ('new_email', models.EmailField(help_text='New email address to change to', max_length=254)),
                ('new_email_token_hash', models.CharField(help_text='Token for verifying new email', max_length=255, unique=True)),
                ('old_email_token_hash', models.CharField(blank=True, help_text='Token for confirming old email', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admin_approved', 'Admin Approved'), ('old_email_confirmed', 'Old Email Confirmed'), ('new_email_verified', 'New Email Verified'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the email change request', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When admin approved the email change', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When change was requested')),
                ('expires_at', models.DateTimeField(help_text='When this request expires')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When email change was completed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the failed login attempt occurred.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the failed login occurred.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent associated with the failed login attempt.', null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('asn', models.CharField(blank=True, help_text='Autonomous System Number, if available.', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Failed Login Attempt',
                'verbose_name_plural': 'Failed Login Attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Started'), ('ended', 'Ended')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reason_type', models.CharField(choices=[('support', 'Customer Support'), ('debug', 'Debugging'), ('fraud', 'Fraud Investigation')], max_length=32)),
                ('reason_details', models.TextField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpersonationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the raw impersonation token.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the impersonation token was used.', null=True)),
            ],
            options={
                'verbose_name': 'Impersonation Token',
                'verbose_name_plural': 'Impersonation Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Whitelisted IP address')),
                ('label', models.CharField(blank=True, help_text="User-friendly label (e.g., 'Home', 'Office')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this IP was whitelisted')),
                ('last_used', models.DateTimeField(blank=True, help_text='When this IP was last used for login', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this whitelist entry is active')),
            ],
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Hashed session token.', max_length=255, unique=True)),
                ('session_type', models.CharField(choices=[('password', 'Password Login'), ('magic_link', 'Magic Link'), ('mfa', 'MFA'), ('impersonation', 'Impersonation')], default='password', help_text='How this session was authenticated.', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, help_text='Associated device fingerprint hash, if available.', max_length=255, null=True)),
                ('logged_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Absolute expiry for this login session.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the raw magic-link token.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the magic link was created.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the magic link becomes invalid.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the magic link was used.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the magic link was requested.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent from which the magic link was requested.', null=True)),
            ],
            options={
                'verbose_name': 'Magic Link',
                'verbose_name_plural': 'Magic Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('totp', 'Authenticator App'), ('email', 'Email OTP'), ('sms', 'SMS OTP')], help_text='MFA method used by this device.', max_length=32)),
                ('name', models.CharField(help_text='User-friendly label for the MFA device.', max_length=100)),
                ('secret', models.CharField(blank=True, help_text='Secret associated with the MFA device. For TOTP, this is the shared secret used to generate codes.', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for SMS-based MFA, if applicable.', max_length=32)),
                ('email', models.EmailField(blank=True, help_text='Email used for email-based MFA, if applicable.', max_length=254)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the user's primary MFA device.")),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this MFA device has been verified.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this MFA device is currently active.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp when this device was last used.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MFA Device',
                'verbose_name_plural': 'MFA Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether MFA is enabled for this user.')),
                ('is_required', models.BooleanField(default=False, help_text='Whether MFA is mandatory for this user.')),
                ('preferred_method', models.CharField(blank=True, choices=[('totp', 'Authenticator App'), ('email', 'Email Verification'), ('sms', 'SMS Verification')], help_text='Preferred MFA method for the user.', max_length=32, null=True)),
                ('allow_totp', models.BooleanField(default=True, help_text='Whether TOTP authenticator apps are allowed.')),
                ('allow_email', models.BooleanField(default=True, help_text='Whether email-based MFA is allowed.')),
                ('allow_sms', models.BooleanField(default=False, help_text='Whether SMS-based MFA is allowed.')),
                ('remember_device_days', models.PositiveIntegerField(default=30, help_text='Number of days to remember trusted devices.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MFA Settings',
                'verbose_name_plural': 'MFA Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('account_unlock', 'Account Unlock'), ('other', 'Other')], max_length=50)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordBreachCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash_prefix', models.CharField(help_text='First 5 characters of SHA-1 hash (for HIBP API)', max_length=5)),
                ('is_breached', models.BooleanField(default=False, help_text='Whether password was found in breach database')),
                ('breach_count', models.IntegerField(default=0, help_text='Number of times password appeared in breaches')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='When the check was performed')),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warned', 'User Warned'), ('forced_change', 'Password Change Forced')], default='none', help_text='Action taken based on breach check', max_length=50)),
            ],
            options={
                'verbose_name': 'Password Breach Check',
                'verbose_name_plural': 'Password Breach Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordExpirationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the password was last changed')),
                ('expires_in_days', models.IntegerField(default=90, help_text='Number of days before password expires')),
                ('warning_days_before', models.IntegerField(default=7, help_text='Days before expiration to show warning')),
                ('is_exempt', models.BooleanField(default=False, help_text='If True, password never expires')),
                ('last_warning_sent', models.DateTimeField(blank=True, help_text='When the last expiration warning was sent', null=True)),
            ],
            options={
                'verbose_name': 'Password Expiration Policy',
                'verbose_name_plural': 'Password Expiration Policies',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='Hashed password (stored securely)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this password was set')),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, help_text='SHA-256 hash of the raw reset token.', max_length=255, null=True, unique=True)),
                ('otp_hash', models.CharField(blank=True, help_text='SHA-256 hash of the raw OTP code.', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reset request was created.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the reset request becomes invalid.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the reset request was used.', null=True)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number to verify (E.164 format)', max_length=20)),
                ('code_hash', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether phone number is verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When phone was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When verification was initiated')),
                ('expires_at', models.DateTimeField(help_text='When verification code expires')),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum verification attempts allowed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationConfirmationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Hashed registration token.', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Hashed token value.', max_length=255, unique=True)),
                ('purpose', models.CharField(choices=[('api_key', 'API Key'), ('refresh_token', 'Refresh Token'), ('unlock_account', 'Unlock Account'), ('other', 'Other')], help_text='Purpose of the token.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_verified', '2FA Verified'), ('magic_link_used', 'Magic Link Used'), ('device_trusted', 'Device Trusted'), ('device_revoked', 'Device Revoked'), ('session_created', 'Session Created'), ('session_revoked', 'Session Revoked'), ('suspicious_activity', 'Suspicious Activity'), ('suspicious_session_reported', 'Suspicious Session Reported'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('profile_updated', 'Profile Updated'), ('privacy_settings_changed', 'Privacy Settings Changed')], help_text='Type of security event.', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Severity of the event.', max_length=10)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Whether this event is suspicious.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the event.', null=True)),
                ('location', models.CharField(blank=True, help_text='Geographic location summary.', max_length=255, null=True)),
                ('device', models.CharField(blank=True, help_text='Device information.', max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event occurred.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata.')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='The security question text.', max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Question',
                'verbose_name_plural': 'Security Questions',
                'ordering': ['question_text'],
            },
        ),
        migrations.CreateModel(
            name='SessionLimitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=3, help_text='Maximum number of concurrent active sessions.')),
                ('allow_unlimited_trusted', models.BooleanField(default=False, help_text='Allow unlimited sessions from trusted devices.')),
                ('revoke_oldest_on_limit', models.BooleanField(default=True, help_text='Revoke the oldest active session when the limit is reached.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Limit Policy',
                'verbose_name_plural': 'Session Limit Policies',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='Hashed token for the trusted device.', max_length=255, unique=True)),
                ('device_info', models.TextField(help_text='Device user-agent or metadata for tracking.')),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Expiration time for trusted device.')),
            ],
        ),
        migrations.CreateModel(
            name='UserIPWhitelistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether IP whitelist is enabled for this user')),
                ('allow_emergency_bypass', models.BooleanField(default=True, help_text='Allow emergency bypass via email verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_hash', models.CharField(help_text='Hashed normalized answer.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active.')),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts.')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last successful verification time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Security Question',
                'verbose_name_plural': 'User Security Questions',
            },
        ),
    ]
