# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='accountsuspension',
            name='user',
            field=models.ForeignKey(help_text='User whose account is suspended', on_delete=django.db.models.deletion.CASCADE, related_name='account_suspension', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountsuspension',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='account_suspensions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='accountunlockrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_unlock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountunlockrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_unlock_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='authsecurityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authsecurityevent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_security_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='backupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backupcode',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ips', to='websites.website'),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to='websites.website'),
        ),
        migrations.AddField(
            model_name='emailchangerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the email change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_email_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailchangerequest',
            name='user',
            field=models.ForeignKey(help_text='User requesting email change', on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailchangerequest',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='failedloginattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='failedloginattempt',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_login_attempts', to='websites.website'),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_logs_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_logs_as_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='impersonationtoken',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_impersonation_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationtoken',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_impersonation_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationtoken',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_tokens', to='websites.website'),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='authentication.impersonationtoken'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='user',
            field=models.ForeignKey(help_text='User who owns this whitelist entry', on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist_entries', to='websites.website'),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='magiclink',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Optional actor who generated the magic link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_magic_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='magiclink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='magiclink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='websites.website'),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to='websites.website'),
        ),
        migrations.AddField(
            model_name='mfasettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfasettings',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='passwordbreachcheck',
            name='user',
            field=models.ForeignKey(help_text='User whose password was checked', on_delete=django.db.models.deletion.CASCADE, related_name='password_breach_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordbreachcheck',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='password_breach_checks', to='websites.website'),
        ),
        migrations.AddField(
            model_name='passwordexpirationpolicy',
            name='user',
            field=models.ForeignKey(help_text='User whose password expiration is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='password_expiration_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordexpirationpolicy',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='password_expiration_policies', to='websites.website'),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(help_text='User whose password history is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='website',
            field=models.ForeignKey(help_text='Website context for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='password_histories', to='websites.website'),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='user',
            field=models.ForeignKey(help_text='User whose phone is being verified', on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='registrationconfirmationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_confirmation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationconfirmationlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_confirmation_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='websites.website'),
        ),
        migrations.AddField(
            model_name='securetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securetoken',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_tokens', to='websites.website'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(help_text='User this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='website',
            field=models.ForeignKey(help_text='Website this event occurred on.', on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='sessionlimitpolicy',
            name='user',
            field=models.ForeignKey(help_text='User whose session limits are configured.', on_delete=django.db.models.deletion.CASCADE, related_name='session_limit_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionlimitpolicy',
            name='website',
            field=models.ForeignKey(help_text='Website context.', on_delete=django.db.models.deletion.CASCADE, related_name='session_limit_policies', to='websites.website'),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices_website', to='websites.website'),
        ),
        migrations.AddField(
            model_name='useripwhitelistsettings',
            name='user',
            field=models.ForeignKey(help_text='User whose whitelist settings are configured', on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useripwhitelistsettings',
            name='website',
            field=models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='usersecurityquestion',
            name='question',
            field=models.ForeignKey(help_text='Selected recovery question.', on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='authentication.securityquestion'),
        ),
        migrations.AddField(
            model_name='usersecurityquestion',
            name='user',
            field=models.ForeignKey(help_text='User who owns this recovery question.', on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersecurityquestion',
            name='website',
            field=models.ForeignKey(help_text='Website context.', on_delete=django.db.models.deletion.CASCADE, related_name='user_security_questions', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['status', 'scheduled_deletion_at'], name='authenticat_status_bd1667_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['status', 'retained_until'], name='authenticat_status_a9ff1c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['user', 'website', 'status'], name='authenticat_user_id_f3b89f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsuspension',
            index=models.Index(fields=['user', 'website', 'is_suspended'], name='authenticat_user_id_948c81_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsuspension',
            index=models.Index(fields=['scheduled_reactivation_at'], name='authenticat_schedul_abdca9_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountsuspension',
            constraint=models.UniqueConstraint(fields=('user', 'website'), name='unique_account_suspension_per_user_per_website'),
        ),
        migrations.AddIndex(
            model_name='accountunlockrequest',
            index=models.Index(fields=['user', 'website', 'created_at'], name='authenticat_user_id_96d492_idx'),
        ),
        migrations.AddIndex(
            model_name='accountunlockrequest',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_a05654_idx'),
        ),
        migrations.AddIndex(
            model_name='authsecurityevent',
            index=models.Index(fields=['website', 'event_type'], name='authenticat_website_767c16_idx'),
        ),
        migrations.AddIndex(
            model_name='authsecurityevent',
            index=models.Index(fields=['user', 'event_type'], name='authenticat_user_id_f725d4_idx'),
        ),
        migrations.AddIndex(
            model_name='authsecurityevent',
            index=models.Index(fields=['created_at'], name='authenticat_created_1c172f_idx'),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['user', 'website'], name='authenticat_user_id_5b2009_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['website', 'ip_address'], name='authenticat_website_6839a5_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['blocked_until'], name='authenticat_blocked_3176e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockedip',
            constraint=models.UniqueConstraint(fields=('website', 'ip_address'), name='unique_blocked_ip_per_website'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['user', 'website'], name='authenticat_user_id_a38f61_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['website', 'fingerprint_hash'], name='authenticat_website_d26fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['is_trusted', 'last_seen_at'], name='authenticat_is_trus_54b02b_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicefingerprint',
            constraint=models.UniqueConstraint(fields=('user', 'website', 'fingerprint_hash'), name='unique_fingerprint_per_user_per_website'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', 'website', 'status'], name='authenticat_user_id_8e995d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_8fc13a_idx'),
        ),
        migrations.AddIndex(
            model_name='failedloginattempt',
            index=models.Index(fields=['user', 'website', 'timestamp'], name='authenticat_user_id_347f81_idx'),
        ),
        migrations.AddIndex(
            model_name='failedloginattempt',
            index=models.Index(fields=['website', 'timestamp'], name='authenticat_website_826b09_idx'),
        ),
        migrations.AddIndex(
            model_name='failedloginattempt',
            index=models.Index(fields=['ip_address', 'timestamp'], name='authenticat_ip_addr_8f98af_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationtoken',
            index=models.Index(fields=['admin_user', 'website', 'created_at'], name='authenticat_admin_u_5cb5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationtoken',
            index=models.Index(fields=['target_user', 'website', 'created_at'], name='authenticat_target__51c884_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationtoken',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_c640be_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationlog',
            index=models.Index(fields=['admin_user', 'website', 'created_at'], name='authenticat_admin_u_05171c_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationlog',
            index=models.Index(fields=['target_user', 'website', 'created_at'], name='authenticat_target__2fedfc_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationlog',
            index=models.Index(fields=['action', 'created_at'], name='authenticat_action_3c81fb_idx'),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['user', 'website', 'is_active'], name='authenticat_user_id_92e01f_idx'),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['ip_address'], name='authenticat_ip_addr_ee591b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipwhitelist',
            constraint=models.UniqueConstraint(fields=('user', 'website', 'ip_address'), name='unique_whitelisted_ip_per_user_per_website'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'website'], name='authenticat_user_id_24f2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['token_hash'], name='authenticat_token_h_afb7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['fingerprint_hash'], name='authenticat_fingerp_182055_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_54fa79_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['user', 'website', 'created_at'], name='authenticat_user_id_67cd32_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_16d637_idx'),
        ),
        migrations.AddIndex(
            model_name='mfadevice',
            index=models.Index(fields=['user', 'website'], name='authenticat_user_id_57130a_idx'),
        ),
        migrations.AddIndex(
            model_name='mfadevice',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_235c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='mfadevice',
            index=models.Index(fields=['user', 'is_primary'], name='authenticat_user_id_69d516_idx'),
        ),
        migrations.AddConstraint(
            model_name='mfadevice',
            constraint=models.UniqueConstraint(fields=('user', 'website', 'name'), name='unique_mfa_device_name_per_user_per_website'),
        ),
        migrations.AddIndex(
            model_name='mfasettings',
            index=models.Index(fields=['website', 'is_enabled'], name='authenticat_website_c36c89_idx'),
        ),
        migrations.AddIndex(
            model_name='mfasettings',
            index=models.Index(fields=['user', 'website'], name='authenticat_user_id_be4c89_idx'),
        ),
        migrations.AddConstraint(
            model_name='mfasettings',
            constraint=models.UniqueConstraint(fields=('user', 'website'), name='unique_mfa_settings_per_user_per_website'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'website', 'purpose'], name='authenticat_user_id_9f3973_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_d93129_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordbreachcheck',
            index=models.Index(fields=['user', '-checked_at'], name='authenticat_user_id_83fc03_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordbreachcheck',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_5f82d4_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordbreachcheck',
            index=models.Index(fields=['is_breached', 'action_taken'], name='authenticat_is_brea_fdc853_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordexpirationpolicy',
            index=models.Index(fields=['user', 'password_changed_at'], name='authenticat_user_id_31ff1a_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordexpirationpolicy',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_fd5eaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordexpirationpolicy',
            constraint=models.UniqueConstraint(fields=('user', 'website'), name='unique_password_expiration_policy_per_user_website'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_922126_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_c23171_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordhistory',
            constraint=models.UniqueConstraint(fields=('user', 'website', 'password_hash'), name='unique_password_hash_per_user_website'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_c5bed8_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['website', 'created_at'], name='authenticat_website_f4a260_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_fb9fed_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordresetrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('used_at__isnull', True)), fields=('user',), name='unique_active_password_reset_request_per_user'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['user', 'website', 'phone_number'], name='authenticat_user_id_5e0404_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_a615ef_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationconfirmationlog',
            index=models.Index(fields=['user', 'website', 'confirmed_at'], name='authenticat_user_id_e9e3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationconfirmationlog',
            index=models.Index(fields=['success', 'confirmed_at'], name='authenticat_success_c70351_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['user', 'website', 'created_at'], name='authenticat_user_id_35ab20_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_d9b096_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['token_hash'], name='authenticat_token_h_fe8a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='securetoken',
            index=models.Index(fields=['user', 'website', 'purpose'], name='authenticat_user_id_3c14ef_idx'),
        ),
        migrations.AddIndex(
            model_name='securetoken',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_344814_idx'),
        ),
        migrations.AddIndex(
            model_name='securetoken',
            index=models.Index(fields=['token_hash'], name='authenticat_token_h_40c9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_6bfbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['website', '-created_at'], name='authenticat_website_b2f059_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='authenticat_user_id_e40ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='authenticat_event_t_a8e92a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['is_suspicious', '-created_at'], name='authenticat_is_susp_44ccf6_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlimitpolicy',
            index=models.Index(fields=['user', 'website'], name='authenticat_user_id_7f79bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionlimitpolicy',
            constraint=models.UniqueConstraint(fields=('user', 'website'), name='unique_session_limit_policy_per_user_website'),
        ),
        migrations.AddConstraint(
            model_name='useripwhitelistsettings',
            constraint=models.UniqueConstraint(fields=('user', 'website'), name='unique_ip_whitelist_settings_per_user_per_website'),
        ),
        migrations.AddIndex(
            model_name='usersecurityquestion',
            index=models.Index(fields=['user', 'website', 'is_active'], name='authenticat_user_id_c94d84_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersecurityquestion',
            constraint=models.UniqueConstraint(fields=('user', 'website', 'question'), name='unique_security_question_per_user_website_question'),
        ),
    ]
