# Generated by Django 5.2.2 on 2026-05-28 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('websites', '0003_websiteactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason the user account was locked.')),
                ('lock_type', models.CharField(choices=[('automatic', 'Automatic'), ('admin', 'Admin'), ('risk', 'Risk-Based')], default='automatic', help_text='Type of account lockout.', max_length=20)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_until', models.DateTimeField(blank=True, help_text='When the lockout ends.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the lockout expires, if temporary.', null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, help_text='The time when the account is unlocked.', null=True)),
                ('cleared_at', models.DateTimeField(blank=True, help_text='When the lockout was cleared.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this lockout is currently active.')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether the account is locked or not.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created the lockout, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_lockouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_lockouts', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_lockouts', to='websites.website')),
            ],
            options={
                'verbose_name': 'Account Lockout',
                'verbose_name_plural': 'Account Lockouts',
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['user', 'website', 'is_active'], name='authenticat_user_id_c6fd3b_idx'), models.Index(fields=['website', 'locked_at'], name='authenticat_website_aae667_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_f70a2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedIPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address that was blocked.')),
                ('reason', models.TextField(help_text='Reason the IP address was blocked.')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the block was recorded.')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the block in minutes.')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ip_logs', to='websites.website')),
            ],
            options={
                'verbose_name': 'Blocked IP Log',
                'verbose_name_plural': 'Blocked IP Logs',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['website', 'ip_address'], name='authenticat_website_6e5756_idx'), models.Index(fields=['blocked_at'], name='authenticat_blocked_c462a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the issued MFA challenge code.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Timestamp when this challenge becomes invalid.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when this challenge was successfully used.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the challenge was initiated.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent from which the challenge was initiated.', null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of attempts made against this challenge.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='authentication.mfadevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to='websites.website')),
            ],
            options={
                'verbose_name': 'MFA Challenge',
                'verbose_name_plural': 'MFA Challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'website', 'created_at'], name='authenticat_user_id_9f1954_idx'), models.Index(fields=['device', 'created_at'], name='authenticat_device__f90ced_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_a27b44_idx')],
            },
        ),
    ]
