# Generated by Django 5.2.2 on 2026-06-01 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_accountlockout_blockediplog_mfachallenge'),
        ('websites', '0004_add_website_branding_and_payment_disclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='websites.website'),
        ),
    ]
