# Generated by Django 5.2.2 on 2026-06-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_allow_null_website_on_login_session'),
        ('websites', '0004_add_website_branding_and_payment_disclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website this event occurred on.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='websites.website'),
        ),
    ]
