# Generated by Django 5.0.14 on 2025-12-03 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_security_questions'),
        ('websites', '0007_website_guest_block_urgent_before_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ipwhitelist',
            name='unique_user_website_ip',
        ),
        migrations.RemoveIndex(
            model_name='emailchangerequest',
            name='authenticat_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsuspension',
            new_name='authenticat_user_id_8aa71e_idx',
            old_name='authenticat_user_id_suspended_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsuspension',
            new_name='authenticat_schedul_f85f70_idx',
            old_name='authenticat_scheduled_react_idx',
        ),
        migrations.RenameIndex(
            model_name='emailchangerequest',
            new_name='authenticat_verific_94c1ba_idx',
            old_name='authenticat_verification_token_idx',
        ),
        migrations.RenameIndex(
            model_name='emailchangerequest',
            new_name='authenticat_expires_8fc13a_idx',
            old_name='authenticat_expires_at_idx',
        ),
        migrations.RenameIndex(
            model_name='ipwhitelist',
            new_name='authenticat_user_id_25ef30_idx',
            old_name='authenticat_user_id_active_idx',
        ),
        migrations.RenameIndex(
            model_name='ipwhitelist',
            new_name='authenticat_ip_addr_ee591b_idx',
            old_name='authenticat_ip_address_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordbreachcheck',
            new_name='authenticat_user_id_83fc03_idx',
            old_name='authenticat_user_id_checked_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordbreachcheck',
            new_name='authenticat_is_brea_fdc853_idx',
            old_name='authenticat_breached_action_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordexpirationpolicy',
            new_name='authenticat_user_id_31ff1a_idx',
            old_name='authenticat_user_id_changed_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordexpirationpolicy',
            new_name='authenticat_website_fd5eaa_idx',
            old_name='authenticat_website_user_pol_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='authenticat_user_id_922126_idx',
            old_name='authenticat_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='authenticat_website_c23171_idx',
            old_name='authenticat_website_user_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneverification',
            new_name='authenticat_phone_n_328601_idx',
            old_name='authenticat_phone_number_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneverification',
            new_name='authenticat_expires_a615ef_idx',
            old_name='authenticat_phone_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='authenticat_user_id_6bfbe5_idx',
            old_name='authenticat_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='authenticat_event_t_a8e92a_idx',
            old_name='authenticat_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='authenticat_is_susp_44ccf6_idx',
            old_name='authenticat_is_susp_idx',
        ),
        migrations.RenameIndex(
            model_name='usersecurityquestion',
            new_name='authenticat_user_id_c94d84_idx',
            old_name='authenticat_user_website_active_idx',
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_verified', '2FA Verified'), ('magic_link_used', 'Magic Link Used'), ('device_trusted', 'Device Trusted'), ('device_revoked', 'Device Revoked'), ('session_created', 'Session Created'), ('session_revoked', 'Session Revoked'), ('suspicious_activity', 'Suspicious Activity'), ('suspicious_session_reported', 'Suspicious Session Reported'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('profile_updated', 'Profile Updated'), ('privacy_settings_changed', 'Privacy Settings Changed')], help_text='Type of security event', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='ipwhitelist',
            unique_together={('user', 'website', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='accountsuspension',
            index=models.Index(fields=['website', 'is_suspended'], name='authenticat_website_6b4827_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_eab131_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_138f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_4ead07_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordbreachcheck',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_5f82d4_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_172965_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_12d689_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlimitpolicy',
            index=models.Index(fields=['user'], name='authenticat_user_id_47246b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlimitpolicy',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_1ac15d_idx'),
        ),
        migrations.AddIndex(
            model_name='useripwhitelistsettings',
            index=models.Index(fields=['user', 'is_enabled'], name='authenticat_user_id_21c8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='useripwhitelistsettings',
            index=models.Index(fields=['website', 'user'], name='authenticat_website_0c02fa_idx'),
        ),
    ]
