# Generated by Django 5.0.14 on 2025-12-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_loginsession_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impersonationlog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='impersonationlog',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='impersonationlog',
            name='token',
        ),
        migrations.RemoveField(
            model_name='impersonationlog',
            name='website',
        ),
        migrations.RemoveField(
            model_name='impersonationtoken',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='impersonationtoken',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='impersonationtoken',
            name='website',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='website',
        ),
        migrations.DeleteModel(
            name='AccountLockout',
        ),
        migrations.DeleteModel(
            name='ImpersonationLog',
        ),
        migrations.DeleteModel(
            name='ImpersonationToken',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
