# Generated by Django 5.1.6 on 2025-02-22 03:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_initial'),
        ('orders', '0003_remove_paymenttransaction_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminLog',
            new_name='AdminActivityLog',
        ),
    ]
