# Generated by Django 5.0.14 on 2026-05-28 06:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Academic Level (e.g., University, College, Masters, BSN, etc).', max_length=100)),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
            },
        ),
        migrations.CreateModel(
            name='CriticalDeadlineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_deadline_threshold_hours', models.PositiveIntegerField(default=8, help_text='Hours before deadline when order becomes critical')),
            ],
            options={
                'verbose_name': 'Critical Deadline Setting',
                'verbose_name_plural': 'Critical Deadline Settings',
            },
        ),
        migrations.CreateModel(
            name='EditingRequirementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_editing_by_default', models.BooleanField(default=True, help_text='Enable editing for orders by default (unless urgent or explicitly disabled)')),
                ('skip_editing_for_urgent', models.BooleanField(default=True, help_text='Skip editing for urgent orders (deadline < 24 hours or is_urgent=True)')),
                ('allow_editing_for_early_submissions', models.BooleanField(default=True, help_text='Allow editing for orders submitted before deadline')),
                ('early_submission_hours_threshold', models.PositiveIntegerField(default=24, help_text="Hours before deadline to consider submission 'early' (for editing eligibility)")),
                ('editing_required_for_first_orders', models.BooleanField(default=True, help_text="Require editing for client's first order")),
                ('editing_required_for_high_value', models.BooleanField(default=True, help_text='Require editing for high-value orders')),
                ('high_value_threshold', models.DecimalField(decimal_places=2, default=Decimal('300'), help_text="Order value threshold (USD) to consider 'high value'", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_qa_by_default', models.BooleanField(default=False, help_text="Enable QA review for orders that don't require editing.")),
                ('qa_required_for_high_value', models.BooleanField(default=True, help_text='Require QA for orders above high_value_threshold.')),
                ('qa_required_for_new_writers', models.BooleanField(default=True, help_text='Require QA for orders from writers below new_writer_order_threshold.')),
                ('new_writer_order_threshold', models.PositiveIntegerField(default=5, help_text="Writers with fewer completed orders than this threshold are considered 'new' and their orders go through QA.")),
            ],
            options={
                'verbose_name': 'Editing Requirement Config',
                'verbose_name_plural': 'Editing Requirement Configs',
            },
        ),
        migrations.CreateModel(
            name='EnglishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English type (e.g., US English, UK English).', max_length=50)),
                ('code', models.CharField(help_text='Short code (e.g., US, UK).', max_length=10)),
            ],
            options={
                'verbose_name': 'English Type',
                'verbose_name_plural': 'English Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormattingandCitationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Formatting style (e.g., APA, MLA).', max_length=50)),
            ],
            options={
                'verbose_name': 'Formatting and Citation Style',
                'verbose_name_plural': 'Formatting and Citation Styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of paper (e.g., Essay, Report).', max_length=100)),
            ],
            options={
                'verbose_name': 'Paper Type',
                'verbose_name_plural': 'Paper Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperTypeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'High School Assignments', 'Graduate Research Papers')", max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('nursing', 'Nursing & Healthcare'), ('technical', 'Technical & Engineering'), ('business', 'Business'), ('law', 'Law & Legal')], default='general', help_text='Category of this template', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('paper_types', models.JSONField(default=list, help_text="List of paper types as ['Paper Type Name', ...]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for cloning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paper Type Template',
                'verbose_name_plural': 'Paper Type Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RevisionPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('free_revision_days', models.PositiveIntegerField(default=14)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revision Policy Config',
                'verbose_name_plural': 'Revision Policy Configs',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject (e.g., Nursing, Physics).', max_length=100)),
                ('is_technical', models.BooleanField(default=False, help_text='Is this subject technical?')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Nursing & Healthcare', 'Computer Science')", max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('humanities', 'Humanities'), ('sciences', 'Sciences'), ('health_sciences', 'Health Sciences'), ('nursing', 'Nursing & Healthcare'), ('computing', 'Computing & Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('education', 'Education'), ('social_sciences', 'Social Sciences')], default='general', help_text='Category of this template', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('subjects', models.JSONField(default=list, help_text="List of subjects as [{'name': 'Subject Name', 'is_technical': bool}, ...]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for cloning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Template',
                'verbose_name_plural': 'Subject Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of work (e.g., Writing, Editing).', max_length=50)),
            ],
            options={
                'verbose_name': 'Type of Work',
                'verbose_name_plural': 'Types of Work',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfWorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Complete Writing Services', 'Editing & Proofreading')", max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('writing', 'Writing Services'), ('editing', 'Editing & Revision'), ('proofreading', 'Proofreading & Correction'), ('rewriting', 'Rewriting & Paraphrasing'), ('plagiarism', 'Plagiarism Services'), ('formatting', 'Formatting & Styling'), ('research', 'Research Services'), ('analysis', 'Analysis Services'), ('review', 'Review & Critique'), ('grading', 'Grading & Marking'), ('technical', 'Technical Services')], default='general', help_text='Category of this template', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('types_of_work', models.JSONField(default=list, help_text="List of types of work as ['Type Name', ...]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for cloning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type of Work Template',
                'verbose_name_plural': 'Type of Work Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WriterDeadlineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_deadline_percentage', models.PositiveIntegerField(default=80, help_text="Percentage of the client's deadline given to the writer (e.g., 80%).")),
            ],
            options={
                'verbose_name': 'Writer Deadline Config',
                'verbose_name_plural': 'Writer Deadline Configs',
                'ordering': ['writer_deadline_percentage'],
            },
        ),
    ]
