# Generated by Django 5.0.14 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Academic Level (e.g., University, College, Masters, BSN, etc).', max_length=100)),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
            },
        ),
        migrations.CreateModel(
            name='CriticalDeadlineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_deadline_threshold_hours', models.PositiveIntegerField(default=8, help_text='Hours before deadline when order becomes critical')),
            ],
            options={
                'verbose_name': 'Critical Deadline Setting',
                'verbose_name_plural': 'Critical Deadline Settings',
            },
        ),
        migrations.CreateModel(
            name='EnglishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English type (e.g., US English, UK English).', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Short code (e.g., US, UK).', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'English Type',
                'verbose_name_plural': 'English Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormattingandCitationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Formatting style (e.g., APA, MLA).', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Formatting and Citation Style',
                'verbose_name_plural': 'Formatting and Citation Styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of paper (e.g., Essay, Report).', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Paper Type',
                'verbose_name_plural': 'Paper Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RevisionPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('free_revision_days', models.PositiveIntegerField(default=14)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revision Policy Config',
                'verbose_name_plural': 'Revision Policy Configs',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject (e.g., Nursing, Physics).', max_length=100, unique=True)),
                ('is_technical', models.BooleanField(default=False, help_text='Is this subject technical?')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of work (e.g., Writing, Editing).', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type of Work',
                'verbose_name_plural': 'Types of Work',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WriterDeadlineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_deadline_percentage', models.PositiveIntegerField(default=80, help_text="Percentage of the client's deadline given to the writer (e.g., 80%).")),
            ],
            options={
                'verbose_name': 'Writer Deadline Config',
                'verbose_name_plural': 'Writer Deadline Configs',
                'ordering': ['writer_deadline_percentage'],
            },
        ),
    ]
