# Generated by Django 5.0.14 on 2026-05-28 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_configs', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevel',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='websites.website'),
        ),
        migrations.AddField(
            model_name='editingrequirementconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_editing_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editingrequirementconfig',
            name='website',
            field=models.ForeignKey(help_text='Website this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='editing_requirements', to='websites.website'),
        ),
        migrations.AddField(
            model_name='englishtype',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_type', to='websites.website'),
        ),
        migrations.AddField(
            model_name='formattingandcitationstyle',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatting', to='websites.website'),
        ),
        migrations.AddField(
            model_name='papertype',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_type', to='websites.website'),
        ),
        migrations.AddField(
            model_name='papertypetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paper_type_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revisionpolicyconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_policies', to='websites.website'),
        ),
        migrations.AddField(
            model_name='subject',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='websites.website'),
        ),
        migrations.AddField(
            model_name='subjecttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_work', to='websites.website'),
        ),
        migrations.AddField(
            model_name='typeofworktemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_type_of_work_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerdeadlineconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_deadline_threshold', to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='academiclevel',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='editingrequirementconfig',
            unique_together={('website',)},
        ),
        migrations.AlterUniqueTogether(
            name='englishtype',
            unique_together={('website', 'name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='formattingandcitationstyle',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='papertype',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='papertypetemplate',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='revisionpolicyconfig',
            unique_together={('website', 'active')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subjecttemplate',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='typeofwork',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='typeofworktemplate',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='writerdeadlineconfig',
            unique_together={('website', 'writer_deadline_percentage')},
        ),
    ]
