# Generated by Django 5.2.2 on 2026-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_configs', '0003_add_subject_category_and_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiclevel',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Academic Level', 'verbose_name_plural': 'Academic Levels'},
        ),
        migrations.AlterModelOptions(
            name='englishtype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'English Type', 'verbose_name_plural': 'English Types'},
        ),
        migrations.AlterModelOptions(
            name='formattingandcitationstyle',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Formatting and Citation Style', 'verbose_name_plural': 'Formatting and Citation Styles'},
        ),
        migrations.AlterModelOptions(
            name='papertype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Paper Type', 'verbose_name_plural': 'Paper Types'},
        ),
        migrations.AlterModelOptions(
            name='typeofwork',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Type of Work', 'verbose_name_plural': 'Types of Work'},
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='description',
            field=models.CharField(blank=True, help_text='Short clarification shown to clients.', max_length=255),
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort position — lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive levels are hidden from clients.'),
        ),
        migrations.AddField(
            model_name='englishtype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort position — lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='englishtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive types are hidden from clients.'),
        ),
        migrations.AddField(
            model_name='formattingandcitationstyle',
            name='description',
            field=models.CharField(blank=True, help_text='Short note about when to use this style.', max_length=255),
        ),
        migrations.AddField(
            model_name='formattingandcitationstyle',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort position — lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='formattingandcitationstyle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive styles are hidden from clients.'),
        ),
        migrations.AddField(
            model_name='papertype',
            name='description',
            field=models.CharField(blank=True, help_text='Short description shown to clients.', max_length=255),
        ),
        migrations.AddField(
            model_name='papertype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort position — lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='papertype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive types are hidden from clients.'),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='description',
            field=models.CharField(blank=True, help_text='Short description shown to clients.', max_length=255),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort position — lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive types are hidden from clients.'),
        ),
        migrations.AlterField(
            model_name='academiclevel',
            name='name',
            field=models.CharField(help_text='Academic level label shown to clients (e.g. Undergraduate, Masters).', max_length=100),
        ),
        migrations.AlterField(
            model_name='englishtype',
            name='code',
            field=models.CharField(help_text='Short code (e.g., US, UK, AU).', max_length=10),
        ),
        migrations.AlterField(
            model_name='englishtype',
            name='name',
            field=models.CharField(help_text='English variant label shown to clients.', max_length=50),
        ),
        migrations.AlterField(
            model_name='formattingandcitationstyle',
            name='name',
            field=models.CharField(help_text='Style name shown to clients (e.g. APA 7th Edition).', max_length=50),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='name',
            field=models.CharField(help_text='Paper type label shown to clients (e.g. Essay, Case Study).', max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='name',
            field=models.CharField(help_text='Work type shown to clients (e.g. Writing, Editing).', max_length=50),
        ),
    ]
