# Generated by Django 5.2.2 on 2026-06-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_configs', '0004_add_is_active_display_order_description'),
        ('websites', '0010_website_settings_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticaldeadlinesetting',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a platform-wide fallback. A per-tenant row overrides the fallback for that site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critical_deadline_settings', to='websites.website'),
        ),
        migrations.AddConstraint(
            model_name='criticaldeadlinesetting',
            constraint=models.UniqueConstraint(condition=models.Q(('website__isnull', False)), fields=('website',), name='unique_critical_deadline_per_website'),
        ),
    ]
