# Generated by Django 5.0.14 on 2025-12-08 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_configs', '0004_alter_englishtype_code_alter_englishtype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTypeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'High School Assignments', 'Graduate Research Papers')", max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('nursing', 'Nursing & Healthcare'), ('technical', 'Technical & Engineering'), ('business', 'Business'), ('law', 'Law & Legal')], default='general', help_text='Category of this template', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('paper_types', models.JSONField(default=list, help_text="List of paper types as ['Paper Type Name', ...]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for cloning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paper_type_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Type Template',
                'verbose_name_plural': 'Paper Type Templates',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Nursing & Healthcare', 'Computer Science')", max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('humanities', 'Humanities'), ('sciences', 'Sciences'), ('health_sciences', 'Health Sciences'), ('nursing', 'Nursing & Healthcare'), ('computing', 'Computing & Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('education', 'Education'), ('social_sciences', 'Social Sciences')], default='general', help_text='Category of this template', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('subjects', models.JSONField(default=list, help_text="List of subjects as [{'name': 'Subject Name', 'is_technical': bool}, ...]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for cloning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject Template',
                'verbose_name_plural': 'Subject Templates',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
