# Generated by Django 5.0.14 on 2025-12-08 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_configs', '0005_add_subject_and_paper_type_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Complete Writing Services', 'Editing & Proofreading')", max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('writing', 'Writing Services'), ('editing', 'Editing & Revision'), ('proofreading', 'Proofreading & Correction'), ('rewriting', 'Rewriting & Paraphrasing'), ('plagiarism', 'Plagiarism Services'), ('formatting', 'Formatting & Styling'), ('research', 'Research Services'), ('analysis', 'Analysis Services'), ('review', 'Review & Critique'), ('grading', 'Grading & Marking'), ('technical', 'Technical Services')], default='general', help_text='Category of this template', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('types_of_work', models.JSONField(default=list, help_text="List of types of work as ['Type Name', ...]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for cloning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_type_of_work_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type of Work Template',
                'verbose_name_plural': 'Type of Work Templates',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
