# Generated by Django 5.1.6 on 2025-02-22 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('name', models.CharField(help_text="Website's name", max_length=255, unique=True)),
                ('domain', models.URLField(help_text="Website's domain (e.g., https://example.com)", unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the website is currently active')),
                ('logo', models.ImageField(blank=True, help_text='Logo for the website', null=True, upload_to='logos/')),
                ('theme_color', models.CharField(blank=True, help_text='Primary theme color in HEX (e.g., #FFFFFF)', max_length=7, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Support contact email for the website', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Support contact phone number for the website', max_length=15, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow users to register directly on this website')),
                ('allow_guest_checkout', models.BooleanField(default=False, help_text='Allow guest checkout without account registration')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
