# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Website's name", max_length=255, unique=True)),
                ('domain', models.URLField(help_text="Website's domain (e.g., https://example.com)", unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the website is currently active')),
                ('logo', models.ImageField(blank=True, help_text='Logo for the website', null=True, upload_to='logos/')),
                ('theme_color', models.CharField(blank=True, help_text='Primary theme color in HEX (e.g., #FFFFFF)', max_length=7, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Support contact email for the website', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Support contact phone number for the website', max_length=15, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow users to register directly on this website')),
                ('allow_guest_checkout', models.BooleanField(default=False, help_text='Allow guest checkout without account registration')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp for soft deletion', null=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID (e.g., UA-123456789-1 or G-XXXXXXXXXX)', max_length=50, null=True)),
                ('google_search_console_id', models.CharField(blank=True, help_text='Google Search Console verification meta tag', max_length=255, null=True)),
                ('bing_webmaster_id', models.CharField(blank=True, help_text='Bing Webmaster Tools verification meta tag', max_length=255, null=True)),
                ('default_sender_name', models.CharField(blank=True, help_text="Default sender name for emails from this website (e.g., 'ABC Support')", max_length=100, null=True)),
                ('default_sender_email', models.EmailField(blank=True, help_text='Default email address used to send emails from this website', max_length=254, null=True)),
                ('marketing_sender_email', models.EmailField(blank=True, help_text='Used for newsletters, promo emails (e.g., offers@site.com)', max_length=254, null=True)),
                ('notification_sender_email', models.EmailField(blank=True, help_text='Used for do-not-reply emails (e.g., do-not-reply@site.com)', max_length=254, null=True)),
                ('support_sender_email', models.EmailField(blank=True, help_text='Used for support replies (e.g., support@site.com)', max_length=254, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='websites_we_domain_2b7670_idx'), models.Index(fields=['is_active'], name='websites_we_is_acti_e458bc_idx'), models.Index(fields=['is_deleted'], name='websites_we_is_dele_ccbdf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SEO_UPDATED', 'SEO Settings Updated'), ('SOFT_DELETED', 'Website Soft Deleted'), ('RESTORED', 'Website Restored')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Extra details about the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_reply_email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('domain_url', models.URLField(help_text='The main domain of the website')),
                ('sender_name', models.CharField(help_text='Name of the sender (e.g., Company name)', max_length=100)),
                ('sender_email', models.EmailField(help_text="Sender's email address", max_length=200)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_settings', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteStaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, help_text='Schedule content update', null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('previous_versions', models.JSONField(blank=True, default=list, help_text='Stores older versions')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_pages', to='websites.website')),
            ],
            options={
                'unique_together': {('website', 'slug')},
            },
        ),
    ]
