# Generated by Django 4.2 on 2025-01-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='allow_guest_checkout',
            field=models.BooleanField(default=False, help_text='Allow guest checkout without account registration'),
        ),
        migrations.AddField(
            model_name='website',
            name='allow_registration',
            field=models.BooleanField(default=True, help_text='Allow users to register directly on this website'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Support contact email for the website', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Support contact phone number for the website', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo for the website', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='website',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_color',
            field=models.CharField(blank=True, help_text='Primary theme color in HEX (e.g., #FFFFFF)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.URLField(help_text="Website's domain (e.g., https://example.com)", unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the website is currently active'),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(help_text="Website's name", max_length=255, unique=True),
        ),
    ]
