# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid by the client in USD.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('source_type', models.CharField(choices=[('wallet', 'Wallet'), ('external', 'External')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_initiated', 'Payment Initiated'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('requires_manual_review', models.BooleanField(default=False, help_text='Whether this tip requires administrative review before settlement.')),
                ('manually_reviewed', models.BooleanField(default=False)),
                ('manually_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, help_text='Internal settlement correlation reference.', max_length=255)),
                ('client_note', models.TextField(blank=True, help_text='Optional message attached by the client.')),
                ('is_settled', models.BooleanField(db_index=True, default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount_cents', models.PositiveBigIntegerField(help_text='Total tip amount in minor currency units.', validators=[django.core.validators.MinValueValidator(1)])),
                ('writer_share_cents', models.PositiveBigIntegerField(default=0, help_text='Writer payout portion in minor currency units.', validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee_cents', models.PositiveBigIntegerField(default=0, help_text='Platform fee portion in minor currency units.', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_tips', models.PositiveIntegerField(default=0)),
                ('total_successful_tips', models.PositiveIntegerField(default=0)),
                ('total_failed_tips', models.PositiveIntegerField(default=0)),
                ('total_volume_cents', models.BigIntegerField(default=0)),
                ('writer_earnings_cents', models.BigIntegerField(default=0)),
                ('platform_fee_cents', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('order', 'Order'), ('class', 'Class'), ('special_order', 'Special Order'), ('writer', 'Writer'), ('other', 'Other')], db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True, help_text='Optional contextual explanation for the tip.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('tip.created', 'Tip Created'), ('tip.payment_initiated', 'Tip Payment Initiated'), ('tip.processing', 'Tip Processing'), ('tip.succeeded', 'Tip Succeeded'), ('tip.failed', 'Tip Failed'), ('tip.cancelled', 'Tip Cancelled'), ('wallet.hold.created', 'Wallet Hold Created'), ('wallet.hold.captured', 'Wallet Hold Captured'), ('wallet.hold.released', 'Wallet Hold Released')], db_index=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('deduplication_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('failed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('writer_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of the tip allocated to the writer.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('platform_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of the tip retained by the platform.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('minimum_tip_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum allowable tip amount in USD.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('risk_review_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Tips above this amount may be flagged for review.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('allow_wallet_tips', models.BooleanField(default=True, help_text='Controls whether wallet-funded tips are permitted.')),
                ('allow_external_tips', models.BooleanField(default=True, help_text='Controls whether externally funded tips are permitted.')),
                ('require_manual_review', models.BooleanField(default=False, help_text='When enabled, newly created tips may require manual review before settlement.')),
                ('maximum_tip_frequency_per_day', models.PositiveIntegerField(default=25, help_text='Maximum number of tips a client may create within a rolling 24-hour window.', validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_other_reason_tips', models.BooleanField(default=True, help_text="Controls whether clients may create freeform 'other' attribution tips.")),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one policy should be active at a time.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Monotonic version used for historical snapshots.')),
                ('effective_from', models.DateTimeField(blank=True, help_text='Optional activation timestamp for scheduled rollout.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipPolicySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_version', models.PositiveIntegerField()),
                ('writer_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipSettlementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('writer_tip_share', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('platform_tip_share', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('settled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-settled_at'],
            },
        ),
    ]
