# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0002_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('special_orders', '0002_initial'),
        ('tips', '0002_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='wallet_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='wallets.wallethold'),
        ),
        migrations.AlterUniqueTogether(
            name='tipanalyticsdaily',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='tipattribution',
            name='class_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='tipattribution',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='orders.order'),
        ),
        migrations.AddField(
            model_name='tipattribution',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='tipattribution',
            name='tip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='tips.tip'),
        ),
        migrations.AddField(
            model_name='tipidempotencykey',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_idempotency_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipidempotencykey',
            name='tip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.tip'),
        ),
        migrations.AddField(
            model_name='tipoutboxevent',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='tips.tip'),
        ),
        migrations.AddField(
            model_name='tippolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tip_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tippolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tip_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='active_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tips', to='tips.tippolicy'),
        ),
        migrations.AddField(
            model_name='tippolicysnapshot',
            name='tip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_snapshot', to='tips.tip'),
        ),
        migrations.AddField(
            model_name='tipsettlementsnapshot',
            name='tip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_snapshot', to='tips.tip'),
        ),
        migrations.AddIndex(
            model_name='tipattribution',
            index=models.Index(fields=['context_type', 'created_at'], name='tip_attr_context_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipidempotencykey',
            unique_together={('sender', 'key')},
        ),
        migrations.AddIndex(
            model_name='tipoutboxevent',
            index=models.Index(fields=['processed', 'available_at'], name='tip_outbox_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoutboxevent',
            index=models.Index(fields=['failed', 'next_retry_at'], name='tip_outbox_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoutboxevent',
            index=models.Index(fields=['event_type', 'processed'], name='tip_outbox_type_idx'),
        ),
        migrations.AddIndex(
            model_name='tippolicy',
            index=models.Index(fields=['is_active'], name='tip_policy_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tippolicy',
            index=models.Index(fields=['effective_from'], name='tip_policy_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='tippolicy',
            constraint=models.CheckConstraint(condition=models.Q(('writer_percentage__gte', 0), ('platform_percentage__gte', 0)), name='tip_policy_percentages_positive'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['sender', 'created_at'], name='tip_sender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['receiver', 'created_at'], name='tip_receiver_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['status', 'created_at'], name='tip_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['source_type', 'created_at'], name='tip_source_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='tip',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0)), name='tip_gross_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='tip',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='tip_sender_receiver_different'),
        ),
        migrations.AddIndex(
            model_name='tipsettlementsnapshot',
            index=models.Index(fields=['settled_at'], name='tip_settlement_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipsettlementsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='tip_snapshot_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='tipsettlementsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('writer_tip_share__gte', 0)), name='tip_snapshot_writer_positive'),
        ),
        migrations.AddConstraint(
            model_name='tipsettlementsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('platform_tip_share__gte', 0)), name='tip_snapshot_platform_positive'),
        ),
    ]
