# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_days', models.PositiveIntegerField(default=30, help_text='Global grace period in days before final deletion after a deletion request.')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_data', models.JSONField(help_text='Stores the fields requested for update.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's response to the request.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('EMAIL_CHANGE', 'Email Change'), ('ROLE_CHANGE', 'Role Change'), ('ACCOUNT_DELETION', 'Account Deletion'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('SUSPENSION', 'Account Suspension'), ('ACTIVATION', 'Account Activation'), ('PROFILE_UPDATE', 'Profile Update'), ('BLACKLISTED', 'Email Blacklisted'), ('PHONE_NUMBER_CHANGE', 'Phone Number Change')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('admin_initiated', models.BooleanField(default=False)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('consent_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profile_pictures/')),
                ('avatar', models.CharField(choices=[('avatars/universal.png', 'Universal Avatar'), ('avatars/male1.png', 'Male Avatar 1'), ('avatars/male2.png', 'Male Avatar 2'), ('avatars/female1.png', 'Female Avatar 1'), ('avatars/female2.png', 'Female Avatar 2')], default='avatars/universal.png', help_text='Select a predefined avatar for privacy.', max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='User-selected country', max_length=2, null=True)),
                ('state', models.CharField(blank=True, help_text='Manually entered state/province', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Optional bio field for writers/editors.', null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact number for the user.', max_length=128, null=True, region=None)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, help_text='Last activity timestamp.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('writer', 'Writer'), ('client', 'Client')], default='client', help_text='Role assigned to the user.', max_length=20)),
                ('is_mfa_enabled', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(choices=[('none', 'No MFA'), ('email_otp', 'Email OTP'), ('sms_otp', 'SMS OTP'), ('totp', 'TOTP (Google Authenticator)'), ('qr_code', 'QR CODE')], default='none', max_length=20)),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('backup_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_recovery_token', models.CharField(blank=True, max_length=64, null=True)),
                ('mfa_recovery_expires', models.DateTimeField(blank=True, null=True)),
                ('notify_mfa_login', models.BooleanField(default=True)),
                ('notify_password_change', models.BooleanField(default=True)),
                ('notify_wallet_transactions', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('is_impersonated', models.BooleanField(default=False)),
                ('impersonation_start_at', models.DateTimeField(blank=True, null=True)),
                ('impersonation_end_at', models.DateTimeField(blank=True, null=True)),
                ('impersonation_reason', models.TextField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('is_deletion_requested', models.BooleanField(default=False)),
                ('deletion_scheduled', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=30, help_text='Number of days before final deletion after request.')),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('suspension_start_date', models.DateTimeField(blank=True, null=True)),
                ('suspension_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_on_probation', models.BooleanField(default=False)),
                ('probation_reason', models.TextField(blank=True, null=True)),
                ('probation_start_date', models.DateTimeField(blank=True, null=True)),
                ('probation_end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_country', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, max_length=64, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('session_device', models.CharField(blank=True, max_length=255, null=True)),
                ('trusted_devices', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('impersonated_by', models.ForeignKey(blank=True, help_text='The admin user who is currently impersonating this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_impersonated_by', to=settings.AUTH_USER_MODEL)),
                ('notification_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='notifications_system.notificationpreferenceprofile')),
                ('user', models.ForeignKey(help_text='Reference to the user associated with this model.', on_delete=django.db.models.deletion.CASCADE, related_name='the_specific_user', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
