# Generated by Django 5.1.5 on 2025-01-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, choices=[('avatars/universal.png', 'Universal Avatar'), ('avatars/male1.png', 'Male Avatar 1'), ('avatars/male2.png', 'Male Avatar 2'), ('avatars/female1.png', 'Female Avatar 1'), ('avatars/female2.png', 'Female Avatar 2')], default='avatars/universal.png', help_text='Select a predefined avatar for privacy.', max_length=255, null=True),
        ),
    ]
