# Generated by Django 5.0.14 on 2025-10-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Reference to the user associated with this model.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_specific_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
