# Generated by Django 5.2.2 on 2026-06-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
        ('websites', '0009_add_wagtail_site_to_website'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='changelogentry',
            new_name='changelog_c_portal__abd2d7_idx',
            old_name='changelog_surface_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='changelogentry',
            new_name='changelog_c_website_d52dac_idx',
            old_name='changelog_website_surface_idx',
        ),
        migrations.AlterField(
            model_name='changelogentry',
            name='body',
            field=models.TextField(help_text='Markdown supported.'),
        ),
        migrations.AlterField(
            model_name='changelogentry',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned entries appear at the top regardless of date.'),
        ),
        migrations.AlterField(
            model_name='changelogentry',
            name='version',
            field=models.CharField(blank=True, help_text="Optional — e.g. '2026-06-04' or '1.4.2'", max_length=30),
        ),
        migrations.AlterField(
            model_name='changelogentry',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all websites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='websites.website'),
        ),
    ]
