<template>
  <div class="space-y-6 p-4 md:p-6" v-if="!componentError && !initialLoading">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">Holiday & Special Days Management</h1>
        <p class="mt-2 text-sm md:text-base text-gray-600 dark:text-gray-400">Manage holidays, special events, and automated marketing campaigns</p>
      </div>
      <div class="flex flex-wrap gap-2 w-full sm:w-auto">
        <button 
          @click="showCreateModal = true"
          class="flex-1 sm:flex-none px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors text-sm font-medium flex items-center justify-center gap-2"
        >
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
          Add Special Day
        </button>
        <button 
          @click="checkReminders"
          class="flex-1 sm:flex-none px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          :disabled="checkingReminders"
        >
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
          {{ checkingReminders ? 'Checking...' : 'Check Reminders' }}
        </button>
        <button 
          @click="autoGenerateDiscounts"
          class="flex-1 sm:flex-none px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          :disabled="generatingDiscounts"
        >
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
          </svg>
          {{ generatingDiscounts ? 'Generating...' : 'Auto-Generate Discounts' }}
        </button>
      </div>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      <div class="card p-4 bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-800/20 border border-blue-200 dark:border-blue-800">
        <p class="text-xs sm:text-sm font-medium text-blue-700 dark:text-blue-300 mb-1">Total Special Days</p>
        <p class="text-2xl sm:text-3xl font-bold text-blue-900 dark:text-blue-100">{{ stats.total || 0 }}</p>
      </div>
      <div class="card p-4 bg-gradient-to-br from-yellow-50 to-yellow-100 dark:from-yellow-900/20 dark:to-yellow-800/20 border border-yellow-200 dark:border-yellow-800">
        <p class="text-xs sm:text-sm font-medium text-yellow-700 dark:text-yellow-300 mb-1">Upcoming (30d)</p>
        <p class="text-2xl sm:text-3xl font-bold text-yellow-900 dark:text-yellow-100">{{ stats.upcoming || 0 }}</p>
      </div>
      <div class="card p-4 bg-gradient-to-br from-orange-50 to-orange-100 dark:from-orange-900/20 dark:to-orange-800/20 border border-orange-200 dark:border-orange-800">
        <p class="text-xs sm:text-sm font-medium text-orange-700 dark:text-orange-300 mb-1">Pending Reminders</p>
        <p class="text-2xl sm:text-3xl font-bold text-orange-900 dark:text-orange-100">{{ pendingRemindersCount }}</p>
      </div>
      <div class="card p-4 bg-gradient-to-br from-green-50 to-green-100 dark:from-green-900/20 dark:to-green-800/20 border border-green-200 dark:border-green-800">
        <p class="text-xs sm:text-sm font-medium text-green-700 dark:text-green-300 mb-1">Active Campaigns</p>
        <p class="text-2xl sm:text-3xl font-bold text-green-900 dark:text-green-100">{{ stats.activeCampaigns || 0 }}</p>
      </div>
    </div>

    <!-- Filters -->
    <div class="card p-4">
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        <div>
          <label class="block text-xs sm:text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">Country</label>
          <select 
            v-model="filters.country" 
            @change="loadSpecialDays" 
            class="w-full border dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded px-3 py-2 text-sm"
          >
            <option value="">All Countries</option>
            <option value="US">United States</option>
            <option value="CA">Canada</option>
            <option value="GB">United Kingdom</option>
            <option value="AU">Australia</option>
            <option value="NZ">New Zealand</option>
            <option value="IE">Ireland</option>
          </select>
        </div>
        <div>
          <label class="block text-xs sm:text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">Event Type</label>
          <select 
            v-model="filters.event_type" 
            @change="loadSpecialDays" 
            class="w-full border dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded px-3 py-2 text-sm"
          >
            <option value="">All Types</option>
            <option value="holiday">Holiday</option>
            <option value="special_day">Special Day</option>
            <option value="anniversary">Anniversary</option>
            <option value="seasonal">Seasonal</option>
            <option value="cultural">Cultural</option>
          </select>
        </div>
        <div>
          <label class="block text-xs sm:text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">Status</label>
          <select 
            v-model="filters.is_active" 
            @change="loadSpecialDays" 
            class="w-full border dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded px-3 py-2 text-sm"
          >
            <option value="">All</option>
            <option value="true">Active</option>
            <option value="false">Inactive</option>
          </select>
        </div>
        <div class="flex items-end">
          <label class="flex items-center gap-2 cursor-pointer">
            <input 
              type="checkbox" 
              v-model="filters.upcoming"
              @change="loadSpecialDays"
              class="w-4 h-4 text-primary-600 rounded focus:ring-primary-500"
            />
            <span class="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Upcoming Only</span>
          </label>
        </div>
        <div class="flex items-end">
          <button 
            @click="resetFilters" 
            class="w-full px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors text-sm font-medium"
          >
            Reset
          </button>
        </div>
      </div>
    </div>

    <!-- Tabs -->
    <div class="border-b border-gray-200 dark:border-gray-700 overflow-x-auto">
      <nav class="-mb-px flex space-x-4 sm:space-x-8 min-w-max">
        <button 
          :class="[
            'whitespace-nowrap py-3 sm:py-4 px-1 border-b-2 font-medium text-xs sm:text-sm transition-colors',
            activeTab === 'special-days'
              ? 'border-primary-500 text-primary-600 dark:text-primary-400'
              : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 hover:border-gray-300 dark:hover:border-gray-600'
          ]"
          @click="activeTab = 'special-days'"
        >
          Special Days
          <span v-if="specialDays.length > 0" class="ml-2 px-2 py-0.5 text-xs bg-gray-200 dark:bg-gray-700 rounded-full">
            {{ specialDays.length }}
          </span>
        </button>
        <button 
          :class="[
            'whitespace-nowrap py-3 sm:py-4 px-1 border-b-2 font-medium text-xs sm:text-sm transition-colors',
            activeTab === 'reminders'
              ? 'border-primary-500 text-primary-600 dark:text-primary-400'
              : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 hover:border-gray-300 dark:hover:border-gray-600'
          ]"
          @click="activeTab = 'reminders'"
        >
          Reminders
          <span v-if="pendingRemindersCount > 0" class="ml-2 px-2 py-0.5 text-xs bg-orange-500 text-white rounded-full">
            {{ pendingRemindersCount }}
          </span>
        </button>
        <button 
          :class="[
            'whitespace-nowrap py-3 sm:py-4 px-1 border-b-2 font-medium text-xs sm:text-sm transition-colors',
            activeTab === 'campaigns'
              ? 'border-primary-500 text-primary-600 dark:text-primary-400'
              : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 hover:border-gray-300 dark:hover:border-gray-600'
          ]"
          @click="activeTab = 'campaigns'"
        >
          Discount Campaigns
          <span v-if="campaigns.length > 0" class="ml-2 px-2 py-0.5 text-xs bg-gray-200 dark:bg-gray-700 rounded-full">
            {{ campaigns.length }}
          </span>
        </button>
      </nav>
    </div>

    <!-- Special Days Tab -->
    <div v-if="activeTab === 'special-days'" class="space-y-4">
      <div class="card overflow-hidden">
        <!-- Mobile Card View -->
        <div class="block sm:hidden space-y-4 p-4">
          <div
            v-for="day in filteredSpecialDays"
            :key="day.id"
            @click="viewSpecialDay(day)"
            class="border dark:border-gray-700 rounded-lg p-4 hover:shadow-md transition-shadow cursor-pointer"
          >
            <div class="flex items-start justify-between mb-2">
              <div class="flex-1">
                <h3 class="font-semibold text-gray-900 dark:text-white">{{ day.name }}</h3>
                <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">{{ formatEventType(day.event_type) }}</p>
              </div>
              <div class="flex flex-col items-end gap-1">
                <span 
                  :class="getPriorityClass(day.priority)" 
                  class="px-2 py-1 rounded-full text-xs font-medium"
                >
                  {{ day.priority }}
                </span>
                <span 
                  :class="day.is_active ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300' : 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300'" 
                  class="px-2 py-1 rounded-full text-xs font-medium"
                >
                  {{ day.is_active ? 'Active' : 'Inactive' }}
                </span>
              </div>
            </div>
            <div class="text-xs text-gray-600 dark:text-gray-400 space-y-1">
              <p><strong>Date:</strong> {{ formatDate(day.event_date_this_year) }}</p>
              <p v-if="day.days_until !== undefined">
                <strong>Days Until:</strong> 
                <span :class="day.days_until <= 7 ? 'text-orange-600 dark:text-orange-400 font-semibold' : ''">
                  {{ day.days_until }} days
                </span>
              </p>
              <p v-if="day.countries_display?.length">
                <strong>Countries:</strong> {{ day.countries_display.join(', ') }}
              </p>
            </div>
          </div>
        </div>

        <!-- Desktop Table View -->
        <div class="hidden sm:block overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-800">
              <tr>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Name</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Type</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Date</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Days Until</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Priority</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Status</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
              <tr 
                v-for="day in filteredSpecialDays" 
                :key="day.id" 
                class="hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors cursor-pointer"
                @click="viewSpecialDay(day)"
              >
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap">
                  <div class="text-sm font-medium text-gray-900 dark:text-white">{{ day.name }}</div>
                  <div v-if="day.description" class="text-xs text-gray-500 dark:text-gray-400 truncate max-w-xs">
                    {{ day.description }}
                  </div>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  {{ formatEventType(day.event_type) }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                  {{ formatDate(day.event_date_this_year) }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm">
                  <span 
                    :class="day.days_until <= 7 ? 'text-orange-600 dark:text-orange-400 font-semibold' : 'text-gray-600 dark:text-gray-400'"
                  >
                    {{ day.days_until !== undefined ? `${day.days_until} days` : 'N/A' }}
                  </span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap">
                  <span 
                    :class="getPriorityClass(day.priority)" 
                    class="px-2 py-1 rounded-full text-xs font-medium"
                  >
                    {{ day.priority }}
                  </span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap">
                  <span 
                    :class="day.is_active ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300' : 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300'" 
                    class="px-2 py-1 rounded-full text-xs font-medium"
                  >
                    {{ day.is_active ? 'Active' : 'Inactive' }}
                  </span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <div class="flex items-center gap-2">
                    <button 
                      @click.stop="editSpecialDay(day)" 
                      class="text-primary-600 dark:text-primary-400 hover:text-primary-900 dark:hover:text-primary-300"
                      title="Edit"
                    >
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                    </button>
                    <button 
                      @click.stop="handleGenerateDiscount(day.id)" 
                      class="text-green-600 dark:text-green-400 hover:text-green-900 dark:hover:text-green-300"
                      title="Generate Discount"
                    >
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                      </svg>
                    </button>
                    <button 
                      @click.stop="handleDelete(day)" 
                      class="text-red-600 dark:text-red-400 hover:text-red-900 dark:hover:text-red-300"
                      title="Delete"
                    >
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div v-if="!filteredSpecialDays.length && !loading" class="text-center py-12 text-gray-500 dark:text-gray-400">
          <p class="text-lg">No special days found</p>
          <p class="text-sm mt-2">Create your first special day to get started</p>
        </div>
      </div>
    </div>

    <!-- Reminders Tab -->
    <div v-if="activeTab === 'reminders'" class="space-y-4">
      <div class="card overflow-hidden">
        <div v-if="loadingReminders" class="flex items-center justify-center py-12">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
        </div>
        <div v-else-if="reminders.length === 0" class="text-center py-12 text-gray-500 dark:text-gray-400">
          <p class="text-lg">No reminders found</p>
        </div>
        <div v-else class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-800">
              <tr>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Special Day</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Reminder Date</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Status</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Broadcast Sent</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Discount Created</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
              <tr 
                v-for="reminder in reminders" 
                :key="reminder.id" 
                class="hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
              >
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                  {{ reminder.special_day_name || 'N/A' }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  {{ formatDate(reminder.reminder_date) }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap">
                  <span 
                    :class="getStatusClass(reminder.status)" 
                    class="px-2 py-1 rounded-full text-xs font-medium"
                  >
                    {{ reminder.status }}
                  </span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  <span v-if="reminder.broadcast_sent" class="text-green-600 dark:text-green-400">✓</span>
                  <span v-else class="text-gray-400">—</span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  <span v-if="reminder.discount_created" class="text-green-600 dark:text-green-400">✓</span>
                  <span v-else class="text-gray-400">—</span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <div class="flex items-center gap-2">
                    <button 
                      v-if="reminder.status === 'pending'"
                      @click="markReminderSent(reminder.id)" 
                      class="text-blue-600 dark:text-blue-400 hover:text-blue-900 dark:hover:text-blue-300"
                      title="Mark as Sent"
                    >
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                      </svg>
                    </button>
                    <button 
                      v-if="!reminder.discount_created"
                      @click="createDiscountFromReminder(reminder.id)" 
                      class="text-green-600 dark:text-green-400 hover:text-green-900 dark:hover:text-green-300"
                      title="Create Discount"
                    >
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                      </svg>
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Campaigns Tab -->
    <div v-if="activeTab === 'campaigns'" class="space-y-4">
      <div class="card overflow-hidden">
        <div v-if="loadingCampaigns" class="flex items-center justify-center py-12">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
        </div>
        <div v-else-if="campaigns.length === 0" class="text-center py-12 text-gray-500 dark:text-gray-400">
          <p class="text-lg">No campaigns found</p>
        </div>
        <div v-else class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-800">
              <tr>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Special Day</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Year</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Discount Code</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Discount %</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Status</th>
                <th class="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Auto-Generated</th>
              </tr>
            </thead>
            <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
              <tr 
                v-for="campaign in campaigns" 
                :key="campaign.id" 
                class="hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
              >
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                  {{ campaign.special_day_name || 'N/A' }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  {{ campaign.year }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-900 dark:text-white">
                  {{ campaign.discount_code || 'N/A' }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                  {{ campaign.discount_percentage ? `${campaign.discount_percentage}%` : 'N/A' }}
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap">
                  <span 
                    :class="campaign.is_active ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300' : 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300'" 
                    class="px-2 py-1 rounded-full text-xs font-medium"
                  >
                    {{ campaign.is_active ? 'Active' : 'Inactive' }}
                  </span>
                </td>
                <td class="px-4 lg:px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  <span v-if="campaign.auto_generated" class="text-green-600 dark:text-green-400">✓</span>
                  <span v-else class="text-gray-400">—</span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Create/Edit Special Day Modal -->
    <div 
      v-if="showCreateModal || editingSpecialDay"
      class="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4 overflow-y-auto"
      @click.self="closeModal"
    >
      <div class="bg-white dark:bg-gray-800 rounded-lg max-w-4xl w-full my-auto p-4 md:p-6 max-h-[90vh] overflow-y-auto">
        <div class="flex items-center justify-between mb-6">
          <h3 class="text-xl md:text-2xl font-bold text-gray-900 dark:text-white">
            {{ editingSpecialDay ? 'Edit Special Day' : 'Create Special Day' }}
          </h3>
          <button 
            @click="closeModal" 
            class="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 text-2xl"
          >
            ✕
          </button>
        </div>
        <SpecialDayForm
          :special-day="editingSpecialDay"
          @save="handleSaveSpecialDay"
          @cancel="closeModal"
        />
      </div>
    </div>

    <!-- Special Day Detail Modal -->
    <div 
      v-if="selectedSpecialDay"
      class="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4 overflow-y-auto"
      @click.self="selectedSpecialDay = null"
    >
      <div class="bg-white dark:bg-gray-800 rounded-lg max-w-4xl w-full my-auto p-4 md:p-6 max-h-[90vh] overflow-y-auto">
        <div class="flex items-center justify-between mb-6">
          <h3 class="text-xl md:text-2xl font-bold text-gray-900 dark:text-white">{{ selectedSpecialDay?.name }}</h3>
          <button 
            @click="selectedSpecialDay = null" 
            class="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 text-2xl"
          >
            ✕
          </button>
        </div>
        <SpecialDayDetail
          :special-day="selectedSpecialDay"
          @edit="editSpecialDay"
          @generate-discount="generateDiscount"
          @close="selectedSpecialDay = null"
        />
      </div>
    </div>

  </div>

  <!-- Error State -->
  <div v-else-if="componentError" class="p-6">
    <div class="card p-6 text-center">
      <h2 class="text-xl font-bold text-red-900 dark:text-red-300 mb-2">Error Loading Page</h2>
      <p class="text-red-700 dark:text-red-400 mb-4">{{ componentError }}</p>
      <button @click="loadSpecialDays" class="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors">
        Retry
      </button>
    </div>
  </div>

  <!-- Loading State -->
  <div v-else-if="initialLoading" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
      <p class="mt-4 text-gray-600 dark:text-gray-400">Loading holidays...</p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useToast } from '@/composables/useToast'
import { holidaysAPI } from '@/api'
import SpecialDayForm from '@/components/holidays/SpecialDayForm.vue'
import SpecialDayDetail from '@/components/holidays/SpecialDayDetail.vue'

const { success: showSuccess, error: showError } = useToast()

// State
const activeTab = ref('special-days')
const loading = ref(false)
const loadingReminders = ref(false)
const loadingCampaigns = ref(false)
const checkingReminders = ref(false)
const generatingDiscounts = ref(false)
const initialLoading = ref(true)
const componentError = ref(null)
const showCreateModal = ref(false)
const editingSpecialDay = ref(null)
const selectedSpecialDay = ref(null)

const specialDays = ref([])
const reminders = ref([])
const campaigns = ref([])
const stats = ref({
  total: 0,
  upcoming: 0,
  activeCampaigns: 0
})

const filters = ref({
  country: '',
  event_type: '',
  is_active: '',
  upcoming: false
})

// Computed
const pendingRemindersCount = computed(() => {
  return reminders.value.filter(r => r.status === 'pending').length
})

const filteredSpecialDays = computed(() => {
  return specialDays.value
})

// Methods
const loadSpecialDays = async () => {
  loading.value = true
  componentError.value = null
  try {
    const params = {
      ...filters.value,
      upcoming: filters.value.upcoming ? 'true' : undefined
    }
    Object.keys(params).forEach(key => {
      if (params[key] === '' || params[key] === undefined) {
        delete params[key]
      }
    })
    
    const response = await holidaysAPI.specialDays.list(params)
    specialDays.value = response.data.results || response.data || []
    
    // Calculate stats
    stats.value.total = specialDays.value.length
    stats.value.upcoming = specialDays.value.filter(d => d.is_upcoming || (d.days_until !== undefined && d.days_until >= 0 && d.days_until <= 30)).length
  } catch (error) {
    console.error('Error loading special days:', error)
    const errorMessage = error.response?.data?.detail || error.response?.data?.message || error.message || 'Failed to load special days'
    componentError.value = errorMessage
    showError(errorMessage)
    // Still set initialLoading to false so the error message can be shown
    initialLoading.value = false
  } finally {
    loading.value = false
    if (initialLoading.value) {
      initialLoading.value = false
    }
  }
}

const loadReminders = async () => {
  loadingReminders.value = true
  try {
    const response = await holidaysAPI.reminders.list({ pending: 'true' })
    reminders.value = response.data.results || response.data || []
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to load reminders')
  } finally {
    loadingReminders.value = false
  }
}

const loadCampaigns = async () => {
  loadingCampaigns.value = true
  try {
    const response = await holidaysAPI.campaigns.list()
    campaigns.value = response.data.results || response.data || []
    stats.value.activeCampaigns = campaigns.value.filter(c => c.is_active).length
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to load campaigns')
  } finally {
    loadingCampaigns.value = false
  }
}

const checkReminders = async () => {
  checkingReminders.value = true
  try {
    await holidaysAPI.reminders.checkAndCreate()
    showSuccess('Reminders checked successfully')
    await loadReminders()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to check reminders')
  } finally {
    checkingReminders.value = false
  }
}

const autoGenerateDiscounts = async () => {
  generatingDiscounts.value = true
  try {
    const response = await holidaysAPI.specialDays.autoGenerateDiscounts()
    showSuccess(response.data.message || 'Discounts generated successfully')
    await loadCampaigns()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to generate discounts')
  } finally {
    generatingDiscounts.value = false
  }
}

const viewSpecialDay = (day) => {
  selectedSpecialDay.value = day
}

const editSpecialDay = (day) => {
  editingSpecialDay.value = day
  selectedSpecialDay.value = null
  showCreateModal.value = true
}

const handleSaveSpecialDay = async (data) => {
  try {
    if (editingSpecialDay.value) {
      await holidaysAPI.specialDays.update(editingSpecialDay.value.id, data)
      showSuccess('Special day updated successfully')
    } else {
      await holidaysAPI.specialDays.create(data)
      showSuccess('Special day created successfully')
    }
    closeModal()
    await loadSpecialDays()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to save special day')
  }
}

const handleGenerateDiscount = async (specialDayId) => {
  try {
    const year = new Date().getFullYear()
    await holidaysAPI.specialDays.generateDiscount(specialDayId, { year })
    showSuccess('Discount generated successfully')
    await loadCampaigns()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to generate discount')
  }
}

const generateDiscount = async (specialDayId, year) => {
  await handleGenerateDiscount(specialDayId)
  selectedSpecialDay.value = null
}

const handleDelete = async (day) => {
  if (!confirm(`Are you sure you want to delete "${day.name}"?`)) {
    return
  }
  try {
    await holidaysAPI.specialDays.delete(day.id)
    showSuccess('Special day deleted successfully')
    await loadSpecialDays()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to delete special day')
  }
}

const markReminderSent = async (reminderId) => {
  try {
    await holidaysAPI.reminders.markSent(reminderId)
    showSuccess('Reminder marked as sent')
    await loadReminders()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to mark reminder as sent')
  }
}

const createDiscountFromReminder = async (reminderId) => {
  try {
    await holidaysAPI.reminders.createDiscount(reminderId)
    showSuccess('Discount created successfully')
    await loadReminders()
    await loadCampaigns()
  } catch (error) {
    showError(error.response?.data?.detail || error.message || 'Failed to create discount')
  }
}

const resetFilters = () => {
  filters.value = {
    country: '',
    event_type: '',
    is_active: '',
    upcoming: false
  }
  loadSpecialDays()
}

const closeModal = () => {
  showCreateModal.value = false
  editingSpecialDay.value = null
}

const formatEventType = (type) => {
  const types = {
    'holiday': 'Holiday',
    'special_day': 'Special Day',
    'anniversary': 'Anniversary',
    'seasonal': 'Seasonal Event',
    'cultural': 'Cultural Event'
  }
  return types[type] || type
}

const formatDate = (dateString) => {
  if (!dateString) return 'N/A'
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

const getPriorityClass = (priority) => {
  const classes = {
    'low': 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300',
    'medium': 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300',
    'high': 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300',
    'critical': 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300',
  }
  return classes[priority] || classes.medium
}

const getStatusClass = (status) => {
  const classes = {
    'pending': 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300',
    'sent': 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
    'dismissed': 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300',
    'completed': 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
  }
  return classes[status] || classes.pending
}

// Watch tab changes
watch(activeTab, (newTab) => {
  if (newTab === 'reminders') {
    loadReminders()
  } else if (newTab === 'campaigns') {
    loadCampaigns()
  }
})

// Lifecycle
onMounted(async () => {
  // Set a timeout to ensure page doesn't stay blank forever
  const timeout = setTimeout(() => {
    if (initialLoading.value) {
      console.warn('HolidayManagement initialization timeout')
      initialLoading.value = false
      if (!componentError.value) {
        componentError.value = 'Page took too long to load. Please refresh.'
      }
    }
  }, 10000) // 10 second timeout

  try {
    await Promise.all([
      loadSpecialDays(),
      loadCampaigns() // Load campaigns for stats
    ])
    clearTimeout(timeout)
  } catch (error) {
    clearTimeout(timeout)
    console.error('Error initializing HolidayManagement:', error)
    componentError.value = error.message || 'Failed to initialize page'
    initialLoading.value = false
  }
})
</script>

<style scoped>
.card {
  background-color: white;
  border-radius: 0.5rem;
  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
  border: 1px solid rgb(229 231 235);
}

.dark .card {
  background-color: rgb(31 41 55);
  border-color: rgb(55 65 81);
}
</style>
