# Generated by Django 5.0.14 on 2026-05-28 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_management', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('thread_created', 'Thread created'), ('thread_locked', 'Thread locked'), ('thread_closed', 'Thread closed'), ('message_created', 'Message created'), ('message_edited', 'Message edited'), ('message_hidden', 'Message hidden'), ('message_deleted', 'Message deleted'), ('message_read', 'Message read'), ('participant_added', 'Participant added'), ('participant_removed', 'Participant removed'), ('attachment_added', 'Attachment added'), ('attachment_hidden', 'Attachment hidden'), ('moderation_flagged', 'Moderation flagged'), ('moderation_resolved', 'Moderation resolved'), ('escalation_created', 'Escalation created'), ('escalation_resolved', 'Escalation resolved'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed'), ('link_review_created', 'Link review created'), ('link_review_approved', 'Link review approved'), ('link_review_rejected', 'Link review rejected'), ('link_review_blocked', 'Link review blocked')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('reason', models.TextField()),
                ('resolution_note', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLinkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('internal_note', 'Internal note'), ('moderation_notice', 'Moderation notice')], default='user', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('held_for_review', 'Held for review')], default='active', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_body', models.TextField()),
                ('new_body', models.TextField()),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer'), ('admin', 'Admin'), ('superadmin', 'Superadmin'), ('support', 'Support'), ('finance', 'Finance'), ('observer', 'Observer'), ('system', 'System')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('can_send', models.BooleanField(default=True)),
                ('can_upload', models.BooleanField(default=True)),
                ('is_observer', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationSavedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationScreeningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pattern', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('regex', 'Regex')], default='contains', max_length=20)),
                ('action', models.CharField(choices=[('mask', 'Mask'), ('flag', 'Flag'), ('hold_for_review', 'Hold for review'), ('hide', 'Hide'), ('block', 'Block')], default='flag', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('replacement_text', models.CharField(default='*****', max_length=80)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_platform_rule', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('client_support', 'Client support'), ('client_writer', 'Client writer'), ('writer_support', 'Writer support'), ('admin_client', 'Admin client'), ('admin_writer', 'Admin writer'), ('internal_staff', 'Internal staff'), ('revision', 'Revision'), ('dispute', 'Dispute'), ('sensitive_coordination', 'Sensitive coordination'), ('system', 'System')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('archived', 'Archived'), ('closed', 'Closed')], default='open', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThreadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThreadPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_kind', models.CharField(max_length=40)),
                ('allow_client_messages', models.BooleanField(default=True)),
                ('allow_writer_messages', models.BooleanField(default=True)),
                ('allow_staff_messages', models.BooleanField(default=True)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('require_attachment_moderation', models.BooleanField(default=False)),
                ('require_message_moderation', models.BooleanField(default=False)),
                ('auto_add_support', models.BooleanField(default=True)),
                ('auto_add_assigned_writer', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThreadSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('next_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_writer_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_staff_response_at', models.DateTimeField(blank=True, null=True)),
                ('is_breached', models.BooleanField(default=False)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThreadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationThreadTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('requires_moderation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_attachments', to='files_management.managedfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_communication_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
