# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0002_initial'),
        ('special_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='special_orders.specialorder'),
        ),
    ]
