# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_add_content_type_fields'),
        ('orders', '0007_rename_orders_order_status_idx_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationthread',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order (not required for class_bundle threads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_thread', to='orders.order'),
        ),
    ]
