# Generated by Django 5.0.14 on 2025-12-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_add_message_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_thread__c48ee4_idx',
            old_name='comm_msg_thread_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_thread__25e2f8_idx',
            old_name='comm_msg_thread_read_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_sender__aeefc2_idx',
            old_name='comm_msg_sender_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_recipie_9ba47a_idx',
            old_name='comm_msg_recipient_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_thread__529214_idx',
            old_name='comm_msg_thread_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_thread__6c95ca_idx',
            old_name='comm_msg_thread_archived_idx',
        ),
    ]
