# Generated by Django 5.0.14 on 2025-12-22 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_add_writer_acknowledgment_message_review_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communicationmessage',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['is_deleted'], name='communicati_is_dele_1dd55e_idx'),
        ),
    ]
