# Generated by Django 5.0.14 on 2026-01-04 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_alter_communicationmessage_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0021_add_cancellation_request_model'),
        ('special_orders', '0004_specialorder_writer_payment_amount_and_more'),
        ('websites', '0011_add_external_review_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationthread',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['order', '-updated_at'], name='communicati_order_i_59cd56_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['website', '-updated_at'], name='communicati_website_8c93f0_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['thread_type', '-updated_at'], name='communicati_thread__ae43fd_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['is_active', '-updated_at'], name='communicati_is_acti_b33182_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['website', 'order', '-updated_at'], name='communicati_website_f29a14_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['website', 'thread_type', '-updated_at'], name='communicati_website_f30979_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['order', 'is_active'], name='communicati_order_i_54adc7_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['is_active', 'updated_at'], name='communicati_is_acti_8a6038_idx'),
        ),
    ]
