# Generated by Django 5.1.6 on 2025-02-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerpayoutpreference',
            name='preferred_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Crypto', 'Crypto'), ('Mpesa', 'Mpesa'), ('Other', 'Other')], default='PayPal', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
