# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional rating from 1 (worst) to 5 (best).', null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional client comment about the order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_deadline', models.DateTimeField()),
                ('new_deadline', models.DateTimeField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', help_text='The current status of the dispute.', max_length=20)),
                ('resolution_outcome', models.CharField(blank=True, choices=[('writer_wins', 'Writer Wins'), ('client_wins', 'Client Wins'), ('extend_deadline', 'Extend Deadline'), ('reassign', 'Reassign Order')], help_text='Outcome of the dispute resolution.', max_length=20, null=True)),
                ('reason', models.TextField(help_text='Reason for raising the dispute.')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes or comments regarding the resolution.', null=True)),
                ('writer_responded', models.BooleanField(default=False, help_text='Indicates whether the writer has responded.')),
                ('admin_extended_deadline', models.DateTimeField(blank=True, help_text='If set, admin has manually extended the deadline.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the dispute was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the dispute was last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeWriterResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text="Writer's response or clarification.")),
                ('response_file', models.FileField(blank=True, help_text='Optional file upload for revised work.', null=True, upload_to='dispute_responses/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of response.')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='The topic or title of the order.', max_length=255)),
                ('discount_code_used', models.CharField(blank=True, help_text='Discount code applied to the order.', max_length=100, null=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('number_of_pages', models.PositiveIntegerField(help_text='Number of pages required.')),
                ('number_of_slides', models.PositiveIntegerField(default=0, help_text='Number of slides.')),
                ('number_of_refereces', models.PositiveIntegerField(default=0, help_text='Number of references or sources.')),
                ('spacing', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', help_text='Spacing for the order.', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('submitted', 'SUBMITTED'), ('in_review', 'IN_REVIEW'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('in_progress', 'IN_PROGRESS'), ('revision_requested', 'REVISION_REQUESTED'), ('on_revision', 'ON_REVISION'), ('revised', 'REVISED'), ('completed', 'COMPLETED'), ('under_editing', 'UNDER_EDITING'), ('rated', 'RATED'), ('reviewed', 'REVIEWED'), ('closed', 'CLOSED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED'), ('created', 'CREATED'), ('reassigned', 'REASSIGNED'), ('unpaid', 'UNPAID'), ('pending', 'PENDING'), ('on_hold', 'ON_HOLD'), ('available', 'AVAILABLE'), ('pending_preferred', 'PENDING_PREFERRED'), ('critical', 'CRITICAL'), ('assigned', 'ASSIGNED'), ('late', 'LATE'), ('disputed', 'DISPUTED'), ('archived', 'ARCHIVED'), ('expired', 'EXPIRED'), ('under_review', 'UNDER_REVIEW'), ('re_opened', 'REOPENED')], default='created', help_text='Current status of the order.', max_length=20)),
                ('flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('UO', 'Urgent Order'), ('FCO', 'First Client Order'), ('HVO', 'High Value Order'), ('PO', 'Preferred Order'), ('RCO', 'Returning Client Order'), ('CO', 'Critical Order'), ('LO', 'Late Order'), ('DO', 'Disputed Order'), ('AO', 'Archived Order'), ('EO', 'Expired Order'), ('URO', 'Under Review Order'), ('RO', 'Reopened Order')], max_length=10), blank=True, default=list, help_text='Flags related to the order (e.g., Urgent Order (UO), Returning Client (RC0)).', size=None)),
                ('client_deadline', models.DateTimeField(help_text='The deadline for the order.')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total price of the order.', max_digits=10, null=True)),
                ('writer_compensation', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Compensation for the writer.', max_digits=10, null=True)),
                ('writer_deadline', models.DateTimeField(blank=True, help_text="Writer's deadline.", null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates if the order is paid.')),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_by_admin', models.BooleanField(default=False, help_text='Indicates if the order was created by an admin.')),
                ('is_special_order', models.BooleanField(default=False, help_text='Indicates if this is a special order.')),
                ('is_public', models.BooleanField(default=False)),
                ('reassignment_requested', models.BooleanField(default=False)),
                ('order_instructions', models.TextField(help_text='Detailed instructions for the order.')),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the order was last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_data', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_feedback', models.TextField(blank=True, null=True)),
                ('accepted_by_admin_at', models.DateTimeField(blank=True, null=True)),
                ('writer_accepted_assignment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('is_automatic', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PreferredWriterResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReassignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer')], help_text='Whether the client or writer requested this reassignment.', max_length=10)),
                ('admin_initiated', models.BooleanField(default=False, help_text='Was this reassignment initiated by admin?')),
                ('reason', models.TextField(help_text='The reason for requesting reassignment.')),
                ('fine_applied', models.DecimalField(decimal_places=2, default=0.0, help_text='Fine applied to writer if they requested reassignment near deadline.', max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned')], default='pending', help_text='The current status of the reassignment request.', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Optional field for system flags, debug info, auto-approved flags, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('request_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('text_description', models.TextField(blank=True, help_text='Optional update details.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WriterReassignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the reassignment.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the reassignment occurred.')),
            ],
            options={
                'verbose_name': 'Writer Reassignment Log',
                'verbose_name_plural': 'Writer Reassignment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('deadline_extension', 'Deadline Extension'), ('page_increase', 'Page Increase'), ('slide_increase', 'Slide Increase')], max_length=50)),
                ('new_deadline', models.DateTimeField(blank=True, null=True)),
                ('additional_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_slides', models.PositiveIntegerField(blank=True, null=True)),
                ('request_reason', models.TextField()),
                ('client_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of request', max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Final cost to be charged', max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('requires_payment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
