# Generated by Django 5.0.14 on 2026-05-28 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '__first__'),
        ('discounts', '__first__'),
        ('order_configs', '0002_initial'),
        ('order_pricing_core', '0002_initial'),
        ('orders', '0001_initial'),
        ('websites', '0001_initial'),
        ('writer_management', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dispute', to='websites.website'),
        ),
        migrations.AddField(
            model_name='disputewriterresponse',
            name='dispute',
            field=models.ForeignKey(help_text='The dispute being responded to.', on_delete=django.db.models.deletion.CASCADE, related_name='writer_responses_to_disputes', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='disputewriterresponse',
            name='responded_by',
            field=models.ForeignKey(help_text='The writer responding to the dispute.', limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_writer_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputewriterresponse',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_writer_response', to='websites.website'),
        ),
        migrations.AddField(
            model_name='draftrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='User who requested the draft (client or admin)', on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='order',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text='Requested academic level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order_configs.academiclevel'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client who placed the order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed the order workflow, if completed manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Actor who soft deleted the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Discount applied to the order, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='english_type',
            field=models.ForeignKey(blank=True, help_text='Requested English variant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_configs.englishtype'),
        ),
        migrations.AddField(
            model_name='order',
            name='formatting_style',
            field=models.ForeignKey(blank=True, help_text='Formatting or citation style.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_configs.formattingandcitationstyle'),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_type',
            field=models.ForeignKey(help_text='Requested paper type.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order_configs.papertype'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_writer',
            field=models.ForeignKey(blank=True, help_text='Preferred writer chosen for the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_order',
            field=models.ForeignKey(blank=True, help_text='Previous order this order follows up on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_snapshot',
            field=models.ForeignKey(blank=True, help_text="Current upstream pricing-core snapshot used for the order's present commercial state.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order_pricing_core.pricingsnapshot'),
        ),
        migrations.AddField(
            model_name='order',
            name='qa_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='restored_by',
            field=models.ForeignKey(blank=True, help_text='Actor who restored the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Academic subject area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_configs.subject'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_work',
            field=models.ForeignKey(blank=True, help_text='Requested type of work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_configs.typeofwork'),
        ),
        migrations.AddField(
            model_name='order',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='websites.website'),
        ),
        migrations.AddField(
            model_name='order',
            name='writer_level',
            field=models.ForeignKey(blank=True, help_text='Requested writer level option.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_pricing_core.writerlevelrate'),
        ),
        migrations.AddField(
            model_name='draftrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(help_text='The order associated with this dispute.', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_disputes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderadjustmentevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Actor associated with the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_adjustment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderadjustmentevent',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this event.', on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustment_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderadjustmentfunding',
            name='billing_payment_request',
            field=models.ForeignKey(blank=True, help_text='Billing payment request linked to the adjustment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_adjustment_fundings', to='billing.paymentrequest'),
        ),
        migrations.AddField(
            model_name='orderadjustmentfunding',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Billing invoice linked to the adjustment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_adjustment_fundings', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='orderadjustmentfunding',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this funding record.', on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustment_fundings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderadjustmentpricingsnapshot',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this pricing snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustment_pricing_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderadjustmentproposal',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='Actor who created the proposal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_adjustment_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderadjustmentproposal',
            name='supersedes_proposal',
            field=models.ForeignKey(blank=True, help_text='Previous proposal this proposal supersedes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='orders.orderadjustmentproposal'),
        ),
        migrations.AddField(
            model_name='orderadjustmentproposal',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this proposal.', on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustment_proposals', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderadjustmentpricingsnapshot',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Proposal this pricing snapshot was generated for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_snapshots', to='orders.orderadjustmentproposal'),
        ),
        migrations.AddField(
            model_name='orderadjustmentevent',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Related proposal for the event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orders.orderadjustmentproposal'),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='accepted_proposal',
            field=models.ForeignKey(blank=True, help_text='Proposal that became commercially binding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by_adjustment_requests', to='orders.orderadjustmentproposal'),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='counter_pricing_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_adjustment_requests', to='order_pricing_core.pricingsnapshot'),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='countered_by',
            field=models.ForeignKey(blank=True, help_text='Actor who issued the counter proposal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countered_order_adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='current_proposal',
            field=models.ForeignKey(blank=True, help_text='Latest active proposal in the negotiation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_adjustment_requests', to='orders.orderadjustmentproposal'),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='order',
            field=models.ForeignKey(help_text='Order affected by the adjustment request.', on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Actor who initiated the adjustment request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Actor who last reviewed the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_order_adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='source_pricing_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_requests', to='order_pricing_core.pricingsnapshot'),
        ),
        migrations.AddField(
            model_name='orderadjustmentrequest',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns the adjustment request.', on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustment_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderadjustmentproposal',
            name='adjustment_request',
            field=models.ForeignKey(help_text='Adjustment request this proposal belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='orderadjustmentpricingsnapshot',
            name='adjustment_request',
            field=models.ForeignKey(help_text='Adjustment request this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_snapshots', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='orderadjustmentfunding',
            name='adjustment_request',
            field=models.OneToOneField(help_text='Adjustment request this funding record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='funding', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='orderadjustmentevent',
            name='adjustment_request',
            field=models.ForeignKey(help_text='Adjustment request this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='orderadjustmentscopesnapshot',
            name='adjustment_request',
            field=models.OneToOneField(help_text='Adjustment request this scope snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_snapshot', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='orderadjustmentscopesnapshot',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this scope snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustment_scope_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Actor who performed the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(help_text='Order being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignment', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='ordercompensationadjustment',
            name='adjustment_request',
            field=models.ForeignKey(help_text='Adjustment request that created this compensation.', on_delete=django.db.models.deletion.CASCADE, related_name='compensation_adjustments', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='ordercompensationadjustment',
            name='order',
            field=models.ForeignKey(help_text='Order this compensation adjustment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='compensation_adjustments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordercompensationadjustment',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this compensation record.', on_delete=django.db.models.deletion.CASCADE, related_name='order_compensation_adjustments', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ordercompensationadjustment',
            name='writer',
            field=models.ForeignKey(blank=True, help_text='Writer affected by the compensation delta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_compensation_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, help_text='Staff actor currently reviewing the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='opened_by',
            field=models.ForeignKey(blank=True, help_text='Actor who opened the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_order_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='order',
            field=models.ForeignKey(help_text='Order this dispute belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this dispute.', on_delete=django.db.models.deletion.CASCADE, related_name='order_disputes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderdisputeevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Actor associated with the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_dispute_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdisputeevent',
            name='dispute',
            field=models.ForeignKey(help_text='Dispute this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderdispute'),
        ),
        migrations.AddField(
            model_name='orderdisputeevent',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this dispute event.', on_delete=django.db.models.deletion.CASCADE, related_name='order_dispute_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderdisputeresolution',
            name='dispute',
            field=models.OneToOneField(help_text='Dispute this resolution belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='orders.orderdispute'),
        ),
        migrations.AddField(
            model_name='orderdisputeresolution',
            name='reassign_to_writer',
            field=models.ForeignKey(blank=True, help_text='Replacement writer when outcome is reassignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_reassignments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdisputeresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Staff actor who resolved the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdisputeresolution',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this resolution record.', on_delete=django.db.models.deletion.CASCADE, related_name='order_dispute_resolutions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderflag',
            name='order',
            field=models.ForeignKey(help_text='Order this flag belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='flag_records', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderflag',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this order flag.', on_delete=django.db.models.deletion.CASCADE, related_name='order_flags', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderhold',
            name='order',
            field=models.ForeignKey(help_text='Order placed on hold.', on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderhold',
            name='placed_by',
            field=models.ForeignKey(blank=True, help_text='Staff actor who placed the hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_order_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhold',
            name='released_by',
            field=models.ForeignKey(blank=True, help_text='Staff actor who released the hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_order_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhold',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Actor who requested the hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_order_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhold',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this hold record.', on_delete=django.db.models.deletion.CASCADE, related_name='order_holds', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderinterest',
            name='order',
            field=models.ForeignKey(help_text='Order the writer expressed interest in.', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderinterest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Actor who reviewed the interest record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_order_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderinterest',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this interest record.', on_delete=django.db.models.deletion.CASCADE, related_name='order_interests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderinterest',
            name='writer',
            field=models.ForeignKey(help_text='Writer who expressed interest or received invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='order_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='source_interest',
            field=models.ForeignKey(blank=True, help_text='Interest record that produced this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_assignments', to='orders.orderinterest'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pricing_snapshot',
            field=models.ForeignKey(blank=True, help_text='Frozen pricing snapshot used to create this order item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='order_pricing_core.pricingsnapshot'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderpricingsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Actor who generated the pricing snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_pricing_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpricingsnapshot',
            name='order',
            field=models.ForeignKey(help_text='Order this pricing snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_snapshots', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpricingsnapshot',
            name='source_pricing_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_snapshots', to='order_pricing_core.pricingsnapshot'),
        ),
        migrations.AddField(
            model_name='orderpricingsnapshot',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this pricing snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='order_pricing_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderreassignmentrequest',
            name='assign_to_writer',
            field=models.ForeignKey(blank=True, help_text='Writer chosen when assigning directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_order_reassignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderreassignmentrequest',
            name='current_assignment',
            field=models.ForeignKey(blank=True, help_text='Current assignment being challenged or released.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_requests', to='orders.orderassignment'),
        ),
        migrations.AddField(
            model_name='orderreassignmentrequest',
            name='order',
            field=models.ForeignKey(help_text='Order affected by the reassignment request.', on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderreassignmentrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Actor who requested reassignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_order_reassignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderreassignmentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff actor who reviewed the reassignment request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_order_reassignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderreassignmentrequest',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this reassignment request.', on_delete=django.db.models.deletion.CASCADE, related_name='order_reassignment_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrevisionevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Actor associated with the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_revision_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrevisionevent',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this revision event.', on_delete=django.db.models.deletion.CASCADE, related_name='order_revision_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderrevisionrequest',
            name='order',
            field=models.ForeignKey(help_text='Order this revision request belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderrevisionrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Actor who requested the revision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrevisionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Actor who reviewed the revision request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrevisionrequest',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this revision request.', on_delete=django.db.models.deletion.CASCADE, related_name='order_revision_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderrevisionevent',
            name='revision_request',
            field=models.ForeignKey(help_text='Revision request this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderrevisionrequest'),
        ),
        migrations.AddField(
            model_name='orderscope',
            name='order',
            field=models.OneToOneField(help_text='Order this scope record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderscope',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this scope record.', on_delete=django.db.models.deletion.CASCADE, related_name='order_scopes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ordertimelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Actor associated with the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertimelineevent',
            name='order',
            field=models.ForeignKey(help_text='Order this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordertimelineevent',
            name='website',
            field=models.ForeignKey(help_text='Tenant website that owns this event.', on_delete=django.db.models.deletion.CASCADE, related_name='order_timeline_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_reassignment_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='preferred_writer',
            field=models.ForeignKey(blank=True, help_text='Optional preferred writer requested by the client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_reassignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin or system user who processed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='requester',
            field=models.ForeignKey(help_text='The actual user who made the request.', on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidordermessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unpaid_order_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidordermessage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_unpaid_order_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidordermessage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_order_messages', to='websites.website'),
        ),
        migrations.AddField(
            model_name='unpaidordermessagedispatch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_order_message_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidordermessagedispatch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_order_message_dispatches', to='orders.order'),
        ),
        migrations.AddField(
            model_name='unpaidordermessagedispatch',
            name='unpaid_order_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='orders.unpaidordermessage'),
        ),
        migrations.AddField(
            model_name='unpaidordermessagedispatch',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_order_message_dispatches', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='order',
            field=models.ForeignKey(help_text='The order associated with this progress log.', on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_progress', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, help_text='Admin/superadmin who withdrew this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_progress_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='writer',
            field=models.ForeignKey(help_text='The writer associated with this progress log.', limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='writerrequest',
            name='requested_by_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_deadline_pages_request', to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='disputewriterresponse',
            unique_together={('dispute', 'responded_by')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['website', 'status'], name='orders_orde_website_e58188_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_orde_client__7fa500_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['visibility_mode', 'status'], name='orders_orde_visibil_f44131_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['preferred_writer', 'status'], name='orders_orde_preferr_69e3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='orders_orde_status_c50fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['website', 'payment_status'], name='orders_orde_website_af0329_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['website', 'is_deleted'], name='orders_orde_website_0e590d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='orders_order_total_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='orders_order_amount_paid_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('writer_compensation__gte', 0)), name='orders_order_writer_comp_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_writer_fee_amount__gte', 0)), name='orders_order_pref_fee_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='draftrequest',
            index=models.Index(fields=['order', 'status'], name='orders_draf_order_i_3deb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='draftrequest',
            index=models.Index(fields=['requested_by', 'status'], name='orders_draf_request_736415_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentrequest',
            index=models.Index(fields=['website', 'status'], name='orders_orde_website_f94b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentrequest',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_18b123_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentrequest',
            index=models.Index(fields=['requested_by', 'status'], name='orders_orde_request_3a38be_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentrequest',
            index=models.Index(fields=['expires_at'], name='orders_orde_expires_1a53f0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentrequest',
            index=models.Index(fields=['created_at'], name='orders_orde_created_f81504_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentproposal',
            index=models.Index(fields=['website', 'adjustment_request'], name='orders_orde_website_ef1869_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentproposal',
            index=models.Index(fields=['adjustment_request', 'is_active'], name='orders_orde_adjustm_a7d990_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentproposal',
            index=models.Index(fields=['proposal_type', 'created_at'], name='orders_orde_proposa_90cf90_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderadjustmentproposal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='orders_adj_proposal_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentpricingsnapshot',
            index=models.Index(fields=['website', 'adjustment_request'], name='orders_orde_website_2798dc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentpricingsnapshot',
            index=models.Index(fields=['adjustment_request', 'proposal'], name='orders_orde_adjustm_b84632_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderadjustmentpricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', 0)), name='orders_adj_price_snap_base_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderadjustmentpricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('computed_amount__gte', 0)), name='orders_adj_price_snap_computed_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentfunding',
            index=models.Index(fields=['website', 'status'], name='orders_orde_website_b5e192_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentfunding',
            index=models.Index(fields=['payment_request_reference'], name='orders_orde_payment_22a81a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentfunding',
            index=models.Index(fields=['payment_intent_reference'], name='orders_orde_payment_1db858_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentfunding',
            index=models.Index(fields=['invoice_reference'], name='orders_orde_invoice_e0dde0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentfunding',
            index=models.Index(fields=['funding_reference'], name='orders_orde_funding_32be9c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentfunding',
            index=models.Index(fields=['created_at'], name='orders_orde_created_aaecba_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentevent',
            index=models.Index(fields=['website', 'adjustment_request'], name='orders_orde_website_9d5da0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentevent',
            index=models.Index(fields=['adjustment_request', 'event_type'], name='orders_orde_adjustm_c2debc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentevent',
            index=models.Index(fields=['created_at'], name='orders_orde_created_4fb2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderadjustmentscopesnapshot',
            index=models.Index(fields=['website', 'adjustment_request'], name='orders_orde_website_9aaf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercompensationadjustment',
            index=models.Index(fields=['website', 'status'], name='orders_orde_website_dc18ad_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercompensationadjustment',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_e60f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercompensationadjustment',
            index=models.Index(fields=['writer', 'status'], name='orders_orde_writer__bd73a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordercompensationadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_delta__gte', 0)), name='orders_comp_adj_amount_delta_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['website', 'status'], name='orders_orde_website_8e21c5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_6f4bea_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['opened_by', 'status'], name='orders_orde_opened__c8c5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['assigned_reviewer', 'status'], name='orders_orde_assigne_6940cb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['opened_at'], name='orders_orde_opened__684aaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdispute',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'in_review', 'escalated'])), fields=('order',), name='orders_one_active_dispute_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderdisputeevent',
            index=models.Index(fields=['website', 'dispute'], name='orders_orde_website_736622_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputeevent',
            index=models.Index(fields=['dispute', 'event_type'], name='orders_orde_dispute_76d15a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputeevent',
            index=models.Index(fields=['created_at'], name='orders_orde_created_04e552_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputeresolution',
            index=models.Index(fields=['website', 'outcome'], name='orders_orde_website_a0c812_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputeresolution',
            index=models.Index(fields=['resolved_at'], name='orders_orde_resolve_4de419_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdisputeresolution',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__isnull', True), ('refund_amount__gte', 0), _connector='OR'), name='orders_dispute_resolution_refund_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='orderflag',
            index=models.Index(fields=['website', 'flag_key'], name='orders_orde_website_18ad34_idx'),
        ),
        migrations.AddIndex(
            model_name='orderflag',
            index=models.Index(fields=['order', 'is_active'], name='orders_orde_order_i_6177d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderflag',
            constraint=models.UniqueConstraint(fields=('order', 'flag_key'), name='unique_order_flag_key'),
        ),
        migrations.AddIndex(
            model_name='orderhold',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_8a2569_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhold',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_5803ba_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhold',
            index=models.Index(fields=['status', 'requested_at'], name='orders_orde_status_674255_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderhold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('order',), name='orders_one_active_hold_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderinterest',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_6af9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinterest',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_cbdfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinterest',
            index=models.Index(fields=['writer', 'status'], name='orders_orde_writer__09aac7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinterest',
            index=models.Index(fields=['interest_type', 'status'], name='orders_orde_interes_7cbfc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderinterest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('order', 'writer', 'interest_type'), name='orders_interest_one_open_per_type'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_b2e9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['order', 'is_current'], name='orders_orde_order_i_a5fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['writer', 'status'], name='orders_orde_writer__6d5014_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['source', 'status'], name='orders_orde_source_8bf515_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('order',), name='orders_one_current_assignment_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_4fbaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['website', 'service_family'], name='orders_orde_website_15757b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['website', 'service_code'], name='orders_orde_website_3095e7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpricingsnapshot',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_6d3bed_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpricingsnapshot',
            index=models.Index(fields=['order', 'is_current'], name='orders_orde_order_i_cad50f_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderpricingsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('order',), name='unique_current_order_pricing_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='orderpricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='orders_price_snap_subtotal_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderpricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='orders_price_snap_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderpricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='orders_price_snap_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderpricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('writer_compensation_amount__gte', 0)), name='orders_price_snap_writer_comp_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='orderreassignmentrequest',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_8cea71_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreassignmentrequest',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_a66607_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreassignmentrequest',
            index=models.Index(fields=['requested_by', 'status'], name='orders_orde_request_afacf1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreassignmentrequest',
            index=models.Index(fields=['reviewed_by', 'status'], name='orders_orde_reviewe_3d6f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreassignmentrequest',
            index=models.Index(fields=['created_at'], name='orders_orde_created_d4b85d_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderreassignmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='orders_one_pending_reassignment_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['order', 'expires_at'], name='orders_orde_order_i_8ec5bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrequest',
            unique_together={('order', 'writer')},
        ),
        migrations.AddIndex(
            model_name='orderrevisionrequest',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_dc66cb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrevisionrequest',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_e55c69_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrevisionrequest',
            index=models.Index(fields=['created_at'], name='orders_orde_created_e3b723_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrevisionevent',
            index=models.Index(fields=['website', 'revision_request'], name='orders_orde_website_c58f85_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrevisionevent',
            index=models.Index(fields=['revision_request', 'event_type'], name='orders_orde_revisio_07dd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrevisionevent',
            index=models.Index(fields=['created_at'], name='orders_orde_created_6a745c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderscope',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_d9308e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimelineevent',
            index=models.Index(fields=['website', 'order'], name='orders_orde_website_530eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimelineevent',
            index=models.Index(fields=['order', 'event_type'], name='orders_orde_order_i_17fca7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimelineevent',
            index=models.Index(fields=['created_at'], name='orders_orde_created_81d3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='unpaidordermessage',
            index=models.Index(fields=['website', 'is_active'], name='orders_unpa_website_6892ed_idx'),
        ),
        migrations.AddIndex(
            model_name='unpaidordermessage',
            index=models.Index(fields=['website', 'sequence_number'], name='orders_unpa_website_b19dbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='unpaidordermessage',
            constraint=models.UniqueConstraint(fields=('website', 'sequence_number'), name='uq_unpaid_order_message_website_sequence'),
        ),
        migrations.AddIndex(
            model_name='unpaidordermessagedispatch',
            index=models.Index(fields=['website', 'status', 'scheduled_for'], name='orders_unpa_website_1c086a_idx'),
        ),
        migrations.AddIndex(
            model_name='unpaidordermessagedispatch',
            index=models.Index(fields=['order', 'status'], name='orders_unpa_order_i_822425_idx'),
        ),
        migrations.AddIndex(
            model_name='unpaidordermessagedispatch',
            index=models.Index(fields=['client', 'status'], name='orders_unpa_client__c5f8ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='unpaidordermessagedispatch',
            constraint=models.UniqueConstraint(fields=('order', 'unpaid_order_message'), name='uq_unpaid_order_dispatch_order_message'),
        ),
        migrations.AddIndex(
            model_name='writerprogress',
            index=models.Index(fields=['order', '-timestamp'], name='orders_writ_order_i_0ec762_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprogress',
            index=models.Index(fields=['writer', '-timestamp'], name='orders_writ_writer__70d8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprogress',
            index=models.Index(fields=['is_withdrawn'], name='orders_writ_is_with_8460ec_idx'),
        ),
        migrations.AddIndex(
            model_name='writerrequest',
            index=models.Index(fields=['order', 'request_type', 'status'], name='orders_writ_order_i_e787eb_idx'),
        ),
    ]
