# Generated by Django 6.0.5 on 2026-05-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_operational_note'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderoperationalnote',
            new_name='orders_orde_order_i_d0cfbe_idx',
            old_name='orders_orde_order_i_idx',
        ),
    ]
