# Generated by Django 5.0.14 on 2025-11-24 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_orders_order_status_idx_orders_orde_status_c6dd84_idx_and_more'),
        ('websites', '0002_add_payment_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the draft request', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from client about what they want to see', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the draft was requested')),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When the writer uploaded the draft', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the request was cancelled', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests', to='orders.order')),
                ('requested_by', models.ForeignKey(help_text='Client who requested the draft', on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests_made', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests', to='websites.website')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The draft file', upload_to='draft_files/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('description', models.TextField(blank=True, help_text="Optional description of what's in this draft", null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the draft was uploaded')),
                ('is_visible_to_client', models.BooleanField(default=True, help_text='Whether client can view this draft')),
                ('order', models.ForeignKey(help_text='The order this draft belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='draft_files', to='orders.order')),
                ('uploaded_by', models.ForeignKey(help_text='Writer who uploaded the draft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_files_uploaded', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_files', to='websites.website')),
                ('draft_request', models.ForeignKey(help_text='The draft request this file fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.draftrequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='draftrequest',
            index=models.Index(fields=['order', 'status'], name='orders_draf_order_i_3deb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='draftrequest',
            index=models.Index(fields=['requested_by', 'status'], name='orders_draf_request_736415_idx'),
        ),
        migrations.AddIndex(
            model_name='draftfile',
            index=models.Index(fields=['draft_request', 'uploaded_at'], name='orders_draf_draft_r_fcc3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='draftfile',
            index=models.Index(fields=['order', 'uploaded_at'], name='orders_draf_order_i_56a49e_idx'),
        ),
    ]
