# Generated by Django 5.2.2 on 2026-06-08 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_allow_non_paper_orders'),
        ('payments_processor', '0004_paymentintent_client_disclosure_text_and_more'),
        ('websites', '0005_payment_disclosure_acknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name/description for this reminder (e.g., 'First Reminder', 'Final Warning')", max_length=255)),
                ('deadline_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of deadline elapsed when to send (e.g., 30.00 for 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('message', models.TextField(help_text='Message to send in notification/email')),
                ('send_as_notification', models.BooleanField(default=True, help_text='Send as in-app notification')),
                ('send_as_email', models.BooleanField(default=True, help_text='Send as email')),
                ('email_subject', models.CharField(blank=True, help_text='Email subject (if blank, uses default)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reminder is active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying reminders (lower = earlier)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this reminder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website this reminder config applies to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminder_configs', to='websites.website')),
            ],
            options={
                'verbose_name': 'Payment Reminder Configuration',
                'verbose_name_plural': 'Payment Reminder Configurations',
                'ordering': ['display_order', 'deadline_percentage'],
                'unique_together': {('website', 'deadline_percentage')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReminderDeletionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message to send when order is deleted after deadline')),
                ('send_as_notification', models.BooleanField(default=True, help_text='Send as in-app notification')),
                ('send_as_email', models.BooleanField(default=True, help_text='Send as email')),
                ('email_subject', models.CharField(blank=True, help_text='Email subject (if blank, uses default)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this deletion message is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deletion_messages', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website this message applies to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_deletion_messages', to='websites.website')),
            ],
            options={
                'verbose_name': 'Payment Deletion Message',
                'verbose_name_plural': 'Payment Deletion Messages',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reminder_hours', models.PositiveIntegerField(default=12, help_text='Hours before expiration for the first reminder.')),
                ('final_reminder_hours', models.PositiveIntegerField(default=3, help_text='Hours before expiration for the final reminder.')),
                ('first_reminder_message', models.TextField(default='Your order payment is still pending. Please complete it to avoid cancellation.', help_text='Message for the first reminder email/notification.')),
                ('final_reminder_message', models.TextField(default='Your order payment will expire soon. Complete payment now to prevent cancellation.', help_text='Message for the final reminder email/notification.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin who last updated the settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminder_settings', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_reminders', to='websites.website')),
            ],
            options={
                'verbose_name': 'Payment Reminder Setting',
                'verbose_name_plural': 'Payment Reminder Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminderSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_as_notification', models.BooleanField(default=False)),
                ('sent_as_email', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders_sent', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_sent', to='payments_processor.paymentintent')),
                ('reminder_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to='orders.paymentreminderconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'reminder_config'], name='orders_paym_order_i_c9a3aa_idx'), models.Index(fields=['payment', 'reminder_config'], name='orders_paym_payment_437b74_idx'), models.Index(fields=['client', 'sent_at'], name='orders_paym_client__bfb4b0_idx')],
                'unique_together': {('reminder_config', 'order', 'payment')},
            },
        ),
    ]
