# Generated by Django 5.0.14 on 2025-11-27 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_configs', '0004_alter_englishtype_code_alter_englishtype_name_and_more'),
        ('orders', '0008_add_draft_requests'),
        ('websites', '0002_add_payment_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for easy identification', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('topic', models.CharField(max_length=500)),
                ('number_of_pages', models.PositiveIntegerField(default=1)),
                ('order_instructions', models.TextField()),
                ('additional_services', models.JSONField(blank=True, default=list)),
                ('preferred_writer_id', models.IntegerField(blank=True, null=True)),
                ('preferred_deadline_days', models.PositiveIntegerField(blank=True, help_text='Default number of days from now for deadline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.academiclevel')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_templates', to=settings.AUTH_USER_MODEL)),
                ('paper_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.papertype')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.subject')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
            options={
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['client', 'is_active'], name='orders_orde_client__d1f9dc_idx'), models.Index(fields=['website'], name='orders_orde_website_a9385b_idx')],
            },
        ),
    ]
