# Generated by Django 5.2.2 on 2026-06-17 05:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment_reminder_models'),
        ('websites', '0009_add_wagtail_site_to_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Client's reason for requesting cancellation")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the cancellation request', max_length=20)),
                ('deadline_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of deadline elapsed when cancellation was requested', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('forfeiture_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of order amount to forfeit (calculated based on deadline percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('forfeiture_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount to forfeit (calculated from forfeiture_percentage)', max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to refund to client (total_price - forfeiture_amount)', max_digits=10)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on the cancellation request', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancellation Request',
                'verbose_name_plural': 'Cancellation Requests',
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyOrderPricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_data', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders_legacyorderpricingsnapshot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('is_automatic', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterAssignmentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Whether the writer has accepted or rejected the assignment', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Writer's reason for accepting or rejecting (optional)", null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was made')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the writer accepted or rejected', null=True)),
            ],
            options={
                'verbose_name': 'Writer Assignment Acceptance',
                'verbose_name_plural': 'Writer Assignment Acceptances',
                'ordering': ['-assigned_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterReassignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the reassignment.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the reassignment occurred.')),
            ],
            options={
                'verbose_name': 'Writer Reassignment Log',
                'verbose_name_plural': 'Writer Reassignment Logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('unpaid', 'Unpaid'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('ready_for_staffing', 'Ready for Staffing'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('qa_review', 'QA Review'), ('under_editing', 'Under Editing'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('archived', 'Archived'), ('revision_requested', 'Revision Requested'), ('pending_writer_acceptance', 'Pending Writer Acceptance'), ('pending_cancellation', 'Pending Cancellation')], default='created', help_text='Current order workflow status.', max_length=32),
        ),
        migrations.AlterField(
            model_name='ordertimelineevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('pool_opened', 'Pool Opened'), ('preferred_writer_invited', 'Preferred Writer Invited'), ('preferred_writer_accepted', 'Preferred Writer Accepted'), ('preferred_writer_declined', 'Preferred Writer Declined'), ('preferred_writer_expired', 'Preferred Writer Expired'), ('interest_created', 'Interest Created'), ('interest_withdrawn', 'Interest Withdrawn'), ('interests_reactivated', 'Interests Reactivated'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('returned_to_pool', 'Returned To Pool'), ('reassignment_requested', 'Reassignment Requested'), ('reassignment_rejected', 'Reassignment Rejected'), ('reassignment_cancelled', 'Reassignment Cancelled'), ('hold_requested', 'Hold Requested'), ('hold_activated', 'Hold Activated'), ('hold_released', 'Hold Released'), ('writer_acknowledged', 'Writer Acknowledged'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('soft_deleted', 'Soft Deleted'), ('restored', 'Restored'), ('adjustment_created', 'Adjustment Created'), ('adjustment_funded', 'Adjustment Funded'), ('assignment_accepted', 'Assignment Accepted'), ('assignment_rejected', 'Assignment Rejected'), ('cancellation_requested', 'Cancellation Requested'), ('cancellation_approved', 'Cancellation Approved'), ('cancellation_rejected', 'Cancellation Rejected')], help_text='Type of business event.', max_length=64),
        ),
        migrations.CreateModel(
            name='OrderCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('pre_request_status', models.CharField(help_text='Order status before the request was made — used to revert on rejection.', max_length=50)),
                ('forfeiture_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of order value forfeited (0–80).', max_digits=5)),
                ('forfeiture_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cancellation_requests', to='orders.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cancellation_requests', to='websites.website')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDirectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_assignment', to='orders.order')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_direct_assignments', to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
