# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_add_public_order_number_and_sequence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordernumbersequence",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ordernumbersequence",
            constraint=models.UniqueConstraint(
                fields=("website", "scope", "period"),
                condition=models.Q(("is_active", True)),
                name="uniq_active_order_number_sequence_per_period",
            ),
        ),
    ]
