# Generated by Django 5.0.14 on 2025-12-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_add_writer_acknowledgment_message_review_reminders'),
        ('orders', '0012_add_writer_acknowledgment_message_review_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('unread', 'Unread Message'), ('unresponded', 'Unresponded Message'), ('urgent', 'Urgent Response Needed')], default='unread', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_responded', models.BooleanField(default=False)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('next_reminder_at', models.DateTimeField(blank=True, help_text='When to send the next reminder', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, help_text='Specific message that needs attention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='communications.communicationmessage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reminders', to='orders.order')),
                ('user', models.ForeignKey(help_text='User who needs to be reminded', on_delete=django.db.models.deletion.CASCADE, related_name='message_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'is_responded'], name='orders_mess_user_id_b2bb6d_idx'), models.Index(fields=['order', 'reminder_type'], name='orders_mess_order_i_2840f9_idx'), models.Index(fields=['next_reminder_at'], name='orders_mess_next_re_bb34e3_idx')],
                'unique_together': {('order', 'user', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ReviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_completed_at', models.DateTimeField(help_text='When the order was completed')),
                ('has_reviewed', models.BooleanField(default=False)),
                ('has_rated', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating given (1-5)', null=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('next_reminder_at', models.DateTimeField(blank=True, help_text='When to send the next reminder', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_reminders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_reminder', to='orders.order')),
                ('writer', models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer_review_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_completed_at'],
                'indexes': [models.Index(fields=['client', 'has_reviewed', 'has_rated'], name='orders_revi_client__322f69_idx'), models.Index(fields=['order'], name='orders_revi_order_i_0932b2_idx'), models.Index(fields=['next_reminder_at'], name='orders_revi_next_re_5c61aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='WriterAssignmentAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('has_sent_message', models.BooleanField(default=False)),
                ('has_downloaded_files', models.BooleanField(default=False)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text="Writer's notes about the assignment")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_acknowledgments', to='orders.order')),
                ('writer', models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'writer'], name='orders_writ_order_i_39f37d_idx'), models.Index(fields=['writer', 'acknowledged_at'], name='orders_writ_writer__7570e6_idx')],
                'unique_together': {('order', 'writer')},
            },
        ),
    ]
