# Generated by Django 5.0.14 on 2025-12-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_add_writer_request_counter_offer_fields'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('submitted', 'SUBMITTED'), ('in_review', 'IN_REVIEW'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('in_progress', 'IN_PROGRESS'), ('revision_requested', 'REVISION_REQUESTED'), ('on_revision', 'ON_REVISION'), ('revised', 'REVISED'), ('completed', 'COMPLETED'), ('under_editing', 'UNDER_EDITING'), ('rated', 'RATED'), ('reviewed', 'REVIEWED'), ('closed', 'CLOSED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED'), ('created', 'CREATED'), ('reassigned', 'REASSIGNED'), ('unpaid', 'UNPAID'), ('pending', 'PENDING'), ('on_hold', 'ON_HOLD'), ('available', 'AVAILABLE'), ('pending_preferred', 'PENDING_PREFERRED'), ('pending_writer_assignment', 'PENDING_WRITER_ASSIGNMENT'), ('critical', 'CRITICAL'), ('assigned', 'ASSIGNED'), ('late', 'LATE'), ('disputed', 'DISPUTED'), ('archived', 'ARCHIVED'), ('expired', 'EXPIRED'), ('under_review', 'UNDER_REVIEW'), ('re_opened', 'REOPENED')], default='created', help_text='Current status of the order.', max_length=30),
        ),
        migrations.CreateModel(
            name='WriterAssignmentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Whether the writer has accepted or rejected the assignment', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Writer's reason for accepting or rejecting (optional)", null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was made')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the writer accepted or rejected', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin/support who assigned the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='The order that was assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_acceptance', to='orders.order')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_assignment_acceptances', to='websites.website')),
                ('writer', models.ForeignKey(help_text='The writer who was assigned', limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writer Assignment Acceptance',
                'verbose_name_plural': 'Writer Assignment Acceptances',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['writer', 'status'], name='orders_writ_writer__bbec8b_idx'), models.Index(fields=['order', 'status'], name='orders_writ_order_i_99f7a5_idx'), models.Index(fields=['status', 'assigned_at'], name='orders_writ_status_ad42c3_idx')],
            },
        ),
    ]
