# Generated by Django 5.0.14 on 2025-12-14 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_seasonalevent'),
        ('order_configs', '0006_add_type_of_work_template'),
        ('orders', '0015_alter_order_status_writerassignmentacceptance'),
        ('pricing_configs', '0004_alter_preferredwriterconfig_options_and_more'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delete_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for soft-deleting the order.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag. When True, order is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='order',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was restored from soft-delete.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restored_by',
            field=models.ForeignKey(blank=True, help_text='User who restored the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted'], name='orders_orde_is_dele_b3c224_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='orders_orde_is_dele_128087_idx'),
        ),
    ]
