# Generated by Django 5.0.14 on 2025-12-21 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_configs', '0006_add_type_of_work_template'),
        ('orders', '0018_remove_orderdraft_client_and_more'),
        ('pricing_configs', '0004_alter_preferredwriterconfig_options_and_more'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=500)),
                ('order_instructions', models.TextField(blank=True)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_slides', models.PositiveIntegerField(default=0)),
                ('number_of_refereces', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price calculated from draft', max_digits=10, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the draft', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this draft')),
                ('is_quote', models.BooleanField(default=False, help_text='Whether this is a quote (not yet an order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_drafts', to=settings.AUTH_USER_MODEL)),
                ('converted_to_order', models.ForeignKey(blank=True, help_text='The order this draft was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='orders.order')),
                ('english_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.englishtype')),
                ('extra_services', models.ManyToManyField(blank=True, related_name='order_drafts', to='pricing_configs.additionalservice')),
                ('preferred_writer', models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_preferences', to=settings.AUTH_USER_MODEL)),
                ('type_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.typeofwork')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drafts', to='websites.website')),
            ],
            options={
                'verbose_name': 'Order Draft',
                'verbose_name_plural': 'Order Drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['client', 'website'], name='orders_orde_client__a62f05_idx'), models.Index(fields=['is_quote', '-updated_at'], name='orders_orde_is_quot_ce63f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this preset (e.g., 'Academic Essay', 'Business Report')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of when to use this preset')),
                ('default_spacing', models.CharField(blank=True, help_text='Default spacing (single, double, etc.)', max_length=10)),
                ('default_number_of_refereces', models.PositiveIntegerField(default=0, help_text='Default number of references')),
                ('style_preferences', models.JSONField(blank=True, default=dict, help_text='Style preferences: tone, formatting, citation style, etc.')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this preset has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this preset was last used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this preset is active and available')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default preset for the client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_presets', to=settings.AUTH_USER_MODEL)),
                ('default_english_type', models.ForeignKey(blank=True, help_text='Default English style', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.englishtype')),
                ('default_extra_services', models.ManyToManyField(blank=True, related_name='order_presets', to='pricing_configs.additionalservice')),
                ('default_type_of_work', models.ForeignKey(blank=True, help_text='Default type of work', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.typeofwork')),
                ('preferred_writer', models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preset_preferences', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_presets', to='websites.website')),
            ],
            options={
                'verbose_name': 'Order Preset',
                'verbose_name_plural': 'Order Presets',
                'ordering': ['-is_default', '-usage_count', '-updated_at'],
                'indexes': [models.Index(fields=['client', 'website', 'is_active'], name='orders_orde_client__c24880_idx'), models.Index(fields=['is_default', 'client'], name='orders_orde_is_defa_ccc7cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title/summary of the revision request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what needs to be changed')),
                ('changes_required', models.JSONField(default=list, help_text="List of specific changes: [{'section': 'Introduction', 'issue': '...', 'request': '...'}]")),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], default='moderate', help_text='Severity of the revision', max_length=20)),
                ('priority', models.PositiveIntegerField(default=5, help_text='Priority level (1-10, higher = more urgent)')),
                ('requested_deadline', models.DateTimeField(blank=True, help_text="Client's requested deadline for the revision", null=True)),
                ('agreed_deadline', models.DateTimeField(blank=True, help_text='Agreed deadline (may differ from requested)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the revision was completed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('client_notes', models.TextField(blank=True, help_text='Additional notes from client')),
                ('writer_notes', models.TextField(blank=True, help_text='Notes from writer during revision')),
                ('is_urgent', models.BooleanField(default=False, help_text='Marked as urgent by client')),
                ('requires_client_review', models.BooleanField(default=True, help_text='Whether client needs to review after completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['writer', 'editor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='orders.order')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests_made', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='websites.website')),
            ],
            options={
                'verbose_name': 'Revision Request',
                'verbose_name_plural': 'Revision Requests',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_revi_order_i_0100ee_idx'), models.Index(fields=['requested_by', 'status'], name='orders_revi_request_c8ba4c_idx'), models.Index(fields=['assigned_to', 'status'], name='orders_revi_assigne_a5bcd9_idx'), models.Index(fields=['severity', 'status'], name='orders_revi_severit_e4162f_idx')],
            },
        ),
    ]
