# Generated by Django 5.0.14 on 2025-12-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderdraft_orderpreset_revisionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text="Client's requested deadline for the draft", null=True),
        ),
    ]
