# Generated by Django 5.0.14 on 2025-12-28 09:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_add_cancellation_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Client's reason for requesting cancellation")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the cancellation request', max_length=20)),
                ('deadline_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of deadline elapsed when cancellation was requested', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('forfeiture_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of order amount to forfeit (calculated based on deadline percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('forfeiture_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount to forfeit (calculated from forfeiture_percentage)', max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to refund to client (total_price - forfeiture_amount)', max_digits=10)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on the cancellation request', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='orders.order')),
                ('requested_by', models.ForeignKey(help_text='Client who requested the cancellation', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cancellation Request',
                'verbose_name_plural': 'Cancellation Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_canc_order_i_a6de39_idx'), models.Index(fields=['requested_by', 'status'], name='orders_canc_request_dc5490_idx'), models.Index(fields=['status', 'requested_at'], name='orders_canc_status_66dc16_idx')],
            },
        ),
    ]
