# Generated by Django 5.0.14 on 2026-01-08 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_merge_20260106_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_preferr_200625_idx',
            old_name='orders_orde_preferred_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_assigne_148250_idx',
            old_name='orders_orde_writer_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_assigne_134c69_idx',
            old_name='orders_orde_writer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_website_f97437_idx',
            old_name='orders_orde_website_status_paid_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_website_acd751_idx',
            old_name='orders_orde_website_status_paid_pref_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_4843d2_idx',
            old_name='orders_orde_status_writer_deleted_idx',
        ),
        migrations.AlterField(
            model_name='draftrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='User who requested the draft (client or admin)', on_delete=django.db.models.deletion.CASCADE, related_name='draft_requests_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
