# Generated by Django 6.0.5 on 2026-05-28 09:06

import billing.models.invoice
import billing.models.payment_request
import billing.models.receipt
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, help_text='Fallback email for the invoice recipient. Used when no client user is linked.', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Display name for the invoice recipient.', max_length=255)),
                ('reference', models.CharField(default=billing.models.invoice.generate_invoice_reference, editable=False, help_text='Unique human-readable identifier for the invoice.', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Short title describing the invoice.', max_length=200)),
                ('purpose', models.CharField(choices=[('order', 'Order'), ('special_order', 'Special Order'), ('class_purchase', 'Class Purchase'), ('manual', 'Manual'), ('other', 'Other')], default='other', help_text='Structured classification of the invoice purpose.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of the invoice.')),
                ('order_number', models.CharField(blank=True, help_text='Optional display reference for external systems.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount to be paid.', max_digits=12)),
                ('currency', models.CharField(blank=True, help_text='Currency code for the invoice (e.g., ISO format).', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', help_text='Current lifecycle state of the invoice.', max_length=20)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice amount before discounts.', max_digits=12, null=True)),
                ('discount_code', models.CharField(blank=True, help_text='Discount code applied to this invoice.', max_length=64)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount applied to this invoice.', max_digits=12)),
                ('discount_usage_id', models.PositiveBigIntegerField(blank=True, help_text='Linked discount usage record ID.', null=True)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Timestamp when the invoice was officially issued.', null=True)),
                ('due_at', models.DateTimeField(help_text='Deadline for payment.')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when the invoice was fully paid.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when the invoice was cancelled.', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Timestamp when the invoice expired.', null=True)),
                ('payment_token', models.CharField(blank=True, help_text='Secure token used for generating payment links.', max_length=128, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp for the payment token.', null=True)),
                ('custom_payment_link', models.URLField(blank=True, help_text='Optional override link for payment.', max_length=500, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp of last invoice email dispatch.', null=True)),
                ('email_sent_count', models.PositiveIntegerField(default=0, help_text='Number of times the invoice email has been sent.')),
                ('payment_intent_reference', models.CharField(blank=True, help_text='Reference identifier linking this invoice to a payment intent in the payments_processor domain.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the invoice was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the invoice was last updated.')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('sequence_number', models.PositiveIntegerField(help_text='Installment order within the invoice schedule.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount due for this installment.', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already allocated to this installment.', max_digits=12)),
                ('due_at', models.DateTimeField(help_text='Timestamp after which the installment is overdue.')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when this installment became fully paid.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when this installment was cancelled.', null=True)),
            ],
            options={
                'ordering': ('invoice_id', 'sequence_number', 'due_at', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('recipient_email', models.EmailField(blank=True, help_text='Fallback recipient email when no client is linked.', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Display name for the payment request recipient.', max_length=255)),
                ('reference', models.CharField(default=billing.models.payment_request.generate_payment_request_reference, editable=False, help_text='Unique payment request reference.', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Short title describing the payment request.', max_length=200)),
                ('purpose', models.CharField(choices=[('order_payment', 'Order Payment'), ('order_extra_charge', 'Order Extra Charge'), ('special_order_payment', 'Special Order Payment'), ('class_purchase', 'Class Purchase'), ('manual_billing', 'Manual Billing'), ('other', 'Other')], default='other', help_text='Structured business purpose of the request.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed customer-facing request description.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount requested from the recipient.', max_digits=12)),
                ('currency', models.CharField(blank=True, help_text='Currency code used for the request amount.', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', help_text='Current lifecycle state of the payment request.', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment request was issued.', null=True)),
                ('due_at', models.DateTimeField(blank=True, help_text='Optional due timestamp for the request.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when the request became fully paid.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was cancelled.', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Timestamp when the request expired.', null=True)),
                ('payment_token', models.CharField(blank=True, help_text='Secure token used for payment request access.', max_length=128, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp for the payment request token.', null=True)),
                ('payment_intent_reference', models.CharField(blank=True, help_text='Linked payment intent reference from the processor.', max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('recipient_email', models.EmailField(blank=True, help_text='Fallback recipient email when no client is linked.', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Display name for the receipt recipient.', max_length=255)),
                ('reference', models.CharField(default=billing.models.receipt.generate_receipt_reference, editable=False, help_text='Unique human-readable receipt reference.', max_length=32, unique=True)),
                ('title_snapshot', models.CharField(blank=True, help_text='Short title describing what the payment covered at the time the receipt was issued.', max_length=255)),
                ('description_snapshot', models.TextField(blank=True, help_text='Longer human-readable description of what the payment covered at the time the receipt was issued.')),
                ('company_name_snapshot', models.CharField(blank=True, help_text='Tenant company or brand name shown to the client when the payment was made.', max_length=255)),
                ('website_name_snapshot', models.CharField(blank=True, help_text='Website display name shown to the client when the payment was made.', max_length=255)),
                ('website_domain_snapshot', models.CharField(blank=True, help_text='Website domain or hostname shown to the client when the payment was made.', max_length=255)),
                ('support_email_snapshot', models.EmailField(blank=True, help_text='Support email presented on the receipt at the time of issuance.', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Settled amount acknowledged by the receipt.', max_digits=12)),
                ('currency', models.CharField(blank=True, help_text='Currency code used for the settled amount.', max_length=10)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('voided', 'Voided')], default='issued', help_text='Current lifecycle state of the receipt.', max_length=20)),
                ('payment_intent_reference', models.CharField(blank=True, help_text='Payment intent reference tied to the receipt.', max_length=100)),
                ('external_reference', models.CharField(blank=True, help_text='External payment provider reference.', max_length=100)),
                ('payment_provider', models.CharField(blank=True, help_text='Payment provider used for the settled transaction.', max_length=100)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Timestamp when the receipt was issued.', null=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='Timestamp when the receipt was voided.', null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('channel', models.CharField(help_text='Delivery channel used for the reminder.', max_length=50)),
                ('event_key', models.CharField(help_text='Notification event key used for dispatch.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Outcome state of the reminder attempt.', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Scheduled dispatch timestamp for the reminder.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the reminder was sent.', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when the reminder failed.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Failure detail when the reminder attempt failed.')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('file', models.FileField(help_text='Stored billing document file.', upload_to='billing/documents/')),
                ('title', models.CharField(blank=True, help_text='Short display title for the document.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed note describing the document.')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
