# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('class_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='class_purchase',
            field=models.ForeignKey(blank=True, help_text='Optional link to a class purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='class_management.classorder'),
        ),
    ]
