# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('class_management', '0001_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('special_orders', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='System user associated with the invoice, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who created or issued the invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_billing_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Optional link to an order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='special_order',
            field=models.ForeignKey(blank=True, help_text='Optional link to a special order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='website',
            field=models.ForeignKey(help_text='Tenant context that owns this invoice.', on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice to which this installment belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='website',
            field=models.ForeignKey(help_text='Tenant context that owns this billing record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_billing_records', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='class_purchase',
            field=models.ForeignKey(blank=True, help_text='Optional linked class purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_requests', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked user recipient when the recipient exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Optional invoice created from this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_payment_requests', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Optional linked order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='order_adjustment_request',
            field=models.ForeignKey(blank=True, help_text='Order adjustment request that produced this receivable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_requests', to='orders.orderadjustmentrequest'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Actor who created the payment request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_billing_payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='special_order',
            field=models.ForeignKey(blank=True, help_text='Optional linked special order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_requests', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='website',
            field=models.ForeignKey(help_text='Tenant context that owns this billing record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_billing_records', to='websites.website'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked user recipient when the recipient exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice settled by this receipt, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_request',
            field=models.ForeignKey(blank=True, help_text='Billing payment request settled by this receipt, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='billing.paymentrequest'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='website',
            field=models.ForeignKey(help_text='Tenant context that owns this billing record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_billing_records', to='websites.website'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Linked invoice reminder target, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='payment_request',
            field=models.ForeignKey(blank=True, help_text='Linked payment request reminder target, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='billing.paymentrequest'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='website',
            field=models.ForeignKey(help_text='Tenant context that owns this billing record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_billing_records', to='websites.website'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Linked invoice for this document, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='payment_request',
            field=models.ForeignKey(blank=True, help_text='Linked payment request for this document, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='billing.paymentrequest'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='website',
            field=models.ForeignKey(help_text='Tenant context that owns this billing record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_billing_records', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['reference'], name='billing_inv_referen_d5533f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['website', 'status'], name='billing_inv_website_83ec7a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['website', 'client'], name='billing_inv_website_724ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['website', 'due_at'], name='billing_inv_website_130f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_at'], name='billing_inv_status_bc0902_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_token'], name='billing_inv_payment_1247bd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_intent_reference'], name='billing_inv_payment_dc87e2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['invoice', 'sequence_number'], name='billing_pay_invoice_84ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['website', 'due_at'], name='billing_pay_website_e41f64_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['website', 'invoice'], name='billing_pay_website_75683a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['website', 'paid_at'], name='billing_pay_website_d1099b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['website', 'cancelled_at'], name='billing_pay_website_d0bba8_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstallment',
            constraint=models.UniqueConstraint(fields=('invoice', 'sequence_number'), name='unique_installment_sequence_per_invoice'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['reference'], name='billing_pay_referen_b1cdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['website', 'status'], name='billing_pay_website_c4b92a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['website', 'client'], name='billing_pay_website_5d7df6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['payment_intent_reference'], name='billing_pay_payment_44caf4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['reference'], name='billing_rec_referen_b243ec_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['website', 'client'], name='billing_rec_website_0c401d_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['website', 'status'], name='billing_rec_website_fef954_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice'], name='billing_rec_invoice_1a519f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_request'], name='billing_rec_payment_ea634a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_intent_reference'], name='billing_rec_payment_41f357_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['external_reference'], name='billing_rec_externa_029b10_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['issued_at'], name='billing_rec_issued__0ed642_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['website', 'status'], name='billing_rem_website_41b782_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['website', 'scheduled_for'], name='billing_rem_website_335904_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['website', 'created_at'], name='billing_sup_website_2ddaf6_idx'),
        ),
    ]
