# Generated by Django 5.2.2 on 2026-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_client_disclosure_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='client_disclosure_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receipt',
            name='disclosure_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='disclosure_shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processor_display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='receipt',
            name='statement_descriptor_snapshot',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
    ]
