# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_pages_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pages', to='websites.website'),
        ),
        migrations.AddField(
            model_name='servicepageclick',
            name='service_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_pages_management.servicepage'),
        ),
        migrations.AddField(
            model_name='servicepageclick',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='servicepageconversion',
            name='service_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_pages_management.servicepage'),
        ),
        migrations.AddField(
            model_name='servicepageconversion',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepage',
            unique_together={('website', 'slug')},
        ),
    ]
