# Generated by Django 5.0.14 on 2025-12-04 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages_management', '0008_alter_blogpost_meta_description_and_more'),
        ('service_pages_management', '0004_servicepagecta_servicepageedithistory_servicepagefaq_and_more'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (recommended max 160 characters)', validators=[django.core.validators.MaxLengthValidator(160)]),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (recommended max 60 characters)', max_length=255, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.CreateModel(
            name='ServicePageContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Position in content (paragraph/heading index)')),
                ('auto_insert', models.BooleanField(default=False, help_text='Whether this was auto-inserted')),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Service page-specific data overriding template data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='service_pages_management.servicepage')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_page_blocks', to='blog_pages_management.contentblocktemplate')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['service_page', 'is_active'], name='service_pag_service_e396c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceWebsiteContentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('published_pages', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('page_metrics', models.JSONField(blank=True, default=dict)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_website_content_metrics', to='websites.website')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['website', 'calculated_at'], name='service_pag_website_7954b3_idx')],
            },
        ),
    ]
