# Generated by Django 5.0.14 on 2025-12-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title (used in <h1> and meta title)', max_length=255)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'best-essay-writing-service')", max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (defaults to title if empty)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('blocks', models.JSONField(blank=True, default=list, help_text='Array of content blocks (paragraph, heading, image, CTA, etc.)')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this page is published and publicly accessible')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='When this page was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp for soft deletion', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seo_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_seo_pages', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website this SEO page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='websites.website')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['website', 'slug', 'is_published'], name='seo_pages_s_website_782d21_idx'), models.Index(fields=['website', 'is_published', 'publish_date'], name='seo_pages_s_website_e45267_idx')],
                'unique_together': {('website', 'slug')},
            },
        ),
    ]
