# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title (used in <h1> and meta title)', max_length=255)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'best-essay-writing-service')", max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (defaults to title if empty)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('blocks', models.JSONField(blank=True, default=list, help_text='Array of content blocks (paragraph, heading, image, CTA, etc.)')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this page is published and publicly accessible')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='When this page was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp for soft deletion', null=True)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
