# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seo_pages', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seo_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seopage',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_seo_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seopage',
            name='website',
            field=models.ForeignKey(help_text='Website this SEO page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='seopage',
            index=models.Index(fields=['website', 'slug', 'is_published'], name='seo_pages_s_website_782d21_idx'),
        ),
        migrations.AddIndex(
            model_name='seopage',
            index=models.Index(fields=['website', 'is_published', 'publish_date'], name='seo_pages_s_website_e45267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seopage',
            unique_together={('website', 'slug')},
        ),
    ]
