# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance.', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The user associated with this wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='websites.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('transaction_type', models.CharField(choices=[('top-up', 'Top-Up'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('payment', 'Payment'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment'), ('referral_bonus', 'Referral Bonus'), ('credit', 'Credit'), ('debit', 'Debit'), ('loyalty_point', 'Loyalty Point Redemption')], help_text='Type of transaction.', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount.', max_digits=12)),
                ('description', models.CharField(blank=True, help_text='Optional description for the transaction.', max_length=255)),
                ('source', models.CharField(blank=True, help_text="Source of the transaction (e.g., 'order', 'referral', etc.).", max_length=50)),
                ('note', models.TextField(blank=True, help_text='Additional notes or details about the transaction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(help_text='The wallet this transaction belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='websites.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested withdrawal amount.', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the withdrawal request.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description for the request.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(help_text='The wallet requesting the withdrawal.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_request', to='websites.website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
