# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tickets', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The admin/support user assigned to this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='website',
            field=models.ForeignKey(help_text='The website this ticket is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(help_text='The ticket this file is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the file.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(help_text='The ticket this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='The ticket this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_slas', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ticketstatistics',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stats', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['ticket', 'resolution_deadline'], name='tickets_tic_ticket__02f237_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['website', 'resolution_breached'], name='tickets_tic_website_06b7dd_idx'),
        ),
    ]
