# Generated by Django 5.0.14 on 2025-12-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_sla_timers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketsla',
            new_name='tickets_tic_ticket__02f237_idx',
            old_name='tickets_tick_ticket__idx',
        ),
        migrations.RenameIndex(
            model_name='ticketsla',
            new_name='tickets_tic_website_06b7dd_idx',
            old_name='tickets_tick_website_idx',
        ),
    ]
