# Generated by Django 5.2.2 on 2026-06-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_exit_intent_popup_config'),
        ('websites', '0010_website_settings_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCookieConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(default='2026-06-15', help_text='Bumping this value forces all visitors to re-consent.', max_length=50)),
                ('policy_version', models.CharField(default='2026-06-15', help_text='Version of the privacy/cookie policy document. Should be updated whenever policy content changes.', max_length=50)),
                ('privacy_policy_url', models.CharField(default='/privacy', help_text='Relative or absolute URL for the privacy policy page.', max_length=255)),
                ('cookie_policy_url', models.CharField(default='/privacy#cookies', help_text='Relative or absolute URL for the cookie policy section.', max_length=255)),
                ('marketing_available', models.BooleanField(default=False, help_text='Show the Marketing consent category. Enable only when the site has advertising or attribution integrations configured.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_config', to='websites.website')),
            ],
            options={
                'verbose_name': 'Cookie Config',
                'verbose_name_plural': 'Cookie Configs',
            },
        ),
    ]
