# Generated by Django 4.2 on 2025-01-26 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0002_website_allow_guest_checkout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('code', models.CharField(help_text='Unique discount code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the discount', null=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', help_text='Type of discount', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., $10 or 15%)', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of uses allowed', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times the code has been used')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date for the discount')),
                ('end_date', models.DateTimeField(blank=True, help_text='End date for the discount', null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value to apply the discount', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the discount is active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, help_text='Website this record is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='websites.website')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('code', 'website')},
            },
        ),
    ]
