# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year this campaign is for')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this campaign is currently active')),
                ('auto_generated', models.BooleanField(default=False, help_text='Whether this was auto-generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday Discount Campaign',
                'verbose_name_plural': 'Holiday Discount Campaigns',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(help_text='Date when reminder was/will be sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dismissed', 'Dismissed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('broadcast_sent', models.BooleanField(default=False, help_text='Whether broadcast message was sent')),
                ('discount_created', models.BooleanField(default=False, help_text='Whether discount code was created')),
                ('discount_code', models.CharField(blank=True, help_text='Generated discount code (if applicable)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday Reminder',
                'verbose_name_plural': 'Holiday Reminders',
                'ordering': ['-reminder_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the special day (e.g., 'Thanksgiving Day', 'Black Friday')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the special day')),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('special_day', 'Special Day'), ('anniversary', 'Anniversary'), ('seasonal', 'Seasonal Event'), ('cultural', 'Cultural Event')], default='holiday', help_text='Type of special day', max_length=20)),
                ('date', models.DateField(help_text='Date of the special day (for annual events, use any year)')),
                ('is_annual', models.BooleanField(default=True, help_text='Whether this event repeats annually')),
                ('is_international', models.BooleanField(default=False, help_text='Whether this is an international event')),
                ('countries', models.JSONField(blank=True, default=list, help_text="List of country codes where this event is observed (empty for international). Format: ['US', 'CA', 'GB']")),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level for reminders', max_length=20)),
                ('reminder_days_before', models.PositiveIntegerField(default=7, help_text='Number of days before the event to send reminder')),
                ('send_broadcast_reminder', models.BooleanField(default=True, help_text='Whether to remind admin to send broadcast message')),
                ('auto_generate_discount', models.BooleanField(default=False, help_text='Whether to automatically generate discount code')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (if auto-generating discount)', max_digits=5, null=True)),
                ('discount_code_prefix', models.CharField(blank=True, help_text="Prefix for auto-generated discount code (e.g., 'THANKS2024')", max_length=20)),
                ('discount_valid_days', models.PositiveIntegerField(default=1, help_text='Number of days the discount is valid')),
                ('broadcast_message_template', models.TextField(blank=True, help_text='Template for broadcast message (can include {name}, {date}, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this special day is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special Day',
                'verbose_name_plural': 'Special Days',
                'ordering': ['date', 'priority'],
            },
        ),
    ]
