# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('holiday_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaydiscountcampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holiday_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidaydiscountcampaign',
            name='discount',
            field=models.ForeignKey(help_text='The discount code created for this special day', on_delete=django.db.models.deletion.CASCADE, related_name='holiday_campaigns', to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='holidayreminder',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_reminders_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidayreminder',
            name='special_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='holiday_management.specialday'),
        ),
        migrations.AddField(
            model_name='holidaydiscountcampaign',
            name='special_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_campaigns', to='holiday_management.specialday'),
        ),
        migrations.AddIndex(
            model_name='specialday',
            index=models.Index(fields=['date', 'is_active'], name='holiday_man_date_08228d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialday',
            index=models.Index(fields=['is_annual', 'is_active'], name='holiday_man_is_annu_7dc8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='specialday',
            index=models.Index(fields=['priority', 'date'], name='holiday_man_priorit_549e55_idx'),
        ),
        migrations.AddIndex(
            model_name='holidayreminder',
            index=models.Index(fields=['status', 'reminder_date'], name='holiday_man_status_43cf23_idx'),
        ),
        migrations.AddIndex(
            model_name='holidayreminder',
            index=models.Index(fields=['special_day', 'reminder_date'], name='holiday_man_special_85f7fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidayreminder',
            unique_together={('special_day', 'reminder_date')},
        ),
        migrations.AddIndex(
            model_name='holidaydiscountcampaign',
            index=models.Index(fields=['special_day', 'year'], name='holiday_man_special_7f2389_idx'),
        ),
        migrations.AddIndex(
            model_name='holidaydiscountcampaign',
            index=models.Index(fields=['is_active', 'year'], name='holiday_man_is_acti_40b62d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaydiscountcampaign',
            unique_together={('special_day', 'year')},
        ),
    ]
