# Generated by Django 5.0.14 on 2026-05-28 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '__first__'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('google_docs', 'Google Docs'), ('google_sheets', 'Google Sheets'), ('google_slides', 'Google Slides'), ('dropbox', 'Dropbox'), ('one_drive', 'OneDrive'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('loom', 'Loom'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(blank=True, help_text='Optional readable label for the external file.', max_length=255)),
                ('url', models.URLField(help_text='External file or folder URL.', max_length=1000)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Staff note explaining approval or rejection.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive links are hidden from normal workflows.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider metadata, permissions, or extracted info.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_external_file_links', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_external_file_links', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_file_links', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(choices=[('order_instruction', 'Order Instruction'), ('order_reference', 'Order Reference'), ('order_draft', 'Order Draft'), ('order_final', 'Order Final'), ('order_revision', 'Order Revision'), ('style_reference', 'Style Reference'), ('extra_service_file', 'Extra Service File'), ('message_attachment', 'Message Attachment'), ('support_attachment', 'Support Attachment'), ('dispute_evidence', 'Dispute Evidence'), ('profile_avatar', 'Profile Avatar'), ('profile_photo', 'Profile Photo'), ('writer_sample', 'Writer Sample'), ('verification_document', 'Verification Document'), ('cms_featured_image', 'CMS Featured Image'), ('cms_inline_image', 'CMS Inline Image'), ('cms_video', 'CMS Video'), ('cms_download', 'CMS Download'), ('cms_sample_work', 'CMS Sample Work'), ('class_resource', 'Class Resource'), ('class_assignment', 'Class Assignment'), ('class_submission', 'Class Submission'), ('payment_proof', 'Payment Proof'), ('invoice', 'Invoice'), ('refund_evidence', 'Refund Evidence'), ('payout_evidence', 'Payout Evidence'), ('mass_email_attachment', 'Mass Email Attachment'), ('admin_internal', 'Admin Internal'), ('legal_document', 'Legal Document'), ('bulk_import', 'Bulk Import'), ('export_file', 'Export File')], max_length=64)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('staff_only', 'Staff Only'), ('owner_only', 'Owner Only'), ('tenant_staff', 'Tenant Staff'), ('internal_only', 'Internal Only'), ('order_participants', 'Order Participants'), ('conversation_participants', 'Conversation Participants'), ('writer_and_staff', 'Writer And Staff'), ('client_and_staff', 'Client And Staff'), ('client_writer_staff', 'Client Writer Staff'), ('cms_public', 'CMS Public')], default='private', max_length=64)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this as the main file for the target object.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive attachments are hidden from normal flows.')),
                ('display_name', models.CharField(blank=True, help_text='Optional display label for this attachment.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional staff or system notes about this attachment.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible context metadata for domain integrations.')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_attachments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('external_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='files_management.externalfilelink')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='websites.website')),
            ],
            options={
                'ordering': ['-attached_at'],
            },
        ),
        migrations.CreateModel(
            name='FileBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bucket_type', models.CharField(choices=[('tenant_public', 'Tenant Public Files'), ('tenant_private', 'Tenant Private Files'), ('order_files', 'Order Files'), ('writer_deliverables', 'Writer Deliverables'), ('cms_attachments', 'CMS Attachments'), ('cms_media', 'CMS Media'), ('user_avatars', 'User Avatars'), ('system', 'System Files')], db_index=True, max_length=50)),
                ('spaces_bucket_name', models.CharField(max_length=100)),
                ('spaces_region', models.CharField(default='nyc3', max_length=20)),
                ('spaces_path_prefix', models.CharField(blank=True, help_text="Path prefix within the bucket (e.g., 'nursemygrade/media')", max_length=255)),
                ('cdn_endpoint', models.URLField(blank=True)),
                ('cdn_enabled', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('requires_signed_urls', models.BooleanField(default=True)),
                ('signed_url_expiry_seconds', models.PositiveIntegerField(default=3600, help_text='Signed URL lifetime in seconds (default: 1 hour)')),
                ('max_file_size_bytes', models.BigIntegerField(default=104857600, help_text='Maximum single file size in bytes (default: 100MB)')),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text='Allowed file extensions (empty = all). e.g., ["pdf", "docx", "jpg"]')),
                ('blocked_extensions', models.JSONField(blank=True, default=list, help_text='Blocked extensions (overrides allowed). e.g., ["exe", "bat"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_buckets', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the category.', max_length=120)),
                ('code', models.CharField(help_text='Stable internal identifier for the category.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the category is currently in use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_categories', to='websites.website')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable policy name.', max_length=150)),
                ('purpose', models.CharField(choices=[('order_instruction', 'Order Instruction'), ('order_reference', 'Order Reference'), ('order_draft', 'Order Draft'), ('order_final', 'Order Final'), ('order_revision', 'Order Revision'), ('style_reference', 'Style Reference'), ('extra_service_file', 'Extra Service File'), ('message_attachment', 'Message Attachment'), ('support_attachment', 'Support Attachment'), ('dispute_evidence', 'Dispute Evidence'), ('profile_avatar', 'Profile Avatar'), ('profile_photo', 'Profile Photo'), ('writer_sample', 'Writer Sample'), ('verification_document', 'Verification Document'), ('cms_featured_image', 'CMS Featured Image'), ('cms_inline_image', 'CMS Inline Image'), ('cms_video', 'CMS Video'), ('cms_download', 'CMS Download'), ('cms_sample_work', 'CMS Sample Work'), ('class_resource', 'Class Resource'), ('class_assignment', 'Class Assignment'), ('class_submission', 'Class Submission'), ('payment_proof', 'Payment Proof'), ('invoice', 'Invoice'), ('refund_evidence', 'Refund Evidence'), ('payout_evidence', 'Payout Evidence'), ('mass_email_attachment', 'Mass Email Attachment'), ('admin_internal', 'Admin Internal'), ('legal_document', 'Legal Document'), ('bulk_import', 'Bulk Import'), ('export_file', 'Export File')], help_text='Attachment purpose this policy applies to.', max_length=64)),
                ('allowed_mime_types', models.JSONField(blank=True, default=list, help_text='Allowed MIME types. Empty falls back to defaults.')),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text='Allowed extensions. Empty falls back to defaults.')),
                ('max_file_size_bytes', models.PositiveBigIntegerField(default=26214400)),
                ('allow_external_links', models.BooleanField(default=False)),
                ('external_links_require_review', models.BooleanField(default=True)),
                ('allowed_external_providers', models.JSONField(blank=True, default=list)),
                ('require_scan_before_download', models.BooleanField(default=False)),
                ('require_review_before_download', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_policies', to='websites.website')),
            ],
            options={
                'ordering': ['purpose'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(help_text='Underlying file stored in the configured storage backend.', upload_to='managed-files/%Y/%m/%d/')),
                ('storage_key', models.CharField(help_text='Full path or object key in the storage backend.', max_length=500, unique=True)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(help_text='Size of the file in bytes.')),
                ('mime_type', models.CharField(help_text='Detected MIME type of the file.', max_length=255)),
                ('file_extension', models.CharField(blank=True, help_text='Normalised file extension without the leading dot.', max_length=20)),
                ('file_kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('external', 'External'), ('cms_image', 'CMS Image'), ('cms_attachment', 'CMS Attachment'), ('cms_media', 'CMS Media'), ('user_avatar', 'User Avatar'), ('author_photo', 'Author Profile Photo'), ('order_file', 'Order File'), ('order_attachment', 'Order Attachment'), ('writer_deliverable', 'Writer Deliverable'), ('revision_file', 'Revision File'), ('message_attachment', 'Message Attachment'), ('ticket_attachment', 'Ticket Attachment'), ('class_material', 'Class Material'), ('special_order_file', 'Special Order File'), ('newsletter_image', 'Newsletter Image'), ('system_backup', 'System Backup'), ('system_export', 'System Export'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('sha256_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file contents for integrity and deduplication.', max_length=64)),
                ('checksum', models.CharField(blank=True, help_text='Optional secondary checksum for integrity verification.', max_length=128)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('not_scanned', 'Not Scanned'), ('queued', 'Queued for Scan'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('error', 'Error'), ('skipped', 'Skipped'), ('passed', 'Passed')], db_index=True, default='not_scanned', max_length=32)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_engine', models.CharField(blank=True, max_length=50)),
                ('scan_result_detail', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('active', 'Active'), ('pending_review', 'Pending Review'), ('quarantined', 'Quarantined'), ('archived', 'Archived'), ('pending_deletion', 'Pending Deletion'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this file is allowed to be publicly accessible.')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('derivative_type', models.CharField(blank=True, choices=[('', 'Original'), ('thumbnail_sm', 'Small thumbnail'), ('thumbnail_md', 'Medium thumbnail'), ('thumbnail_lg', 'Large thumbnail'), ('preview_pdf', 'PDF preview'), ('optimized', 'Optimised version'), ('webp', 'WebP version')], max_length=50)),
                ('retention_policy', models.CharField(choices=[('forever', 'Keep forever'), ('30_days', 'Delete after 30 days'), ('90_days', 'Delete after 90 days'), ('1_year', 'Delete after 1 year'), ('order_complete_30', '30 days after order completion'), ('order_complete_90', '90 days after order completion')], default='forever', max_length=30)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata such as dimensions, duration, or parser output.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files_management.filebucket')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='files_management.managedfile')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_files', to='wagtailcore.site')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files_management.managedfile')),
                ('replaced_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_versions', to='files_management.managedfile')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='FileScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(help_text='Example values: antivirus, pii, moderation, ocr.', max_length=80)),
                ('status', models.CharField(choices=[('not_scanned', 'Not Scanned'), ('queued', 'Queued for Scan'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('error', 'Error'), ('skipped', 'Skipped'), ('passed', 'Passed')], default='queued', max_length=32)),
                ('provider', models.CharField(blank=True, help_text='External or internal scanner name.', max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict, help_text='Raw scanner result or normalized metadata.')),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='files_management.managedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(help_text='Example values: thumbnail, preview, ocr, compress.', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='files_management.managedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='files_management.managedfile')),
            ],
        ),
        migrations.CreateModel(
            name='FileDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason supplied by the requester.')),
                ('scope', models.CharField(choices=[('detach_only', 'Detach Only'), ('archive_file', 'Archive File'), ('delete_file', 'Delete File')], default='detach_only', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Internal staff decision note.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='files_management.fileattachment')),
                ('external_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='files_management.externalfilelink')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_file_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_deletion_requests', to='websites.website')),
                ('managed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='files_management.managedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='managed_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='files_management.managedfile'),
        ),
        migrations.CreateModel(
            name='FileAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('preview', 'Preview'), ('replace', 'Replace'), ('delete', 'Delete'), ('attach', 'Attach'), ('detach', 'Detach')], default='view', max_length=32)),
                ('reason', models.TextField(blank=True, help_text='Reason access was granted.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Empty means the grant does not expire automatically.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_file_access', to=settings.AUTH_USER_MODEL)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access_grants', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_file_access', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access_grants', to='websites.website')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='files_management.fileattachment')),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='files_management.managedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalfilelink',
            index=models.Index(fields=['website', 'review_status'], name='files_manag_website_ea5c07_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfilelink',
            index=models.Index(fields=['provider'], name='files_manag_provide_06a6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfilelink',
            index=models.Index(fields=['is_active'], name='files_manag_is_acti_2f44dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filecategory',
            unique_together={('website', 'code')},
        ),
        migrations.AddIndex(
            model_name='filepolicy',
            index=models.Index(fields=['website', 'purpose'], name='files_manag_website_45cbec_idx'),
        ),
        migrations.AddIndex(
            model_name='filepolicy',
            index=models.Index(fields=['is_active'], name='files_manag_is_acti_4b6cb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filepolicy',
            unique_together={('website', 'purpose')},
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['website', 'file_kind'], name='files_manag_website_71e490_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['website', 'lifecycle_status'], name='files_manag_website_eff145_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['website', 'scan_status'], name='files_manag_website_91e524_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['site', 'lifecycle_status'], name='files_manag_site_id_7d9432_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['site', 'bucket', 'lifecycle_status'], name='files_manag_site_id_796d06_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['sha256_hash'], name='files_manag_sha256__f69339_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['content_type', 'object_id'], name='files_manag_content_1ec2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['delete_after'], name='files_manag_delete__7b9895_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('file', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='filescanresult',
            index=models.Index(fields=['managed_file', 'scan_type'], name='files_manag_managed_f8988f_idx'),
        ),
        migrations.AddIndex(
            model_name='filescanresult',
            index=models.Index(fields=['status'], name='files_manag_status_c65d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='filescanresult',
            index=models.Index(fields=['scanned_at'], name='files_manag_scanned_24011e_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['managed_file', 'job_type'], name='files_manag_managed_bf75aa_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['status'], name='files_manag_status_962a86_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['scheduled_at'], name='files_manag_schedul_19a4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='filedownloadlog',
            index=models.Index(fields=['downloaded_at'], name='files_manag_downloa_226d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='filedeletionrequest',
            index=models.Index(fields=['website', 'status'], name='files_manag_website_e8ce93_idx'),
        ),
        migrations.AddIndex(
            model_name='filedeletionrequest',
            index=models.Index(fields=['scope'], name='files_manag_scope_c7ad47_idx'),
        ),
        migrations.AddIndex(
            model_name='filedeletionrequest',
            index=models.Index(fields=['created_at'], name='files_manag_created_d74d51_idx'),
        ),
        migrations.AddConstraint(
            model_name='filedeletionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('managed_file__isnull', False), ('external_link__isnull', False), _connector='OR'), name='file_deletion_request_has_source'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['website', 'is_active'], name='files_manag_website_f0afe8_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='files_manag_content_43b0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['purpose'], name='files_manag_purpose_43c8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['visibility'], name='files_manag_visibil_3949aa_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['attached_at'], name='files_manag_attache_8b6df5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('managed_file__isnull', False), ('external_link__isnull', True)), models.Q(('managed_file__isnull', True), ('external_link__isnull', False)), _connector='OR'), name='file_attachment_exactly_one_source'),
        ),
        migrations.AddIndex(
            model_name='fileaccessgrant',
            index=models.Index(fields=['website', 'grantee'], name='files_manag_website_e1280a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccessgrant',
            index=models.Index(fields=['managed_file', 'action'], name='files_manag_managed_49551c_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccessgrant',
            index=models.Index(fields=['expires_at'], name='files_manag_expires_6062d3_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccessgrant',
            index=models.Index(fields=['revoked_at'], name='files_manag_revoked_0235bf_idx'),
        ),
    ]
