# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(blank=True, choices=[('late_submission', 'Late Submission'), ('quality', 'Quality Penalty'), ('plagiarism', 'Plagiarism'), ('inactivity', 'Inactivity/Abandonment'), ('comm_breach', 'Communication Breach'), ('excessive_revisions', 'Excessive Revisions'), ('extension_overuse', 'Deadline Extension Overuse'), ('manual_violation', 'Manual Violation'), ('privacy_violation', 'Privacy Violation'), ('late_reassignment', 'Late Reassignment Request'), ('dropping_order_late', 'Dropping Order Late'), ('wrong_files', 'Uploaded Wrong Files')], db_index=True, help_text='Legacy fine type enum (for backward compatibility)', max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(help_text='Detailed reason for the fine.')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('appealed', 'Appealed'), ('disputed', 'Disputed'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('waived', 'Waived'), ('voided', 'Voided')], db_index=True, default='issued', max_length=20)),
                ('imposed_at', models.DateTimeField(auto_now_add=True, help_text='When the fine was issued.')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this fine has been resolved (waived, voided, or resolved).')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the fine was resolved.', null=True)),
                ('resolved_reason', models.TextField(blank=True, help_text='Reason for resolution.', null=True)),
                ('waived_at', models.DateTimeField(blank=True, help_text='Timestamp when the fine was waived.', null=True)),
                ('waiver_reason', models.TextField(blank=True, help_text='Reason given for waiving the fine.', null=True)),
            ],
            options={
                'ordering': ['-imposed_at'],
            },
        ),
        migrations.CreateModel(
            name='FineAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text="Writer's explanation for why the fine should be waived.")),
                ('evidence', models.TextField(blank=True, help_text='Any additional evidence or context provided by the writer.')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('appealed', 'Appealed'), ('disputed', 'Disputed'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('waived', 'Waived'), ('voided', 'Voided')], default='disputed', help_text='Current status of the appeal (tracks fine status).', max_length=20)),
                ('escalated', models.BooleanField(default=False, help_text='Whether this appeal has been escalated for higher-level review.')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When the appeal was escalated.', null=True)),
                ('escalation_reason', models.TextField(blank=True, help_text='Reason for escalation.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the appeal was reviewed.', null=True)),
                ('review_decision', models.CharField(choices=[('accepted', 'Accepted (Fine Waived)'), ('rejected', 'Rejected (Fine Upheld)'), ('pending', 'Pending Review')], default='pending', help_text='Decision made on the appeal.', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text="Admin's notes on the review decision.")),
                ('resolution_notes', models.TextField(blank=True, help_text='Final resolution notes after appeal is closed.')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FineAppealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('event_type', models.CharField(choices=[('appeal_submitted', 'Appeal Submitted'), ('writer_update', 'Writer Update'), ('evidence_added', 'Evidence Added'), ('admin_response', 'Admin Response'), ('status_change', 'Status Update'), ('system', 'System Notice')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FineAppealEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/fine_appeals/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'txt', 'zip'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FinePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(choices=[('late_submission', 'Late Submission'), ('quality', 'Quality Penalty'), ('plagiarism', 'Plagiarism'), ('inactivity', 'Inactivity/Abandonment'), ('comm_breach', 'Communication Breach'), ('excessive_revisions', 'Excessive Revisions'), ('extension_overuse', 'Deadline Extension Overuse'), ('manual_violation', 'Manual Violation'), ('privacy_violation', 'Privacy Violation'), ('late_reassignment', 'Late Reassignment Request'), ('dropping_order_late', 'Dropping Order Late'), ('wrong_files', 'Uploaded Wrong Files')], db_index=True, max_length=30)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('waived_at', models.DateTimeField(blank=True, help_text='Timestamp when the fine was waived.', null=True)),
                ('waiver_reason', models.TextField(blank=True, help_text='Reason given for waiving the fine.', null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FineTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system_defined', models.CharField(choices=[('system', 'System-Defined (Late Submission)'), ('admin', 'Admin-Defined')], default='admin', help_text='System-defined types (e.g., late submission) cannot be deleted', max_length=10)),
                ('code', models.CharField(db_index=True, help_text="Unique code for this fine type (e.g., 'quality_issue', 'privacy_violation')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Quality Issue', 'Privacy Violation')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when this fine applies')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Base Amount'), ('progressive_hourly', 'Progressive Hourly (Late Submission Only)')], default='fixed', help_text='How to calculate the fine amount', max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Fixed fine amount (if calculation_type is 'fixed')", max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Fine percentage (if calculation_type is 'percentage')", max_digits=5, null=True)),
                ('base_amount', models.CharField(blank=True, choices=[('writer_compensation', 'Writer Compensation'), ('total_price', 'Order Total Price')], default='writer_compensation', help_text='Base amount for percentage calculation', max_length=20, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fine amount (enforced regardless of calculation)', max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fine amount (cap for percentage calculations)', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this fine type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fine Type Config',
                'verbose_name_plural': 'Fine Type Configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LatenessFineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hour_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Fine percentage for first hour late (e.g., 5%)', max_digits=5)),
                ('second_hour_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Fine percentage for second hour late (e.g., 10%)', max_digits=5)),
                ('third_hour_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Fine percentage for third hour late (e.g., 15%)', max_digits=5)),
                ('subsequent_hours_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Additional percentage per hour after 3 hours (e.g., 5% per hour)', max_digits=5)),
                ('daily_rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Fine percentage per day after 24 hours (e.g., 20% per day)', max_digits=5)),
                ('max_fine_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fine percentage cap (None = no cap)', max_digits=5, null=True)),
                ('calculation_mode', models.CharField(choices=[('cumulative', 'Cumulative (5% + 10% + 15% = 30% after 3 hours)'), ('progressive', 'Progressive (5% for hour 1, 10% for hour 2, 15% for hour 3, etc.)')], default='cumulative', help_text='How to calculate fines: cumulative or progressive per hour', max_length=20)),
                ('base_amount', models.CharField(choices=[('writer_compensation', 'Writer Compensation'), ('total_price', 'Order Total Price')], default='writer_compensation', help_text='What amount to calculate fine percentage from', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this rule becomes active')),
                ('end_date', models.DateTimeField(blank=True, help_text='When this rule expires (None = never expires)', null=True)),
                ('description', models.TextField(blank=True, help_text='Admin notes about this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lateness Fine Rule',
                'verbose_name_plural': 'Lateness Fine Rules',
                'ordering': ['-start_date'],
            },
        ),
    ]
