# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0001_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued the fine (null for system-issued fines).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='order',
            field=models.ForeignKey(help_text='The order this fine is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='orders.order'),
        ),
        migrations.AddField(
            model_name='fine',
            name='waived_by',
            field=models.ForeignKey(blank=True, help_text='User who waived the fine, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_waived_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='escalated_to',
            field=models.ForeignKey(blank=True, help_text='Admin/support user this appeal was escalated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='fine',
            field=models.OneToOneField(help_text='The fine being appealed.', on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed the appeal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Writer who submitted the appeal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fineappealevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_appeal_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fineappealevent',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fines.fineappeal'),
        ),
        migrations.AddField(
            model_name='fineappealevidence',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='fines.fineappeal'),
        ),
        migrations.AddField(
            model_name='fineappealevidence',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fines.fineappealevent'),
        ),
        migrations.AddField(
            model_name='fineappealevidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_appeal_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finepolicy',
            name='waived_by',
            field=models.ForeignKey(blank=True, help_text='User who waived the fine, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_waived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finetypeconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this fine type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fine_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finetypeconfig',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website this fine type applies to (None = all websites)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_type_configs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='fine',
            name='fine_type_config',
            field=models.ForeignKey(blank=True, help_text='Admin-configurable fine type (preferred)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fines.finetypeconfig'),
        ),
        migrations.AddField(
            model_name='latenessfinerule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lateness_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latenessfinerule',
            name='website',
            field=models.ForeignKey(help_text='Website this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='lateness_fine_rules', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='fineappeal',
            index=models.Index(fields=['fine', 'status'], name='fines_finea_fine_id_aac417_idx'),
        ),
        migrations.AddIndex(
            model_name='fineappeal',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='fines_finea_submitt_3a4cef_idx'),
        ),
        migrations.AddIndex(
            model_name='fineappeal',
            index=models.Index(fields=['status', 'reviewed_at'], name='fines_finea_status_857de9_idx'),
        ),
        migrations.AddIndex(
            model_name='finepolicy',
            index=models.Index(fields=['fine_type', 'start_date'], name='fines_finep_fine_ty_b8d33d_idx'),
        ),
        migrations.AddIndex(
            model_name='finetypeconfig',
            index=models.Index(fields=['code'], name='fines_finet_code_68b272_idx'),
        ),
        migrations.AddIndex(
            model_name='finetypeconfig',
            index=models.Index(fields=['website', 'active'], name='fines_finet_website_16756a_idx'),
        ),
        migrations.AddIndex(
            model_name='finetypeconfig',
            index=models.Index(fields=['is_system_defined'], name='fines_finet_is_syst_366d85_idx'),
        ),
        migrations.AddConstraint(
            model_name='finetypeconfig',
            constraint=models.UniqueConstraint(fields=('code', 'website'), name='unique_fine_type_per_website'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['order', 'status'], name='fines_fine_order_i_4defd8_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status', 'imposed_at'], name='fines_fine_status_8090dc_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['fine_type'], name='fines_fine_fine_ty_5fc703_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['fine_type_config'], name='fines_fine_fine_ty_aa3c49_idx'),
        ),
        migrations.AddIndex(
            model_name='latenessfinerule',
            index=models.Index(fields=['website', 'active'], name='fines_laten_website_dce433_idx'),
        ),
        migrations.AddIndex(
            model_name='latenessfinerule',
            index=models.Index(fields=['start_date', 'end_date'], name='fines_laten_start_d_c0b9f0_idx'),
        ),
    ]
