# Generated by Django 5.0.14 on 2025-11-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0003_add_fine_type_config_and_lateness_rules'),
        ('fines', '0003_update_fineappeal_fields'),
    ]

    operations = [
    ]
