# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0005_alter_finetypeconfig_fields'),
        ('orders', '0007_rename_orders_order_status_idx_orders_orde_status_c6dd84_idx_and_more'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fineappeal',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='finetypeconfig',
            options={'ordering': ['name'], 'verbose_name': 'Fine Type Config', 'verbose_name_plural': 'Fine Type Configs'},
        ),
        migrations.AlterModelOptions(
            name='latenessfinerule',
            options={'ordering': ['-start_date'], 'verbose_name': 'Lateness Fine Rule', 'verbose_name_plural': 'Lateness Fine Rules'},
        ),
        migrations.RemoveIndex(
            model_name='fine',
            name='fines_fine_order_i_33c7aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='fine',
            name='fines_fine_status_1fd55b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='finetypeconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fineappeal',
            name='appealed_by',
        ),
        migrations.AddField(
            model_name='fine',
            name='waived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the fine was waived.', null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='waived_by',
            field=models.ForeignKey(blank=True, help_text='User who waived the fine, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_waived_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='waiver_reason',
            field=models.TextField(blank=True, help_text='Reason given for waiving the fine.', null=True),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='evidence',
            field=models.TextField(blank=True, help_text='Any additional evidence or context provided by the writer.'),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Writer who submitted the appeal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_type',
            field=models.CharField(blank=True, choices=[('late_submission', 'Late Submission'), ('quality', 'Quality Penalty'), ('plagiarism', 'Plagiarism'), ('inactivity', 'Inactivity/Abandonment'), ('comm_breach', 'Communication Breach'), ('excessive_revisions', 'Excessive Revisions'), ('extension_overuse', 'Deadline Extension Overuse'), ('manual_violation', 'Manual Violation'), ('privacy_violation', 'Privacy Violation'), ('late_reassignment', 'Late Reassignment Request'), ('dropping_order_late', 'Dropping Order Late'), ('wrong_files', 'Uploaded Wrong Files')], db_index=True, help_text='Legacy fine type enum (for backward compatibility)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_type_config',
            field=models.ForeignKey(blank=True, help_text='Admin-configurable fine type (preferred)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fines.finetypeconfig'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='imposed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the fine was issued.'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued the fine (null for system-issued fines).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fine',
            name='order',
            field=models.ForeignKey(help_text='The order this fine is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='reason',
            field=models.TextField(help_text='Detailed reason for the fine.'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Whether this fine has been resolved (waived, voided, or resolved).'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the fine was resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='resolved_reason',
            field=models.TextField(blank=True, help_text='Reason for resolution.', null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('appealed', 'Appealed'), ('disputed', 'Disputed'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('waived', 'Waived'), ('voided', 'Voided')], db_index=True, default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Whether this appeal has been escalated for higher-level review.'),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When the appeal was escalated.', null=True),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='escalated_to',
            field=models.ForeignKey(blank=True, help_text='Admin/support user this appeal was escalated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalation.'),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='fine',
            field=models.OneToOneField(help_text='The fine being appealed.', on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='fines.fine'),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='reason',
            field=models.TextField(help_text="Writer's explanation for why the fine should be waived."),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Final resolution notes after appeal is closed.'),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='review_decision',
            field=models.CharField(choices=[('accepted', 'Accepted (Fine Waived)'), ('rejected', 'Rejected (Fine Upheld)'), ('pending', 'Pending Review')], default='pending', help_text='Decision made on the appeal.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='review_notes',
            field=models.TextField(blank=True, help_text="Admin's notes on the review decision."),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the appeal was reviewed.', null=True),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed the appeal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fineappeal',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('appealed', 'Appealed'), ('disputed', 'Disputed'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('waived', 'Waived'), ('voided', 'Voided')], default='disputed', help_text='Current status of the appeal (tracks fine status).', max_length=20),
        ),
        migrations.AlterField(
            model_name='finepolicy',
            name='fine_type',
            field=models.CharField(choices=[('late_submission', 'Late Submission'), ('quality', 'Quality Penalty'), ('plagiarism', 'Plagiarism'), ('inactivity', 'Inactivity/Abandonment'), ('comm_breach', 'Communication Breach'), ('excessive_revisions', 'Excessive Revisions'), ('extension_overuse', 'Deadline Extension Overuse'), ('manual_violation', 'Manual Violation'), ('privacy_violation', 'Privacy Violation'), ('late_reassignment', 'Late Reassignment Request'), ('dropping_order_late', 'Dropping Order Late'), ('wrong_files', 'Uploaded Wrong Files')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this fine type is currently active'),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Base Amount'), ('progressive_hourly', 'Progressive Hourly (Late Submission Only)')], default='fixed', help_text='How to calculate the fine amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='code',
            field=models.CharField(db_index=True, help_text="Unique code for this fine type (e.g., 'quality_issue', 'privacy_violation')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this fine type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fine_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='description',
            field=models.TextField(blank=True, help_text='Description of when this fine applies'),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Fixed fine amount (if calculation_type is 'fixed')", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fine amount (cap for percentage calculations)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fine amount (enforced regardless of calculation)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='name',
            field=models.CharField(help_text="Display name (e.g., 'Quality Issue', 'Privacy Violation')", max_length=100),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Fine percentage (if calculation_type is 'percentage')", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='finetypeconfig',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website this fine type applies to (None = all websites)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_type_configs', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this rule is currently active'),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='base_amount',
            field=models.CharField(choices=[('writer_compensation', 'Writer Compensation'), ('total_price', 'Order Total Price')], default='writer_compensation', help_text='What amount to calculate fine percentage from', max_length=20),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='calculation_mode',
            field=models.CharField(choices=[('cumulative', 'Cumulative (5% + 10% + 15% = 30% after 3 hours)'), ('progressive', 'Progressive (5% for hour 1, 10% for hour 2, 15% for hour 3, etc.)')], default='cumulative', help_text='How to calculate fines: cumulative or progressive per hour', max_length=20),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lateness_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='daily_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Fine percentage per day after 24 hours (e.g., 20% per day)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='description',
            field=models.TextField(blank=True, help_text='Admin notes about this rule'),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When this rule expires (None = never expires)', null=True),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='first_hour_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Fine percentage for first hour late (e.g., 5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='max_fine_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fine percentage cap (None = no cap)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='second_hour_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Fine percentage for second hour late (e.g., 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this rule becomes active'),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='subsequent_hours_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Additional percentage per hour after 3 hours (e.g., 5% per hour)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='third_hour_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Fine percentage for third hour late (e.g., 15%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='latenessfinerule',
            name='website',
            field=models.ForeignKey(help_text='Website this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='lateness_fine_rules', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['order', 'status'], name='fines_fine_order_i_4defd8_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status', 'imposed_at'], name='fines_fine_status_8090dc_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['fine_type_config'], name='fines_fine_fine_ty_aa3c49_idx'),
        ),
        migrations.AddIndex(
            model_name='fineappeal',
            index=models.Index(fields=['fine', 'status'], name='fines_finea_fine_id_aac417_idx'),
        ),
        migrations.AddIndex(
            model_name='fineappeal',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='fines_finea_submitt_3a4cef_idx'),
        ),
        migrations.AddIndex(
            model_name='fineappeal',
            index=models.Index(fields=['status', 'reviewed_at'], name='fines_finea_status_857de9_idx'),
        ),
        migrations.AddIndex(
            model_name='finetypeconfig',
            index=models.Index(fields=['code'], name='fines_finet_code_68b272_idx'),
        ),
        migrations.AddIndex(
            model_name='finetypeconfig',
            index=models.Index(fields=['website', 'active'], name='fines_finet_website_16756a_idx'),
        ),
        migrations.AddIndex(
            model_name='finetypeconfig',
            index=models.Index(fields=['is_system_defined'], name='fines_finet_is_syst_366d85_idx'),
        ),
        migrations.AddIndex(
            model_name='latenessfinerule',
            index=models.Index(fields=['website', 'active'], name='fines_laten_website_dce433_idx'),
        ),
        migrations.AddIndex(
            model_name='latenessfinerule',
            index=models.Index(fields=['start_date', 'end_date'], name='fines_laten_start_d_c0b9f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='finetypeconfig',
            constraint=models.UniqueConstraint(fields=('code', 'website'), name='unique_fine_type_per_website'),
        ),
    ]
