# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('writer_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerpayment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_wallet_payments', to='websites.website'),
        ),
    ]
