# Generated by Django 5.0.14 on 2025-11-24 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_add_payment_settings'),
        ('writer_wallet', '0002_alter_writerpayment_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='schedule_type',
            field=models.CharField(choices=[('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Manual', 'Manual')], max_length=10),
        ),
        migrations.CreateModel(
            name='WriterPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount requested by writer', max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, help_text="Writer's available balance at time of request", max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the payment request', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('scheduled_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='writer_wallet.scheduledwriterpayment')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='writer_wallet.writerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='writer_wall_status_d36dea_idx'), models.Index(fields=['writer_wallet', 'status'], name='writer_wall_writer__d37180_idx')],
            },
        ),
    ]
