# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_files', '0002_initial'),
        ('orders', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfilelink',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_link_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalfilelink',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the external file link', on_delete=django.db.models.deletion.CASCADE, related_name='external_file_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalfilelink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_external_file_link', to='websites.website'),
        ),
        migrations.AddField(
            model_name='extraservicefile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_service_files', to='orders.order'),
        ),
        migrations.AddField(
            model_name='extraservicefile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extraservicefile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_service_file', to='websites.website'),
        ),
        migrations.AddField(
            model_name='filedeletionrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='User who requested the file deletion', on_delete=django.db.models.deletion.CASCADE, related_name='file_deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filedeletionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_deletion_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filedeletionrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_deletion_request', to='websites.website'),
        ),
        migrations.AddField(
            model_name='filedownloadlog',
            name='downloaded_by',
            field=models.ForeignKey(help_text='User who downloaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filedownloadlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_download_log', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_file', to='websites.website'),
        ),
        migrations.AddField(
            model_name='filedownloadlog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='order_files.orderfile'),
        ),
        migrations.AddField(
            model_name='filedeletionrequest',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_files.orderfile'),
        ),
        migrations.AddField(
            model_name='orderfilecategory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_file_category', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_files.orderfilecategory'),
        ),
        migrations.AddField(
            model_name='extraservicefile',
            name='category',
            field=models.ForeignKey(help_text='Category for the extra service file (e.g., Plagiarism Report, Smart Paper)', on_delete=django.db.models.deletion.CASCADE, related_name='extra_service_files', to='order_files.orderfilecategory'),
        ),
        migrations.AddField(
            model_name='orderfilesconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='websites.website'),
        ),
    ]
