# Generated by Django 5.0.14 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, help_text='Unique referral code used by the referee.', max_length=50, null=True)),
                ('referral_source', models.CharField(blank=True, help_text='Optional: how the referral came in (manual, auto, promo code, etc)', max_length=30, null=True)),
                ('referrer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('referee_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_awarded', models.BooleanField(default=False)),
                ('registration_bonus_credited', models.BooleanField(default=False)),
                ('first_order_bonus_credited', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_bonus', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus amount when a referee places their first order.', max_digits=10)),
                ('first_order_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='fixed', max_length=10)),
                ('first_order_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_expiry_days', models.IntegerField(default=30)),
                ('max_referrals_per_month', models.PositiveIntegerField(default=10, help_text='Max number of referrals a user can make in a month.')),
                ('max_referral_bonus_per_month', models.DecimalField(decimal_places=2, default=100.0, help_text='Max referral bonus a user can earn in a month.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralBonusDecay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decay_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Decay percentage per month.', max_digits=5)),
                ('decay_start_at', models.DateTimeField(help_text='When the decay starts applying.')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralBonusUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique referral code.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('successful_referrals', models.PositiveIntegerField(default=0)),
                ('referral_bonus_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_referral_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
