# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_payments_management', '0002_initial'),
        ('orders', '0002_initial'),
        ('referrals', '0001_initial'),
        ('wallet', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(help_text='User who was referred.', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(help_text='The user who made the referral.', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralbonusconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralbonusdecay',
            name='wallet_transaction',
            field=models.OneToOneField(help_text='The wallet transaction associated with the bonus.', on_delete=django.db.models.deletion.CASCADE, related_name='decay', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='referralbonusdecay',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_decay', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
        migrations.AddField(
            model_name='referralbonususage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_usage', to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this referral code.', on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='referralstats',
            name='user',
            field=models.OneToOneField(help_text='The user whose referral stats are tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='referral_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
