# Generated by Django 5.0.14 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='extra_service_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('allowed_extensions', models.JSONField(default=list)),
                ('is_final_draft', models.BooleanField(default=False)),
                ('is_extra_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFilesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_extensions', models.JSONField(default=list)),
                ('enable_external_links', models.BooleanField(default=True)),
                ('max_upload_size', models.IntegerField(default=100)),
                ('final_draft_required', models.BooleanField(default=True)),
                ('extra_service_file_rules', models.JSONField(default=dict)),
            ],
        ),
    ]
