# Generated by Django 5.0.14 on 2025-12-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_files', '0003_initial'),
        ('orders', '0013_add_writer_acknowledgment_message_review_reminders'),
        ('websites', '0006_enhance_file_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfile',
            options={'ordering': ['-created_at', '-version']},
        ),
        migrations.AddField(
            model_name='orderfile',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about this file version'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='is_final_paper',
            field=models.BooleanField(default=False, help_text='Mark this file as the final paper for submission'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='previous_version',
            field=models.ForeignKey(blank=True, help_text='Previous version of this file (for versioning chain)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='order_files.orderfile'),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('revision', 'Revision'), ('final', 'Final Paper'), ('archived', 'Archived')], default='draft', help_text='File status (draft, revision, final, archived)', max_length=20),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='File version number'),
        ),
        migrations.AddIndex(
            model_name='orderfile',
            index=models.Index(fields=['order', 'is_final_paper'], name='order_files_order_i_30575d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfile',
            index=models.Index(fields=['order', 'status'], name='order_files_order_i_d75e29_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfile',
            index=models.Index(fields=['order', 'version'], name='order_files_order_i_22e85e_idx'),
        ),
    ]
