# Generated by Django 5.0.14 on 2025-12-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_files', '0005_add_style_reference_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stylereferencefile',
            new_name='order_files_order_i_58c45b_idx',
            old_name='order_files_order_i_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='stylereferencefile',
            new_name='order_files_order_i_641134_idx',
            old_name='order_files_order_i_ref_type_idx',
        ),
    ]
