# Generated by Django 5.0.14 on 2025-12-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_files', '0008_add_universal_file_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfilecategory',
            options={'verbose_name_plural': 'Order File Categories'},
        ),
    ]
