# Generated by Django 5.0.14 on 2026-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_files', '0009_alter_orderfilecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedeletionrequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin comment on the deletion request', null=True),
        ),
        migrations.AddField(
            model_name='filedeletionrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for requesting file deletion', null=True),
        ),
        migrations.AddField(
            model_name='filedeletionrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
