# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('special_orders', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedspecialorderconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_order_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predefinedspecialorderconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_special_order_configs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='predefinedspecialorderduration',
            name='predefined_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='predefinedspecialorderduration',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_special_order_durations', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='converted_order',
            field=models.ForeignKey(blank=True, help_text='Optional standard order created from this special order for execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_special_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='predefined_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_orders', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='predefined_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_orders', to='special_orders.predefinedspecialorderduration'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='writer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_special_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderaccessgrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_special_order_sensitive_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderaccessgrant',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_sensitive_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderaccessgrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_special_order_sensitive_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderaccessgrant',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_access_grants', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderaccessgrant',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_access_grants', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderaccesslog',
            name='accessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_order_sensitive_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderaccesslog',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_access_logs', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderaccesslog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_access_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_special_order_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_special_order_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_special_order_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_overrides', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_admin_overrides', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderanalyticsevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_order_analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderanalyticsevent',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderanalyticsevent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_analytics_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialordercapacityrule',
            name='predefined_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_rules', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialordercapacityrule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_capacity_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderchangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_special_order_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_special_order_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderchangerequest',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderchangerequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_change_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderchangerequestquote',
            name='change_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='special_orders.specialorderchangerequest'),
        ),
        migrations.AddField(
            model_name='specialorderchangerequestquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_order_change_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderchangerequestquote',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_change_request_quotes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderclienttierdiscountrule',
            name='predefined_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tier_rules', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialorderclienttierdiscountrule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_client_tier_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialordercompletionlog',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_order_completion_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialordercompletionlog',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialordercompletionlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_completion_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialordercurrencypriceoverride',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_overrides', to='special_orders.predefinedspecialorderduration'),
        ),
        migrations.AddField(
            model_name='specialordercurrencypriceoverride',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_currency_overrides', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdeliverable',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_special_order_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdeliverable',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderdeliverable',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_special_order_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdeliverable',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_deliverables', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdeliverycheckpoint',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_checkpoints', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderdeliverycheckpoint',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_special_order_checkpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdeliverycheckpoint',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_delivery_checkpoints', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='delivery_checkpoint',
            field=models.ForeignKey(blank=True, help_text='Delivery checkpoint affected by this override, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_overrides', to='special_orders.specialorderdeliverycheckpoint'),
        ),
        migrations.AddField(
            model_name='specialorderdiscountapplication',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_special_order_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdiscountapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_special_order_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdiscountapplication',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderdiscountapplication',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_discount_applications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdiscountrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_order_discount_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdiscountrule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_discount_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdiscountapplication',
            name='discount_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='special_orders.specialorderdiscountrule'),
        ),
        migrations.AddField(
            model_name='specialorderdispute',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_special_order_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdispute',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_special_order_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdispute',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderdispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_disputes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdisputeresolution',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='special_orders.specialorderdispute'),
        ),
        migrations.AddField(
            model_name='specialorderdisputeresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_special_order_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderdisputeresolution',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_resolutions', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderdisputeresolution',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_dispute_resolutions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderexternallink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_order_external_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderexternallink',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderexternallink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_external_links', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderfundingmilestone',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_milestones', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderfundingmilestone',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_funding_milestones', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdeliverycheckpoint',
            name='required_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_checkpoints', to='special_orders.specialorderfundingmilestone'),
        ),
        migrations.AddField(
            model_name='specialorderfundingplan',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_special_order_funding_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderfundingplan',
            name='special_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_plan', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderfundingplan',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_funding_plans', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderfundingmilestone',
            name='funding_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='special_orders.specialorderfundingplan'),
        ),
        migrations.AddField(
            model_name='specialorderinquiryfile',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_files', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderinquiryfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_special_order_inquiry_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderinquiryfile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_inquiry_files', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderinstitutionprofile',
            name='special_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderinstitutionprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_institution_profiles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialordermilestonetemplate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_milestone_templates', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialordermilestonetemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='special_orders.specialordermilestonetemplate'),
        ),
        migrations.AddField(
            model_name='specialorderpaymentapplication',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_special_order_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderpaymentapplication',
            name='funding_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='special_orders.specialorderfundingplan'),
        ),
        migrations.AddField(
            model_name='specialorderpaymentapplication',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_applications', to='special_orders.specialorderfundingmilestone'),
        ),
        migrations.AddField(
            model_name='specialorderpaymentapplication',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderpaymentapplication',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_payment_applications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderadminoverride',
            name='payment_application',
            field=models.ForeignKey(blank=True, help_text='Payment application created by this override, if the override affects funding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_overrides', to='special_orders.specialorderpaymentapplication'),
        ),
        migrations.AddField(
            model_name='specialorderplatformaccessvault',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_order_access_vaults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderplatformaccessvault',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_vaults', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderplatformaccessvault',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_access_vaults', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderaccesslog',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='special_orders.specialorderplatformaccessvault'),
        ),
        migrations.AddField(
            model_name='specialorderaccessgrant',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='special_orders.specialorderplatformaccessvault'),
        ),
        migrations.AddField(
            model_name='specialorderplatformdifficultyrule',
            name='predefined_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_rules', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialorderplatformdifficultyrule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_difficulty_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderpricingsnapshot',
            name='special_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_snapshot', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderpricingsnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_pricing_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_order_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderquote',
            name='special_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderquote',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_quotes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdiscountapplication',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='special_orders.specialorderquote'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='accepted_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_order', to='special_orders.specialorderquote'),
        ),
        migrations.AddField(
            model_name='specialorderquoteline',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='special_orders.specialorderquote'),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_special_order_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='funding_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_applications', to='special_orders.specialorderfundingplan'),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_applications', to='special_orders.specialorderfundingmilestone'),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='original_payment_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_applications', to='special_orders.specialorderpaymentapplication'),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_special_order_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_applications', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderrefundapplication',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_refund_applications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderdisputeresolution',
            name='refund_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to='special_orders.specialorderrefundapplication'),
        ),
        migrations.AddField(
            model_name='specialorderrushsurchargerule',
            name='predefined_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rush_rules', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialorderrushsurchargerule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_rush_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorderstatushistory',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderstatushistory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_status_history', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialordertwofactorrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_two_factor_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialordertwofactorrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_special_order_two_factor_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialordertwofactorrequest',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_requests', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialordertwofactorrequest',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_requests', to='special_orders.specialorderplatformaccessvault'),
        ),
        migrations.AddField(
            model_name='specialordertwofactorrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_two_factor_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderwriterlevelsurchargerule',
            name='predefined_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_level_rules', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialorderwriterlevelsurchargerule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_writer_level_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderwriterpayrule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_writer_pay_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='writer_pay_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_orders', to='special_orders.specialorderwriterpayrule'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_order_bonuses', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_bonus', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='estimatedspecialordersettings',
            index=models.Index(fields=['website'], name='special_ord_website_21ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='predefinedspecialorderconfig',
            index=models.Index(fields=['website', 'is_active'], name='special_ord_website_f2b745_idx'),
        ),
        migrations.AddIndex(
            model_name='predefinedspecialorderconfig',
            index=models.Index(fields=['website', 'slug'], name='special_ord_website_cab5b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='predefinedspecialorderconfig',
            constraint=models.UniqueConstraint(fields=('website', 'slug'), name='unique_special_order_config_slug_per_website'),
        ),
        migrations.AddConstraint(
            model_name='predefinedspecialorderconfig',
            constraint=models.UniqueConstraint(fields=('website', 'name'), name='unique_special_order_config_name_per_website'),
        ),
        migrations.AddIndex(
            model_name='predefinedspecialorderduration',
            index=models.Index(fields=['website', 'duration_days'], name='special_ord_website_c6cc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='predefinedspecialorderduration',
            index=models.Index(fields=['predefined_order', 'is_active'], name='special_ord_predefi_443ae7_idx'),
        ),
        migrations.AddConstraint(
            model_name='predefinedspecialorderduration',
            constraint=models.UniqueConstraint(fields=('predefined_order', 'duration_days'), name='unique_special_order_duration_per_config'),
        ),
        migrations.AddIndex(
            model_name='specialorderanalyticsevent',
            index=models.Index(fields=['website', 'event_type'], name='special_ord_website_b20ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderanalyticsevent',
            index=models.Index(fields=['website', 'conversion_stage'], name='special_ord_website_e33ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderanalyticsevent',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_76a4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderanalyticsevent',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_e73cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderchangerequest',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_ea3f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderchangerequest',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_cfd725_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderchangerequest',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_3afdba_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderchangerequestquote',
            index=models.Index(fields=['website', 'change_request'], name='special_ord_website_cb3bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderchangerequestquote',
            index=models.Index(fields=['website', 'expires_at'], name='special_ord_website_00615a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordercompletionlog',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_483d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordercompletionlog',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_5f8c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordercompletionlog',
            index=models.Index(fields=['action'], name='special_ord_action_756225_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdeliverable',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_21082b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdeliverable',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_1989c0_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdeliverable',
            index=models.Index(fields=['file_reference'], name='special_ord_file_re_844b59_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountrule',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_fc149b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountrule',
            index=models.Index(fields=['website', 'code'], name='special_ord_website_b3051c_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountrule',
            index=models.Index(fields=['website', 'scope'], name='special_ord_website_b18d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountrule',
            index=models.Index(fields=['website', 'expires_at'], name='special_ord_website_3fbbd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialorderdiscountrule',
            constraint=models.UniqueConstraint(fields=('website', 'code'), name='unique_special_order_discount_code_per_site'),
        ),
        migrations.AddIndex(
            model_name='specialorderdispute',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_9a69d2_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdispute',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_ba0932_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdispute',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_e980ac_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderexternallink',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_c956de_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderexternallink',
            index=models.Index(fields=['website', 'link_type'], name='special_ord_website_b0e168_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdeliverycheckpoint',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_68de69_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdeliverycheckpoint',
            index=models.Index(fields=['website', 'checkpoint_type'], name='special_ord_website_491bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdeliverycheckpoint',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_5f3fec_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialorderdeliverycheckpoint',
            constraint=models.UniqueConstraint(fields=('special_order', 'checkpoint_type'), name='unique_special_order_delivery_checkpoint_type'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingplan',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_791c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingplan',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_e1e6de_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingplan',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_b02002_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingmilestone',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_04587b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingmilestone',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_5a89e9_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingmilestone',
            index=models.Index(fields=['funding_plan', 'sequence'], name='special_ord_funding_3bd74d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderfundingmilestone',
            index=models.Index(fields=['website', 'due_at'], name='special_ord_website_a9d6b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialorderfundingmilestone',
            constraint=models.UniqueConstraint(fields=('funding_plan', 'sequence'), name='unique_special_order_funding_milestone_sequence'),
        ),
        migrations.AddIndex(
            model_name='specialorderinstitutionprofile',
            index=models.Index(fields=['website', 'institution_name'], name='special_ord_website_302af5_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderinstitutionprofile',
            index=models.Index(fields=['website', 'institution_type'], name='special_ord_website_d4818e_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderinstitutionprofile',
            index=models.Index(fields=['website', 'program_name'], name='special_ord_website_82e64d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderinstitutionprofile',
            index=models.Index(fields=['website', 'course_code'], name='special_ord_website_2c0b74_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordermilestonetemplate',
            index=models.Index(fields=['website', 'is_active'], name='special_ord_website_64fb93_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialordermilestonetemplate',
            constraint=models.UniqueConstraint(fields=('website', 'name'), name='unique_special_order_milestone_template_name'),
        ),
        migrations.AddConstraint(
            model_name='specialordermilestonetemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'sequence'), name='unique_special_order_template_item_sequence'),
        ),
        migrations.AddIndex(
            model_name='specialorderpaymentapplication',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_cbf393_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderpaymentapplication',
            index=models.Index(fields=['website', 'source'], name='special_ord_website_4c3b31_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderpaymentapplication',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_b5f5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderpaymentapplication',
            index=models.Index(fields=['website', 'idempotency_key'], name='special_ord_website_cbc9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderpaymentapplication',
            index=models.Index(fields=['payment_intent_reference'], name='special_ord_payment_a30f51_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderpaymentapplication',
            index=models.Index(fields=['payment_transaction_reference'], name='special_ord_payment_030f0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialorderpaymentapplication',
            constraint=models.UniqueConstraint(fields=('website', 'idempotency_key'), name='unique_special_order_payment_idempotency_per_site'),
        ),
        migrations.AddIndex(
            model_name='specialorderadminoverride',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_d44692_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderadminoverride',
            index=models.Index(fields=['website', 'override_type'], name='special_ord_website_340798_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderadminoverride',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_59bb78_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderadminoverride',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_4245ac_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderplatformaccessvault',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_797233_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderplatformaccessvault',
            index=models.Index(fields=['website', 'platform'], name='special_ord_website_17df7e_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderplatformaccessvault',
            index=models.Index(fields=['website', 'is_active'], name='special_ord_website_82c3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccesslog',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_9342f7_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccesslog',
            index=models.Index(fields=['website', 'vault'], name='special_ord_website_bf4a86_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccesslog',
            index=models.Index(fields=['website', 'accessed_by'], name='special_ord_website_37835c_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccesslog',
            index=models.Index(fields=['website', 'action'], name='special_ord_website_d99524_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccesslog',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_ed786d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccessgrant',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_371eed_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccessgrant',
            index=models.Index(fields=['website', 'vault'], name='special_ord_website_8ec2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccessgrant',
            index=models.Index(fields=['website', 'granted_to'], name='special_ord_website_df11a3_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccessgrant',
            index=models.Index(fields=['website', 'expires_at'], name='special_ord_website_f67f72_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderaccessgrant',
            index=models.Index(fields=['website', 'revoked_at'], name='special_ord_website_f23bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderpricingsnapshot',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_588154_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderquote',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_ec6b04_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderquote',
            index=models.Index(fields=['website', 'expires_at'], name='special_ord_website_111b26_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountapplication',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_6638dc_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountapplication',
            index=models.Index(fields=['website', 'quote'], name='special_ord_website_311a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountapplication',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_b79de6_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdiscountapplication',
            index=models.Index(fields=['website', 'code'], name='special_ord_website_5f071b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderrefundapplication',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_a775ed_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderrefundapplication',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_51b61d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderrefundapplication',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_c4015e_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderrefundapplication',
            index=models.Index(fields=['refund_transaction_reference'], name='special_ord_refund__1a26d0_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdisputeresolution',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_159513_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdisputeresolution',
            index=models.Index(fields=['website', 'dispute'], name='special_ord_website_475036_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderdisputeresolution',
            index=models.Index(fields=['website', 'resolution_type'], name='special_ord_website_18eba9_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderstatushistory',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_049a26_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderstatushistory',
            index=models.Index(fields=['website', 'new_status'], name='special_ord_website_8cfc37_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderstatushistory',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_223190_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordertwofactorrequest',
            index=models.Index(fields=['website', 'special_order'], name='special_ord_website_f5437c_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordertwofactorrequest',
            index=models.Index(fields=['website', 'vault'], name='special_ord_website_2e5cff_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordertwofactorrequest',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_0a2e11_idx'),
        ),
        migrations.AddIndex(
            model_name='specialordertwofactorrequest',
            index=models.Index(fields=['website', 'expires_at'], name='special_ord_website_453221_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorderwriterpayrule',
            index=models.Index(fields=['website', 'is_active'], name='special_ord_website_27a84d_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialorderwriterpayrule',
            constraint=models.UniqueConstraint(fields=('website', 'name'), name='unique_special_order_writer_pay_rule_name'),
        ),
        migrations.AddIndex(
            model_name='specialorder',
            index=models.Index(fields=['website', 'status'], name='special_ord_website_b18540_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorder',
            index=models.Index(fields=['website', 'pricing_mode'], name='special_ord_website_7fe2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorder',
            index=models.Index(fields=['website', 'client'], name='special_ord_website_18499e_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorder',
            index=models.Index(fields=['website', 'writer'], name='special_ord_website_c70fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorder',
            index=models.Index(fields=['website', 'priority'], name='special_ord_website_6af726_idx'),
        ),
        migrations.AddIndex(
            model_name='specialorder',
            index=models.Index(fields=['website', 'created_at'], name='special_ord_website_40a04d_idx'),
        ),
    ]
