# Generated by Django 5.0.14 on 2025-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_orders', '0003_installmentpayment_payment_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialorder',
            name='writer_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed payment amount for the writer (set by admin when assigning).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='writer_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment percentage of order total for the writer (set by admin when assigning).', max_digits=5, null=True),
        ),
    ]
