# Generated by Django 5.0.14 on 2026-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_orders', '0002_add_class_payment_category'),
        ('special_orders', '0004_specialorder_writer_payment_amount_and_more'),
    ]

    operations = [
    ]
