# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='orders.order'),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='appealed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_appealed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='fine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='fineappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_appeals_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finepolicy',
            name='waived_by',
            field=models.ForeignKey(blank=True, help_text='User who waived the fine, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_waived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['order'], name='fines_fine_order_i_33c7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['fine_type'], name='fines_fine_fine_ty_5fc703_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status'], name='fines_fine_status_1fd55b_idx'),
        ),
        migrations.AddIndex(
            model_name='finepolicy',
            index=models.Index(fields=['fine_type', 'start_date'], name='fines_finep_fine_ty_b8d33d_idx'),
        ),
    ]
