# Generated by Django 5.0.14 on 2025-12-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCalculatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Django session key or user identifier', max_length=40)),
                ('order_data', models.JSONField(help_text='Order details (paper_type, pages, deadline, etc.)')),
                ('calculated_price', models.DecimalField(decimal_places=2, help_text='Calculated total price', max_digits=10)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price before adjustments', max_digits=10, null=True)),
                ('adjustments', models.JSONField(default=dict, help_text='Price adjustments breakdown (urgency, level, etc.)')),
                ('discount_code', models.CharField(blank=True, help_text='Applied discount code if any', max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final price after discounts', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this session expires (default 24 hours)')),
                ('converted_to_order', models.BooleanField(default=False, help_text='Whether this was converted to an actual order')),
                ('order_id', models.IntegerField(blank=True, help_text='Order ID if converted', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User if logged in, null for anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'expires_at'], name='pricing_pri_session_d25ca1_idx'), models.Index(fields=['user', 'converted_to_order'], name='pricing_pri_user_id_08ad99_idx')],
            },
        ),
    ]
