# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(default=0.0)),
                ('avg_scroll_depth', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0, help_text='Percentage of visits with scroll_depth < 25%')),
                ('thumbs_up_count', models.PositiveIntegerField(default=0)),
                ('thumbs_down_count', models.PositiveIntegerField(default=0)),
                ('love_count', models.PositiveIntegerField(default=0)),
                ('useful_count', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.PositiveIntegerField(default=0, help_text='Weighted score 0-100 from views, reactions, shares')),
                ('helpfulness_ratio', models.FloatField(default=0.0, help_text='(positive reactions) / (total reactions), 0.0 to 1.0')),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_summaries', to='wagtailcore.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'engagement_score'], name='cms_engagem_site_id_f2bf0b_idx'), models.Index(fields=['site', 'helpfulness_ratio'], name='cms_engagem_site_id_7dff18_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='PageBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='cms_engagem_user_id_69dcbf_idx')],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('reaction_type', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('love', 'Love'), ('useful', 'Found this useful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_reactions', to='wagtailcore.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'reaction_type'], name='cms_engagem_content_ee6d71_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('content_type', 'object_id', 'user'), name='unique_reaction_per_user'), models.UniqueConstraint(condition=models.Q(('session_id__gt', '')), fields=('content_type', 'object_id', 'session_id'), name='unique_reaction_per_session')],
            },
        ),
        migrations.CreateModel(
            name='PageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('reddit', 'Reddit'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('copy_link', 'Copy Link')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_shares', to='wagtailcore.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'platform'], name='cms_engagem_content_c07050_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('time_on_page', models.PositiveIntegerField(default=0, help_text='Seconds spent on page')),
                ('scroll_depth', models.PositiveSmallIntegerField(default=0, help_text='Maximum scroll depth percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='wagtailcore.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='cms_engagem_content_709a51_idx'), models.Index(fields=['site', 'created_at'], name='cms_engagem_site_id_7228f0_idx'), models.Index(fields=['session_id'], name='cms_engagem_session_b27670_idx')],
            },
        ),
    ]
