/**
 * Holidays & Special Days API
 * Manages special days, holidays, and automated marketing features
 */
import api from './client'

export const holidaysAPI = {
  /**
   * Special Days
   */
  specialDays: {
    /**
     * Get all special days
     * @param {Object} params - Query parameters (country, event_type, is_active, upcoming, days_ahead)
     */
    list(params = {}) {
      return api.get('/holidays/special-days/', { params })
    },

    /**
     * Get a specific special day
     * @param {number} id - Special day ID
     */
    get(id) {
      return api.get(`/holidays/special-days/${id}/`)
    },

    /**
     * Create a new special day
     * @param {Object} data - Special day data
     */
    create(data) {
      return api.post('/holidays/special-days/', data)
    },

    /**
     * Update a special day
     * @param {number} id - Special day ID
     * @param {Object} data - Updated special day data
     */
    update(id, data) {
      return api.patch(`/holidays/special-days/${id}/`, data)
    },

    /**
     * Delete a special day
     * @param {number} id - Special day ID
     */
    delete(id) {
      return api.delete(`/holidays/special-days/${id}/`)
    },

    /**
     * Get upcoming special days
     * @param {Object} params - Query parameters (days_ahead, country)
     */
    upcoming(params = {}) {
      return api.get('/holidays/special-days/upcoming/', { params })
    },

    /**
     * Generate discount for a special day
     * @param {number} id - Special day ID
     * @param {Object} data - Optional year
     */
    generateDiscount(id, data = {}) {
      return api.post(`/holidays/special-days/${id}/generate_discount/`, data)
    },

    /**
     * Auto-generate discounts for upcoming special days
     */
    autoGenerateDiscounts() {
      return api.post('/holidays/special-days/auto_generate_discounts/')
    }
  },

  /**
   * Holiday Reminders
   */
  reminders: {
    /**
     * Get all reminders
     * @param {Object} params - Query parameters (status, pending)
     */
    list(params = {}) {
      return api.get('/holidays/reminders/', { params })
    },

    /**
     * Get a specific reminder
     * @param {number} id - Reminder ID
     */
    get(id) {
      return api.get(`/holidays/reminders/${id}/`)
    },

    /**
     * Mark reminder as sent
     * @param {number} id - Reminder ID
     */
    markSent(id) {
      return api.post(`/holidays/reminders/${id}/mark_sent/`)
    },

    /**
     * Create discount for reminder's special day
     * @param {number} id - Reminder ID
     * @param {Object} data - Optional year
     */
    createDiscount(id, data = {}) {
      return api.post(`/holidays/reminders/${id}/create_discount/`, data)
    },

    /**
     * Check and create reminders for upcoming special days
     */
    checkAndCreate() {
      return api.post('/holidays/reminders/check_and_create/')
    },

    /**
     * Notify admins about pending reminders
     */
    notifyAdmins() {
      return api.post('/holidays/reminders/notify_admins/')
    }
  },

  /**
   * Holiday Discount Campaigns
   */
  campaigns: {
    /**
     * Get all campaigns
     * @param {Object} params - Query parameters (special_day, year, is_active)
     */
    list(params = {}) {
      return api.get('/holidays/campaigns/', { params })
    },

    /**
     * Get a specific campaign
     * @param {number} id - Campaign ID
     */
    get(id) {
      return api.get(`/holidays/campaigns/${id}/`)
    }
  }
}

