# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReputationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.UUIDField(db_index=True, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Precomputed reputation intelligence. Used for rewards, routing, leaderboards, and analytics.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('review.processed', 'Review Processed'), ('review.shadowed', 'Review Shadowed'), ('review.rejected', 'Review Rejected'), ('reputation.recalculated', 'Reputation Recalculated'), ('trust_score.updated', 'Trust Score Updated'), ('bonus.qualified', 'Bonus Qualified'), ('bonus.revoked', 'Bonus Revoked'), ('percentile.changed', 'Percentile Changed')], db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('review_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='reputation__target__ea5156_idx'), models.Index(fields=['event_type', 'created_at'], name='reputation__event_t_0242df_idx')],
            },
        ),
        migrations.CreateModel(
            name='WriterReputationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_id', models.UUIDField(db_index=True, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('verified_review_count', models.PositiveIntegerField(default=0)),
                ('trust_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Composite trust score derived from reputation, performance quality, consistency, and penalties.', max_digits=6)),
                ('percentile_rank', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outperforms X% of writers.', max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Measures rating stability over time.', max_digits=6)),
                ('rating_velocity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recent reputation momentum.', max_digits=6)),
                ('dispute_penalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('revision_penalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('cancellation_penalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('moderation_penalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('qualifies_for_bonus', models.BooleanField(default=False)),
                ('bonus_eligibility_reason', models.CharField(blank=True, max_length=255)),
                ('last_bonus_qualified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Precomputed reputation intelligence. Used for rewards, routing, leaderboards, and analytics.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_reputation_snapshots', to='websites.website')),
            ],
            options={
                'ordering': ['-trust_score'],
                'indexes': [models.Index(fields=['trust_score'], name='writer_rep_trust_idx'), models.Index(fields=['percentile_rank'], name='writer_rep_percentile_idx'), models.Index(fields=['qualifies_for_bonus'], name='writer_rep_bonus_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', Decimal('0.00')), ('rating__lte', Decimal('5.00'))), name='writer_rep_rating_range'), models.CheckConstraint(condition=models.Q(('percentile_rank__gte', Decimal('0.00')), ('percentile_rank__lte', Decimal('100.00'))), name='writer_rep_percentile_range'), models.CheckConstraint(condition=models.Q(('trust_score__gte', Decimal('0.00'))), name='writer_rep_trust_gte_0')],
            },
        ),
    ]
