# Generated by Django 5.0.14 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedSpecialOrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_deposit_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Default deposit percentage (e.g., 50.00 means 50%).', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Date when the installment is due.')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount for this installment.', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates whether this installment is paid.')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date when the installment was paid.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_steps', models.CharField(choices=[('writer_marked_complete_files', 'Writer Marked Complete with Files'), ('writer_marked_complete_no_files', 'Writer Marked Complete (No Files)'), ('admin_marked_paid', 'Admin Marked as Paid'), ('admin_unlocked_files', 'Admin Unlocked File Access')], help_text='Completion step taken.', max_length=255)),
                ('justification', models.TextField(blank=True, help_text='Reason for order completion.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedSpecialOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the predefined order type (e.g., Shadow Health).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the predefined order type.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this predefined order type is active.')),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedSpecialOrderDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days for the special order (e.g., 3, 5, 10).')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the special order based on the duration.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('predefined', 'Predefined Cost'), ('estimated', 'Estimated Cost')], default='estimated', max_length=20)),
                ('inquiry_details', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry Submitted'), ('awaiting_approval', 'Awaiting Approval'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='inquiry', max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days for the special order (e.g., 2, 3, 10).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Price per day for estimated orders.', max_digits=10, null=True)),
                ('admin_approved_cost', models.DecimalField(blank=True, decimal_places=2, help_text='The cost the admin has approved for this special order.', max_digits=10, null=True)),
                ('admin_marked_paid', models.BooleanField(default=False, help_text='Has the admin manually marked this order as paid?')),
                ('admin_unlocked_files', models.BooleanField(default=False, help_text='Has the admin manually unlocked file downloads?')),
                ('writer_completed_no_files', models.BooleanField(default=False, help_text='Did the writer complete the order without uploading files?')),
            ],
        ),
        migrations.CreateModel(
            name='WriterBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('performance', 'Outstanding Performance'), ('order_completion', 'Order Completion'), ('client_tip', 'Client Tip'), ('other', 'Other')], default='client_tip', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
