# Generated by Django 5.1.6 on 2025-02-22 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedSpecialOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the predefined order type (e.g., Shadow Health).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the predefined order type.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this predefined order type is active.')),
                ('website', models.ForeignKey(help_text='Website for which this configuration is valid.', on_delete=django.db.models.deletion.CASCADE, related_name='predefined_special_order_configs', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('predefined', 'Predefined Cost'), ('estimated', 'Estimated Cost')], default='estimated', max_length=20)),
                ('inquiry_details', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry Submitted'), ('awaiting_approval', 'Awaiting Approval'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='inquiry', max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days for the special order (e.g., 2, 3, 10).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_marked_paid', models.BooleanField(default=False, help_text='Has the admin manually marked this order as paid?')),
                ('admin_unlocked_files', models.BooleanField(default=False, help_text='Has the admin manually unlocked file downloads?')),
                ('writer_completed_no_files', models.BooleanField(default=False, help_text='Did the writer complete the order without uploading files?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to=settings.AUTH_USER_MODEL)),
                ('predefined_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_orders', to='special_orders.predefinedspecialorderconfig')),
                ('website', models.ForeignKey(help_text='Website associated with this special order.', on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to='websites.website')),
                ('writer', models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_special_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_method', models.CharField(choices=[('admin_marked_paid', 'Admin Marked as Paid'), ('admin_unlocked_files', 'Admin Unlocked File Access'), ('writer_completed_no_files', 'Writer Marked Complete (No Files)')], help_text='Completion method used.', max_length=50)),
                ('justification', models.TextField(blank=True, help_text='Reason for order completion.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_completions', to=settings.AUTH_USER_MODEL)),
                ('special_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='special_orders.specialorder')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Date when the installment is due.')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount for this installment.', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates whether this installment is paid.')),
                ('special_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='special_orders.specialorder')),
            ],
        ),
        migrations.CreateModel(
            name='WriterBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('performance', 'Outstanding Performance'), ('client_tip', 'Client Tip'), ('other', 'Other')], default='client_tip', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('special_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='special_orders.specialorder')),
                ('writer', models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedSpecialOrderDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days for the special order (e.g., 3, 5, 10).')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the special order based on the duration.', max_digits=10)),
                ('predefined_order', models.ForeignKey(help_text='The predefined order this pricing is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='special_orders.predefinedspecialorderconfig')),
            ],
            options={
                'unique_together': {('predefined_order', 'duration_days')},
            },
        ),
    ]
