# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('special_orders', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedspecialordersettings',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_order_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ordercompletionlog',
            name='completed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercompletionlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdo_completion_log', to='websites.website'),
        ),
        migrations.AddField(
            model_name='predefinedspecialorderconfig',
            name='website',
            field=models.ForeignKey(help_text='Website for which this configuration is valid.', on_delete=django.db.models.deletion.CASCADE, related_name='predefined_special_order_configs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='predefinedspecialorderduration',
            name='predefined_order',
            field=models.ForeignKey(help_text='The predefined order this pricing is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='predefinedspecialorderduration',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdo_duration', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='predefined_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_orders', to='special_orders.predefinedspecialorderconfig'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='website',
            field=models.ForeignKey(help_text='Website associated with this special order.', on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='writer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_special_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercompletionlog',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_bonus', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='predefinedspecialorderduration',
            unique_together={('predefined_order', 'duration_days')},
        ),
    ]
