# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classperformancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientanalytics',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientanalytics',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_analytics', to='websites.website'),
        ),
        migrations.AddField(
            model_name='clientanalyticssnapshot',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_analytics_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientanalyticssnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_analytics_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='contentevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentevent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writeranalytics',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_analytics', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writeranalytics',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='writer_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeranalyticssnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_analytics_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writeranalyticssnapshot',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='writer_analytics_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classanalytics',
            index=models.Index(fields=['website', 'class_name', 'period_start'], name='analytics_c_website_fb2347_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classanalytics',
            unique_together={('website', 'class_name', 'class_id', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='clientanalytics',
            index=models.Index(fields=['client', 'website', 'period_start'], name='analytics_c_client__fef457_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientanalytics',
            unique_together={('client', 'website', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='clientanalyticssnapshot',
            index=models.Index(fields=['client', 'website', 'snapshot_date'], name='analytics_c_client__81fcf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientanalyticssnapshot',
            unique_together={('client', 'website', 'snapshot_date', 'snapshot_type')},
        ),
        migrations.AddIndex(
            model_name='contentevent',
            index=models.Index(fields=['website', 'event_type', 'created_at'], name='analytics_c_website_f9a440_idx'),
        ),
        migrations.AddIndex(
            model_name='contentevent',
            index=models.Index(fields=['website', 'content_type', 'object_id'], name='analytics_c_website_bf3dec_idx'),
        ),
        migrations.AddIndex(
            model_name='writeranalytics',
            index=models.Index(fields=['writer', 'website', 'period_start'], name='analytics_w_writer__75f41c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writeranalytics',
            unique_together={('writer', 'website', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='writeranalyticssnapshot',
            index=models.Index(fields=['writer', 'website', 'snapshot_date'], name='analytics_w_writer__5f57a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writeranalyticssnapshot',
            unique_together={('writer', 'website', 'snapshot_date', 'snapshot_type')},
        ),
    ]
