# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the additional service (e.g., Plagiarism Report).', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the service.')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of the service (USD).', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently active.')),
                ('slug', models.SlugField(help_text='Unique slug for the service (used in URLs).', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the pricing was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the pricing was last updated.')),
            ],
            options={
                'verbose_name': 'Additional Service',
                'verbose_name_plural': 'Additional Services',
            },
        ),
        migrations.CreateModel(
            name='DeadlineMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Label for the deadline (e.g., '1 Hour', '1 Day', '2 Days').", max_length=100)),
                ('hours', models.PositiveIntegerField(help_text='Deadline in hours (e.g. 24 hours for a day, 48 for 2 days, etc.)')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier for this deadline (e.g., 1.3 for 24h)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deadline Multiplier',
                'verbose_name_plural': 'Deadline Multipliers',
                'ordering': ['website', 'hours'],
            },
        ),
        migrations.CreateModel(
            name='PreferredWriterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_writer_cost', models.DecimalField(decimal_places=2, help_text='Extra cost (in USD) for selecting this preferred writer', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['website', 'writer'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_page', models.DecimalField(decimal_places=2, help_text='Base price per page (USD).', max_digits=10)),
                ('base_price_per_slide', models.DecimalField(decimal_places=2, help_text='Base price per slide (USD).', max_digits=10)),
                ('technical_multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier for technical subjects (e.g., 1.5x for technical.)', max_digits=5)),
                ('non_technical_order_multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier for non-technical subjects(e.g., 1.0x for non-technical).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the pricing was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the pricing was last updated.')),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='TypeOfWorkMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of work (e.g., Technical Writing, Lab Report, etc.)', max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier applied to base price for this work type.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('description', models.TextField(blank=True, help_text='Optional description of the work type.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the multiplier was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the multiplier was last updated.')),
            ],
            options={
                'verbose_name': 'Order Type Multiplier',
                'verbose_name_plural': 'Order Type Multipliers',
                'ordering': ['website', 'name', 'multiplier'],
            },
        ),
        migrations.CreateModel(
            name='WriterLevelOptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label shown to clients (e.g., Top 10, Advanced)', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Fixed price or multiplier based on pricing_type', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional client-facing note')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Writer Level Option',
                'verbose_name_plural': 'Writer Level Options',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLevelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier applied to base order pricing for this academic level.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('level_name', models.CharField(help_text='Name of the academic level (e.g., Undergraduate, Graduate, PhD).', max_length=100)),
                ('slug', models.SlugField(help_text='Unique slug for the academic level (used in URLs).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the academic level.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the pricing was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the pricing was last updated.')),
                ('academic_level', models.OneToOneField(help_text='Academic Level this pricing applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_for_academic_level', to='order_configs.academiclevel')),
            ],
            options={
                'verbose_name': 'Academic Level Pricing',
                'verbose_name_plural': 'Academic Level Pricing',
                'ordering': ['website', 'academic_level'],
            },
        ),
    ]
