# Generated by Django 5.0.14 on 2026-05-28 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_pricing_core', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevelrate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='analysislevelrate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_pricing_analysis_level_rates', to='websites.website'),
        ),
        migrations.AddField(
            model_name='compositepricingquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_composite_pricing_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compositepricingquote',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_pricing_quotes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='compositepricingquoteitem',
            name='composite_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_pricing_core.compositepricingquote'),
        ),
        migrations.AddField(
            model_name='deadlinerate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_pricing_deadline_rates', to='websites.website'),
        ),
        migrations.AddField(
            model_name='diagramcomplexityrate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_pricing_diagram_complexity_rates', to='websites.website'),
        ),
        migrations.AddField(
            model_name='papertyperate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='pricingcalculatorsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User if logged in, null for anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_pricing_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingquote',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pricing_quotes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='compositepricingquoteitem',
            name='pricing_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composite_items', to='order_pricing_core.pricingquote'),
        ),
        migrations.AddField(
            model_name='pricingquoteinput',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_data', to='order_pricing_core.pricingquote'),
        ),
        migrations.AddField(
            model_name='pricingquoteline',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order_pricing_core.pricingquote'),
        ),
        migrations.AddField(
            model_name='pricingsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_core_pricing_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingsnapshot',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot', to='order_pricing_core.pricingquote'),
        ),
        migrations.AddField(
            model_name='pricingsnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_pricing_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='pricingsnapshotline',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order_pricing_core.pricingsnapshot'),
        ),
        migrations.AddField(
            model_name='serviceaddon',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pricing_addons', to='websites.website'),
        ),
        migrations.AddField(
            model_name='serviceaddonapplicability',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='order_pricing_core.serviceaddon'),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pricing_services', to='websites.website'),
        ),
        migrations.AddField(
            model_name='serviceaddonapplicability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_links', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='pricingsnapshot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_snapshots', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='pricingquote',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_quotes', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='paperorderserviceconfig',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_order_config', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='diagramorderserviceconfig',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_order_config', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='designorderserviceconfig',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_order_config', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='compositepricingquoteitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composite_quote_items', to='order_pricing_core.servicecatalogitem'),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='subjectrate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='order_pricing_core.subjectcategory'),
        ),
        migrations.AddField(
            model_name='subjectrate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='websitepricingprofile',
            name='cloned_from_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_orders_pricing_profiles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='websitepricingprofile',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders_pricing_profile', to='websites.website'),
        ),
        migrations.AddField(
            model_name='worktyperate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerlevelrate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='academiclevelrate',
            unique_together={('website', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='analysislevelrate',
            unique_together={('website', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='diagramcomplexityrate',
            unique_together={('website', 'complexity')},
        ),
        migrations.AlterUniqueTogether(
            name='papertyperate',
            unique_together={('website', 'code')},
        ),
        migrations.AddIndex(
            model_name='pricingcalculatorsession',
            index=models.Index(fields=['session_key', 'expires_at'], name='order_prici_session_8c7918_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingcalculatorsession',
            index=models.Index(fields=['user', 'converted_to_order'], name='order_prici_user_id_80edb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaddon',
            unique_together={('website', 'addon_code')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecatalogitem',
            unique_together={('website', 'service_code')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceaddonapplicability',
            unique_together={('addon', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='compositepricingquoteitem',
            unique_together={('composite_quote', 'pricing_quote')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectcategory',
            unique_together={('website', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectrate',
            unique_together={('website', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='worktyperate',
            unique_together={('website', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='writerlevelrate',
            unique_together={('website', 'code')},
        ),
    ]
