# Generated by Django 5.0.14 on 2025-10-29 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(help_text='Duration copied from config', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('exhausted', 'Exhausted'), ('completed', 'Completed')], default='in_progress', help_text='The status of the class bundle.', max_length=20)),
                ('level', models.CharField(help_text='Level copied from config', max_length=10)),
                ('bundle_size', models.PositiveIntegerField(help_text='Number of classes in this bundle')),
                ('price_per_class', models.DecimalField(decimal_places=2, help_text='Price per class in this bundle', max_digits=10)),
                ('number_of_classes', models.PositiveIntegerField(help_text='Actual number of classes client needs done')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Calculated full price of the bundle', max_digits=10)),
                ('balance_remaining', models.DecimalField(decimal_places=2, help_text='Remaining balance after payments', max_digits=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Class Bundle',
                'verbose_name_plural': 'Class Bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassBundleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('undergrad', 'Undergraduate'), ('grad', 'Graduate')], help_text='Academic level', max_length=10)),
                ('bundle_size', models.PositiveIntegerField(help_text='Number of classes in bundle')),
                ('price_per_class', models.DecimalField(decimal_places=2, help_text='Price per individual class', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(help_text="Short identifier e.g., '15-16'", max_length=10)),
                ('label', models.CharField(help_text="Human-readable label e.g., '15–16 weeks'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', help_text='Current payment status', max_length=20)),
                ('price_locked', models.DecimalField(decimal_places=2, help_text='Locked price at time of payment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Payment processor ref (e.g. Stripe)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date for the express class')),
                ('end_date', models.DateField(help_text='End date for the express class')),
                ('discipline', models.CharField(help_text='Discipline of the express class e.g., Math, Nursing', max_length=100)),
                ('number_of_discussion_posts', models.PositiveIntegerField(help_text='Number of discussion posts required')),
                ('number_of_discussion_posts_replies', models.PositiveIntegerField(help_text='Number of discussion post replies required')),
                ('number_of_assignments', models.PositiveIntegerField(help_text='Number of assignments required')),
                ('number_of_exams', models.PositiveIntegerField(help_text='Number of exams required')),
                ('number_of_quizzes', models.PositiveIntegerField(help_text='Number of quizzes required')),
                ('number_of_projects', models.PositiveIntegerField(help_text='Number of projects required')),
                ('number_of_presentations', models.PositiveIntegerField(help_text='Number of presentations required')),
                ('number_of_papers', models.PositiveIntegerField(help_text='Number of papers required')),
                ('total_workload_in_pages', models.CharField(help_text="Workload e.g., 'number of pages total'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the express class', max_digits=10)),
                ('installments_needed', models.PositiveIntegerField(help_text='Number of installments needed')),
                ('instructions', models.TextField(help_text='Special instructions for the express class')),
                ('institution', models.CharField(help_text="Client's institution", max_length=255)),
                ('course', models.CharField(help_text='Course name or code', max_length=255)),
                ('academic_level', models.CharField(help_text='Academic level e.g., Undergraduate, Graduate', max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Express Class',
                'verbose_name_plural': 'Express Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('deduction', 'Deduction'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
