# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classaccessdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_access_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classaccessdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_class_access_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classaccessgrant',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_class_access_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classaccesslog',
            name='viewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classinstallment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='class_management.classinstallmentplan'),
        ),
        migrations.AddField(
            model_name='classorder',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_class_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_class_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classorder',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_orders', to='websites.website'),
        ),
        migrations.AddField(
            model_name='classinvoicelink',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classinstallmentplan',
            name='class_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classaccesslog',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classaccessgrant',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classaccessdetail',
            name='class_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_detail', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classpaymentallocation',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classpaymentallocation',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='class_management.classinstallment'),
        ),
        migrations.AddField(
            model_name='classportalworklog',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_work_logs', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classportalworklog',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_class_portal_work_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classportalworklog',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_portal_work_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classpricecounteroffer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_price_counter_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classpriceproposal',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_class_price_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classpriceproposal',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_proposals', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classpriceproposal',
            name='proposed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_price_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classpricecounteroffer',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='class_management.classpriceproposal'),
        ),
        migrations.AddField(
            model_name='classorder',
            name='latest_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='class_management.classpriceproposal'),
        ),
        migrations.AddField(
            model_name='classscopeassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_scope_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classscopeassessment',
            name='class_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope_assessment', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classscopeitem',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classscopeitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_scope_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtask',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtask',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtask',
            name='scope_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='class_management.classscopeitem'),
        ),
        migrations.AddField(
            model_name='classportalworklog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_work_logs', to='class_management.classtask'),
        ),
        migrations.AddField(
            model_name='classtimelineevent',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classtimelineevent',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtwofactorrequest',
            name='class_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_requests', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classtwofactorrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_class_two_factor_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtwofactorwindow',
            name='access_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_windows', to='class_management.classaccessdetail'),
        ),
        migrations.AddField(
            model_name='classwritercompensation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_class_writer_compensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classwritercompensation',
            name='class_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_compensation', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='classwritercompensation',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_class_writer_compensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classwritercompensation',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_writer_compensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classinstallment',
            index=models.Index(fields=['status', 'due_at'], name='class_manag_status_ecd68e_idx'),
        ),
        migrations.AddIndex(
            model_name='classinvoicelink',
            index=models.Index(fields=['class_order', 'invoice_id'], name='class_manag_class_o_b1436b_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['class_order', 'status'], name='class_manag_class_o_679c04_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['writer', 'status'], name='class_manag_writer__f37cec_idx'),
        ),
        migrations.AddIndex(
            model_name='classaccesslog',
            index=models.Index(fields=['class_order', 'viewed_at'], name='class_manag_class_o_b1cce8_idx'),
        ),
        migrations.AddIndex(
            model_name='classaccesslog',
            index=models.Index(fields=['viewed_by', 'viewed_at'], name='class_manag_viewed__1eebe3_idx'),
        ),
        migrations.AddConstraint(
            model_name='classaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('class_order', 'user'), name='unique_active_class_access_grant'),
        ),
        migrations.AddIndex(
            model_name='classpaymentallocation',
            index=models.Index(fields=['class_order', 'source_type'], name='class_manag_class_o_a52da7_idx'),
        ),
        migrations.AddIndex(
            model_name='classpaymentallocation',
            index=models.Index(fields=['payment_intent_id'], name='class_manag_payment_16b2af_idx'),
        ),
        migrations.AddIndex(
            model_name='classpaymentallocation',
            index=models.Index(fields=['wallet_transaction_id'], name='class_manag_wallet__acc0cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='classpaymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_intent_id', ''), _negated=True), fields=('payment_intent_id',), name='unique_class_payment_intent_id'),
        ),
        migrations.AddConstraint(
            model_name='classpaymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_transaction_id', ''), _negated=True), fields=('payment_transaction_id',), name='unique_class_payment_transaction_id'),
        ),
        migrations.AddIndex(
            model_name='classpriceproposal',
            index=models.Index(fields=['class_order', 'status'], name='class_manag_class_o_528f61_idx'),
        ),
        migrations.AddIndex(
            model_name='classorder',
            index=models.Index(fields=['website', 'status'], name='class_manag_website_8b8dff_idx'),
        ),
        migrations.AddIndex(
            model_name='classorder',
            index=models.Index(fields=['website', 'client'], name='class_manag_website_b97d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='classorder',
            index=models.Index(fields=['website', 'assigned_writer'], name='class_manag_website_8d1949_idx'),
        ),
        migrations.AddIndex(
            model_name='classorder',
            index=models.Index(fields=['payment_status'], name='class_manag_payment_52ea25_idx'),
        ),
        migrations.AddConstraint(
            model_name='classorder',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='class_order_currency_not_empty'),
        ),
        migrations.AddIndex(
            model_name='classscopeitem',
            index=models.Index(fields=['class_order', 'item_type'], name='class_manag_class_o_fc1b31_idx'),
        ),
        migrations.AddIndex(
            model_name='classscopeitem',
            index=models.Index(fields=['due_at'], name='class_manag_due_at_a76507_idx'),
        ),
        migrations.AddIndex(
            model_name='classtask',
            index=models.Index(fields=['class_order', 'status'], name='class_manag_class_o_5d9e41_idx'),
        ),
        migrations.AddIndex(
            model_name='classtask',
            index=models.Index(fields=['assigned_writer', 'status'], name='class_manag_assigne_f41d91_idx'),
        ),
        migrations.AddIndex(
            model_name='classtask',
            index=models.Index(fields=['due_at'], name='class_manag_due_at_3d78fe_idx'),
        ),
        migrations.AddIndex(
            model_name='classportalworklog',
            index=models.Index(fields=['class_order', 'activity_type'], name='class_manag_class_o_0d6118_idx'),
        ),
        migrations.AddIndex(
            model_name='classportalworklog',
            index=models.Index(fields=['writer', 'logged_at'], name='class_manag_writer__19ba46_idx'),
        ),
        migrations.AddIndex(
            model_name='classportalworklog',
            index=models.Index(fields=['verification_status'], name='class_manag_verific_07db97_idx'),
        ),
        migrations.AddIndex(
            model_name='classportalworklog',
            index=models.Index(fields=['visible_to_client'], name='class_manag_visible_6f5115_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimelineevent',
            index=models.Index(fields=['class_order', 'created_at'], name='class_manag_class_o_d14b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimelineevent',
            index=models.Index(fields=['event_type'], name='class_manag_event_t_e87689_idx'),
        ),
        migrations.AddIndex(
            model_name='classtwofactorrequest',
            index=models.Index(fields=['class_order', 'status'], name='class_manag_class_o_ada212_idx'),
        ),
        migrations.AddIndex(
            model_name='classtwofactorwindow',
            index=models.Index(fields=['weekday', 'is_active'], name='class_manag_weekday_ca0003_idx'),
        ),
        migrations.AddConstraint(
            model_name='classwritercompensation',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gte', 0)), name='class_writer_comp_final_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='classwritercompensation',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='class_writer_comp_paid_amount_non_negative'),
        ),
    ]
