# Generated by Django 5.2.2 on 2026-06-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0003_class_service_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classorder',
            new_name='class_manag_website_27759d_idx',
            old_name='class_manag_website_18541c_idx',
        ),
        migrations.RenameIndex(
            model_name='classserviceconfig',
            new_name='class_manag_website_fbd380_idx',
            old_name='class_manag_website_295020_idx',
        ),
        migrations.RenameIndex(
            model_name='classserviceconfig',
            new_name='class_manag_website_46e33b_idx',
            old_name='class_manag_website_3aad64_idx',
        ),
        migrations.RenameIndex(
            model_name='classserviceconfig',
            new_name='class_manag_display_30bdbf_idx',
            old_name='class_manag_display_f9d343_idx',
        ),
    ]
