# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0004_rename_class_manag_website_18541c_idx_class_manag_website_27759d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classorder",
            name="public_order_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "Admin-configured public-facing class reference. "
                    "Never equals the database primary key."
                ),
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
