# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0005_alter_classinstallment_options_and_more'),
        ('order_payments_management', '0011_alter_orderpayment_payment_status_and_more'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classbundlefile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, help_text='Remaining balance after payments (excluding deposit)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='bundle_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of classes in this bundle', null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='config',
            field=models.ForeignKey(blank=True, help_text='Base pricing config used (if from config)', null=True, on_delete=django.db.models.deletion.PROTECT, to='class_management.classbundleconfig'),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of deposit already paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount required before starting classes (set by admin, after discount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration copied from config or manually set', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='end_date',
            field=models.DateField(blank=True, help_text='Class end date (date B)', null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of installments (set by admin)', null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='installments_enabled',
            field=models.BooleanField(default=False, help_text='Whether installments are enabled for this bundle'),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='level',
            field=models.CharField(blank=True, help_text='Level copied from config or manually set', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='price_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per class in this bundle', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='pricing_source',
            field=models.CharField(choices=[('config', 'From Bundle Config'), ('manual', 'Admin Manual Entry')], default='config', help_text='Whether pricing came from config or manual admin entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='start_date',
            field=models.DateField(blank=True, help_text='Class start date (date A)', null=True),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price of the bundle (from config or manually set, before discount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='classbundle',
            name='website',
            field=models.ForeignKey(help_text='Website this bundle belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='class_bundles', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the file'),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='file',
            field=models.FileField(help_text='Uploaded file', upload_to='class_bundles/files/'),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='is_visible_to_client',
            field=models.BooleanField(default=True, help_text='Whether file is visible to client'),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='is_visible_to_writer',
            field=models.BooleanField(default=True, help_text='Whether file is visible to writer'),
        ),
        migrations.AlterField(
            model_name='classbundlefile',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='class_bundle_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classpurchase',
            name='bundle',
            field=models.ForeignKey(help_text='Target class bundle', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='class_management.classbundle'),
        ),
        migrations.AlterField(
            model_name='classpurchase',
            name='payment_record',
            field=models.ForeignKey(blank=True, help_text='The actual payment transaction record (for unified payment workflow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_purchases', to='order_payments_management.orderpayment'),
        ),
        migrations.AlterField(
            model_name='classpurchase',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit Payment'), ('full', 'Full Payment'), ('installment', 'Installment Payment')], default='deposit', help_text='Type of payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='classpurchase',
            name='website',
            field=models.ForeignKey(help_text='Website this purchase belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='class_purchases', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='expressclass',
            name='client',
            field=models.ForeignKey(help_text='Client booking the express class', on_delete=django.db.models.deletion.CASCADE, related_name='express_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expressclass',
            name='website',
            field=models.ForeignKey(help_text='Website this express class belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='express_classes', to='websites.website'),
        ),
    ]
