# Generated by Django 5.0.14 on 2026-01-08 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0020_add_class_payment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classpayment',
            new_name='class_manag_class_b_4fa850_idx',
            old_name='class_manage_class_b_client_p_idx',
        ),
        migrations.RenameIndex(
            model_name='classpayment',
            new_name='class_manag_assigne_e71819_idx',
            old_name='class_manage_assigned_writer_p_idx',
        ),
        migrations.RenameIndex(
            model_name='classpayment',
            new_name='class_manag_website_b736f3_idx',
            old_name='class_manage_website_client_p_idx',
        ),
        migrations.RenameIndex(
            model_name='classpayment',
            new_name='class_manag_assigne_116ff2_idx',
            old_name='class_manage_assigned_writer_w_idx',
        ),
        migrations.RenameIndex(
            model_name='classpaymentinstallment',
            new_name='class_manag_class_p_fcf2ce_idx',
            old_name='class_manage_class_p_is_paid_idx',
        ),
        migrations.RenameIndex(
            model_name='classpaymentinstallment',
            new_name='class_manag_class_p_c0bc37_idx',
            old_name='class_manage_class_p_installment_idx',
        ),
        migrations.RenameIndex(
            model_name='classwriterpayment',
            new_name='class_manag_class_p_1ae2dd_idx',
            old_name='class_manage_class_p_is_paid_w_idx',
        ),
        migrations.RenameIndex(
            model_name='classwriterpayment',
            new_name='class_manag_class_p_010d41_idx',
            old_name='class_manage_class_p_payment_t_idx',
        ),
        migrations.AlterField(
            model_name='classpayment',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, help_text='Writer assigned to this class bundle', limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
