# Generated by Django 5.0.14 on 2026-01-09 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0021_rename_class_manage_class_b_client_p_idx_class_manag_class_b_4fa850_idx_and_more'),
        ('websites', '0011_add_external_review_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expressclass',
            name='availability_hours',
            field=models.CharField(blank=True, help_text="When the writer can access the portal (e.g., 'Mon-Fri 9am-5pm EST' or '24/7')", max_length=255),
        ),
        migrations.AddField(
            model_name='expressclass',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Client's stated budget for negotiation purposes", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expressclass',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether two-factor authentication is required for this account'),
        ),
        migrations.CreateModel(
            name='ExpressClassInquiryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='express_classes/inquiry_files/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded')),
                ('express_class', models.ForeignKey(help_text='Express class this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_files', to='class_management.expressclass')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='express_class_inquiry_files_uploaded', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_class_inquiry_files', to='websites.website')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['express_class', 'uploaded_at'], name='class_manag_express_322361_idx')],
            },
        ),
    ]
