# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('order.created', 'Order created'), ('order.paid', 'Order paid'), ('order.assigned', 'Order assigned'), ('order.submitted', 'Order submitted'), ('order.completed', 'Order completed'), ('order.revision_requested', 'Order revision requested'), ('file.uploaded', 'File uploaded'), ('file.approved', 'File approved'), ('message.sent', 'Message sent'), ('thread.created', 'Thread created'), ('wallet.credited', 'Wallet credited'), ('wallet.debited', 'Wallet debited'), ('payment.received', 'Payment received'), ('refund.requested', 'Refund requested'), ('class.created', 'Class created'), ('class.updated', 'Class updated'), ('special_order.created', 'Special order created'), ('special_order.milestone_funded', 'Special order milestone funded'), ('system.notice', 'System notice')], db_index=True, max_length=80)),
                ('actor_type', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('writer', 'Writer'), ('support', 'Support'), ('editor', 'Editor'), ('superadmin', 'Super Admin'), ('system', 'System')], default='system', max_length=24)),
                ('actor_object_id', models.CharField(blank=True, max_length=64)),
                ('target_object_id', models.CharField(db_index=True, max_length=64)),
                ('subject_object_id', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=24)),
                ('audiences', models.JSONField(default=list, help_text='Audience codes allowed to view this event.')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_actor_events', to='contenttypes.contenttype')),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_subject_events', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_target_events', to='contenttypes.contenttype')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='websites.website')),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeedState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_states', to='activity.activityevent')),
            ],
            options={
                'verbose_name': 'Activity Feed State',
                'verbose_name_plural': 'Activity Feed States',
            },
        ),
    ]
