# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeedstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['website', 'occurred_at'], name='activity_ac_website_fd51ad_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['website', 'verb', 'occurred_at'], name='activity_ac_website_0125c0_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='activity_ac_target__962019_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['actor_content_type', 'actor_object_id'], name='activity_ac_actor_c_23b33d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['severity', 'occurred_at'], name='activity_ac_severit_bb2679_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeedstate',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='activity_ac_user_id_6f8ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeedstate',
            index=models.Index(fields=['user', 'is_dismissed', 'created_at'], name='activity_ac_user_id_941388_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityfeedstate',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_activity_feed_state_per_user'),
        ),
    ]
