# Generated by Django 5.2.2 on 2026-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('order.created', 'Order created'), ('order.paid', 'Order paid'), ('order.assigned', 'Order assigned'), ('order.submitted', 'Order submitted'), ('order.completed', 'Order completed'), ('order.revision_requested', 'Order revision requested'), ('file.uploaded', 'File uploaded'), ('file.approved', 'File approved'), ('file.downloaded', 'File downloaded'), ('message.sent', 'Message sent'), ('thread.created', 'Thread created'), ('wallet.credited', 'Wallet credited'), ('wallet.debited', 'Wallet debited'), ('payment.received', 'Payment received'), ('refund.requested', 'Refund requested'), ('class.created', 'Class created'), ('class.updated', 'Class updated'), ('special_order.created', 'Special order created'), ('special_order.milestone_funded', 'Special order milestone funded'), ('system.notice', 'System notice')], db_index=True, max_length=80),
        ),
    ]
