from __future__ import annotations

from decimal import Decimal

from orders.models.orders.enums import (
    OrderAdjustmentEventType,
    OrderAdjustmentFundingStatus,
    OrderAdjustmentProposalRole,
    OrderAdjustmentProposalType,
    OrderAdjustmentStatus,
    OrderAdjustmentType,
    OrderAssignmentSource,
    OrderAssignmentStatus,
    OrderCompensationAdjustmentStatus,
    OrderCompensationAdjustmentType,
    OrderHoldStatus,
    OrderInterestStatus,
    OrderInterestType,
    OrderPaymentStatus,
    OrderPostCounterEscalationReason,
    OrderRevisionEventType,
    OrderRevisionStatus,
    OrderScopeUnitType,
    OrderSpacingOptions,
    OrderStatus,
    OrderTimelineEventType,
    OrderVisibilityMode,
    PreferredWriterStatus,
)

# Spacing Options
ORDER_SINGLE_SPACING = OrderSpacingOptions.SINGLE_SPACING
ORDER_DOUBLE_SPACING = OrderSpacingOptions.DOUBLE_SPACING

# Order Statuses
ORDER_STATUS_CREATED = OrderStatus.CREATED
ORDER_STATUS_UNPAID = OrderStatus.UNPAID
ORDER_STATUS_PENDING_PAYMENT = OrderStatus.PENDING_PAYMENT
ORDER_STATUS_PAID = OrderStatus.PAID
ORDER_STATUS_READY_FOR_STAFFING = OrderStatus.READY_FOR_STAFFING
ORDER_STATUS_IN_PROGRESS = OrderStatus.IN_PROGRESS
ORDER_STATUS_ON_HOLD = OrderStatus.ON_HOLD
ORDER_STATUS_QA_REVIEW = OrderStatus.QA_REVIEW
ORDER_STATUS_SUBMITTED = OrderStatus.SUBMITTED
ORDER_STATUS_COMPLETED = OrderStatus.COMPLETED
ORDER_STATUS_DISPUTED = OrderStatus.DISPUTED
ORDER_STATUS_CANCELLED = OrderStatus.CANCELLED
ORDER_STATUS_ARCHIVED = OrderStatus.ARCHIVED

# Visibility
ORDER_VISIBILITY_HIDDEN = OrderVisibilityMode.HIDDEN
ORDER_VISIBILITY_POOL = OrderVisibilityMode.POOL
ORDER_VISIBILITY_PREFERRED_WRITER_ONLY = (
    OrderVisibilityMode.PREFERRED_WRITER_ONLY
)

# Preferred Writer Status
PREFERRED_WRITER_STATUS_NOT_REQUESTED = (
    PreferredWriterStatus.NOT_REQUESTED
)
PREFERRED_WRITER_STATUS_INVITED = PreferredWriterStatus.INVITED
PREFERRED_WRITER_STATUS_ACCEPTED = PreferredWriterStatus.ACCEPTED
PREFERRED_WRITER_STATUS_DECLINED = PreferredWriterStatus.DECLINED
PREFERRED_WRITER_STATUS_EXPIRED = PreferredWriterStatus.EXPIRED
PREFERRED_WRITER_STATUS_FALLBACK_TO_POOL = (
    PreferredWriterStatus.FALLBACK_TO_POOL
)

# Interest Types
ORDER_INTEREST_TYPE_BID = OrderInterestType.BID
ORDER_INTEREST_TYPE_SHOW_INTEREST = OrderInterestType.SHOW_INTEREST
ORDER_INTEREST_TYPE_REQUEST_TAKE = OrderInterestType.REQUEST_TAKE
ORDER_INTEREST_TYPE_PREFERRED_WRITER_INVITATION = (
    OrderInterestType.PREFERRED_WRITER_INVITATION
)

# Interest Statuses
ORDER_INTEREST_STATUS_PENDING = OrderInterestStatus.PENDING
ORDER_INTEREST_STATUS_ACCEPTED = OrderInterestStatus.ACCEPTED
ORDER_INTEREST_STATUS_REJECTED = OrderInterestStatus.REJECTED
ORDER_INTEREST_STATUS_WITHDRAWN = OrderInterestStatus.WITHDRAWN
ORDER_INTEREST_STATUS_DECLINED = OrderInterestStatus.DECLINED
ORDER_INTEREST_STATUS_EXPIRED = OrderInterestStatus.EXPIRED
ORDER_INTEREST_STATUS_SUPERSEDED = OrderInterestStatus.SUPERSEDED

# Assignment Source
ORDER_ASSIGNMENT_SOURCE_STAFF_ASSIGNMENT = (
    OrderAssignmentSource.STAFF_ASSIGNMENT
)
ORDER_ASSIGNMENT_SOURCE_AUTO_ASSIGNMENT = (
    OrderAssignmentSource.AUTO_ASSIGNMENT
)
ORDER_ASSIGNMENT_SOURCE_SELF_TAKE = OrderAssignmentSource.SELF_TAKE
ORDER_ASSIGNMENT_SOURCE_ACCEPTED_INTEREST = (
    OrderAssignmentSource.ACCEPTED_INTEREST
)
ORDER_ASSIGNMENT_SOURCE_PREFERRED_WRITER_ACCEPTANCE = (
    OrderAssignmentSource.PREFERRED_WRITER_ACCEPTANCE
)
ORDER_ASSIGNMENT_SOURCE_REASSIGNMENT = (
    OrderAssignmentSource.REASSIGNMENT
)

# Assignment Statuses
ORDER_ASSIGNMENT_STATUS_ACTIVE = OrderAssignmentStatus.ACTIVE
ORDER_ASSIGNMENT_STATUS_RELEASED = OrderAssignmentStatus.RELEASED
ORDER_ASSIGNMENT_STATUS_REASSIGNED = OrderAssignmentStatus.REASSIGNED
ORDER_ASSIGNMENT_STATUS_DROPPED = OrderAssignmentStatus.DROPPED
ORDER_ASSIGNMENT_STATUS_CANCELLED = OrderAssignmentStatus.CANCELLED

# Hold Statuses
ORDER_HOLD_STATUS_PENDING = OrderHoldStatus.PENDING
ORDER_HOLD_STATUS_ACTIVE = OrderHoldStatus.ACTIVE
ORDER_HOLD_STATUS_RELEASED = OrderHoldStatus.RELEASED
ORDER_HOLD_STATUS_CANCELLED = OrderHoldStatus.CANCELLED

# Timeline Events
ORDER_TIMELINE_EVENT_CREATED = OrderTimelineEventType.CREATED
ORDER_TIMELINE_EVENT_PAID = OrderTimelineEventType.PAID
ORDER_TIMELINE_EVENT_POOL_OPENED = OrderTimelineEventType.POOL_OPENED
ORDER_TIMELINE_EVENT_PREFERRED_WRITER_INVITED = (
    OrderTimelineEventType.PREFERRED_WRITER_INVITED
)
ORDER_TIMELINE_EVENT_PREFERRED_WRITER_ACCEPTED = (
    OrderTimelineEventType.PREFERRED_WRITER_ACCEPTED
)
ORDER_TIMELINE_EVENT_PREFERRED_WRITER_DECLINED = (
    OrderTimelineEventType.PREFERRED_WRITER_DECLINED
)
ORDER_TIMELINE_EVENT_PREFERRED_WRITER_EXPIRED = (
    OrderTimelineEventType.PREFERRED_WRITER_EXPIRED
)
ORDER_TIMELINE_EVENT_INTEREST_CREATED = (
    OrderTimelineEventType.INTEREST_CREATED
)
ORDER_TIMELINE_EVENT_INTEREST_WITHDRAWN = (
    OrderTimelineEventType.INTEREST_WITHDRAWN
)
ORDER_TIMELINE_EVENT_ASSIGNED = OrderTimelineEventType.ASSIGNED
ORDER_TIMELINE_EVENT_REASSIGNED = OrderTimelineEventType.REASSIGNED
ORDER_TIMELINE_EVENT_RETURNED_TO_POOL = (
    OrderTimelineEventType.RETURNED_TO_POOL
)
ORDER_TIMELINE_EVENT_REASSIGNMENT_REQUESTED = (
    OrderTimelineEventType.REASSIGNMENT_REQUESTED
)
ORDER_TIMELINE_EVENT_REASSIGNMENT_REJECTED = (
    OrderTimelineEventType.REASSIGNMENT_REJECTED
)
ORDER_TIMELINE_EVENT_REASSIGNMENT_CANCELLED = (
    OrderTimelineEventType.REASSIGNMENT_CANCELLED
)
ORDER_TIMELINE_EVENT_HOLD_REQUESTED = (
    OrderTimelineEventType.HOLD_REQUESTED
)
ORDER_TIMELINE_EVENT_HOLD_ACTIVATED = (
    OrderTimelineEventType.HOLD_ACTIVATED
)
ORDER_TIMELINE_EVENT_HOLD_RELEASED = (
    OrderTimelineEventType.HOLD_RELEASED
)
ORDER_TIMELINE_EVENT_WRITER_ACKNOWLEDGED = (
    OrderTimelineEventType.WRITER_ACKNOWLEDGED
)
ORDER_TIMELINE_EVENT_SUBMITTED = OrderTimelineEventType.SUBMITTED
ORDER_TIMELINE_EVENT_APPROVED = OrderTimelineEventType.APPROVED
ORDER_TIMELINE_EVENT_COMPLETED = OrderTimelineEventType.COMPLETED
ORDER_TIMELINE_EVENT_REOPENED = OrderTimelineEventType.REOPENED
ORDER_TIMELINE_EVENT_DISPUTED = OrderTimelineEventType.DISPUTED
ORDER_TIMELINE_EVENT_CANCELLED = OrderTimelineEventType.CANCELLED
ORDER_TIMELINE_EVENT_ARCHIVED = OrderTimelineEventType.ARCHIVED
ORDER_TIMELINE_EVENT_SOFT_DELETED = (
    OrderTimelineEventType.SOFT_DELETED
)
ORDER_TIMELINE_EVENT_RESTORED = OrderTimelineEventType.RESTORED
ORDER_TIMELINE_EVENT_ADJUSTMENT_CREATED = (
    OrderTimelineEventType.ADJUSTMENT_CREATED
)
ORDER_TIMELINE_EVENT_ADJUSTMENT_FUNDED = (
    OrderTimelineEventType.ADJUSTMENT_FUNDED
)

# Revision Statuses
ORDER_REVISION_STATUS_PENDING = OrderRevisionStatus.PENDING

# Revision Events
ORDER_REVISION_EVENT_CREATED = OrderRevisionEventType.CREATED
ORDER_REVISION_EVENT_REJECTED = OrderRevisionEventType.REJECTED

# Adjustment Types
ORDER_ADJUSTMENT_TYPE_PAGE_INCREASE = OrderAdjustmentType.PAGE_INCREASE
ORDER_ADJUSTMENT_TYPE_SLIDE_INCREASE = OrderAdjustmentType.SLIDE_INCREASE
ORDER_ADJUSTMENT_TYPE_DEADLINE_DECREASE = (
    OrderAdjustmentType.DEADLINE_DECREASE
)
ORDER_ADJUSTMENT_TYPE_DESIGN_CONCEPT_INCREASE = (
    OrderAdjustmentType.DESIGN_CONCEPT_INCREASE
)
ORDER_ADJUSTMENT_TYPE_DIAGRAM_INCREASE = (
    OrderAdjustmentType.DIAGRAM_INCREASE
)
ORDER_ADJUSTMENT_TYPE_EXTRA_SERVICE = OrderAdjustmentType.EXTRA_SERVICE
ORDER_ADJUSTMENT_TYPE_PAID_REVISION = OrderAdjustmentType.PAID_REVISION
ORDER_ADJUSTMENT_TYPE_SCOPE_EXPANSION = OrderAdjustmentType.SCOPE_EXPANSION

ORDER_ADJUSTMENT_TYPE_OTHER = OrderAdjustmentType.OTHER

# Adjustment Statuses
ORDER_ADJUSTMENT_STATUS_PENDING_CLIENT_RESPONSE = (
    OrderAdjustmentStatus.PENDING_CLIENT_RESPONSE
)
ORDER_ADJUSTMENT_STATUS_CLIENT_COUNTERED = (
    OrderAdjustmentStatus.CLIENT_COUNTERED
)
ORDER_ADJUSTMENT_STATUS_ACCEPTED = OrderAdjustmentStatus.ACCEPTED
ORDER_ADJUSTMENT_STATUS_DECLINED = OrderAdjustmentStatus.DECLINED
ORDER_ADJUSTMENT_STATUS_FUNDING_PENDING = (
    OrderAdjustmentStatus.FUNDING_PENDING
)
ORDER_ADJUSTMENT_STATUS_FUNDED = OrderAdjustmentStatus.FUNDED
ORDER_ADJUSTMENT_STATUS_COUNTER_FUNDED_FINAL = (
    OrderAdjustmentStatus.COUNTER_FUNDED_FINAL
)
ORDER_ADJUSTMENT_STATUS_APPROVED_BY_STAFF = (
    OrderAdjustmentStatus.APPROVED_BY_STAFF
)
ORDER_ADJUSTMENT_STATUS_REJECTED_BY_CLIENT = (
    OrderAdjustmentStatus.REJECTED_BY_CLIENT
)
ORDER_ADJUSTMENT_STATUS_REJECTED_BY_STAFF = (
    OrderAdjustmentStatus.REJECTED_BY_STAFF
)
ORDER_ADJUSTMENT_STATUS_CANCELLED = OrderAdjustmentStatus.CANCELLED
ORDER_ADJUSTMENT_STATUS_EXPIRED = OrderAdjustmentStatus.EXPIRED
ORDER_ADJUSTMENT_STATUS_REVERSED = OrderAdjustmentStatus.REVERSED

# Adjustment Proposal Types
ORDER_ADJUSTMENT_PROPOSAL_TYPE_SYSTEM_QUOTE = (
    OrderAdjustmentProposalType.SYSTEM_QUOTE
)
ORDER_ADJUSTMENT_PROPOSAL_TYPE_CLIENT_COUNTER = (
    OrderAdjustmentProposalType.CLIENT_COUNTER
)
ORDER_ADJUSTMENT_PROPOSAL_TYPE_STAFF_OVERRIDE = (
    OrderAdjustmentProposalType.STAFF_OVERRIDE
)
ORDER_ADJUSTMENT_PROPOSAL_TYPE_FINAL_AGREEMENT = (
    OrderAdjustmentProposalType.FINAL_AGREEMENT
)

# Order Scope Unit Types
ORDER_SCOPE_UNIT_TYPE_PAGE = OrderScopeUnitType.PAGE
ORDER_SCOPE_UNIT_TYPE_SLIDE = OrderScopeUnitType.SLIDE
ORDER_SCOPE_UNIT_TYPE_DEADLINE = OrderScopeUnitType.DEADLINE
ORDER_SCOPE_UNIT_TYPE_DIAGRAM = OrderScopeUnitType.DIAGRAM
ORDER_SCOPE_UNIT_TYPE_DESIGN_CONCEPT = (
    OrderScopeUnitType.DESIGN_CONCEPT
)
ORDER_SCOPE_UNIT_SECTION = OrderScopeUnitType.SECTION
ORDER_SCOPE_UNIT_TYPE_OTHER = OrderScopeUnitType.OTHER

# Order Adjustment Kinds
ORDER_ADJUSTMENT_KIND_SCOPE_INCREMENT = "scope_increment"
ORDER_ADJUSTMENT_KIND_EXTRA_SERVICE = "extra_service"

ORDER_ITEM_KIND_SCOPE_UNIT = "scope_unit"
ORDER_ITEM_KIND_EXTRA_SERVICE = "extra_service"



# Adjustment Proposal Roles
ORDER_ADJUSTMENT_PROPOSAL_ROLE_SYSTEM = (
    OrderAdjustmentProposalRole.SYSTEM
)
ORDER_ADJUSTMENT_PROPOSAL_ROLE_CLIENT = (
    OrderAdjustmentProposalRole.CLIENT
)
ORDER_ADJUSTMENT_PROPOSAL_ROLE_WRITER = (
    OrderAdjustmentProposalRole.WRITER
)
ORDER_ADJUSTMENT_PROPOSAL_ROLE_STAFF = (
    OrderAdjustmentProposalRole.STAFF
)

# Adjustment Events
ORDER_ADJUSTMENT_EVENT_REQUEST_CREATED = (
    OrderAdjustmentEventType.REQUEST_CREATED
)
ORDER_ADJUSTMENT_EVENT_PROPOSAL_CREATED = (
    OrderAdjustmentEventType.PROPOSAL_CREATED
)
ORDER_ADJUSTMENT_EVENT_CLIENT_NOTIFIED = (
    OrderAdjustmentEventType.CLIENT_NOTIFIED
)
ORDER_ADJUSTMENT_EVENT_CLIENT_COUNTERED = (
    OrderAdjustmentEventType.CLIENT_COUNTERED
)
ORDER_ADJUSTMENT_EVENT_ACCEPTED = (
    OrderAdjustmentEventType.ACCEPTED
)
ORDER_ADJUSTMENT_EVENT_DECLINED = (
    OrderAdjustmentEventType.DECLINED
)
ORDER_ADJUSTMENT_EVENT_BILLING_CREATED = (
    OrderAdjustmentEventType.BILLING_CREATED
)
ORDER_ADJUSTMENT_EVENT_PAYMENT_INTENT_CREATED = (
    OrderAdjustmentEventType.PAYMENT_INTENT_CREATED
)
ORDER_ADJUSTMENT_EVENT_PAYMENT_PARTIALLY_APPLIED = (
    OrderAdjustmentEventType.PAYMENT_PARTIALLY_APPLIED
)
ORDER_ADJUSTMENT_EVENT_PAYMENT_FULLY_APPLIED = (
    OrderAdjustmentEventType.PAYMENT_FULLY_APPLIED
)
ORDER_ADJUSTMENT_EVENT_FUNDED = OrderAdjustmentEventType.FUNDED
ORDER_ADJUSTMENT_EVENT_CANCELLED = (
    OrderAdjustmentEventType.CANCELLED
)
ORDER_ADJUSTMENT_EVENT_EXPIRED = OrderAdjustmentEventType.EXPIRED
ORDER_ADJUSTMENT_EVENT_REVERSED = OrderAdjustmentEventType.REVERSED
ORDER_ADJUSTMENT_EVENT_COMPENSATION_CREATED = (
    OrderAdjustmentEventType.COMPENSATION_CREATED
)
ORDER_ADJUSTMENT_EVENT_COMPENSATION_REVERSED = (
    OrderAdjustmentEventType.COMPENSATION_REVERSED
)

# Adjustment Funding Statuses
ORDER_ADJUSTMENT_FUNDING_STATUS_NOT_STARTED = (
    OrderAdjustmentFundingStatus.NOT_STARTED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_PAYMENT_REQUEST_CREATED = (
    OrderAdjustmentFundingStatus.PAYMENT_REQUEST_CREATED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_PAYMENT_INTENT_CREATED = (
    OrderAdjustmentFundingStatus.PAYMENT_INTENT_CREATED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_PARTIALLY_FUNDED = (
    OrderAdjustmentFundingStatus.PARTIALLY_FUNDED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_FUNDED = (
    OrderAdjustmentFundingStatus.FUNDED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_FAILED = (
    OrderAdjustmentFundingStatus.FAILED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_CANCELLED = (
    OrderAdjustmentFundingStatus.CANCELLED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_EXPIRED = (
    OrderAdjustmentFundingStatus.EXPIRED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_REFUNDED = (
    OrderAdjustmentFundingStatus.REFUNDED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_WAIVED = (
    OrderAdjustmentFundingStatus.WAIVED
)
ORDER_ADJUSTMENT_FUNDING_STATUS_REVERSED = (
    OrderAdjustmentFundingStatus.REVERSED
)

# Compensation Adjustment Statuses
ORDER_COMPENSATION_ADJUSTMENT_STATUS_PENDING = (
    OrderCompensationAdjustmentStatus.PENDING
)
ORDER_COMPENSATION_ADJUSTMENT_STATUS_ACTIVE = (
    OrderCompensationAdjustmentStatus.ACTIVE
)
ORDER_COMPENSATION_ADJUSTMENT_STATUS_RECOGNIZED = (
    OrderCompensationAdjustmentStatus.RECOGNIZED
)
ORDER_COMPENSATION_ADJUSTMENT_STATUS_REVERSED = (
    OrderCompensationAdjustmentStatus.REVERSED
)
ORDER_COMPENSATION_ADJUSTMENT_STATUS_CANCELLED = (
    OrderCompensationAdjustmentStatus.CANCELLED
)

# Compensation Adjustment Types
ORDER_COMPENSATION_ADJUSTMENT_TYPE_PAGE_DELTA = (
    OrderCompensationAdjustmentType.PAGE_DELTA
)
ORDER_COMPENSATION_ADJUSTMENT_TYPE_SLIDE_DELTA = (
    OrderCompensationAdjustmentType.SLIDE_DELTA
)
ORDER_COMPENSATION_ADJUSTMENT_TYPE_EXTRA_SERVICE = (
    OrderCompensationAdjustmentType.EXTRA_SERVICE
)
ORDER_COMPENSATION_ADJUSTMENT_TYPE_DEADLINE_DELTA = (
    OrderCompensationAdjustmentType.DEADLINE_DELTA
)
ORDER_COMPENSATION_ADJUSTMENT_TYPE_PAID_REVISION = (
    OrderCompensationAdjustmentType.PAID_REVISION
)
ORDER_COMPENSATION_ADJUSTMENT_TYPE_OTHER = (
    OrderCompensationAdjustmentType.OTHER
)

# Post Counter Escalation
ORDER_POST_COUNTER_ESCALATION_REASON_SCOPE_UNACCEPTABLE = (
    OrderPostCounterEscalationReason.SCOPE_UNACCEPTABLE
)

# Order Payment Statuses
ORDER_PAYMENT_STATUS_UNPAID = OrderPaymentStatus.UNPAID
ORDER_PAYMENT_STATUS_PARTIALLY_PAID = (
    OrderPaymentStatus.PARTIALLY_PAID
)
ORDER_PAYMENT_STATUS_FULLY_PAID = OrderPaymentStatus.FULLY_PAID
ORDER_PAYMENT_STATUS_REFUNDED = OrderPaymentStatus.REFUNDED

FREE_REVISION_WINDOW_DAYS = 14
DEFAULT_PAID_REVISION_PERCENT = Decimal("0.50")
MIN_PAID_REVISION_PERCENT = Decimal("0.40")
MAX_PAID_REVISION_PERCENT = Decimal("0.50")
DEFAULT_PREFERRED_WRITER_RESPONSE_HOURS = 24

ORDER_REFERENCE_PREFIX = "ord"
ADJUSTMENT_REFERENCE_PREFIX = "adj"

ORDER_POOL_VISIBLE_STATUSES = frozenset({
    ORDER_STATUS_READY_FOR_STAFFING,
})

ORDER_TERMINAL_STATUSES = frozenset({
    ORDER_STATUS_COMPLETED,
    ORDER_STATUS_CANCELLED,
    ORDER_STATUS_ARCHIVED,
})

ORDER_INTEREST_TERMINAL_STATUSES = frozenset({
    ORDER_INTEREST_STATUS_ACCEPTED,
    ORDER_INTEREST_STATUS_REJECTED,
    ORDER_INTEREST_STATUS_WITHDRAWN,
    ORDER_INTEREST_STATUS_DECLINED,
    ORDER_INTEREST_STATUS_EXPIRED,
    ORDER_INTEREST_STATUS_SUPERSEDED,
})

ORDER_ASSIGNMENT_TERMINAL_STATUSES = frozenset({
    ORDER_ASSIGNMENT_STATUS_RELEASED,
    ORDER_ASSIGNMENT_STATUS_REASSIGNED,
    ORDER_ASSIGNMENT_STATUS_DROPPED,
    ORDER_ASSIGNMENT_STATUS_CANCELLED,
})

ORDER_HOLD_TERMINAL_STATUSES = frozenset({
    ORDER_HOLD_STATUS_RELEASED,
    ORDER_HOLD_STATUS_CANCELLED,
})

ADJUSTMENT_TERMINAL_STATUSES = frozenset({
    ORDER_ADJUSTMENT_STATUS_DECLINED,
    ORDER_ADJUSTMENT_STATUS_CANCELLED,
    ORDER_ADJUSTMENT_STATUS_FUNDED,
    ORDER_ADJUSTMENT_STATUS_COUNTER_FUNDED_FINAL,
    ORDER_ADJUSTMENT_STATUS_EXPIRED,
    ORDER_ADJUSTMENT_STATUS_REVERSED,
    ORDER_ADJUSTMENT_STATUS_REJECTED_BY_CLIENT,
    ORDER_ADJUSTMENT_STATUS_REJECTED_BY_STAFF,
    ORDER_ADJUSTMENT_STATUS_APPROVED_BY_STAFF,
})

ORDER_EXTRA_SERVICE_PROGRESSIVE_DELIVERY = "progressive_delivery"