# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_blog', '0002_blogpostpage_funnel_fks'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('journal_article', 'Peer-reviewed journal article'), ('book', 'Book'), ('book_chapter', 'Book chapter'), ('website', 'Website / web article'), ('government_publication', 'Government publication'), ('professional_organization', 'Professional organization document'), ('clinical_guideline', 'Clinical practice guideline'), ('news_article', 'News article'), ('report', 'Industry / research report'), ('thesis', 'Thesis / dissertation'), ('conference_paper', 'Conference paper'), ('other', 'Other')], default='website', max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(blank=True, default=list, help_text='List of author dicts: [{"family": "Smith", "given": "J.", "middle": "A."}]')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=255)),
                ('journal_volume', models.CharField(blank=True, max_length=20)),
                ('journal_issue', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, help_text="e.g., '234-251'", max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publisher_location', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, db_index=True, help_text='Digital Object Identifier (the gold standard)', max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('pmid', models.CharField(blank=True, help_text='PubMed ID — especially relevant for nursing content', max_length=20)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('url_archived', models.URLField(blank=True, help_text='Wayback Machine snapshot URL — auto-captured on add', max_length=500)),
                ('is_url_dead', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, help_text='Last time the URL was verified as reachable', null=True)),
                ('is_open_access', models.BooleanField(default=False)),
                ('is_peer_reviewed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Reviewed and confirmed as credible by an editor')),
                ('quality_tier', models.CharField(blank=True, choices=[('tier_1', 'Peer-reviewed primary research'), ('tier_2', 'Clinical guideline / professional org'), ('tier_3', 'Authoritative website (.gov, .edu, established org)'), ('tier_4', 'Reputable secondary source'), ('tier_5', 'Other / general')], max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Cached count of blog posts citing this reference')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal-only notes — never displayed publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_references', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='wagtailcore.site')),
                ('tags', models.ManyToManyField(blank=True, related_name='references', to='cms_references.referencetag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Order in the references list (1, 2, 3...)')),
                ('page', models.CharField(blank=True, help_text="e.g., 'pp. 23-25'", max_length=50)),
                ('editor_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='cms_blog.blogpostpage')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='cms_references.reference')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('blog_post', 'reference')},
            },
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['site', 'reference_type'], name='cms_referen_site_id_d424e0_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['doi'], name='cms_referen_doi_8a6a59_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['pmid'], name='cms_referen_pmid_5e6afb_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['site', 'is_verified'], name='cms_referen_site_id_95d070_idx'),
        ),
    ]
