# Generated by Django 5.2.2 on 2026-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='effect',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('require_approval', 'Require Approval')], max_length=30),
        ),
    ]
