# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_configs', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevel',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='websites.website'),
        ),
        migrations.AddField(
            model_name='englishtype',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_type', to='websites.website'),
        ),
        migrations.AddField(
            model_name='formattingandcitationstyle',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatting', to='websites.website'),
        ),
        migrations.AddField(
            model_name='papertype',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_type', to='websites.website'),
        ),
        migrations.AddField(
            model_name='revisionpolicyconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_policies', to='websites.website'),
        ),
        migrations.AddField(
            model_name='subject',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='websites.website'),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_work', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerdeadlineconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_deadline_threshold', to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='academiclevel',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='englishtype',
            unique_together={('website', 'name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='formattingandcitationstyle',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='papertype',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='revisionpolicyconfig',
            unique_together={('website', 'active')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='typeofwork',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='writerdeadlineconfig',
            unique_together={('website', 'writer_deadline_percentage')},
        ),
    ]
