# Generated by Django 5.0.14 on 2025-10-29 09:36

import blog_pages_management.models
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='author_images/')),
                ('designation', models.CharField(blank=True, help_text='e.g., Senior Writer', max_length=255, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_fake', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('instagram_profile', models.URLField(blank=True, null=True)),
                ('pinterest_profile', models.URLField(blank=True, null=True)),
                ('medium_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('youtube_channel', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('specialties', models.CharField(blank=True, max_length=255, null=True)),
                ('awards', models.TextField(blank=True, help_text='Awards and recognitions', null=True)),
                ('notable_works', models.TextField(blank=True, help_text='Notable works or publications', null=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_a', models.CharField(max_length=255)),
                ('headline_b', models.CharField(max_length=255)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='blog_images/ab_testing/')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='blog_images/ab_testing/')),
                ('click_count_a', models.PositiveIntegerField(default=0)),
                ('click_count_b', models.PositiveIntegerField(default=0)),
                ('conversion_count_a', models.PositiveIntegerField(default=0)),
                ('conversion_count_b', models.PositiveIntegerField(default=0)),
                ('winning_version', models.CharField(choices=[('A', 'Version A'), ('B', 'Version B'), ('Pending', 'Pending')], default='Pending', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='BlogActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('restored', 'Restored'), ('deleted', 'Permanently Deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed', models.BooleanField(default=False)),
                ('clicked_order_page', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDarkModeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_mode_image', models.ImageField(upload_to='blog_images/light_mode/')),
                ('dark_mode_image', models.ImageField(upload_to='blog_images/dark_mode/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blog_media/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('gif', 'GIF')], max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for SEO', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, help_text='Caption for the media file', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO-friendly title for search engines', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO-friendly description', null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Custom blog URL (use hyphens)', unique=True)),
                ('content', models.Field()),
                ('toc', models.JSONField(blank=True, default=dict)),
                ('is_editorial', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, help_text='Primary image (used in Open Graph and previews)', null=True, upload_to='blog_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_engagement', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('freshness_score', models.IntegerField(default=100, help_text='Content freshness score (0-100)')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=300)),
                ('canonical_url', models.URLField(blank=True, help_text='Original source URL if republished', null=True)),
                ('click_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('daily_clicks', models.PositiveIntegerField(default=0)),
                ('weekly_clicks', models.PositiveIntegerField(default=0)),
                ('monthly_clicks', models.PositiveIntegerField(default=0)),
                ('semi_annual_clicks', models.PositiveIntegerField(default=0)),
                ('annual_clicks', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlogResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('last_shared_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='If True, redirect from old slug is active')),
                ('redirected_count', models.PositiveIntegerField(default=0, help_text='Number of times this old slug was used for redirection')),
                ('last_redirected_at', models.DateTimeField(blank=True, help_text='Last time this slug was used for redirection', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('self_hosted', 'Self-Hosted'), ('other', 'Other')], max_length=15)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail for self-hosted videos', null=True, upload_to='video_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_a', models.CharField(help_text='A/B Test: Subject A', max_length=255)),
                ('subject_b', models.CharField(blank=True, help_text='A/B Test: Subject B', max_length=255, null=True)),
                ('content_a', models.TextField(help_text='A/B Test: Content A')),
                ('content_b', models.TextField(blank=True, help_text='A/B Test: Content B', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('scheduled_send_date', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('A', 'Version A'), ('B', 'Version B')], max_length=1)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(db_index=True, default=blog_pages_management.models.generate_tracking_id, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('share_url_format', models.CharField(help_text='Use {url} as placeholder for the article URL.', max_length=255)),
                ('logo_url', models.URLField(blank=True, help_text="URL to the platform's logo (CDN or self-hosted).", max_length=500, null=True)),
                ('is_disabled_by_owner', models.BooleanField(default=False, help_text='If True, this platform is disabled for this website.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
