# Generated by Django 5.0.14 on 2025-12-03 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded media file (image, video, document, etc.)', null=True, upload_to='media_assets/')),
                ('embed_provider', models.CharField(blank=True, help_text='Provider name for embedded media, e.g. youtube, vimeo', max_length=50)),
                ('embed_id', models.CharField(blank=True, help_text='Provider-specific ID or URL for embedded media', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text / accessibility description (for images and thumbnails).', max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Optional list of tags/keywords for searching.')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag; inactive assets are hidden from pickers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['website', 'type'], name='media_manag_website_d292fa_idx'), models.Index(fields=['website', 'is_active', 'created_at'], name='media_manag_website_1e89e7_idx')],
            },
        ),
    ]
