# Generated by Django 5.0.14 on 2025-12-04 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media_management', '0001_initial'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_object_id', models.PositiveIntegerField(help_text='ID of the media object')),
                ('entity_object_id', models.PositiveIntegerField(help_text='ID of the content using the media')),
                ('context', models.CharField(help_text="How the media is used (e.g., 'featured_image', 'inline', 'cta', 'og_image')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_content_type', models.ForeignKey(help_text='Content type using the media (BlogPost, ServicePage, CTABlock, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='media_usages', to='contenttypes.contenttype')),
                ('media_content_type', models.ForeignKey(help_text='Content type of the media (MediaAsset, BlogMediaFile, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('website', models.ForeignKey(help_text='Website this usage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media_usages', to='websites.website')),
            ],
            options={
                'verbose_name': 'Media Usage',
                'verbose_name_plural': 'Media Usages',
                'indexes': [models.Index(fields=['media_content_type', 'media_object_id'], name='media_manag_media_c_cec36b_idx'), models.Index(fields=['entity_content_type', 'entity_object_id'], name='media_manag_entity__9db9a7_idx'), models.Index(fields=['website', 'context'], name='media_manag_website_159871_idx')],
                'unique_together': {('media_content_type', 'media_object_id', 'entity_content_type', 'entity_object_id', 'context')},
            },
        ),
    ]
