# Generated by Django 5.2.2 on 2026-06-03 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0003_add_badge_and_writerbadge'),
        ('writer_vetting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Writer Test Answer',
            },
        ),
        migrations.CreateModel(
            name='WriterTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted — awaiting review'), ('passed', 'Passed'), ('failed', 'Failed'), ('pending_review', 'Pending manual review (essay)')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score 0–100. Null until graded.', max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, help_text='Null until scored.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Writer Test Attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='vettingquiz',
            new_name='writer_vett_website_46c563_idx',
            old_name='vetting_qui_website_idx',
        ),
        migrations.AlterField(
            model_name='vettingchoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vettingquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after answering (optional — good for learning).'),
        ),
        migrations.AlterField(
            model_name='vettingquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vettingquestion',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, help_text='Points awarded for a correct answer (MCQ/true-false).'),
        ),
        migrations.AlterField(
            model_name='vettingquestion',
            name='text',
            field=models.TextField(help_text='Question text shown to the writer.'),
        ),
        migrations.AlterField(
            model_name='vettingquiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vettingquiz',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions shown to the writer before they start.'),
        ),
        migrations.AlterField(
            model_name='vettingquiz',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='0 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='vettingquiz',
            name='pass_score',
            field=models.PositiveSmallIntegerField(default=75, help_text='Minimum percentage score to pass (MCQ/true-false quizzes only).'),
        ),
        migrations.AlterField(
            model_name='vettingquiz',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='0 = no time limit.'),
        ),
        migrations.AddField(
            model_name='writertestanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='writer_vetting.vettingquestion'),
        ),
        migrations.AddField(
            model_name='writertestanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='writer_vetting.vettingchoice'),
        ),
        migrations.AddField(
            model_name='writertestattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='writer_vetting.vettingquiz'),
        ),
        migrations.AddField(
            model_name='writertestattempt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writertestattempt',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writertestanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='writer_vetting.writertestattempt'),
        ),
        migrations.AddIndex(
            model_name='writertestattempt',
            index=models.Index(fields=['writer', 'status'], name='writer_vett_writer__63bc44_idx'),
        ),
        migrations.AddIndex(
            model_name='writertestattempt',
            index=models.Index(fields=['quiz', 'status'], name='writer_vett_quiz_id_89c256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writertestattempt',
            unique_together={('quiz', 'writer', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='writertestanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
