# Generated by Django 5.2.2 on 2026-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_vetting', '0002_attempt_and_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vettingquiz',
            name='is_required_for_approval',
            field=models.BooleanField(default=False, help_text='Block application approval until the writer has a passing attempt for this quiz.'),
        ),
    ]
