# Generated by Django 5.2.2 on 2026-06-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_vetting', '0003_add_is_required_for_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='writertestanswer',
            name='essay_file_id',
            field=models.CharField(blank=True, default='', help_text='UUID of the uploaded essay file (files_management.ManagedFile).', max_length=36),
        ),
        migrations.AddField(
            model_name='writertestanswer',
            name='essay_file_name',
            field=models.CharField(blank=True, default='', help_text='Original filename stored for display.', max_length=255),
        ),
    ]
