# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_wallet', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwallet',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientwallet',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientwallet',
            name='user',
            field=models.OneToOneField(help_text='The client associated with this wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='client_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientwallet',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website this record is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='websites.website'),
        ),
        migrations.AddField(
            model_name='clientwallettransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientwallettransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientwallettransaction',
            name='wallet',
            field=models.ForeignKey(help_text='The wallet associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='client_wallet.clientwallet'),
        ),
        migrations.AddField(
            model_name='clientwallettransaction',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website this record is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='websites.website'),
        ),
    ]
