# Generated by Django 5.1.5 on 2025-02-04 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('probation', 'Probation'), ('blacklist', 'Blacklist')], max_length=10)),
                ('reason', models.TextField(help_text='Why should this decision be reconsidered?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist_type', models.CharField(choices=[('user', 'User Account'), ('email', 'Email Address'), ('ip', 'IP Address')], default='user', max_length=10)),
                ('email', models.EmailField(blank=True, help_text='Blacklisted email (if applicable).', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Blacklisted IP (if applicable).', null=True)),
                ('reason', models.TextField(help_text='Reason for blacklisting.')),
                ('date_blacklisted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the blacklist is still active.')),
            ],
            options={
                'verbose_name': 'Blacklist Record',
                'verbose_name_plural': 'Blacklist Records',
            },
        ),
        migrations.CreateModel(
            name='Probation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for probation.')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the probation is still active.')),
            ],
            options={
                'verbose_name': 'Probation Record',
                'verbose_name_plural': 'Probation Records',
            },
        ),
        migrations.CreateModel(
            name='SuperadminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_manage', 'User Management'), ('payment', 'Payment Override'), ('report_access', 'Report Access'), ('settings_change', 'Settings Modification'), ('promotion', 'User Promotion/Demotion'), ('suspension', 'User Suspension'), ('probation', 'User Probation'), ('blacklist', 'User Blacklisting'), ('dispute_resolution', 'Dispute Resolution'), ('admin_tracking', 'Admin Tracking'), ('override', 'System Override')], default='override', max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('action_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Superadmin Log',
                'verbose_name_plural': 'Superadmin Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuperadminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=True, help_text='Can add/edit/suspend/delete users.')),
                ('can_manage_payments', models.BooleanField(default=True, help_text='Can oversee all payments.')),
                ('can_view_reports', models.BooleanField(default=True, help_text='Can view financial and operational reports.')),
                ('can_modify_settings', models.BooleanField(default=True, help_text='Can modify system-wide settings.')),
                ('can_promote_users', models.BooleanField(default=True, help_text='Can promote/demote users.')),
                ('can_suspend_users', models.BooleanField(default=True, help_text='Can suspend or reactivate users.')),
                ('can_blacklist_users', models.BooleanField(default=True, help_text='Can blacklist and unblacklist users.')),
                ('can_resolve_disputes', models.BooleanField(default=True, help_text='Can resolve order disputes.')),
                ('can_override_payments', models.BooleanField(default=True, help_text='Can manually adjust payments.')),
                ('can_track_admins', models.BooleanField(default=True, help_text='Can track all admin actions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Superadmin Profile',
                'verbose_name_plural': 'Superadmin Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
