# Generated by Django 5.1.5 on 2025-01-31 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperadminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('superadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperadminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=True, help_text='Can add/edit/suspend/delete users.')),
                ('can_manage_payments', models.BooleanField(default=True, help_text='Can oversee all payments.')),
                ('can_view_reports', models.BooleanField(default=True, help_text='Can view financial and operational reports.')),
                ('can_modify_settings', models.BooleanField(default=True, help_text='Can modify system-wide settings.')),
                ('can_promote_users', models.BooleanField(default=True, help_text='Can promote/demote users.')),
                ('can_suspend_users', models.BooleanField(default=True, help_text='Can suspend or reactivate users.')),
                ('can_blacklist_users', models.BooleanField(default=True, help_text='Can blacklist and unblacklist emails.')),
                ('can_resolve_disputes', models.BooleanField(default=True, help_text='Can resolve order disputes.')),
                ('can_override_payments', models.BooleanField(default=True, help_text='Can manually adjust payments.')),
                ('can_track_admins', models.BooleanField(default=True, help_text='Can track all admin actions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superadmin Profile',
                'verbose_name_plural': 'Superadmin Profiles',
            },
        ),
    ]
