# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_pages_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogabtest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_testing_blogs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogclick',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_clicks', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogconversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogconversion',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_conversions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogdarkmodeimage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dark_mode_images', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogfaq',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_faqs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogmediafile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_media', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(related_name='blog_posts', to='blog_pages_management.authorprofile'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_pages_management.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='Last user who edited this blog', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog_pages_management.blogmediafile'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogfaq',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogdarkmodeimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dark_mode_images', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogconversion',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogclick',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogactionlog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogabtest',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogresource',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogshare',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogshare',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_shares', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogslughistory',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogslughistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who changed the slug', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog_pages_management.blogtag'),
        ),
        migrations.AddField(
            model_name='blogvideo',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog_pages_management.blogpost'),
        ),
        migrations.AddField(
            model_name='blogvideo',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_videos', to='websites.website'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='websites.website'),
        ),
        migrations.AddField(
            model_name='newsletteranalytics',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog_pages_management.newsletter'),
        ),
        migrations.AddField(
            model_name='newsletteranalytics',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_analytics', to='websites.website'),
        ),
        migrations.AddField(
            model_name='newslettercategory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_categories', to='websites.website'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='blog_pages_management.newslettercategory'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog_pages_management.newslettercategory'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='websites.website'),
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_platforms', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blogshare',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_shares', to='blog_pages_management.socialplatform'),
        ),
        migrations.AlterUniqueTogether(
            name='blogclick',
            unique_together={('blog', 'user', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='blogslughistory',
            index=models.Index(fields=['old_slug'], name='blog_pages__old_slu_624be6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogslughistory',
            unique_together={('blog', 'old_slug')},
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_pages__slug_a10169_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['publish_date'], name='blog_pages__publish_30fcf6_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['click_count'], name='blog_pages__click_c_0e48fa_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['conversion_count'], name='blog_pages__convers_555c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published'], name='blog_pages__is_publ_47bb13_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_deleted'], name='blog_pages__is_dele_1321fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialplatform',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='blogshare',
            unique_together={('blog', 'platform')},
        ),
    ]
