# Generated by Django 5.0.14 on 2025-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages_management', '0006_audittrail_authorschema_blogcontentblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='avg_scroll_percent',
            field=models.FloatField(default=0.0, help_text='Average scroll depth percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='dislike_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total dislikes from ContentEvent'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total likes from ContentEvent'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='primary_cta_clicks',
            field=models.PositiveIntegerField(default=0, help_text='Total CTA clicks from ContentEvent'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total views from ContentEvent'),
        ),
    ]
