# Generated by Django 5.0.14 on 2025-12-04 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages_management', '0007_add_content_event_metrics'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO-friendly description (recommended max 160 characters)', null=True, validators=[django.core.validators.MaxLengthValidator(160)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO-friendly title for search engines (recommended max 60 characters)', max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='contenttemplate',
            name='meta_description_template',
            field=models.TextField(blank=True, help_text='Template for meta description (recommended max 160 characters)', validators=[django.core.validators.MaxLengthValidator(160)]),
        ),
        migrations.AlterField(
            model_name='contenttemplate',
            name='meta_title_template',
            field=models.CharField(blank=True, help_text='Template for meta title (recommended max 60 characters)', max_length=255, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.CreateModel(
            name='WebsiteContentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('published_posts', models.PositiveIntegerField(default=0)),
                ('draft_posts', models.PositiveIntegerField(default=0)),
                ('category_metrics', models.JSONField(blank=True, default=dict)),
                ('tag_metrics', models.JSONField(blank=True, default=dict)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_content_metrics', to='websites.website')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['website', 'calculated_at'], name='blog_pages__website_43bc74_idx')],
            },
        ),
    ]
