# Generated by Django 5.0.14 on 2025-12-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages_management', '0010_add_publishing_targets_and_reminders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collaborativechange',
            new_name='blog_pages__session_12fec6_idx',
            old_name='blog_pages__collab_change_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborativechange',
            new_name='blog_pages__applied_702727_idx',
            old_name='blog_pages__collab_change_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborativeeditor',
            new_name='blog_pages__session_1fdb7a_idx',
            old_name='blog_pages__collab_editor_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborativepresence',
            new_name='blog_pages__session_c0e2f2_idx',
            old_name='blog_pages__collab_presence_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborativepresence',
            new_name='blog_pages__last_he_3c9fb5_idx',
            old_name='blog_pages__collab_heartbeat_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborativesession',
            new_name='blog_pages__content_8f4e1f_idx',
            old_name='blog_pages__collab_content_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborativesession',
            new_name='blog_pages__session_dfb907_idx',
            old_name='blog_pages__collab_session_idx',
        ),
        # Conditionally rename index if it exists
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS blog_pages__blog_post_ack_idx RENAME TO blog_pages__blog_po_b9cee6_idx;",
            reverse_sql="ALTER INDEX IF EXISTS blog_pages__blog_po_b9cee6_idx RENAME TO blog_pages__blog_post_ack_idx;",
        ),
        migrations.RenameIndex(
            model_name='editoraction',
            new_name='blog_pages__session_b050c0_idx',
            old_name='blog_pages__session_time_idx',
        ),
        migrations.RenameIndex(
            model_name='editoraction',
            new_name='blog_pages__action__ebb482_idx',
            old_name='blog_pages__action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='editorproductivitymetrics',
            new_name='blog_pages__user_id_bcd46b_idx',
            old_name='blog_pages__user_period_idx',
        ),
        migrations.RenameIndex(
            model_name='editorproductivitymetrics',
            new_name='blog_pages__website_f5aeb4_idx',
            old_name='blog_pages__website_score_idx',
        ),
        migrations.RenameIndex(
            model_name='editorsession',
            new_name='blog_pages__user_id_def7ad_idx',
            old_name='blog_pages__user_sess_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='editorsession',
            new_name='blog_pages__website_b2d546_idx',
            old_name='blog_pages__website_active_idx',
        ),
        migrations.AlterField(
            model_name='contentfreshnessreminder',
            name='blog_post',
            field=models.ForeignKey(help_text='Blog post that needs updating', on_delete=django.db.models.deletion.CASCADE, related_name='freshness_reminders', to='blog_pages_management.blogpost'),
        ),
        migrations.AlterField(
            model_name='contentfreshnessreminder',
            name='is_acknowledged',
            field=models.BooleanField(default=False, help_text='Admin has acknowledged this reminder'),
        ),
        migrations.AlterField(
            model_name='contentfreshnessreminder',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When the last reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='contentfreshnessreminder',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reminders sent for this content'),
        ),
    ]
