# Generated by Django 5.0.14 on 2025-12-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages_management', '0011_rename_blog_pages__collab_change_sess_idx_blog_pages__session_12fec6_idx_and_more'),
    ]

    operations = [
        # Conditionally rename index if it exists (it may have been renamed in 0011)
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS blog_pages__blog_post_ack_idx RENAME TO blog_pages__blog_po_b9cee6_idx;",
            reverse_sql="ALTER INDEX IF EXISTS blog_pages__blog_po_b9cee6_idx RENAME TO blog_pages__blog_post_ack_idx;",
        ),
    ]
