# Generated by Django 5.0.14 on 2026-01-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages_management', '0014_rename_blog_pages__blog_post_ack_idx_blog_pages__blog_po_b9cee6_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentfreshnessreminder',
            new_name='blog_pages__blog_po_b9cee6_idx',
            old_name='blog_pages__blog_post_ack_idx',
        ),
    ]
