# Generated by Django 5.2.2 on 2026-06-01 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_add_website_branding_and_payment_disclosure'),
        ('writer_management', '0002_writerpenalty_order_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji, icon name, or asset key.', max_length=100)),
                ('type', models.CharField(choices=[('performance', 'Performance'), ('loyalty', 'Loyalty'), ('behavioral', 'Behavioral'), ('special', 'Special')], default='performance', max_length=20)),
                ('auto_award', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('rule_code', models.SlugField(blank=True, help_text='Stable internal slug, e.g. consistent_pro.', max_length=100, null=True)),
                ('rule_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_badges', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website that owns this badge configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='websites.website')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto_awarded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_badges', to='writer_management.badge')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_writer_badges', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='writer_management.writerprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(fields=('website', 'rule_code'), name='unique_badge_rule_code_per_website'),
        ),
        migrations.AddConstraint(
            model_name='writerbadge',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked', False)), fields=('writer', 'badge'), name='unique_active_badge_per_writer'),
        ),
        migrations.AlterUniqueTogether(
            name='writerbadge',
            unique_together={('writer', 'badge', 'issued_at')},
        ),
    ]
