# Generated by Django 5.0.14 on 2025-11-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0002_enhance_writer_level_earnings'),
        ('writer_management', '0004_add_writer_performance_snapshot'),
    ]

    operations = [
    ]
