# Generated by Django 5.2.2 on 2026-06-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_add_earning_mode_to_writer_level_settings'),
        ('writer_management', '0004_writerlevel_settings_max_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerlevelsettings',
            name='earning_mode',
            field=models.CharField(choices=[('fixed_per_page', 'Fixed per page'), ('percentage_of_order_cost', 'Percentage of order cost'), ('percentage_of_order_total', 'Percentage of order total')], default='fixed_per_page', help_text="How the writer's gross earnings are computed for an order. fixed_per_page: base_pay_per_page × pages (recommended). percentage modes use the order's cost/total instead.", max_length=30),
        ),
        migrations.CreateModel(
            name='WriterPayoutPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Wise', 'Wise'), ('Crypto', 'Crypto'), ('Other', 'Other')], default='Bank Transfer', max_length=20)),
                ('payout_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum payout threshold.', max_digits=12)),
                ('account_details', models.JSONField(blank=True, default=dict, help_text='Payment account details (e.g., PayPal email, bank details).')),
                ('verified', models.BooleanField(default=False, help_text='Has the payout method been verified by an admin?')),
                ('allowed_currencies', models.JSONField(blank=True, default=list, help_text='Currencies allowed for this payout method.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_payout_preference', to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='writer_management.writerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_currency', models.CharField(default='KSH', help_text='The currency to convert to (e.g., KSH).', max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Conversion rate from 1 USD to target currency.', max_digits=10)),
                ('effective_date', models.DateField(help_text='The date this rate became effective.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_rates', to='websites.website')),
            ],
            options={
                'verbose_name': 'Currency Conversion Rate',
                'verbose_name_plural': 'Currency Conversion Rates',
                'unique_together': {('website', 'target_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='WriterEarningsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Start date of the earnings period.')),
                ('period_end', models.DateTimeField(help_text='End date of the earnings period.')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings for the period.', max_digits=12)),
                ('orders_completed', models.PositiveIntegerField(default=0, help_text='Number of completed orders during this period.')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_earning_history', to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_history', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Earnings History',
                'verbose_name_plural': 'Writer Earnings Histories',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['writer', 'period_end'], name='writer_mana_writer__1a5e5e_idx'), models.Index(fields=['website', 'period_end'], name='writer_mana_website_5963a4_idx'), models.Index(fields=['writer', 'website', 'period_end'], name='writer_mana_writer__f81ac5_idx'), models.Index(fields=['period_start', 'period_end'], name='writer_mana_period__9947ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='WriterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount.', max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonuses received.', max_digits=12)),
                ('fines', models.DecimalField(decimal_places=2, default=0.0, help_text='Fines deducted.', max_digits=12)),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, help_text='Tips received.', max_digits=12)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Amount paid in the writer's local currency (e.g., KSH).", max_digits=12, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, help_text='USD to KSH rate used at time of payment.', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency in which the writer was paid (e.g., USD, KSH).', max_length=5)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date of payment.')),
                ('description', models.TextField(blank=True, help_text='Payment description.', null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_compensation', to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_management_payments', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Compensation',
                'verbose_name_plural': 'Writer Compensation',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['writer', 'payment_date'], name='writer_mana_writer__5336a0_idx'), models.Index(fields=['website', 'payment_date'], name='writer_mana_website_8ed9ad_idx'), models.Index(fields=['writer', 'website', 'payment_date'], name='writer_mana_writer__886da2_idx')],
            },
        ),
    ]
