# Generated by Django 5.2.2 on 2026-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0005_add_earning_mode_to_writer_level_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterDeadlineExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_deadline', models.DateTimeField(help_text='Current order deadline.')),
                ('requested_deadline', models.DateTimeField(help_text='New requested deadline.')),
                ('reason', models.TextField(help_text='Reason for requesting a deadline extension.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterDemotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting writer demotion.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterEarningsReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting earnings review.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderHoldRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting hold.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderReopenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for reopening the order.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the request was made.')),
                ('reason', models.TextField(help_text="Writer's reason for requesting this order (e.g., expertise, availability, interest).")),
                ('approved', models.BooleanField(default=False, help_text='Has the request been approved?')),
            ],
            options={
                'verbose_name': 'Writer Order Request',
                'verbose_name_plural': 'Writer Order Requests',
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderRequestAdminReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True, help_text='When the review was made.')),
                ('comments', models.TextField(blank=True, help_text='Admin comments on the request.', null=True)),
            ],
            options={
                'verbose_name': 'Writer Order Request Admin Review',
                'verbose_name_plural': 'Writer Order Request Admin Reviews',
                'ordering': ['-review_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True, help_text='When the review was made.')),
                ('comments', models.TextField(blank=True, help_text='Admin comments on the request.', null=True)),
            ],
            options={
                'verbose_name': 'Writer Order Request Review',
                'verbose_name_plural': 'Writer Order Request Reviews',
                'ordering': ['-review_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was taken.')),
            ],
            options={
                'verbose_name': 'Writer Order Take',
                'verbose_name_plural': 'Writer Order Takes',
                'ordering': ['-taken_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterOrderTakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True, help_text='When the review was made.')),
                ('comments', models.TextField(blank=True, help_text='Admin comments on the take.', null=True)),
            ],
            options={
                'verbose_name': 'Writer Order Take Review',
                'verbose_name_plural': 'Writer Order Take Reviews',
                'ordering': ['-review_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterReassignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting reassignment.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
