# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_orders_order_status_idx_orders_orde_status_c6dd84_idx_and_more'),
        ('reviews_system', '0003_alter_orderreview_reviewer_and_more'),
        ('websites', '0001_initial'),
        ('writer_management', '0006_add_max_requests_to_writer_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for disputing the order.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes on dispute resolution.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriterAutoRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted', models.BooleanField(default=False, help_text='Has the writer been auto-promoted?')),
                ('demoted', models.BooleanField(default=False, help_text='Has the writer been auto-demoted?')),
                ('reason', models.TextField(help_text='Reason for auto-promotion/demotion.')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content.')),
                ('attachment', models.FileField(blank=True, help_text='Optional message attachment.', null=True, upload_to='writer_messages/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False, help_text='Flagged for admin moderation.')),
            ],
        ),
        migrations.CreateModel(
            name='WriterMessageModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for flagging the message.')),
                ('reviewed', models.BooleanField(default=False, help_text='Has the admin reviewed this message?')),
                ('action_taken', models.CharField(blank=True, choices=[('Delete', 'Delete'), ('Warn Writer', 'Warn Writer'), ('No Action', 'No Action')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriterMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_orders', models.PositiveIntegerField(default=0, help_text='Total number of completed orders.')),
                ('pending_orders', models.PositiveIntegerField(default=0, help_text='Total number of pending orders.')),
                ('late_deliveries', models.PositiveIntegerField(default=0, help_text='Number of orders delivered late.')),
                ('on_time_deliveries', models.PositiveIntegerField(default=0, help_text='Number of orders delivered on time.')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Total number of orders (completed + pending).')),
                ('total_earnings', models.PositiveIntegerField(default=0.0, help_text='Total amount the writer has earned')),
                ('total_disputed_orders', models.PositiveIntegerField(default=0, help_text='Total number of disputed orders.')),
                ('number_of_revisions', models.PositiveIntegerField(default=0, help_text='The number of revisions')),
                ('total_cancelled_orders', models.PositiveIntegerField(default=0, help_text='Total number of cancelled orders.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the performance record was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the performance metrics were updated.')),
            ],
        ),
        migrations.CreateModel(
            name='WriterPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Start of performance tracking period.')),
                ('period_end', models.DateTimeField(help_text='End of performance tracking period.')),
                ('completed_orders', models.PositiveIntegerField(default=0, help_text='Total completed orders.')),
                ('disputes', models.PositiveIntegerField(default=0, help_text='Total disputes.')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating for the period.', max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='WriterRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Current ranking level of the writer.', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Current average rating of the writer.', max_digits=3)),
                ('orders_completed', models.PositiveIntegerField(default=0, help_text='Total orders completed by the writer.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Writer Ranking',
                'verbose_name_plural': 'Writer Rankings',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingAdminReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, help_text='Admin comments on the ranking.', null=True)),
            ],
            options={
                'verbose_name': 'Writer Ranking Admin Review',
                'verbose_name_plural': 'Writer Ranking Admin Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Name of the ranking level.', max_length=100)),
                ('min_orders_completed', models.PositiveIntegerField(default=0, help_text='Minimum orders completed to qualify for this level.')),
                ('min_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum average rating to qualify for this level.', max_digits=3)),
                ('criteria_description', models.TextField(help_text='Description of the criteria for this ranking level.')),
            ],
            options={
                'verbose_name': 'Writer Ranking Criteria',
                'verbose_name_plural': 'Writer Ranking Criteria',
                'ordering': ['level_name'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingCriteriaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Name of the ranking level.', max_length=100)),
                ('min_orders_completed', models.PositiveIntegerField(default=0, help_text='Minimum orders completed to qualify for this level.')),
                ('min_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum average rating to qualify for this level.', max_digits=3)),
                ('criteria_description', models.TextField(help_text='Description of the criteria for this ranking level.')),
            ],
            options={
                'verbose_name': 'Writer Ranking Criteria Admin',
                'verbose_name_plural': 'Writer Ranking Criteria Admins',
                'ordering': ['level_name'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.CharField(help_text='Previous ranking level of the writer.', max_length=100)),
                ('new_level', models.CharField(help_text='New ranking level of the writer.', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Writer Ranking History',
                'verbose_name_plural': 'Writer Ranking Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.CharField(help_text='Previous ranking level of the writer.', max_length=100)),
                ('new_level', models.CharField(help_text='New ranking level of the writer.', max_length=100)),
                ('change_reason', models.TextField(help_text='Reason for the ranking change.')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Writer Ranking Log',
                'verbose_name_plural': 'Writer Ranking Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message about the ranking change.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Writer Ranking Notification',
                'verbose_name_plural': 'Writer Ranking Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='tip',
            new_name='writer_mana_client__7889a8_idx',
            old_name='writer_mana_client__idx',
        ),
        migrations.RenameIndex(
            model_name='tip',
            new_name='writer_mana_writer__c446b1_idx',
            old_name='writer_mana_writer__idx',
        ),
        migrations.RenameIndex(
            model_name='tip',
            new_name='writer_mana_tip_typ_ae6c0f_idx',
            old_name='writer_mana_tip_typ_idx',
        ),
        migrations.RenameIndex(
            model_name='writerperformancesnapshot',
            new_name='writer_mana_website_643dba_idx',
            old_name='writer_mana_website_idx',
        ),
        migrations.AddField(
            model_name='writerreward',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='writerreward',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tip',
            name='writer_level',
            field=models.ForeignKey(help_text='Writer level at time of tip (for percentage calculation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='writer_management.writerlevel'),
        ),
        migrations.AlterField(
            model_name='writerlevel',
            name='base_pay_per_page',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base pay per page (used in fixed_per_page mode or as minimum fallback).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='writerlevel',
            name='base_pay_per_slide',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base pay per slide (used in fixed_per_page mode or as minimum fallback).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='writerlevel',
            name='max_orders',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of orders the writer can take simultaneously (max_takes_per_writer).'),
        ),
        migrations.AlterField(
            model_name='writerlevel',
            name='tip_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of tips writer receives (100% = full tips, 50% = half tips)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='writerlevel',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_level_definitions', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='writerlevelconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_level_configs', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='writerpayment',
            name='tips',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tips received.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='writerpayment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_management_payments', to='writer_management.writerprofile'),
        ),
        migrations.AlterField(
            model_name='writerperformancesnapshot',
            name='client_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total client revenue for writer’s orders', max_digits=12),
        ),
        migrations.AlterField(
            model_name='writerperformancesnapshot',
            name='hvo_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='writerprofile',
            name='pen_name',
            field=models.CharField(blank=True, help_text='Pen name visible to clients (instead of real name). If not set, registration_id will be used.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='writerreward',
            name='performance_metric',
            field=models.JSONField(blank=True, default=dict, help_text='Details of the performance metric used to determine the reward.'),
        ),
        migrations.AlterField(
            model_name='writerreward',
            name='prize',
            field=models.CharField(blank=True, help_text="Prize or benefit (e.g., 'Bonus $50').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='writerreward',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_rewards', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='writerreward',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_order_disputes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerautoranking',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerautoranking',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerautoranking',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_ranking', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_writer_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writermessage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writermessagemoderation',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writermessagemoderation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='writer_management.writermessage'),
        ),
        migrations.AddField(
            model_name='writermessagemoderation',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writermessagethread',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='orders.order'),
        ),
        migrations.AddField(
            model_name='writermessagethread',
            name='participant',
            field=models.ForeignKey(help_text='The client or admin participating in the thread.', on_delete=django.db.models.deletion.CASCADE, related_name='writer_participant_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writermessagethread',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writermessagethread',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writermessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='writer_management.writermessagethread'),
        ),
        migrations.AddField(
            model_name='writerperformance',
            name='average_rating',
            field=models.ForeignKey(default=0.0, help_text='Average rating based on client feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='average_writer_rating', to='reviews_system.writerreview'),
        ),
        migrations.AddField(
            model_name='writerperformance',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_performance', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerperformance',
            name='writer',
            field=models.OneToOneField(help_text='The writer whose performance is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerperformancereport',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_performance_report', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerperformancereport',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerranking',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerranking',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerrankingadminreview',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_admin_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrankingadminreview',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerrankingadminreview',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_admin_reviews', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerrankingcriteria',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerrankingcriteriaadmin',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerrankinghistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrankinghistory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerrankinghistory',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerrankinglog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_log_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrankinglog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerrankinglog',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_logs', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerrankingnotification',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerrankingnotification',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_notifications', to='writer_management.writerprofile'),
        ),
    ]
