# Generated by Django 5.0.14 on 2025-11-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0008_add_reason_to_writer_order_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='manual_payment_requests_enabled',
            field=models.BooleanField(default=False, help_text='Allow this writer to request manual payments outside of scheduled dates'),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='payment_date_preference',
            field=models.CharField(blank=True, help_text="Preferred payment dates (e.g., '1,15' for bi-weekly on 1st and 15th, '1' for monthly on 1st)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='payment_schedule',
            field=models.CharField(choices=[('bi-weekly', 'Bi-Weekly (Every 2 weeks)'), ('monthly', 'Monthly')], default='bi-weekly', help_text="Writer's preferred payment schedule", max_length=20),
        ),
    ]
