# Generated by Django 5.0.14 on 2025-11-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0010_add_pen_name_and_resources'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='writerpennamechangerequest',
            new_name='writer_mana_status_33c805_idx',
            old_name='writer_mana_status_7a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='writerpennamechangerequest',
            new_name='writer_mana_writer__c72efc_idx',
            old_name='writer_mana_writer__8c9e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='writerresource',
            new_name='writer_mana_website_061d78_idx',
            old_name='writer_mana_website_9c8e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='writerresource',
            new_name='writer_mana_categor_db5cba_idx',
            old_name='writer_mana_categor_7d9e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='writerresourceview',
            new_name='writer_mana_writer__049abb_idx',
            old_name='writer_mana_writer__a9e3f1_idx',
        ),
    ]
