# Generated by Django 5.0.14 on 2025-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0015_add_capacity_feedback_portfolio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='writer_mana_order_i_63eb4a_idx',
            old_name='writer_mana_feedback_order_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='writer_mana_to_user_d8f05a_idx',
            old_name='writer_mana_feedback_to_user_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='writer_mana_from_us_e6be00_idx',
            old_name='writer_mana_feedback_from_user_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackhistory',
            new_name='writer_mana_user_id_1ed740_idx',
            old_name='writer_mana_feedback_history_user_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackhistory',
            new_name='writer_mana_average_0c09d7_idx',
            old_name='writer_mana_feedback_history_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliosample',
            new_name='writer_mana_writer__8f1f77_idx',
            old_name='writer_mana_portfolio_sample_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliosample',
            new_name='writer_mana_is_feat_78f683_idx',
            old_name='writer_mana_is_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='writercapacity',
            new_name='writer_mana_writer__745d18_idx',
            old_name='writer_mana_capacity_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='writercapacity',
            new_name='writer_mana_is_avai_e8ebfd_idx',
            old_name='writer_mana_capacity_available_idx',
        ),
        migrations.RenameIndex(
            model_name='writerportfolio',
            new_name='writer_mana_writer__54940b_idx',
            old_name='writer_mana_portfolio_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='writerportfolio',
            new_name='writer_mana_is_enab_4eb08f_idx',
            old_name='writer_mana_portfolio_enabled_idx',
        ),
        migrations.AlterField(
            model_name='writerportfolio',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('clients_only', 'Clients Only'), ('public', 'Public')], default='clients_only', help_text='Who can view this portfolio', max_length=20),
        ),
    ]
