# Generated by Django 5.0.14 on 2025-12-06 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_writer_acknowledgment_message_review_reminders'),
        ('wallet', '0001_initial'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        ('writer_management', '0016_rename_writer_mana_feedback_order_idx_writer_mana_order_i_63eb4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writerearningshistory',
            options={'ordering': ['-period_end'], 'verbose_name': 'Writer Earnings History', 'verbose_name_plural': 'Writer Earnings Histories'},
        ),
        migrations.AlterModelOptions(
            name='writerorderrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Writer Order Request', 'verbose_name_plural': 'Writer Order Requests'},
        ),
        migrations.AlterModelOptions(
            name='writerordertake',
            options={'ordering': ['-taken_at'], 'verbose_name': 'Writer Order Take', 'verbose_name_plural': 'Writer Order Takes'},
        ),
        migrations.AlterModelOptions(
            name='writerpayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Writer Payment', 'verbose_name_plural': 'Writer Payments'},
        ),
        migrations.AlterModelOptions(
            name='writersupportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Writer Support Ticket', 'verbose_name_plural': 'Writer Support Tickets'},
        ),
        migrations.AddIndex(
            model_name='writerearningshistory',
            index=models.Index(fields=['writer', 'period_end'], name='writer_mana_writer__1a5e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningshistory',
            index=models.Index(fields=['website', 'period_end'], name='writer_mana_website_5963a4_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningshistory',
            index=models.Index(fields=['writer', 'website', 'period_end'], name='writer_mana_writer__f81ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningshistory',
            index=models.Index(fields=['period_start', 'period_end'], name='writer_mana_period__9947ca_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderrequest',
            index=models.Index(fields=['writer', 'approved', 'requested_at'], name='writer_mana_writer__61b86f_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderrequest',
            index=models.Index(fields=['website', 'approved'], name='writer_mana_website_97a345_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderrequest',
            index=models.Index(fields=['order', 'approved'], name='writer_mana_order_i_77cf1f_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderrequest',
            index=models.Index(fields=['approved', 'requested_at'], name='writer_mana_approve_90f330_idx'),
        ),
        migrations.AddIndex(
            model_name='writerordertake',
            index=models.Index(fields=['writer', 'taken_at'], name='writer_mana_writer__5e2ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='writerordertake',
            index=models.Index(fields=['website', 'order'], name='writer_mana_website_4736c9_idx'),
        ),
        migrations.AddIndex(
            model_name='writerordertake',
            index=models.Index(fields=['order', 'taken_at'], name='writer_mana_order_i_9c3793_idx'),
        ),
        migrations.AddIndex(
            model_name='writerpayment',
            index=models.Index(fields=['writer', 'payment_date'], name='writer_mana_writer__5336a0_idx'),
        ),
        migrations.AddIndex(
            model_name='writerpayment',
            index=models.Index(fields=['website', 'payment_date'], name='writer_mana_website_8ed9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='writerpayment',
            index=models.Index(fields=['writer', 'website', 'payment_date'], name='writer_mana_writer__886da2_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprofile',
            index=models.Index(fields=['website', 'is_available_for_auto_assignments'], name='writer_mana_website_5357df_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprofile',
            index=models.Index(fields=['writer_level', 'average_rating'], name='writer_mana_writer__b76478_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprofile',
            index=models.Index(fields=['verification_status', 'joined_at'], name='writer_mana_verific_0d719d_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprofile',
            index=models.Index(fields=['is_deleted', 'joined_at'], name='writer_mana_is_dele_33bca7_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprofile',
            index=models.Index(fields=['user'], name='writer_mana_user_id_675603_idx'),
        ),
        migrations.AddIndex(
            model_name='writerprofile',
            index=models.Index(fields=['website', 'is_deleted'], name='writer_mana_website_37c1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='writersupportticket',
            index=models.Index(fields=['writer', 'status', 'created_at'], name='writer_mana_writer__67a51b_idx'),
        ),
        migrations.AddIndex(
            model_name='writersupportticket',
            index=models.Index(fields=['website', 'status'], name='writer_mana_website_5e3daf_idx'),
        ),
        migrations.AddIndex(
            model_name='writersupportticket',
            index=models.Index(fields=['status', 'created_at'], name='writer_mana_status_d0934b_idx'),
        ),
        migrations.AddIndex(
            model_name='writersupportticket',
            index=models.Index(fields=['resolved_by', 'status'], name='writer_mana_resolve_7595f7_idx'),
        ),
    ]
