# Generated by Django 5.0.14 on 2025-12-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0018_add_writer_order_priority'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='writerorderpriority',
            new_name='writer_mana_writer__c11943_idx',
            old_name='writer_mana_writer__priority_idx',
        ),
        migrations.RenameIndex(
            model_name='writerorderpriority',
            new_name='writer_mana_order_i_825fb7_idx',
            old_name='writer_mana_order__priority_idx',
        ),
    ]
