# Generated by Django 5.0.14 on 2025-12-21 11:27

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderdraft_orderpreset_revisionrequest'),
        ('reviews_system', '0003_alter_orderreview_reviewer_and_more'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
        ('writer_management', '0021_recreate_writer_performance_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerperformancemetrics',
            name='percentile_rank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='You’re better than X% of writers', max_digits=6),
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for disputing the order.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes on dispute resolution.', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_order_disputes', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='writer_management.writerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterAutoRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted', models.BooleanField(default=False, help_text='Has the writer been auto-promoted?')),
                ('demoted', models.BooleanField(default=False, help_text='Has the writer been auto-demoted?')),
                ('reason', models.TextField(help_text='Reason for auto-promotion/demotion.')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_reviews', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_ranking', to='writer_management.writerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content.')),
                ('attachment', models.FileField(blank=True, help_text='Optional message attachment.', null=True, upload_to='writer_messages/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False, help_text='Flagged for admin moderation.')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_writer_messages', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='WriterMessageModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for flagging the message.')),
                ('reviewed', models.BooleanField(default=False, help_text='Has the admin reviewed this message?')),
                ('action_taken', models.CharField(blank=True, choices=[('Delete', 'Delete'), ('Warn Writer', 'Warn Writer'), ('No Action', 'No Action')], max_length=50, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='writer_management.writermessage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='WriterMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='orders.order')),
                ('participant', models.ForeignKey(help_text='The client or admin participating in the thread.', on_delete=django.db.models.deletion.CASCADE, related_name='writer_participant_threads', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='writer_management.writerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='writermessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='writer_management.writermessagethread'),
        ),
        migrations.CreateModel(
            name='WriterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_orders', models.PositiveIntegerField(default=0, help_text='Total number of completed orders.')),
                ('pending_orders', models.PositiveIntegerField(default=0, help_text='Total number of pending orders.')),
                ('late_deliveries', models.PositiveIntegerField(default=0, help_text='Number of orders delivered late.')),
                ('on_time_deliveries', models.PositiveIntegerField(default=0, help_text='Number of orders delivered on time.')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Total number of orders (completed + pending).')),
                ('total_earnings', models.PositiveIntegerField(default=0.0, help_text='Total amount the writer has earned')),
                ('total_disputed_orders', models.PositiveIntegerField(default=0, help_text='Total number of disputed orders.')),
                ('number_of_revisions', models.PositiveIntegerField(default=0, help_text='The number of revisions')),
                ('total_cancelled_orders', models.PositiveIntegerField(default=0, help_text='Total number of cancelled orders.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the performance record was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the performance metrics were updated.')),
                ('average_rating', models.ForeignKey(default=0.0, help_text='Average rating based on client feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='average_writer_rating', to='reviews_system.writerreview')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_performance', to='websites.website')),
                ('writer', models.OneToOneField(help_text='The writer whose performance is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='writer_management.writerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Start of performance tracking period.')),
                ('period_end', models.DateTimeField(help_text='End of performance tracking period.')),
                ('completed_orders', models.PositiveIntegerField(default=0, help_text='Total completed orders.')),
                ('disputes', models.PositiveIntegerField(default=0, help_text='Total disputes.')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating for the period.', max_digits=3)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_performance_report', to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='writer_management.writerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Current ranking level of the writer.', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Current average rating of the writer.', max_digits=3)),
                ('orders_completed', models.PositiveIntegerField(default=0, help_text='Total orders completed by the writer.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Ranking',
                'verbose_name_plural': 'Writer Rankings',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingAdminReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, help_text='Admin comments on the ranking.', null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_admin_reviews', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_admin_reviews', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Ranking Admin Review',
                'verbose_name_plural': 'Writer Ranking Admin Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Name of the ranking level.', max_length=100)),
                ('min_orders_completed', models.PositiveIntegerField(default=0, help_text='Minimum orders completed to qualify for this level.')),
                ('min_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum average rating to qualify for this level.', max_digits=3)),
                ('criteria_description', models.TextField(help_text='Description of the criteria for this ranking level.')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
            options={
                'verbose_name': 'Writer Ranking Criteria',
                'verbose_name_plural': 'Writer Ranking Criteria',
                'ordering': ['level_name'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingCriteriaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Name of the ranking level.', max_length=100)),
                ('min_orders_completed', models.PositiveIntegerField(default=0, help_text='Minimum orders completed to qualify for this level.')),
                ('min_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum average rating to qualify for this level.', max_digits=3)),
                ('criteria_description', models.TextField(help_text='Description of the criteria for this ranking level.')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
            options={
                'verbose_name': 'Writer Ranking Criteria Admin',
                'verbose_name_plural': 'Writer Ranking Criteria Admins',
                'ordering': ['level_name'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.CharField(help_text='Previous ranking level of the writer.', max_length=100)),
                ('new_level', models.CharField(help_text='New ranking level of the writer.', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_changes', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Ranking History',
                'verbose_name_plural': 'Writer Ranking Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.CharField(help_text='Previous ranking level of the writer.', max_length=100)),
                ('new_level', models.CharField(help_text='New ranking level of the writer.', max_length=100)),
                ('change_reason', models.TextField(help_text='Reason for the ranking change.')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_log_changes', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_logs', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Ranking Log',
                'verbose_name_plural': 'Writer Ranking Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterRankingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message about the ranking change.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_notifications', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Ranking Notification',
                'verbose_name_plural': 'Writer Ranking Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram')], help_text='The platform for the webhook (e.g., Slack, Discord).', max_length=20)),
                ('webhook_url', models.URLField(help_text='The URL to which the webhook will send requests.')),
                ('enabled', models.BooleanField(default=True, help_text="If false, this webhook won't send any events.")),
                ('subscribed_events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('order_revised', 'Order Revised'), ('order_submitted', 'Order Submitted'), ('order_reopened', 'Order Reopened'), ('order_on_hold', 'Order On Hold'), ('order_cancelled', 'Order Cancelled'), ('order_on_revision', 'Order On Revision'), ('revision_requested', 'Revision Requested'), ('order_disputed', 'Order Disputed'), ('order_completed', 'Order Completed'), ('order_reviewed', 'Order Reviewed'), ('order_rated', 'Order Rated')], max_length=50), blank=True, default=list, help_text='List of events this webhook is subscribed to.', size=None)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag — deactivates the webhook without removing the record.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user this webhook setting belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_settings', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Multitenancy support: this webhook is for a specific website.', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_settings', to='websites.website')),
            ],
            options={
                'verbose_name': 'Webhook Setting',
                'verbose_name_plural': 'Webhook Settings',
                'unique_together': {('user', 'platform', 'website')},
            },
        ),
        migrations.CreateModel(
            name='WriterPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('late_orders', models.PositiveIntegerField(default=0)),
                ('revised_orders', models.PositiveIntegerField(default=0)),
                ('disputed_orders', models.PositiveIntegerField(default=0)),
                ('hvo_orders', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('preferred_orders', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('client_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total client revenue for writer’s orders', max_digits=12)),
                ('profit_contribution', models.DecimalField(decimal_places=2, default=0.0, help_text='Client revenue - writer cost', max_digits=12)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('completion_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('lateness_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('revision_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('dispute_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('preferred_order_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('average_turnaround_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted score used to compare writer performance', max_digits=5, null=True)),
                ('better_than_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percent of writers this one outperforms in the same period', max_digits=5, null=True)),
                ('is_cached', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_performance_snapshots', to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='writer_management.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer Performance Snapshot',
                'verbose_name_plural': 'Writer Performance Snapshots',
                'indexes': [models.Index(fields=['website', 'writer', 'period_end'], name='writer_mana_website_643dba_idx')],
                'unique_together': {('website', 'writer', 'period_start', 'period_end')},
            },
        ),
    ]
