# Generated by Django 5.0.14 on 2025-12-31 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_add_cancellation_request_model'),
        ('websites', '0011_add_external_review_links'),
        ('writer_management', '0022_alter_writerperformancemetrics_percentile_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeractionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='writerdeadlineextensionrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='writerearningsreviewrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='writerorderholdrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='writerorderreopenrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddIndex(
            model_name='writeractionlog',
            index=models.Index(fields=['writer', 'created_at'], name='writer_mana_writer__46bbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='writeractionlog',
            index=models.Index(fields=['website', 'action', 'created_at'], name='writer_mana_website_c9c75c_idx'),
        ),
        migrations.AddIndex(
            model_name='writeractionlog',
            index=models.Index(fields=['action', 'created_at'], name='writer_mana_action_9dd885_idx'),
        ),
        migrations.AddIndex(
            model_name='writerdeadlineextensionrequest',
            index=models.Index(fields=['writer', 'approved', 'requested_at'], name='writer_mana_writer__0387dd_idx'),
        ),
        migrations.AddIndex(
            model_name='writerdeadlineextensionrequest',
            index=models.Index(fields=['order', 'approved'], name='writer_mana_order_i_efe4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='writerdeadlineextensionrequest',
            index=models.Index(fields=['website', 'approved'], name='writer_mana_website_cb3351_idx'),
        ),
        migrations.AddIndex(
            model_name='writerdeadlineextensionrequest',
            index=models.Index(fields=['approved', 'requested_at'], name='writer_mana_approve_af3d97_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningsreviewrequest',
            index=models.Index(fields=['writer', 'approved', 'requested_at'], name='writer_mana_writer__a21523_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningsreviewrequest',
            index=models.Index(fields=['order', 'approved'], name='writer_mana_order_i_223320_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningsreviewrequest',
            index=models.Index(fields=['website', 'approved'], name='writer_mana_website_95d260_idx'),
        ),
        migrations.AddIndex(
            model_name='writerearningsreviewrequest',
            index=models.Index(fields=['approved', 'requested_at'], name='writer_mana_approve_a5fc21_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderholdrequest',
            index=models.Index(fields=['writer', 'approved', 'requested_at'], name='writer_mana_writer__8680f1_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderholdrequest',
            index=models.Index(fields=['order', 'approved'], name='writer_mana_order_i_cef015_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderholdrequest',
            index=models.Index(fields=['website', 'approved'], name='writer_mana_website_0ce8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderholdrequest',
            index=models.Index(fields=['approved', 'requested_at'], name='writer_mana_approve_3da29f_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderreopenrequest',
            index=models.Index(fields=['writer', 'approved', 'requested_at'], name='writer_mana_writer__f58176_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderreopenrequest',
            index=models.Index(fields=['order', 'approved'], name='writer_mana_order_i_c72295_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderreopenrequest',
            index=models.Index(fields=['website', 'approved'], name='writer_mana_website_6ee811_idx'),
        ),
        migrations.AddIndex(
            model_name='writerorderreopenrequest',
            index=models.Index(fields=['approved', 'requested_at'], name='writer_mana_approve_f28909_idx'),
        ),
    ]
