# Generated by Django 5.0.14 on 2026-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer_management', '0023_add_can_take_orders_flag'),
        ('writer_management', '0023_alter_writeractionlog_options_and_more'),
    ]

    operations = [
    ]
