# Generated by Django 5.0.14 on 2025-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_add_default_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Indicates this client was created via guest checkout and may be feature-limited.'),
        ),
    ]
