# Generated by Django 5.1.5 on 2025-02-04 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suspend', 'Suspend'), ('activate', 'Activate'), ('deactivate', 'Deactivate')], help_text='The action taken on the client account.', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the action was performed.')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the action.', null=True)),
            ],
            options={
                'verbose_name': 'Client Action',
                'verbose_name_plural': 'Client Actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the activity.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='Country of the client.', max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="Client's timezone for accurate date and time displays.", max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client.', null=True)),
                ('location_verified', models.BooleanField(default=False, help_text="Whether the client's location has been verified.")),
                ('phone_number', models.CharField(blank=True, help_text="Client's phone number.", max_length=15, null=True)),
                ('registration_id', models.CharField(help_text='Unique client registration ID (e.g., Client #12345).', max_length=50, unique=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Total loyalty points accumulated by the client.')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent by the client.', max_digits=12)),
                ('last_online', models.DateTimeField(blank=True, help_text='The last time the client was online.', null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the client registered.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the client account is active.')),
                ('is_suspended', models.BooleanField(default=False, help_text='Indicates whether the client account is suspended.')),
                ('is_locked', models.BooleanField(default=False, help_text='Indicates if the account is locked due to suspicious activity.')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_changes', models.TextField(help_text='The changes requested by the client.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The status of the profile update request.', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response from the admin regarding the request.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the request was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the request was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('detected_country', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Temporary password or reset code.', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='Expiration date and time for the temporary password.')),
            ],
        ),
    ]
