# Generated by Django 5.1.5 on 2025-02-04 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0001_initial'),
        ('loyalty_management', '0001_initial'),
        ('websites', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaction',
            name='performed_by',
            field=models.ForeignKey(help_text='The admin who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_writers',
            field=models.ManyToManyField(blank=True, help_text="Client's preferred writers.", limit_choices_to={'role': 'writer'}, related_name='preferred_by_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Loyalty tier of the client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_in_tier', to='loyalty_management.loyaltytier'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this client profile.', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='website',
            field=models.ForeignKey(help_text='Website the client is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='websites.website'),
        ),
        migrations.AddField(
            model_name='clientactivitylog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='client_management.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientaction',
            name='client',
            field=models.ForeignKey(help_text='The client whose account is being modified.', on_delete=django.db.models.deletion.CASCADE, related_name='client_actions', to='client_management.clientprofile'),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='client',
            field=models.ForeignKey(help_text='The client requesting a profile update.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_requests', to='client_management.clientprofile'),
        ),
        migrations.AddField(
            model_name='suspiciouslogin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_logins', to='client_management.clientprofile'),
        ),
        migrations.AddField(
            model_name='temporarypassword',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_password', to='client_management.clientprofile'),
        ),
    ]
