# Generated by Django 5.0.14 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superadmin', models.BooleanField(default=False, help_text='Has unrestricted access (Superadmin Only).')),
                ('can_manage_users', models.BooleanField(default=True, help_text='Can manage writers, editors, clients, and support staff.')),
                ('can_suspend_users', models.BooleanField(default=True, help_text='Can suspend users (except superadmins).')),
                ('can_put_on_probation', models.BooleanField(default=True, help_text='Can place users on probation.')),
                ('can_handle_orders', models.BooleanField(default=True, help_text='Can manage order assignments, edits, and cancellations.')),
                ('can_resolve_disputes', models.BooleanField(default=True, help_text='Can handle disputes between clients and writers.')),
                ('can_manage_payouts', models.BooleanField(default=True, help_text='Can approve writer payouts and financial transactions.')),
                ('can_manage_financials', models.BooleanField(default=True, help_text='Can manage payments, refunds, and discounts.')),
                ('can_manage_tickets', models.BooleanField(default=True, help_text='Can handle support tickets and client inquiries.')),
                ('can_view_reports', models.BooleanField(default=True, help_text='Can access reporting and analytics.')),
                ('can_blacklist_users', models.BooleanField(default=False, help_text='Can blacklist users (Superadmins only).')),
                ('can_manage_writers', models.BooleanField(default=False)),
                ('can_manage_clients', models.BooleanField(default=False)),
                ('can_manage_editors', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete instead of removing admin.')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp.', null=True)),
                ('last_action', models.CharField(blank=True, help_text='Last performed action.', max_length=255, null=True)),
                ('action_count', models.IntegerField(default=0, help_text='Total actions taken by the admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(default='superadmin', help_text='Role being requested for promotion.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the promotion request.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for requesting promotion.', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was made.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was approved.', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was rejected.', null=True)),
            ],
            options={
                'verbose_name': 'Admin Promotion Request',
                'verbose_name_plural': 'Admin Promotion Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the blacklisted user.', max_length=254, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for blacklisting.', null=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted User',
                'verbose_name_plural': 'Blacklisted Users',
            },
        ),
    ]
