# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='admin',
            field=models.ForeignKey(help_text='Admin who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Admin requesting promotion.', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='website',
            field=models.ForeignKey(help_text='Website for which the promotion request is made.', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='blacklisted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User object of the blacklisted user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='website',
            field=models.ForeignKey(help_text='Website to which the blacklisted user belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_users', to='websites.website'),
        ),
    ]
