# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User the action was performed on, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_log_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminpromotionrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='blacklisted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_users', to='websites.website'),
        ),
        migrations.AddField(
            model_name='staffwebsiteassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffwebsiteassignment',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffwebsiteassignment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['timestamp'], name='admin_manag_timesta_ee3a49_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin', 'timestamp'], name='admin_manag_admin_i_4b1cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['target_user', 'timestamp'], name='admin_manag_target__96557a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffwebsiteassignment',
            unique_together={('staff_member', 'website')},
        ),
    ]
