# Generated by Django 5.2.2 on 2026-06-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0004_operations_command_item_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationscommanditemevent',
            new_name='admin_manag_state_i_3ad923_idx',
            old_name='admin_manag_state_i_7a7f11_idx',
        ),
        migrations.RenameIndex(
            model_name='operationscommanditemevent',
            new_name='admin_manag_actor_i_718246_idx',
            old_name='admin_manag_actor_i_a3d6b9_idx',
        ),
        migrations.RenameIndex(
            model_name='operationscommanditemevent',
            new_name='admin_manag_action_bd669a_idx',
            old_name='admin_manag_action__2f193c_idx',
        ),
        migrations.RenameIndex(
            model_name='operationscommanditemstate',
            new_name='admin_manag_status_e43744_idx',
            old_name='admin_manag_status_46a32d_idx',
        ),
        migrations.RenameIndex(
            model_name='operationscommanditemstate',
            new_name='admin_manag_assigne_ae488c_idx',
            old_name='admin_manag_assigne_7798ac_idx',
        ),
        migrations.RenameIndex(
            model_name='operationscommanditemstate',
            new_name='admin_manag_website_348854_idx',
            old_name='admin_manag_website_25db05_idx',
        ),
        migrations.RenameIndex(
            model_name='operationscommanditemstate',
            new_name='admin_manag_domain_49adc3_idx',
            old_name='admin_manag_domain_079104_idx',
        ),
    ]
