/**
 * Admin/Superadmin Navigation Configuration
 * Organized by logical groups following UI/UX best practices
 */

export const adminNavigationGroups = [
  {
    id: 'core-operations',
    label: 'Core Operations',
    icon: '⚙️',
    items: [
      {
        name: 'OrderManagement',
        to: '/admin/orders',
        label: 'Order Management',
        icon: '📋',
        description: 'Manage all orders, assignments, and status',
      },
      {
        name: 'SpecialOrderManagement',
        to: '/admin/special-orders',
        label: 'Special Orders',
        icon: '⭐',
        description: 'Handle special and custom orders',
      },
      {
        name: 'UserManagement',
        to: '/admin/users',
        label: 'User Management',
        icon: '👥',
        description: 'Manage users, roles, and permissions',
      },
      {
        name: 'SupportTicketsManagement',
        to: '/admin/support-tickets',
        label: 'Support Tickets',
        icon: '🎫',
        description: 'Manage customer support tickets',
        roles: ['admin', 'superadmin', 'support'],
      },
      {
        name: 'SupportProfilesManagement',
        to: '/admin/support-profiles',
        label: 'Support Profiles',
        icon: '👤',
        description: 'Manage support staff profiles',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'WorkloadTracker',
        to: '/admin/workload-tracker',
        label: 'Workload Tracker',
        icon: '📊',
        description: 'Track support staff workload and capacity',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'PaymentIssuesManagement',
        to: '/admin/payment-issues',
        label: 'Payment Issues',
        icon: '💳',
        description: 'Log and track payment-related issues',
        roles: ['admin', 'superadmin', 'support'],
      },
      {
        name: 'EscalationsManagement',
        to: '/admin/escalations',
        label: 'Escalations',
        icon: '⬆️',
        description: 'Track escalated tickets and issues',
        roles: ['admin', 'superadmin', 'support'],
      },
      {
        name: 'FAQsManagement',
        to: '/admin/faqs',
        label: 'FAQs',
        icon: '❓',
        description: 'Manage FAQ articles for knowledge base',
        roles: ['admin', 'superadmin', 'support'],
      },
    ],
  },
  {
    id: 'financial',
    label: 'Financial Management',
    icon: '💰',
    items: [
      {
        name: 'ClientPayments',
        to: '/admin/payments/client-payments',
        label: 'Client Payments',
        icon: '💳',
        description: 'View all client payments, transactions, and top-ups',
      },
      {
        name: 'Payments',
        to: '/admin/payments/writer-payments',
        label: 'Writer Payments',
        icon: '💳',
        description: 'Manage writer payments and payouts',
      },
      {
        name: 'RefundManagement',
        to: '/admin/refunds',
        label: 'Refunds',
        icon: '↩️',
        description: 'Process and manage refunds',
      },
      {
        name: 'DisputeManagement',
        to: '/admin/disputes',
        label: 'Disputes',
        icon: '⚖️',
        description: 'Resolve order disputes',
      },
      {
        name: 'TipManagement',
        to: '/admin/tips',
        label: 'Tips',
        icon: '💸',
        description: 'Manage writer tips',
      },
      {
        name: 'FinesManagement',
        to: '/admin/fines',
        label: 'Fines',
        icon: '🚫',
        description: 'Manage fines and penalties',
      },
      {
        name: 'AdvancePaymentsManagement',
        to: '/admin/advance-payments',
        label: 'Advance Payments',
        icon: '💵',
        description: 'Manage advance payment requests',
      },
      {
        name: 'WalletManagement',
        to: '/admin/wallets',
        label: 'Wallets',
        icon: '💼',
        description: 'Manage user wallets',
      },
      {
        name: 'FinancialOverview',
        to: '/admin/financial-overview',
        label: 'Financial Overview',
        icon: '📊',
        description: 'Financial analytics and reports',
      },
      {
        name: 'InvoiceManagement',
        to: '/admin/invoices',
        label: 'Invoices',
        icon: '📄',
        description: 'Manage invoices',
      },
    ],
  },
  {
    id: 'content',
    label: 'Content & Services',
    icon: '📝',
    items: [
      {
        name: 'ReviewsManagement',
        to: '/admin/reviews',
        label: 'Reviews',
        icon: '💬',
        description: 'Manage reviews and ratings',
      },
      {
        name: 'ReviewModeration',
        to: '/admin/reviews/moderation',
        label: 'Review Moderation',
        icon: '✅',
        description: 'Moderate user reviews',
      },
      {
        name: 'ReviewAggregation',
        to: '/admin/review-aggregation',
        label: 'Review Aggregation',
        icon: '⭐',
        description: 'Aggregate and analyze reviews',
      },
      {
        name: 'ClassManagement',
        to: '/admin/class-management',
        label: 'Class Management',
        icon: '📚',
        description: 'Manage class bundles',
      },
      {
        name: 'ExpressClassesManagement',
        to: '/admin/express-classes',
        label: 'Express Classes',
        icon: '⚡',
        description: 'Manage express class offerings',
      },
      {
        name: 'BlogManagement',
        to: '/admin/blog',
        label: 'Blog Pages',
        icon: '📝',
        description: 'Manage blog content',
      },
      {
        name: 'BlogAuthors',
        to: '/admin/blog-authors',
        label: 'Blog Authors',
        icon: '🖊️',
        description: 'Manage blog authors, bios, and social profiles',
      },
      {
        name: 'SEOPagesManagement',
        to: '/admin/seo-pages',
        label: 'SEO Pages (Service)',
        icon: '🔍',
        description: 'Manage service pages with FAQs and resources',
      },
      {
        name: 'SeoPagesBlockEditor',
        to: '/admin/seo-pages-blocks',
        label: 'SEO Landing Pages',
        icon: '📄',
        description: 'Manage SEO landing pages with block-based content',
      },
      {
        name: 'MediaLibrary',
        to: '/admin/media-library',
        label: 'Media Library',
        icon: '🖼️',
        description: 'Manage images, videos, and media assets',
      },
      {
        name: 'FileManagement',
        to: '/admin/files',
        label: 'File Management',
        icon: '📁',
        description: 'Manage system files',
      },
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics & Reporting',
    icon: '📊',
    items: [
      {
        name: 'AdvancedAnalytics',
        to: '/admin/advanced-analytics',
        label: 'Advanced Analytics',
        icon: '📈',
        description: 'Comprehensive analytics dashboard',
      },
      {
        name: 'EnhancedAnalytics',
        to: '/admin/enhanced-analytics',
        label: 'Enhanced Analytics',
        icon: '📉',
        description: 'Enhanced performance metrics',
      },
      {
        name: 'AnalyticsReports',
        to: '/admin/analytics-reports',
        label: 'Analytics & Reports',
        icon: '📊',
        description: 'Comprehensive yearly analytics comparing orders, classes, income, and more',
      },
      {
        name: 'RefinedStats',
        to: '/admin/geographic-analytics',
        label: 'Refined Stats',
        icon: '📊',
        description: 'View largest spend and number of orders by country, state, and subject',
      },
      {
        name: 'PricingAnalytics',
        to: '/admin/pricing-analytics',
        label: 'Pricing Analytics',
        icon: '💰',
        description: 'Pricing trends and analysis',
      },
      {
        name: 'DiscountAnalytics',
        to: '/admin/discount-analytics',
        label: 'Discount Analytics',
        icon: '🎟️',
        description: 'Discount usage and effectiveness',
      },
      {
        name: 'WriterPerformanceAnalytics',
        to: '/admin/writer-performance',
        label: 'Writer Performance',
        icon: '👤',
        description: 'Writer performance metrics',
      },
      {
        name: 'ReferralTracking',
        to: '/admin/referral-tracking',
        label: 'Referral Tracking',
      },
      {
        name: 'ReferralCodeTracing',
        to: '/admin/referral-code-tracing',
        label: 'Referral Code Tracing',
        icon: '🔍',
        description: 'Trace and analyze referral codes with comprehensive usage statistics',
        icon: '🎁',
        description: 'Track referral programs',
      },
      {
        name: 'RedemptionCategoriesManagement',
        to: '/admin/redemption-categories',
        label: 'Redemption Categories',
        icon: '📂',
        description: 'Manage redemption item categories',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'RedemptionItemsManagement',
        to: '/admin/redemption-items',
        label: 'Redemption Items',
        icon: '🎁',
        description: 'Manage items available for redemption',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'RedemptionRequestsManagement',
        to: '/admin/redemption-requests',
        label: 'Redemption Requests',
        icon: '📋',
        description: 'Manage client redemption requests',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'LoyaltyTracking',
        to: '/admin/loyalty-tracking',
        label: 'Loyalty Tracking',
        icon: '⭐',
        description: 'Track loyalty program usage',
      },
      {
        name: 'LoyaltyManagement',
        to: '/admin/loyalty-management',
        label: 'Loyalty Management',
        icon: '🏆',
        description: 'Manage loyalty programs',
      },
      {
        name: 'CampaignPerformanceDashboard',
        to: '/admin/campaigns',
        label: 'Campaign Analytics',
        icon: '📢',
        description: 'Campaign performance metrics',
      },
      {
        name: 'WriterBadgeAnalytics',
        to: '/admin/writer-badge-analytics',
        label: 'Writer Badge Analytics',
        icon: '🏅',
        description: 'Analytics for writer badge achievements',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'WriterPortfoliosManagement',
        to: '/admin/writer-portfolios',
        label: 'Writer Portfolios',
        icon: '📚',
        description: 'Manage writer portfolios and showcase work',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'WriterFeedbackManagement',
        to: '/admin/writer-feedback',
        label: 'Writer Feedback',
        icon: '💬',
        description: 'View and manage structured feedback for writers',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'EditorWorkloadTracker',
        to: '/admin/editor-workload',
        label: 'Editor Workload Tracker',
        icon: '📊',
        description: 'Monitor and manage editor workload and capacity',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'RateLimitingMonitoring',
        to: '/admin/rate-limiting',
        label: 'Rate Limiting Monitoring',
        icon: '🚦',
        description: 'Monitor API rate limit violations and statistics',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'CompressionMonitoring',
        to: '/admin/compression-monitoring',
        label: 'Compression Monitoring',
        icon: '🗜️',
        description: 'Monitor response compression statistics',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'SystemHealthMonitoring',
        to: '/admin/system-health',
        label: 'System Health',
        icon: '🏥',
        description: 'Monitor system health and alerts',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'FinancialOverview',
        to: '/admin/financial-overview',
        label: 'Financial Overview',
        icon: '💰',
        description: 'Comprehensive financial analytics',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'UnifiedSearch',
        to: '/admin/unified-search',
        label: 'Unified Search',
        icon: '🔍',
        description: 'Search across orders, users, payments, and messages',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'DataExports',
        to: '/admin/data-exports',
        label: 'Data Exports',
        icon: '📥',
        description: 'Export orders, payments, users, and financial data',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'DuplicateDetection',
        to: '/admin/duplicate-detection',
        label: 'Duplicate Detection',
        icon: '🔁',
        description: 'Detect and manage suspected duplicate accounts',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'SuperadminLogs',
        to: '/admin/superadmin-logs',
        label: 'Superadmin Logs',
        icon: '📋',
        description: 'Audit trail of all superadmin actions',
        roles: ['superadmin'],
      },
      {
        name: 'DashboardWidgetsManagement',
        to: '/admin/dashboard-widgets',
        label: 'Dashboard Widgets',
        icon: '📊',
        description: 'Manage customizable dashboard widgets',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'NewsletterAnalytics',
        to: '/admin/newsletter-analytics',
        label: 'Newsletter Analytics',
        icon: '📧',
        description: 'Track newsletter performance and engagement',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'CTAManagement',
        to: '/admin/cta-management',
        label: 'CTA Management',
        icon: '🎯',
        description: 'Manage call-to-action blocks and placements',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'NotificationGroupProfilesManagement',
        to: '/admin/notification-group-profiles',
        label: 'Notification Group Profiles',
        icon: '🔔',
        description: 'Manage notification preferences for user groups',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'BlogAnalyticsManagement',
        to: '/admin/blog-analytics',
        label: 'Blog Analytics',
        icon: '📈',
        description: 'Track clicks, conversions, and shares',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'SocialPlatformsManagement',
        to: '/admin/social-platforms',
        label: 'Social Platforms',
        icon: '📱',
        description: 'Manage social media platforms for sharing',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'ContentBlocksManagement',
        to: '/admin/content-blocks',
        label: 'Content Blocks',
        icon: '🧩',
        description: 'Create reusable content blocks (tables, info boxes, etc.) and insert into blogs',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'ABTestsManagement',
        to: '/admin/ab-tests',
        label: 'A/B Tests',
        icon: '🧪',
        description: 'Manage A/B tests for blog content optimization',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'BlogDarkModeImagesManagement',
        to: '/admin/blog-dark-mode-images',
        label: 'Blog Dark Mode Images',
        icon: '🌙',
        description: 'Manage dark mode images for blog posts',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'ReferralBonusDecaysManagement',
        to: '/admin/referral-bonus-decays',
        label: 'Referral Bonus Decays',
        icon: '📉',
        description: 'Manage referral bonus decay rules',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'WebhookEndpointsManagement',
        to: '/admin/webhook-endpoints',
        label: 'Webhook Endpoints',
        icon: '🔗',
        description: 'Manage webhook endpoints for notification delivery',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'NotificationDashboard',
        to: '/admin/notification-dashboard',
        label: 'Notification Dashboard',
        icon: '📊',
        description: 'Monitor notification system performance and metrics',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'ClassAnalytics',
        to: '/admin/class-analytics',
        label: 'Class Analytics',
        icon: '📚',
        description: 'Analytics for class bundles and bulk orders',
        roles: ['admin', 'superadmin'],
      },
    ],
  },
  {
    id: 'system',
    label: 'System Management',
    icon: '⚙️',
    items: [
      {
        name: 'PerformanceMonitoring',
        to: '/admin/performance-monitoring',
        label: 'Performance Monitoring',
        icon: '⚡',
        description: 'Monitor system performance and query optimization',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'ConfigManagement',
        to: '/admin/configs',
        label: 'Configurations',
        icon: '🎛️',
        description: 'System and pricing configurations',
      },
      {
        name: 'EmailDigestsManagement',
        to: '/admin/email-digests',
        label: 'Email Digests',
        icon: '📧',
        description: 'Manage email digest configurations',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'BroadcastMessagesManagement',
        to: '/admin/broadcast-messages',
        label: 'Broadcast Messages',
        icon: '📢',
        description: 'Manage broadcast email messages',
        roles: ['admin', 'superadmin'],
      },
      {
        name: 'ScreenedWordsManagement',
        to: '/admin/screened-words',
        label: 'Screened Words',
        icon: '🚫',
        description: 'Manage words that are automatically flagged in messages',
      },
      {
        name: 'FlaggedMessagesManagement',
        to: '/admin/flagged-messages',
        label: 'Flagged Messages',
        icon: '⚠️',
        description: 'Review and moderate messages flagged by screened words',
      },
      {
        name: 'SystemHealth',
        to: '/admin/system-health',
        label: 'System Health',
        icon: '🏥',
        description: 'Monitor system performance',
      },
      {
        name: 'ActivityLogs',
        to: '/admin/activity-logs',
        label: 'Activity Logs',
        icon: '📋',
        description: 'View system activity logs',
      },
      {
        name: 'EmailManagement',
        to: '/admin/emails',
        label: 'Email Management',
        icon: '📧',
        description: 'Manage email templates and campaigns',
      },
      {
        name: 'NotificationProfiles',
        to: '/admin/notification-profiles',
        label: 'Notification Profiles',
        icon: '🔔',
        description: 'Configure notification profiles',
      },
      {
        name: 'NotificationGroups',
        to: '/admin/notification-groups',
        label: 'Notification Groups',
        icon: '👥',
        description: 'Manage notification groups',
      },
      {
        name: 'DuplicateAccountDetection',
        to: '/admin/duplicate-detection',
        label: 'Duplicate Detection',
        icon: '🔍',
        description: 'Detect duplicate accounts',
      },
    ],
  },
  {
    id: 'discipline',
    label: 'Discipline & Appeals',
    icon: '⚖️',
    items: [
      {
        name: 'WriterDisciplineManagement',
        to: '/admin/writer-discipline',
        label: 'Writer Discipline',
        icon: '📜',
        description: 'Manage writer discipline actions',
      },
      {
        name: 'AppealsManagement',
        to: '/admin/appeals',
        label: 'Appeals',
        icon: '📝',
        description: 'Handle discipline appeals',
      },
      {
        name: 'DisciplineConfig',
        to: '/admin/discipline-config',
        label: 'Discipline Config',
        icon: '⚙️',
        description: 'Configure discipline rules',
      },
    ],
  },
  {
    id: 'multi-tenant',
    label: 'Multi-Tenant',
    icon: '🌐',
    items: [
      {
        name: 'WebsiteManagement',
        to: '/websites',
        label: 'Websites',
        icon: '🌐',
        description: 'Manage multi-tenant websites',
      },
    ],
  },
  {
    id: 'superadmin-only',
    label: 'Superadmin',
    icon: '👑',
    roles: ['superadmin'],
    items: [
      {
        name: 'SuperadminDashboard',
        to: '/admin/superadmin',
        label: 'Superadmin Dashboard',
        icon: '👑',
        description: 'Superadmin overview and controls',
      },
    ],
  },
]

/**
 * Get navigation groups filtered by user role
 */
export function getAdminNavigationGroups(userRole) {
  return adminNavigationGroups.filter(group => {
    // Filter groups by role
    if (group.roles && !group.roles.includes(userRole)) {
      return false
    }
    // Filter items within groups by role
    if (group.items) {
      group.items = group.items.filter(item => {
        if (item.roles && !item.roles.includes(userRole)) {
          return false
        }
        return true
      })
    }
    // Only return groups that have items
    return !group.items || group.items.length > 0
  })
}

/**
 * Get all navigation items as a flat list (for backward compatibility)
 */
export function getAllAdminNavigationItems(userRole) {
  const groups = getAdminNavigationGroups(userRole)
  return groups.flatMap(group => group.items || [])
}

