import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  ClipboardList,
  CreditCard,
  DollarSign,
  FileText,
  FolderOpen,
  Gauge,
  Headphones,
  Home,
  Inbox,
  KeyRound,
  LifeBuoy,
  Megaphone,
  MessageSquare,
  Newspaper,
  Percent,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Star,
  Users,
  Wallet,
  Wrench,
} from "@lucide/vue";
import type { Component } from "vue";
import type { UserRole } from "@/types/roles";

export interface NavItem {
  label: string;
  to: string;
  icon: Component;
}

export const roleHome: Record<UserRole, string> = {
  superadmin: "/superadmin",
  admin: "/admin",
  writer: "/writer",
  client: "/client",
  editor: "/editor",
  support: "/support",
};

export const navigationByRole: Record<UserRole, NavItem[]> = {
  superadmin: [
    { label: "Command", to: "/superadmin", icon: ShieldCheck },
    { label: "Tenants", to: "/superadmin/tenants", icon: BriefcaseBusiness },
    { label: "Ops Intel", to: "/superadmin/ops", icon: BarChart3 },
    { label: "Activity", to: "/superadmin/activity", icon: Activity },
    { label: "Orders", to: "/superadmin/orders", icon: ClipboardList },
    { label: "Writers", to: "/superadmin/writers", icon: Users },
    { label: "Clients", to: "/superadmin/clients", icon: Users },
    { label: "Finance", to: "/superadmin/finance", icon: CreditCard },
    { label: "Payments", to: "/superadmin/payments", icon: CreditCard },
    { label: "Wallets", to: "/superadmin/wallets", icon: Wallet },
    { label: "Access", to: "/superadmin/access", icon: KeyRound },
    { label: "Comms", to: "/superadmin/communications", icon: Megaphone },
    { label: "Growth", to: "/superadmin/growth", icon: Percent },
    { label: "Publishing", to: "/superadmin/publishing", icon: Newspaper },
    { label: "Files", to: "/superadmin/files", icon: FolderOpen },
    { label: "Analytics", to: "/superadmin/analytics", icon: BarChart3 },
    { label: "Settings", to: "/superadmin/settings", icon: Settings },
    { label: "Support", to: "/superadmin/support", icon: LifeBuoy },
    { label: "Config Hub", to: "/superadmin/config", icon: Wrench },
  ],
  admin: [
    { label: "Operations", to: "/admin", icon: Gauge },
    { label: "Ops Intel", to: "/admin/ops", icon: BarChart3 },
    { label: "Activity", to: "/admin/activity", icon: Activity },
    { label: "Orders", to: "/admin/orders", icon: ClipboardList },
    { label: "Bids", to: "/admin/bids", icon: DollarSign },
    { label: "Classes", to: "/admin/classes", icon: BookOpen },
    { label: "Special Orders", to: "/admin/special-orders", icon: Sparkles },
    { label: "Disputes", to: "/admin/disputes", icon: ShieldAlert },
    { label: "Reviews", to: "/admin/reviews", icon: Star },
    { label: "Writers", to: "/admin/writers", icon: Users },
    { label: "Clients", to: "/admin/clients", icon: Users },
    { label: "Payments", to: "/admin/payments", icon: CreditCard },
    { label: "Wallets", to: "/admin/wallets", icon: Wallet },
    { label: "Access", to: "/admin/access", icon: KeyRound },
    { label: "Comms", to: "/admin/communications", icon: Megaphone },
    { label: "Growth", to: "/admin/growth", icon: Percent },
    { label: "Publishing", to: "/admin/publishing", icon: Newspaper },
    { label: "Files", to: "/admin/files", icon: FolderOpen },
    { label: "Analytics", to: "/admin/analytics", icon: BarChart3 },
    { label: "Settings", to: "/admin/settings", icon: Settings },
    { label: "Support", to: "/admin/support", icon: LifeBuoy },
    { label: "Config Hub", to: "/admin/config", icon: Wrench },
  ],
  writer: [
    { label: "Workspace", to: "/writer", icon: Home },
    { label: "Activity", to: "/writer/activity", icon: Activity },
    { label: "Available", to: "/writer/available", icon: Inbox },
    { label: "Assignments", to: "/writer/assignments", icon: ClipboardList },
    { label: "Classes", to: "/writer/classes", icon: BookOpen },
    { label: "Earnings", to: "/writer/earnings", icon: Wallet },
    { label: "Messages", to: "/writer/messages", icon: MessageSquare },
    { label: "Notifications", to: "/writer/notifications", icon: Bell },
  ],
  client: [
    { label: "Home", to: "/client", icon: Home },
    { label: "Activity", to: "/client/activity", icon: Activity },
    { label: "Orders", to: "/client/orders", icon: ClipboardList },
    { label: "New Order", to: "/client/new-order", icon: FileText },
    { label: "Classes", to: "/client/classes", icon: BookOpen },
    { label: "Special Orders", to: "/client/special-orders", icon: Sparkles },
    { label: "Disputes", to: "/client/disputes", icon: ShieldAlert },
    { label: "Wallet", to: "/client/wallet", icon: Wallet },
    { label: "Messages", to: "/client/messages", icon: MessageSquare },
    { label: "Support", to: "/client/support", icon: LifeBuoy },
    { label: "Notifications", to: "/client/notifications", icon: Bell },
  ],
  editor: [
    { label: "Desk", to: "/editor", icon: Home },
    { label: "Activity", to: "/editor/activity", icon: Activity },
    { label: "QA Queue", to: "/editor/qa", icon: ClipboardList },
    { label: "Publishing", to: "/editor/publishing", icon: Newspaper },
    { label: "Workload", to: "/editor/workload", icon: Gauge },
    { label: "Analytics", to: "/editor/analytics", icon: BarChart3 },
    { label: "Messages", to: "/editor/messages", icon: MessageSquare },
    { label: "Notifications", to: "/editor/notifications", icon: Bell },
    { label: "Settings", to: "/editor/config", icon: Wrench },
  ],
  support: [
    { label: "Queue", to: "/support", icon: Headphones },
    { label: "Activity", to: "/support/activity", icon: Activity },
    { label: "Tickets", to: "/support/tickets", icon: LifeBuoy },
    { label: "Orders", to: "/support/orders", icon: ClipboardList },
    { label: "Publishing", to: "/support/publishing", icon: Newspaper },
    { label: "Escalations", to: "/support/escalations", icon: ShieldCheck },
    { label: "Saved Replies", to: "/support/replies", icon: MessageSquare },
    { label: "Messages", to: "/support/messages", icon: MessageSquare },
    { label: "Notifications", to: "/support/notifications", icon: Bell },
    { label: "Settings", to: "/support/config", icon: Wrench },
  ],
};
