import {
  Activity,
  Ban,
  FileEdit,
  ImageIcon,
  GitBranch,
  AlertTriangle,
  BarChart3,
  LineChart,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardList,
  CreditCard,
  DollarSign,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  Mail,
  Medal,
  Receipt,
  FolderOpen,
  Gauge,
  Headphones,
  Home,
  Inbox,
  KeyRound,
  LifeBuoy,
  Megaphone,
  MessageSquare,
  Newspaper,
  Percent,
  RotateCcw,
  Scale,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Radio,
  Brain,
  Sparkles,
  Star,
  TrendingUp,
  User,
  UserCog,
  Users,
  Users2,
  Wallet,
  Wrench,
  Lightbulb,
} from "@lucide/vue";
import type { Component } from "vue";
import type { UserRole } from "@/types/roles";

export interface NavItem {
  label: string;
  to: string;
  icon: Component;
  separator?: boolean;
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

export const roleHome: Record<UserRole, string> = {
  superadmin: "/superadmin",
  admin: "/admin",
  writer: "/writer",
  client: "/client",
  editor: "/editor",
  support: "/support",
};

export const navigationByRole: Record<UserRole, NavItem[]> = {
  superadmin: [
    { label: "Command", to: "/superadmin", icon: ShieldCheck },
    { label: "Tenants", to: "/superadmin/tenants", icon: BriefcaseBusiness },
    { label: "Command Center", to: "/superadmin/operations", icon: Gauge },
    { label: "Ops Intel", to: "/superadmin/ops", icon: BarChart3 },
    { label: "Feedback", to: "/superadmin/feedback", icon: Lightbulb },
    { label: "What's new", to: "/superadmin/changelog", icon: Newspaper },
    { label: "Activity", to: "/superadmin/activity", icon: Activity },
    { label: "Audit Log", to: "/superadmin/audit", icon: ShieldAlert },
    { label: "Trust Center", to: "/superadmin/trust-center", icon: ShieldCheck },
    { label: "Event System", to: "/superadmin/event-system", icon: Radio },
    { label: "Orders", to: "/superadmin/orders", icon: ClipboardList },
    { label: "Adjustments", to: "/superadmin/adjustments", icon: AlertTriangle },
    { label: "Classes", to: "/superadmin/classes", icon: BookOpen },
    { label: "Special Orders", to: "/superadmin/special-orders", icon: Sparkles },
    { label: "Class Configs", to: "/superadmin/class-config", icon: Settings },
    { label: "SPO-Configs", to: "/superadmin/special-order-config", icon: Wrench },
    { label: "Writers", to: "/superadmin/writers", icon: Users },
    { label: "Applications", to: "/superadmin/writer-applications", icon: FileText },
    { label: "Vetting", to: "/superadmin/writer-vetting", icon: GraduationCap },
    { label: "Writer Pay", to: "/superadmin/writer-pay", icon: DollarSign },
    { label: "Writer Resources", to: "/superadmin/writer-resources", icon: FolderOpen },
    { label: "Clients", to: "/superadmin/clients", icon: Users },
    { label: "Editors", to: "/superadmin/editors", icon: FileEdit },
    { label: "Support Staff", to: "/superadmin/support-staff", icon: Headphones },
    { label: "All Users", to: "/superadmin/access", icon: UserCog },
    { label: "Finance", to: "/superadmin/finance", icon: CreditCard },
    { label: "Payment Disclosure", to: "/superadmin/payment-disclosure", icon: Receipt },
    { label: "Payment Reminders", to: "/superadmin/payment-reminders", icon: Bell },
    { label: "Refunds", to: "/superadmin/refunds", icon: RotateCcw },
    { label: "Compensation", to: "/superadmin/compensation", icon: TrendingUp },
    { label: "Wallets", to: "/superadmin/wallets", icon: Wallet },
    { label: "Ledger", to: "/superadmin/ledger", icon: Scale },
    { label: "Comms", to: "/superadmin/communications", icon: Megaphone },
    { label: "Email", to: "/superadmin/email", icon: Mail },
    { label: "Growth", to: "/superadmin/growth", icon: Percent },
    { label: "Loyalty", to: "/superadmin/loyalty", icon: Gift },
    { label: "Rewards", to: "/superadmin/rewards", icon: Medal },
    { label: "Reputation", to: "/superadmin/reputation", icon: ShieldCheck },
    { label: "Fin. Center", to: "/superadmin/financials", icon: Activity },
    { label: "Fin. Events", to: "/superadmin/financial-events", icon: Activity },
    { label: "Discounts", to: "/superadmin/discounts", icon: Percent },
    { label: "Holidays", to: "/superadmin/holidays", icon: CalendarDays },
    { label: "Publishing", to: "/superadmin/publishing", icon: Newspaper },
    { label: "Newsletters", to: "/superadmin/newsletters", icon: Mail },
    { label: "Guides", to: "/superadmin/guides", icon: BookOpen },
    { label: "Content", to: "/superadmin/content", icon: FileEdit },
    { label: "Images", to: "/superadmin/images", icon: ImageIcon },
    { label: "Content Graph", to: "/superadmin/content-graph", icon: GitBranch },
    { label: "Files", to: "/superadmin/files", icon: FolderOpen },
    { label: "Analytics", to: "/superadmin/analytics", icon: BarChart3 },
    { label: "SEO & Intelligence", to: "/superadmin/seo-intelligence", icon: Brain },
    { label: "Charts", to: "/superadmin/charts", icon: LineChart },
    { label: "Website", to: "/superadmin/website", icon: Globe },
    { label: "Settings", to: "/superadmin/settings", icon: Settings, separator: true },
    { label: "Support", to: "/superadmin/support", icon: LifeBuoy },
    { label: "Config Hub", to: "/superadmin/config", icon: Wrench },
  ],
  admin: [
    { label: "Operations", to: "/admin", icon: Gauge },
    { label: "Command Center", to: "/admin/operations", icon: ShieldAlert },
    { label: "Ops Intel", to: "/admin/ops", icon: BarChart3 },
    { label: "Activity", to: "/admin/activity", icon: Activity },
    { label: "Orders", to: "/admin/orders", icon: ClipboardList },
    { label: "Adjustments", to: "/admin/adjustments", icon: AlertTriangle },
    { label: "Bids", to: "/admin/bids", icon: DollarSign },
    { label: "Classes", to: "/admin/classes", icon: BookOpen },
    { label: "Special Orders", to: "/admin/special-orders", icon: Sparkles },
    { label: "Class Configs", to: "/admin/class-config", icon: Settings },
    { label: "SPO-Configs", to: "/admin/special-order-config", icon: Wrench },
    { label: "Disputes", to: "/admin/disputes", icon: ShieldAlert },
    { label: "Cancellations", to: "/admin/cancellation-queue", icon: Ban },
    { label: "Reviews", to: "/admin/reviews", icon: Star },
    { label: "Writers", to: "/admin/writers", icon: Users },
    { label: "Applications", to: "/admin/writer-applications", icon: FileText },
    { label: "Vetting", to: "/admin/writer-vetting", icon: GraduationCap },
    { label: "Writer Pay", to: "/admin/writer-pay", icon: DollarSign },
    { label: "Writer Resources", to: "/admin/writer-resources", icon: FolderOpen },
    { label: "Clients", to: "/admin/clients", icon: Users },
    { label: "Editors", to: "/admin/editors", icon: FileEdit },
    { label: "Support Staff", to: "/admin/support-staff", icon: Headphones },
    { label: "All Users", to: "/admin/access", icon: UserCog },
    { label: "Payments", to: "/admin/payments", icon: CreditCard },

    { label: "Payment Disclosure", to: "/admin/payment-disclosure", icon: Receipt },
    { label: "Payment Reminders", to: "/admin/payment-reminders", icon: Bell },
    { label: "Refunds", to: "/admin/refunds", icon: RotateCcw },
    { label: "Compensation", to: "/admin/compensation", icon: TrendingUp },
    { label: "Wallets", to: "/admin/wallets", icon: Wallet },
    { label: "Ledger", to: "/admin/ledger", icon: Scale },
    { label: "Comms", to: "/admin/communications", icon: Megaphone },
    { label: "Feedback", to: "/admin/feedback", icon: Lightbulb },
    { label: "What's new", to: "/admin/changelog", icon: Newspaper },
    { label: "Email", to: "/admin/email", icon: Mail },
    { label: "Growth", to: "/admin/growth", icon: Percent },
    { label: "Loyalty", to: "/admin/loyalty", icon: Gift },
    { label: "Rewards", to: "/admin/rewards", icon: Medal },
    { label: "Reputation", to: "/admin/reputation", icon: ShieldCheck },
    { label: "Audit Log", to: "/admin/audit", icon: ShieldAlert },
    { label: "Trust Center", to: "/admin/trust-center", icon: ShieldCheck },
    { label: "Event System", to: "/admin/event-system", icon: Radio },
    { label: "Fin. Center", to: "/admin/financials", icon: Activity },
    { label: "Fin. Events", to: "/admin/financial-events", icon: Activity },
    { label: "Discounts", to: "/admin/discounts", icon: Percent },
    { label: "Holidays", to: "/admin/holidays", icon: CalendarDays },
    { label: "Publishing", to: "/admin/publishing", icon: Newspaper },
    { label: "Newsletters", to: "/admin/newsletters", icon: Mail },
    { label: "Guides", to: "/admin/guides", icon: BookOpen },
    { label: "Content", to: "/admin/content", icon: FileEdit },
    { label: "Images", to: "/admin/images", icon: ImageIcon },
    { label: "Content Graph", to: "/admin/content-graph", icon: GitBranch },
    { label: "Files", to: "/admin/files", icon: FolderOpen },
    { label: "Analytics", to: "/admin/analytics", icon: BarChart3 },
    { label: "SEO & Intelligence", to: "/admin/seo-intelligence", icon: Brain },
    { label: "Charts", to: "/admin/charts", icon: LineChart },
    { label: "Website", to: "/admin/website", icon: Globe },
    { label: "Settings", to: "/admin/settings", icon: Settings, separator: true },
    { label: "Support", to: "/admin/support", icon: LifeBuoy },
    { label: "Config Hub", to: "/admin/config", icon: Wrench },
  ],
  writer: [
    { label: "Workspace", to: "/writer", icon: Home },
    { label: "Activity", to: "/writer/activity", icon: Activity },
    { label: "Available", to: "/writer/available", icon: Inbox },
    { label: "Assignments", to: "/writer/assignments", icon: ClipboardList },
    { label: "Classes", to: "/writer/classes", icon: BookOpen },
    { label: "Special Orders", to: "/writer/special-orders", icon: Sparkles },
    { label: "Earnings", to: "/writer/earnings", icon: Wallet },
    { label: "Charts", to: "/writer/charts", icon: LineChart },
    { label: "Calendar", to: "/writer/calendar", icon: CalendarDays },
    { label: "Bids", to: "/writer/bids", icon: Send },
    { label: "Fines", to: "/writer/fines", icon: AlertTriangle },
    { label: "Resources", to: "/writer/resources", icon: FolderOpen },
    { label: "Vetting", to: "/writer/vetting", icon: GraduationCap },
    { label: "Feedback", to: "/writer/feedback", icon: Lightbulb },
    { label: "What's new", to: "/writer/changelog", icon: Newspaper },
    { label: "Messages", to: "/writer/messages", icon: MessageSquare },
    { label: "Announcements", to: "/writer/announcements", icon: Megaphone },
    { label: "Notifications", to: "/writer/notifications", icon: Bell },
    { label: "Guides", to: "/writer/guides", icon: BookOpen },
    { label: "Account", to: "/writer/account", icon: User, separator: true },
  ],
  client: [
    { label: "Home", to: "/client", icon: Home },
    { label: "Activity", to: "/client/activity", icon: Activity },
    { label: "Orders", to: "/client/orders", icon: ClipboardList },
    { label: "New Order", to: "/client/new-order", icon: FileText },
    { label: "Classes", to: "/client/classes", icon: BookOpen },
    { label: "Special Orders", to: "/client/special-orders", icon: Sparkles },
    { label: "Disputes", to: "/client/disputes", icon: ShieldAlert },
    { label: "Wallet", to: "/client/wallet", icon: Wallet },
    { label: "Billing", to: "/client/billing", icon: Receipt },
    { label: "Loyalty", to: "/client/loyalty", icon: Star },
    { label: "Discounts", to: "/client/discounts", icon: Percent },
    { label: "Charts", to: "/client/charts", icon: LineChart },
    { label: "Referrals", to: "/client/referrals", icon: Users2 },
    { label: "Feedback", to: "/client/feedback", icon: Lightbulb },
    { label: "Rate Us", to: "/client/review", icon: Star },
    { label: "Subscriptions", to: "/client/subscriptions", icon: Bell },
    { label: "What's new", to: "/client/changelog", icon: Newspaper },
    { label: "Messages", to: "/client/messages", icon: MessageSquare },
    { label: "Announcements", to: "/client/announcements", icon: Megaphone },
    { label: "Support", to: "/client/support", icon: LifeBuoy },
    { label: "Notifications", to: "/client/notifications", icon: Bell },
    { label: "Guides", to: "/client/guides", icon: BookOpen },
    { label: "Account", to: "/client/account", icon: User, separator: true },
  ],
  editor: [
    { label: "Desk", to: "/editor", icon: Home },
    { label: "Activity", to: "/editor/activity", icon: Activity },
    { label: "QA Queue", to: "/editor/qa", icon: ClipboardList },
    { label: "Adjustments", to: "/editor/adjustments", icon: AlertTriangle },
    { label: "Publishing", to: "/editor/publishing", icon: Newspaper },
    { label: "Content", to: "/editor/content", icon: FileEdit },
    { label: "Images", to: "/editor/images", icon: ImageIcon },
    { label: "Content Graph", to: "/editor/content-graph", icon: GitBranch },
    { label: "Workload", to: "/editor/workload", icon: Gauge },
    { label: "Analytics", to: "/editor/analytics", icon: BarChart3 },
    { label: "Messages", to: "/editor/messages", icon: MessageSquare },
    { label: "Announcements", to: "/editor/announcements", icon: Megaphone },
    { label: "Notifications", to: "/editor/notifications", icon: Bell },
    { label: "Guides", to: "/editor/guides", icon: BookOpen },
    { label: "Settings", to: "/editor/config", icon: Wrench, separator: true },
    { label: "Account", to: "/editor/account", icon: User },
  ],
  support: [
    { label: "Queue", to: "/support", icon: Headphones },
    { label: "Activity", to: "/support/activity", icon: Activity },
    { label: "Tickets", to: "/support/tickets", icon: LifeBuoy },
    { label: "Orders", to: "/support/orders", icon: ClipboardList },
    { label: "Adjustments", to: "/support/adjustments", icon: AlertTriangle },
    { label: "Classes", to: "/support/classes", icon: BookOpen },
    { label: "Special Orders", to: "/support/special-orders", icon: Sparkles },
    { label: "Publishing", to: "/support/publishing", icon: Newspaper },
    { label: "Content", to: "/support/content", icon: FileEdit },
    { label: "Escalations", to: "/support/escalations", icon: ShieldCheck },
    { label: "Saved Replies", to: "/support/replies", icon: MessageSquare },
    { label: "Messages", to: "/support/messages", icon: MessageSquare },
    { label: "Announcements", to: "/support/announcements", icon: Megaphone },
    { label: "Notifications", to: "/support/notifications", icon: Bell },
    { label: "Charts", to: "/support/charts", icon: LineChart },
    { label: "Guides", to: "/support/guides", icon: BookOpen },
    { label: "Settings", to: "/support/config", icon: Wrench, separator: true },
    { label: "Account", to: "/support/account", icon: User },
  ],
};

export const groupedNavigationByRole: Record<UserRole, NavGroup[]> = {
  superadmin: [
    { label: "Command", items: [
      { label: "Command", to: "/superadmin", icon: ShieldCheck },
      { label: "Tenants", to: "/superadmin/tenants", icon: BriefcaseBusiness },
      { label: "Command Center", to: "/superadmin/operations", icon: Gauge },
      { label: "Ops Intel", to: "/superadmin/ops", icon: BarChart3 },
      { label: "Feedback", to: "/superadmin/feedback", icon: Lightbulb },
      { label: "What's new", to: "/superadmin/changelog", icon: Newspaper },
      { label: "Activity", to: "/superadmin/activity", icon: Activity },
      { label: "Audit Log", to: "/superadmin/audit", icon: ShieldAlert },
      { label: "Trust Center", to: "/superadmin/trust-center", icon: ShieldCheck },
      { label: "Event System", to: "/superadmin/event-system", icon: Radio },
    ]},
    { label: "Work", items: [
      { label: "Orders", to: "/superadmin/orders", icon: ClipboardList },
      { label: "Adjustments", to: "/superadmin/adjustments", icon: AlertTriangle },
      { label: "Classes", to: "/superadmin/classes", icon: BookOpen },
      { label: "Special Orders", to: "/superadmin/special-orders", icon: Sparkles },
    ]},
    { label: "People", items: [
      { label: "Writers", to: "/superadmin/writers", icon: Users },
      { label: "Applications", to: "/superadmin/writer-applications", icon: FileText },
      { label: "Vetting", to: "/superadmin/writer-vetting", icon: GraduationCap },
      { label: "Writer Pay", to: "/superadmin/writer-pay", icon: DollarSign },
      { label: "Writer Resources", to: "/superadmin/writer-resources", icon: FolderOpen },
      { label: "Clients", to: "/superadmin/clients", icon: Users },
      { label: "Editors", to: "/superadmin/editors", icon: FileEdit },
      { label: "Support Staff", to: "/superadmin/support-staff", icon: Headphones },
      { label: "All Users", to: "/superadmin/access", icon: UserCog },
    ]},
    { label: "Finance", items: [
      { label: "Finance", to: "/superadmin/finance", icon: CreditCard },
      { label: "Payment Disclosure", to: "/superadmin/payment-disclosure", icon: Receipt },
      { label: "Payment Reminders", to: "/superadmin/payment-reminders", icon: Bell },
      { label: "Refunds", to: "/superadmin/refunds", icon: RotateCcw },
      { label: "Compensation", to: "/superadmin/compensation", icon: TrendingUp },
      { label: "Wallets", to: "/superadmin/wallets", icon: Wallet },
      { label: "Ledger", to: "/superadmin/ledger", icon: Scale },
      { label: "Fin. Center", to: "/superadmin/financials", icon: Activity },
      { label: "Fin. Events", to: "/superadmin/financial-events", icon: Activity },
    ]},
    { label: "Growth", items: [
      { label: "Growth", to: "/superadmin/growth", icon: Percent },
      { label: "Loyalty", to: "/superadmin/loyalty", icon: Gift },
      { label: "Rewards", to: "/superadmin/rewards", icon: Medal },
      { label: "Reputation", to: "/superadmin/reputation", icon: ShieldCheck },
      { label: "Discounts", to: "/superadmin/discounts", icon: Percent },
    ]},
    { label: "Platform", items: [
      { label: "Comms", to: "/superadmin/communications", icon: Megaphone },
      { label: "Email", to: "/superadmin/email", icon: Mail },
      { label: "Holidays", to: "/superadmin/holidays", icon: CalendarDays },
      { label: "Publishing", to: "/superadmin/publishing", icon: Newspaper },
      { label: "Newsletters", to: "/superadmin/newsletters", icon: Mail },
      { label: "Guides", to: "/superadmin/guides", icon: BookOpen },
      { label: "Content", to: "/superadmin/content", icon: FileEdit },
      { label: "Content Graph", to: "/superadmin/content-graph", icon: GitBranch },
      { label: "Files", to: "/superadmin/files", icon: FolderOpen },
      { label: "Analytics", to: "/superadmin/analytics", icon: BarChart3 },
      { label: "SEO & Intelligence", to: "/superadmin/seo-intelligence", icon: Brain },
      { label: "Charts", to: "/superadmin/charts", icon: LineChart },
      { label: "Website", to: "/superadmin/website", icon: Globe },
    ]},
    { label: "Config", items: [
      { label: "Settings", to: "/superadmin/settings", icon: Settings },
      { label: "Class Configs", to: "/superadmin/class-config", icon: BookOpen },
      { label: "SPO-Configs", to: "/superadmin/special-order-config", icon: Sparkles },
      { label: "Support", to: "/superadmin/support", icon: LifeBuoy },
      { label: "Config Hub", to: "/superadmin/config", icon: Wrench },
      { label: "Portal Definitions", to: "/superadmin/portal-definitions", icon: Globe },
    ]},
  ],
  admin: [
    { label: "Operations", items: [
      { label: "Operations", to: "/admin", icon: Gauge },
      { label: "Command Center", to: "/admin/operations", icon: ShieldAlert },
      { label: "Ops Intel", to: "/admin/ops", icon: BarChart3 },
      { label: "Activity", to: "/admin/activity", icon: Activity },
      { label: "What's new", to: "/admin/changelog", icon: Newspaper },
    ]},
    { label: "Work", items: [
      { label: "Orders", to: "/admin/orders", icon: ClipboardList },
      { label: "Adjustments", to: "/admin/adjustments", icon: AlertTriangle },
      { label: "Bids", to: "/admin/bids", icon: DollarSign },
      { label: "Classes", to: "/admin/classes", icon: BookOpen },
      { label: "Special Orders", to: "/admin/special-orders", icon: Sparkles },
      { label: "Disputes", to: "/admin/disputes", icon: ShieldAlert },
      { label: "Cancellations", to: "/admin/cancellation-queue", icon: Ban },
      { label: "Reviews", to: "/admin/reviews", icon: Star },
    ]},
    { label: "People", items: [
      { label: "Writers", to: "/admin/writers", icon: Users },
      { label: "Applications", to: "/admin/writer-applications", icon: FileText },
      { label: "Vetting", to: "/admin/writer-vetting", icon: GraduationCap },
      { label: "Writer Pay", to: "/admin/writer-pay", icon: DollarSign },
      { label: "Writer Resources", to: "/admin/writer-resources", icon: FolderOpen },
      { label: "Clients", to: "/admin/clients", icon: Users },
      { label: "Editors", to: "/admin/editors", icon: FileEdit },
      { label: "Support Staff", to: "/admin/support-staff", icon: Headphones },
      { label: "All Users", to: "/admin/access", icon: UserCog },
    ]},
    { label: "Finance", items: [
      { label: "Payments", to: "/admin/payments", icon: CreditCard },
      { label: "Payment Disclosure", to: "/admin/payment-disclosure", icon: Receipt },
      { label: "Payment Reminders", to: "/admin/payment-reminders", icon: Bell },
      { label: "Refunds", to: "/admin/refunds", icon: RotateCcw },
      { label: "Compensation", to: "/admin/compensation", icon: TrendingUp },
      { label: "Wallets", to: "/admin/wallets", icon: Wallet },
      { label: "Ledger", to: "/admin/ledger", icon: Scale },
      { label: "Fin. Center", to: "/admin/financials", icon: Activity },
      { label: "Fin. Events", to: "/admin/financial-events", icon: Activity },
    ]},
    { label: "Communications", items: [
      { label: "Comms", to: "/admin/communications", icon: Megaphone },
      { label: "Feedback", to: "/admin/feedback", icon: Lightbulb },
      { label: "Email", to: "/admin/email", icon: Mail },
    ]},
    { label: "Growth", items: [
      { label: "Growth", to: "/admin/growth", icon: Percent },
      { label: "Loyalty", to: "/admin/loyalty", icon: Gift },
      { label: "Rewards", to: "/admin/rewards", icon: Medal },
      { label: "Reputation", to: "/admin/reputation", icon: ShieldCheck },
      { label: "Discounts", to: "/admin/discounts", icon: Percent },
    ]},
    { label: "Security", items: [
      { label: "Audit Log", to: "/admin/audit", icon: ShieldAlert },
      { label: "Trust Center", to: "/admin/trust-center", icon: ShieldCheck },
      { label: "Event System", to: "/admin/event-system", icon: Radio },
    ]},
    { label: "Platform", items: [
      { label: "Holidays", to: "/admin/holidays", icon: CalendarDays },
      { label: "Publishing", to: "/admin/publishing", icon: Newspaper },
      { label: "Newsletters", to: "/admin/newsletters", icon: Mail },
      { label: "Guides", to: "/admin/guides", icon: BookOpen },
      { label: "Content", to: "/admin/content", icon: FileEdit },
      { label: "Content Graph", to: "/admin/content-graph", icon: GitBranch },
      { label: "Files", to: "/admin/files", icon: FolderOpen },
      { label: "Analytics", to: "/admin/analytics", icon: BarChart3 },
      { label: "SEO & Intelligence", to: "/admin/seo-intelligence", icon: Brain },
      { label: "Charts", to: "/admin/charts", icon: LineChart },
      { label: "Website", to: "/admin/website", icon: Globe },
    ]},
    { label: "Config", items: [
      { label: "Settings", to: "/admin/settings", icon: Settings },
      { label: "Class Configs", to: "/admin/class-config", icon: BookOpen },
      { label: "SPO-Configs", to: "/admin/special-order-config", icon: Sparkles },
      { label: "Support", to: "/admin/support", icon: LifeBuoy },
      { label: "Config Hub", to: "/admin/config", icon: Wrench },
    ]},
  ],
  writer: [
    { label: "Work", items: [
      { label: "Workspace", to: "/writer", icon: Home },
      { label: "Available", to: "/writer/available", icon: Inbox },
      { label: "Assignments", to: "/writer/assignments", icon: ClipboardList },
      { label: "Special Orders", to: "/writer/special-orders", icon: Sparkles },
    ]},
    { label: "Learning", items: [
      { label: "Classes", to: "/writer/classes", icon: BookOpen },
      { label: "Resources", to: "/writer/resources", icon: FolderOpen },
      { label: "Guides", to: "/writer/guides", icon: BookOpen },
      { label: "Vetting", to: "/writer/vetting", icon: GraduationCap },
      { label: "Feedback", to: "/writer/feedback", icon: Lightbulb },
      { label: "What's new", to: "/writer/changelog", icon: Newspaper },
    ]},
    { label: "Finance", items: [
      { label: "Earnings", to: "/writer/earnings", icon: Wallet },
      { label: "Charts", to: "/writer/charts", icon: LineChart },
      { label: "Bids", to: "/writer/bids", icon: Send },
      { label: "Fines", to: "/writer/fines", icon: AlertTriangle },
    ]},
    { label: "Schedule", items: [
      { label: "Calendar", to: "/writer/calendar", icon: CalendarDays },
      { label: "Activity", to: "/writer/activity", icon: Activity },
    ]},
    { label: "Communication", items: [
      { label: "Messages", to: "/writer/messages", icon: MessageSquare },
      { label: "Announcements", to: "/writer/announcements", icon: Megaphone },
      { label: "Notifications", to: "/writer/notifications", icon: Bell },
    ]},
  ],
  client: [
    { label: "Home", items: [
      { label: "Home", to: "/client", icon: Home },
      { label: "Activity", to: "/client/activity", icon: Activity },
    ]},
    { label: "Orders", items: [
      { label: "My Orders", to: "/client/orders", icon: ClipboardList },
      { label: "New Order", to: "/client/new-order", icon: FileText },
      { label: "Classes", to: "/client/classes", icon: BookOpen },
      { label: "Special Orders", to: "/client/special-orders", icon: Sparkles },
    ]},
    { label: "Finance", items: [
      { label: "Wallet", to: "/client/wallet", icon: Wallet },
      { label: "Billing", to: "/client/billing", icon: Receipt },
      { label: "Loyalty", to: "/client/loyalty", icon: Star },
      { label: "Charts", to: "/client/charts", icon: LineChart },
      { label: "Referrals", to: "/client/referrals", icon: Users2 },
    ]},
    { label: "Support", items: [
      { label: "Disputes", to: "/client/disputes", icon: ShieldAlert },
      { label: "Messages", to: "/client/messages", icon: MessageSquare },
      { label: "Announcements", to: "/client/announcements", icon: Megaphone },
      { label: "Support", to: "/client/support", icon: LifeBuoy },
      { label: "Notifications", to: "/client/notifications", icon: Bell },
      { label: "Feedback", to: "/client/feedback", icon: Lightbulb },
      { label: "Rate Us", to: "/client/review", icon: Star },
      { label: "Guides", to: "/client/guides", icon: BookOpen },
      { label: "What's new", to: "/client/changelog", icon: Newspaper },
    ]},
  ],
  editor: [
    { label: "Work", items: [
      { label: "Desk", to: "/editor", icon: Home },
      { label: "Activity", to: "/editor/activity", icon: Activity },
      { label: "QA Queue", to: "/editor/qa", icon: ClipboardList },
      { label: "Adjustments", to: "/editor/adjustments", icon: AlertTriangle },
      { label: "Publishing", to: "/editor/publishing", icon: Newspaper },
      { label: "Content", to: "/editor/content", icon: FileEdit },
      { label: "Content Graph", to: "/editor/content-graph", icon: GitBranch },
      { label: "Workload", to: "/editor/workload", icon: Gauge },
      { label: "Analytics", to: "/editor/analytics", icon: BarChart3 },
    ]},
    { label: "Communication", items: [
      { label: "Messages", to: "/editor/messages", icon: MessageSquare },
      { label: "Announcements", to: "/editor/announcements", icon: Megaphone },
      { label: "Notifications", to: "/editor/notifications", icon: Bell },
      { label: "Guides", to: "/editor/guides", icon: BookOpen },
      { label: "What's new", to: "/editor/changelog", icon: Newspaper },
    ]},
    { label: "Config", items: [
      { label: "Settings", to: "/editor/config", icon: Wrench },
      { label: "Account", to: "/editor/account", icon: User },
    ]},
  ],
  support: [
    { label: "Work", items: [
      { label: "Queue", to: "/support", icon: Headphones },
      { label: "Activity", to: "/support/activity", icon: Activity },
      { label: "Tickets", to: "/support/tickets", icon: LifeBuoy },
      { label: "Orders", to: "/support/orders", icon: ClipboardList },
      { label: "Adjustments", to: "/support/adjustments", icon: AlertTriangle },
      { label: "Classes", to: "/support/classes", icon: BookOpen },
      { label: "Special Orders", to: "/support/special-orders", icon: Sparkles },
      { label: "Escalations", to: "/support/escalations", icon: ShieldCheck },
      { label: "Saved Replies", to: "/support/replies", icon: MessageSquare },
    ]},
    { label: "Communication", items: [
      { label: "Messages", to: "/support/messages", icon: MessageSquare },
      { label: "Announcements", to: "/support/announcements", icon: Megaphone },
      { label: "Notifications", to: "/support/notifications", icon: Bell },
    ]},
    { label: "Config", items: [
      { label: "Charts", to: "/support/charts", icon: LineChart },
      { label: "Settings", to: "/support/config", icon: Wrench },
      { label: "Account", to: "/support/account", icon: User },
    ]},
  ],
};
