# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Client's available wallet balance.", max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency of the wallet balance.', max_length=3)),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Accumulated loyalty points.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID for external transactions (if applicable).', max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('top-up', 'Top-Up'), ('payment', 'Payment'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment'), ('referral_bonus', 'Referral Bonus'), ('loyalty_conversion', 'Loyalty Points Conversion')], help_text='Type of transaction.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount.', max_digits=12)),
                ('description', models.CharField(blank=True, help_text='Optional description.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
