# notifications_system/event_labels.py

from .notification_enums import EventType

EVENT_LABELS = {
    EventType.ORDER_ASSIGNED: "Writer Assigned to Order",
    EventType.ORDER_ON_HOLD: "Order Put on Hold",
    EventType.ORDER_COMPLETED: "Order Marked as Completed",
    EventType.ORDER_CANCELLED: "Order Cancelled",
    EventType.ORDER_REJECTED: "Order Rejected",
    EventType.ORDER_UPDATED: "Order Updated",
    EventType.ORDER_CREATED: "New Order Created",
    EventType.ORDER_PAYMENT_FAILED: "Payment Failed",
    EventType.ORDER_PAYMENT_SUCCESS: "Payment Successful",
    EventType.ORDER_REFUNDED: "Order Refunded",
    EventType.ORDER_ON_DISPUTE: "Order Entered Dispute",
    EventType.ORDER_DISPUTE_RESOLVED: "Dispute Resolved",
    EventType.ORDER_DISPUTE_ESCALATED: "Dispute Escalated",
    EventType.ORDER_DISPUTE_CLOSED: "Dispute Closed",
    EventType.ORDER_REVIEW_REQUESTED: "Client Asked to Review Order",
    EventType.ORDER_REVIEW_SUBMITTED: "Review Submitted",
    EventType.ORDER_REVIEW_APPROVED: "Review Approved",
    EventType.ORDER_REVIEW_REJECTED: "Review Rejected",
    EventType.ORDER_ARCHIVED: "Order Archived",
    EventType.ORDER_RESTORED: "Order Restored",
    EventType.ORDER_REASSIGNED: "Writer Reassigned",
    EventType.ORDER_REOPENED: "Order Reopened",
    EventType.ORDER_APPROVED: "Order Approved",
    EventType.FILE_UPLOADED: "File Uploaded",
    EventType.FILE_DELETED: "File Deleted",
    EventType.WALLET_BALANCE_LOW: "Wallet Balance is Low",
    EventType.WALLET_CREDITED: "Wallet Credited",
    EventType.WALLET_DEBITED: "Wallet Debited",
    EventType.WALLET_TRANSACTION_FAILED: "Wallet Transaction Failed",
    EventType.WALLET_TRANSACTION_SUCCESS: "Wallet Transaction Succeeded",
    EventType.WALLET_REFUND_INITIATED: "Refund Initiated",
    EventType.WALLET_REFUND_COMPLETED: "Refund Completed",
    EventType.PAYOUT_PROCESSING: "Payout Processing",
    EventType.PAYOUT_COMPLETED: "Payout Completed",
    EventType.PAYOUT_FAILED: "Payout Failed",
    EventType.PAYOUT_CANCELLED: "Payout Cancelled",
    EventType.TICKET_CREATED: "Support Ticket Created",
    EventType.TICKET_UPDATED: "Support Ticket Updated",
    EventType.TICKET_CLOSED: "Ticket Closed",
    EventType.TICKET_REOPENED: "Ticket Reopened",
    EventType.TICKET_COMMENT_ADDED: "Comment Added to Ticket",
    EventType.TICKET_COMMENT_UPDATED: "Comment Updated on Ticket",
    EventType.TICKET_COMMENT_DELETED: "Comment Deleted from Ticket",
    EventType.TICKET_ASSIGNED: "Ticket Assigned",
    EventType.TICKET_UNASSIGNED: "Ticket Unassigned",
    EventType.TICKET_ESCALATED: "Ticket Escalated",
    EventType.TICKET_RESOLVED: "Ticket Resolved",
    EventType.FEEDBACK_RECEIVED: "Feedback Received",
    EventType.PASSWORD_RESET: "Password Reset Requested",
    EventType.ACCOUNT_SUSPENDED: "Account Suspended",
    EventType.NEW_MESSAGE: "New Message",
    EventType.ORDER_RATED: "Order Rated",
    EventType.ORDER_REVIEWED: "Order Reviewed",
    EventType.WRITER_REVIEWED: "Writer Reviewed",
    EventType.ORDER_REASSIGNMENT_REQUESTED: "Reassignment Requested",
    EventType.ORDER_REASSIGNMENT_APPROVED: "Reassignment Approved",
    EventType.WRITER_SUSPENDED: "Writer Suspended",
    EventType.WRITER_SENT_ON_PROBATION: "Writer Sent on Probation",
    EventType.USER_BLACKLISTED: "User Blacklisted",
    EventType.USER_UNBLACKLISTED: "User Removed from Blacklist",
    EventType.USER_VERIFIED: "User Verified",
    EventType.USER_UNVERIFIED: "User Unverified",
    EventType.WRITER_STRIKED: "Writer Received a Strike",
    EventType.WRITER_UNSTRIKED: "Strike Removed",
    EventType.WRITER_WARNING: "Writer Warning Issued",
}