# Generated by Django 6.0.5 on 2026-05-28 08:37

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Author Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResourceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Resource Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TenantHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tenant Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TenantSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_citation_style', models.CharField(choices=[('apa7', 'APA 7th Edition'), ('mla9', 'MLA 9th Edition'), ('chicago', 'Chicago / Turabian'), ('none', 'No formal citations')], default='apa7', max_length=20)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID (G-XXXXXXXXXX)', max_length=50)),
                ('gsc_property_url', models.URLField(blank=True, help_text='Google Search Console property URL')),
                ('ga4_property_id', models.CharField(blank=True, help_text='GA4 property ID (numeric)', max_length=50)),
                ('schema_org_name', models.CharField(blank=True, help_text='Organization name for Schema.org', max_length=255)),
                ('default_og_image', models.ForeignKey(blank=True, help_text='Default Open Graph image for pages without a featured image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('schema_org_logo', models.ForeignKey(blank=True, help_text='Organization logo for Schema.org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Tenant SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for category page', max_length=60)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description for category page', max_length=160)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='wagtailcore.site')),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['-is_featured', 'display_order', 'name'],
                'unique_together': {('site', 'slug')},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ReservedSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('reason', models.CharField(blank=True, help_text="Why this slug is reserved (e.g., 'Frontend about page')", max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_slugs', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['slug'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='wagtailcore.site')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('old_slug', models.SlugField(max_length=255)),
                ('new_slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'old_slug'], name='cms_core_sl_site_id_c0ca6b_idx'), models.Index(fields=['content_type', 'object_id'], name='cms_core_sl_content_842286_idx')],
            },
        ),
    ]
