# Generated by Django 5.2.2 on 2026-06-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_core', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantseosettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Site favicon — upload a square PNG or SVG (recommended: 512×512px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='tenantseosettings',
            name='site_name',
            field=models.CharField(blank=True, help_text="Display name used in page titles and Schema.org (e.g. 'GradeCrest')", max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantseosettings',
            name='default_og_image',
            field=models.ForeignKey(blank=True, help_text='Default Open Graph image for pages without a featured image (1200×630px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
