# Generated by Django 5.2.2 on 2026-06-25 10:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Guide index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GuideArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, help_text='One-line description shown on the guides listing page.', max_length=300)),
                ('body', wagtail.fields.RichTextField(help_text='Full guide content. Use headings (H2/H3), bullet lists, numbered steps, bold/italic, links, and embedded images.')),
                ('audience', models.CharField(choices=[('all', 'All users'), ('client', 'Clients'), ('writer', 'Writers'), ('staff', 'Staff & Admins')], db_index=True, default='staff', help_text="Who can see this guide in the portal. 'Staff & Admins' covers superadmin, admin, editor, and support roles.", max_length=20)),
                ('icon', models.CharField(blank=True, default='book-open', help_text="Lucide icon name shown on the listing card (e.g. 'book-open', 'users', 'settings').", max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured guides appear prominently on the guides home screen.')),
                ('estimated_read_minutes', models.PositiveSmallIntegerField(default=5, help_text='Estimated reading time in minutes.')),
                ('pdf_attachment', models.ForeignKey(blank=True, help_text='Optional downloadable PDF — training handbooks, SOPs, checklists. Upload via Documents in the Wagtail admin sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Guide article',
                'verbose_name_plural': 'Guide articles',
            },
            bases=('wagtailcore.page',),
        ),
    ]
