# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_configs', '0002_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_review_time', models.DurationField(blank=True, help_text='Average time taken to review tasks.', null=True)),
                ('total_orders_reviewed', models.PositiveIntegerField(default=0, help_text='Total number of orders reviewed by the editor.')),
                ('late_reviews', models.PositiveIntegerField(default=0, help_text='Number of reviews completed past the deadline.')),
                ('average_quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Average quality score given by admin.', max_digits=3, null=True)),
                ('revisions_requested_count', models.PositiveIntegerField(default=0, help_text='Total number of revisions requested.')),
                ('approvals_count', models.PositiveIntegerField(default=0, help_text='Total number of orders approved for delivery.')),
                ('last_calculated_at', models.DateTimeField(blank=True, help_text='When performance metrics were last calculated.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quality score given by editor (0.00-10.00).', max_digits=3, null=True)),
                ('issues_found', models.TextField(blank=True, help_text='Issues/problems found during review.')),
                ('corrections_made', models.TextField(blank=True, help_text='Corrections/edits made by the editor.')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for writer or client.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether editor approves the work for client delivery.')),
                ('requires_revision', models.BooleanField(default=False, help_text='Whether editor requests revision from writer.')),
                ('revision_notes', models.TextField(blank=True, help_text='Notes for writer if revision is required.')),
                ('edited_files', models.JSONField(blank=True, default=list, help_text='List of file IDs that were edited/reviewed.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this review was submitted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time.')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('auto', 'Auto-Assigned'), ('manual', 'Manually Assigned'), ('claimed', 'Self-Claimed')], default='auto', help_text='How this task was assigned.', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this task was assigned.')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('unclaimed', 'Unclaimed')], default='pending', help_text='The current review status of the task.', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the editor started reviewing this task.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task was reviewed.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or feedback from the editor.', null=True)),
                ('editor_rating', models.PositiveIntegerField(blank=True, help_text='Quality rating given by admin/superadmin (1-5).', null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('claimed_task', 'Claimed Task'), ('started_review', 'Started Review'), ('submitted_review', 'Submitted Review'), ('completed_task', 'Completed Task'), ('rejected_task', 'Rejected Task'), ('unclaimed_task', 'Unclaimed Task')], help_text='Type of action performed.', max_length=50)),
                ('action', models.CharField(help_text="Description of the action performed (e.g., 'Reviewed Order').", max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the action.')),
                ('related_order', models.ForeignKey(blank=True, help_text='The order associated with this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_actions', to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EditorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the notification.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.')),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('task_assigned', 'Task Assigned'), ('task_claimed', 'Task Claimed'), ('reminder', 'Reminder'), ('urgent', 'Urgent')], default='info', help_text='Type of notification.', max_length=50)),
                ('related_order', models.ForeignKey(blank=True, help_text='Related order, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_notifications', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the editor.', max_length=255)),
                ('registration_id', models.CharField(help_text='Unique editor registration ID (e.g., Editor #12345).', max_length=50, unique=True)),
                ('email', models.EmailField(help_text="Editor's email address.", max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Editor's phone number.", max_length=15, null=True)),
                ('last_logged_in', models.DateTimeField(blank=True, help_text='The last time the editor logged in.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the editor is active.')),
                ('orders_reviewed', models.PositiveIntegerField(default=0, help_text='Total number of orders reviewed by the editor.')),
                ('can_self_assign', models.BooleanField(default=True, help_text='Whether editor can claim orders themselves.')),
                ('max_concurrent_tasks', models.PositiveIntegerField(default=5, help_text='Maximum number of concurrent editing tasks.')),
                ('expertise_paper_types', models.ManyToManyField(blank=True, help_text='Paper types this editor specializes in.', related_name='expert_editors', to='order_configs.papertype')),
                ('expertise_subjects', models.ManyToManyField(blank=True, help_text='Subjects this editor specializes in.', related_name='expert_editors', to='order_configs.subject')),
            ],
        ),
    ]
