# Generated by Django 5.0.14 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Description of the action performed (e.g., 'Reviewed Order').", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the action.')),
            ],
        ),
        migrations.CreateModel(
            name='EditorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the notification.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.')),
            ],
        ),
        migrations.CreateModel(
            name='EditorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_review_time', models.DurationField(blank=True, help_text='Average time taken to review tasks.', null=True)),
                ('total_orders_reviewed', models.PositiveIntegerField(default=0, help_text='Total number of orders reviewed by the editor.')),
                ('late_reviews', models.PositiveIntegerField(default=0, help_text='Number of reviews completed past the deadline.')),
            ],
        ),
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the editor.', max_length=255)),
                ('registration_id', models.CharField(help_text='Unique editor registration ID (e.g., Editor #12345).', max_length=50, unique=True)),
                ('email', models.EmailField(help_text="Editor's email address.", max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Editor's phone number.", max_length=15, null=True)),
                ('last_logged_in', models.DateTimeField(blank=True, help_text='The last time the editor logged in.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the editor is active.')),
                ('orders_reviewed', models.PositiveIntegerField(default=0, help_text='Total number of orders reviewed by the editor.')),
            ],
        ),
        migrations.CreateModel(
            name='EditorTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed')], default='pending', help_text='The current review status of the task.', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task was reviewed.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or feedback from the editor.', null=True)),
            ],
        ),
    ]
