# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor_management', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editoractionlog',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='The order associated with this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_actions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='editornotification',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='Related order, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_notifications', to='orders.order'),
        ),
    ]
