# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this editor profile.', limit_choices_to={'role': 'editor'}, on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='website',
            field=models.ForeignKey(help_text='The website the editor is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='websites.website'),
        ),
    ]
