# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor_management', '0002_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('writer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='writers_assigned',
            field=models.ManyToManyField(blank=True, help_text='Writers assigned to this editor.', related_name='editors', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='editorperformance',
            name='editor',
            field=models.OneToOneField(help_text='The editor whose performance is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editornotification',
            name='editor',
            field=models.ForeignKey(help_text='The editor receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='editor_based_notifications', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editoractionlog',
            name='editor',
            field=models.ForeignKey(help_text='The editor performing the action.', on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editorreviewsubmission',
            name='editor',
            field=models.ForeignKey(help_text='Editor who submitted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editorreviewsubmission',
            name='order',
            field=models.ForeignKey(help_text='Order that was reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='editor_reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this task (admin/system for auto-assigned).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, help_text='The primary editor assigned to review this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='fallback_editors',
            field=models.ManyToManyField(blank=True, help_text='Fallback editors who can access this task.', related_name='fallback_tasks', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='order',
            field=models.OneToOneField(help_text='The order being assigned for review.', on_delete=django.db.models.deletion.CASCADE, related_name='editor_assignment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='editorreviewsubmission',
            name='task_assignment',
            field=models.OneToOneField(help_text='The task assignment this review belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='review_submission', to='editor_management.editortaskassignment'),
        ),
        migrations.AddField(
            model_name='editornotification',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Related task assignment, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks_notifications', to='editor_management.editortaskassignment'),
        ),
        migrations.AddField(
            model_name='editoractionlog',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='The task assignment associated with this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='editor_management.editortaskassignment'),
        ),
        migrations.AddIndex(
            model_name='editortaskassignment',
            index=models.Index(fields=['assigned_editor', 'review_status'], name='editor_mana_assigne_4949c1_idx'),
        ),
        migrations.AddIndex(
            model_name='editortaskassignment',
            index=models.Index(fields=['review_status', 'assigned_at'], name='editor_mana_review__d3ddda_idx'),
        ),
        migrations.AddIndex(
            model_name='editortaskassignment',
            index=models.Index(fields=['order'], name='editor_mana_order_i_ba317c_idx'),
        ),
        migrations.AddIndex(
            model_name='editornotification',
            index=models.Index(fields=['editor', 'is_read', 'created_at'], name='editor_mana_editor__26de71_idx'),
        ),
        migrations.AddIndex(
            model_name='editoractionlog',
            index=models.Index(fields=['editor', 'timestamp'], name='editor_mana_editor__c84ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='editoractionlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='editor_mana_action__6efe8d_idx'),
        ),
    ]
