# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor_management', '0002_initial'),
        ('orders', '0002_initial'),
        ('websites', '0001_initial'),
        ('writer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this editor profile.', limit_choices_to={'role': 'editor'}, on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='website',
            field=models.ForeignKey(help_text='The website the editor is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='websites.website'),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='writers_assigned',
            field=models.ManyToManyField(blank=True, help_text='Writers assigned to this editor.', related_name='editors', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='editorperformance',
            name='editor',
            field=models.OneToOneField(help_text='The editor whose performance is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editornotification',
            name='editor',
            field=models.ForeignKey(help_text='The editor receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editoractionlog',
            name='editor',
            field=models.ForeignKey(help_text='The editor performing the action.', on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, help_text='The primary editor assigned to review this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='fallback_editors',
            field=models.ManyToManyField(blank=True, help_text='Fallback editors who can access this task.', related_name='fallback_tasks', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editortaskassignment',
            name='order',
            field=models.OneToOneField(help_text='The order being assigned for review.', on_delete=django.db.models.deletion.CASCADE, related_name='editor_assignment', to='orders.order'),
        ),
    ]
