# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_management', '0007_add_editornotification_fields'),
        ('order_configs', '0004_alter_englishtype_code_alter_englishtype_name_and_more'),
        ('orders', '0007_rename_orders_order_status_idx_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quality score given by editor (0.00-10.00).', max_digits=3, null=True)),
                ('issues_found', models.TextField(blank=True, help_text='Issues/problems found during review.')),
                ('corrections_made', models.TextField(blank=True, help_text='Corrections/edits made by the editor.')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for writer or client.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether editor approves the work for client delivery.')),
                ('requires_revision', models.BooleanField(default=False, help_text='Whether editor requests revision from writer.')),
                ('revision_notes', models.TextField(blank=True, help_text='Notes for writer if revision is required.')),
                ('edited_files', models.JSONField(blank=True, default=list, help_text='List of file IDs that were edited/reviewed.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this review was submitted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time.')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='editoractionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='editornotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='editortaskassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS editor_mana_editor__idx RENAME TO editor_mana_editor__c84ef2_idx;",
            reverse_sql="ALTER INDEX IF EXISTS editor_mana_editor__c84ef2_idx RENAME TO editor_mana_editor__idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS editor_mana_action__idx RENAME TO editor_mana_action__6efe8d_idx;",
            reverse_sql="ALTER INDEX IF EXISTS editor_mana_action__6efe8d_idx RENAME TO editor_mana_action__idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS editor_mana_editor__idx RENAME TO editor_mana_editor__26de71_idx;",
            reverse_sql="ALTER INDEX IF EXISTS editor_mana_editor__26de71_idx RENAME TO editor_mana_editor__idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS editor_mana_assigne_idx RENAME TO editor_mana_assigne_4949c1_idx;",
            reverse_sql="ALTER INDEX IF EXISTS editor_mana_assigne_4949c1_idx RENAME TO editor_mana_assigne_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS editor_mana_review__idx RENAME TO editor_mana_review__d3ddda_idx;",
            reverse_sql="ALTER INDEX IF EXISTS editor_mana_review__d3ddda_idx RENAME TO editor_mana_review__idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS editor_mana_order_id_idx RENAME TO editor_mana_order_i_ba317c_idx;",
            reverse_sql="ALTER INDEX IF EXISTS editor_mana_order_i_ba317c_idx RENAME TO editor_mana_order_id_idx;",
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='expertise_paper_types',
            field=models.ManyToManyField(blank=True, help_text='Paper types this editor specializes in.', related_name='expert_editors', to='order_configs.papertype'),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='expertise_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this editor specializes in.', related_name='expert_editors', to='order_configs.subject'),
        ),
        migrations.AlterField(
            model_name='editoractionlog',
            name='action',
            field=models.CharField(help_text="Description of the action performed (e.g., 'Reviewed Order').", max_length=255),
        ),
        migrations.AlterField(
            model_name='editoractionlog',
            name='action_type',
            field=models.CharField(choices=[('claimed_task', 'Claimed Task'), ('started_review', 'Started Review'), ('submitted_review', 'Submitted Review'), ('completed_task', 'Completed Task'), ('rejected_task', 'Rejected Task'), ('unclaimed_task', 'Unclaimed Task')], help_text='Type of action performed.', max_length=50),
        ),
        migrations.AddField(
            model_name='editorreviewsubmission',
            name='editor',
            field=models.ForeignKey(help_text='Editor who submitted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='editor_management.editorprofile'),
        ),
        migrations.AddField(
            model_name='editorreviewsubmission',
            name='order',
            field=models.ForeignKey(help_text='Order that was reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='editor_reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='editorreviewsubmission',
            name='task_assignment',
            field=models.OneToOneField(help_text='The task assignment this review belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='review_submission', to='editor_management.editortaskassignment'),
        ),
    ]
