# Generated by Django 5.0.14 on 2025-11-25 19:52

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """Rename indexes only if they exist."""
    db_alias = schema_editor.connection.alias
    
    # Get the actual index names from the database
    with schema_editor.connection.cursor() as cursor:
        # Check and rename indexes for editoractionlog
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editoractionlog' 
            AND indexname = 'editor_mana_editor__idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_editor__idx RENAME TO editor_mana_editor__c84ef2_idx')
        
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editoractionlog' 
            AND indexname = 'editor_mana_action__idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_action__idx RENAME TO editor_mana_action__6efe8d_idx')
        
        # Check and rename indexes for editornotification
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editornotification' 
            AND indexname = 'editor_mana_editor__idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_editor__idx RENAME TO editor_mana_editor__26de71_idx')
        
        # Check and rename indexes for editortaskassignment
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editortaskassignment' 
            AND indexname = 'editor_mana_assigne_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_assigne_idx RENAME TO editor_mana_assigne_4949c1_idx')
        
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editortaskassignment' 
            AND indexname = 'editor_mana_review__idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_review__idx RENAME TO editor_mana_review__d3ddda_idx')
        
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editortaskassignment' 
            AND indexname = 'editor_mana_order_id_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_order_id_idx RENAME TO editor_mana_order_i_ba317c_idx')


def reverse_rename_index(apps, schema_editor):
    """Reverse the index renames."""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Reverse renames for editoractionlog
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editoractionlog' 
            AND indexname = 'editor_mana_editor__c84ef2_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_editor__c84ef2_idx RENAME TO editor_mana_editor__idx')
        
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editoractionlog' 
            AND indexname = 'editor_mana_action__6efe8d_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_action__6efe8d_idx RENAME TO editor_mana_action__idx')
        
        # Reverse renames for editornotification
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editornotification' 
            AND indexname = 'editor_mana_editor__26de71_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_editor__26de71_idx RENAME TO editor_mana_editor__idx')
        
        # Reverse renames for editortaskassignment
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editortaskassignment' 
            AND indexname = 'editor_mana_assigne_4949c1_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_assigne_4949c1_idx RENAME TO editor_mana_assigne_idx')
        
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editortaskassignment' 
            AND indexname = 'editor_mana_review__d3ddda_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_review__d3ddda_idx RENAME TO editor_mana_review__idx')
        
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'editor_mana_editortaskassignment' 
            AND indexname = 'editor_mana_order_i_ba317c_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX editor_mana_order_i_ba317c_idx RENAME TO editor_mana_order_id_idx')


class Migration(migrations.Migration):

    dependencies = [
        ('editor_management', '0008_editorreviewsubmission_alter_editoractionlog_options_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_index_if_exists, reverse_rename_index),
    ]
