# Generated by Django 5.0.14 on 2025-12-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_management', '0010_rename_editor_mana_editor__idx_editor_mana_editor__c84ef2_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='editoractionlog',
            new_name='editor_mana_editor__c84ef2_idx',
            old_name='editor_mana_editor__idx',
        ),
        migrations.RenameIndex(
            model_name='editoractionlog',
            new_name='editor_mana_action__6efe8d_idx',
            old_name='editor_mana_action__idx',
        ),
        migrations.RenameIndex(
            model_name='editornotification',
            new_name='editor_mana_editor__26de71_idx',
            old_name='editor_mana_editor__idx',
        ),
        migrations.RenameIndex(
            model_name='editortaskassignment',
            new_name='editor_mana_assigne_4949c1_idx',
            old_name='editor_mana_assigne_idx',
        ),
        migrations.RenameIndex(
            model_name='editortaskassignment',
            new_name='editor_mana_review__d3ddda_idx',
            old_name='editor_mana_review__idx',
        ),
        migrations.RenameIndex(
            model_name='editortaskassignment',
            new_name='editor_mana_order_i_ba317c_idx',
            old_name='editor_mana_order_id_idx',
        ),
    ]
