# Generated by Django 5.1.5 on 2025-02-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('NOTIFICATION', 'Notification'), ('COMMUNICATION', 'Communication'), ('LOYALTY', 'Loyalty'), ('USER', 'User'), ('SYSTEM', 'System')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
