# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications_system', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_acknowledgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastacknowledgement',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_acknowledgements', to='websites.website'),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_notifications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='broadcastacknowledgement',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='notifications_system.broadcastnotification'),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='notifications_system.broadcastnotification'),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_overrides', to='websites.website'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='websites.website'),
        ),
        migrations.AddField(
            model_name='globalnotificationsystemsettings',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_system_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications_system.notification'),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationdigestqueue',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='notifications_system.notificationdigest'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['category', 'is_active'], name='notificatio_categor_ec96e8_idx'),
        ),
        migrations.AddField(
            model_name='notificationeventoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationeventoverride',
            name='event_config',
            field=models.ForeignKey(help_text='The base event config this override applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='notifications_system.notificationeventconfig'),
        ),
        migrations.AddField(
            model_name='notificationeventoverride',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Scope to a specific website. Leave null for a global override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_event_overrides', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='notifications_system.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notification_preferences', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationgroupmembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_notification_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='notifications_system.notificationgroup'),
        ),
        migrations.AddField(
            model_name='notificationgroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='delivery',
            field=models.ForeignKey(blank=True, help_text='The delivery attempt this log entry corresponds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications_system.delivery'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='notifications_system.notificationgroup'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications_system.notification'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preferences', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreferenceprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_preference_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreferenceprofile',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Null = global profile available to all websites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference_profiles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profile applied to this user. Individual fields override profile defaults.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_preferences', to='notifications_system.notificationpreferenceprofile'),
        ),
        migrations.AddField(
            model_name='notificationsuserstatus',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='notifications_system.notification'),
        ),
        migrations.AddField(
            model_name='notificationsuserstatus',
            name='pinned_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who pinned this, or null if self-pinned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_notification_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationsuserstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationsuserstatus',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_statuses', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications_system.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Null = global template. Set to override for a specific website.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='websites.website'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outbox',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='rolenotificationpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_notification_preferences', to='websites.website'),
        ),
        migrations.AddField(
            model_name='usernotificationmeta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_meta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationmeta',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_meta', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['website', 'event_type'], name='notificatio_website_636aee_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['is_active', 'scheduled_for'], name='notificatio_is_acti_97b8bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastnotification',
            unique_together={('website', 'title', 'event_type')},
        ),
        migrations.AddIndex(
            model_name='broadcastacknowledgement',
            index=models.Index(fields=['user', 'broadcast'], name='notificatio_user_id_be1b48_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastacknowledgement',
            index=models.Index(fields=['website'], name='notificatio_website_d85873_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastacknowledgement',
            unique_together={('user', 'broadcast')},
        ),
        migrations.AddIndex(
            model_name='broadcastoverride',
            index=models.Index(fields=['website', 'broadcast', 'user'], name='notificatio_website_1fff82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastoverride',
            unique_together={('website', 'broadcast', 'user')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'website', 'status'], name='notificatio_user_id_ba9714_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_key', 'website'], name='notificatio_event_k_3b21b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_digest', 'digest_group'], name='notificatio_is_dige_de555b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_b433a9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'status'], name='notificatio_priorit_6e7948_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'channel'], name='notif_deliv_status_4b00c5_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['user', 'website'], name='notif_deliv_user_id_32d9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['event_key'], name='notif_deliv_event_k_193a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='notif_deliv_status_c3596e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['notification', 'channel'], name='notif_deliv_notific_61df53_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['user', 'website', 'is_sent'], name='notificatio_user_id_ee5815_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['scheduled_for', 'is_sent'], name='notificatio_schedul_a8c223_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['user', 'event_key', 'scheduled_for'], name='notificatio_user_id_269136_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdigest',
            constraint=models.UniqueConstraint(fields=('user', 'event_key', 'scheduled_for'), name='unique_user_event_scheduled'),
        ),
        migrations.AddIndex(
            model_name='notificationdigestqueue',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_88566e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigestqueue',
            index=models.Index(fields=['digest', 'status'], name='notificatio_digest__59af3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationeventoverride',
            unique_together={('website', 'event_config')},
        ),
        migrations.AddIndex(
            model_name='notificationeventpreference',
            index=models.Index(fields=['user', 'website', 'is_enabled'], name='notificatio_user_id_b9f32e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationeventpreference',
            unique_together={('user', 'website', 'event')},
        ),
        migrations.AddIndex(
            model_name='notificationgroup',
            index=models.Index(fields=['website', 'is_active'], name='notificatio_website_f5be22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroup',
            unique_together={('website', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'website', 'status'], name='notificatio_user_id_28c6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_key', 'channel'], name='notificatio_event_k_62c223_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_38cf76_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['attempted_at'], name='notificatio_attempt_fa66fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreferenceprofile',
            unique_together={('website', 'name')},
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'website'], name='notificatio_user_id_18beec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'website')},
        ),
        migrations.AddIndex(
            model_name='notificationsuserstatus',
            index=models.Index(fields=['user', 'website', 'is_read'], name='notificatio_user_id_8e9e54_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationsuserstatus',
            index=models.Index(fields=['user', 'website', 'is_acknowledged'], name='notificatio_user_id_e4ac9a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationsuserstatus',
            index=models.Index(fields=['user', 'is_pinned'], name='notificatio_user_id_20118f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationsuserstatus',
            index=models.Index(fields=['notification', 'priority'], name='notificatio_notific_bbc480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsuserstatus',
            unique_together={('user', 'notification')},
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['channel', 'locale'], name='notif_templ_channel_065aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['event', 'website', 'channel'], name='notif_templ_event_i_d72953_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notif_templ_is_acti_c6f05a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('event', 'website', 'channel', 'locale', 'version')},
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['status', 'next_retry_at'], name='notif_outbo_status_d06303_idx'),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['event_key'], name='notif_outbo_event_k_41481d_idx'),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['processed_at'], name='notif_outbo_process_1ceffb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolenotificationpreference',
            unique_together={('role', 'website')},
        ),
        migrations.AddIndex(
            model_name='usernotificationmeta',
            index=models.Index(fields=['user', 'website'], name='user_notifi_user_id_7e8ab4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationmeta',
            unique_together={('user', 'website')},
        ),
    ]
