# Generated by Django 5.0.14 on 2025-11-27 08:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0002_initial'),
        ('websites', '0002_add_payment_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationgroupprofile',
            name='roles',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'superadmin'), ('ADMIN', 'admin'), ('EDITOR', 'editor'), ('SUPPORT', 'support'), ('WRITER', 'writer'), ('CLIENT', 'client')], help_text='Target role for this profile', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='NotificationWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(help_text='Destination URL that will receive webhook payloads.')),
                ('secret_token', models.CharField(blank=True, help_text='Optional secret used to sign outgoing payloads.', max_length=255)),
                ('signature_algorithm', models.CharField(choices=[('sha256', 'SHA256'), ('sha1', 'SHA1')], default='sha256', max_length=10)),
                ('include_rendered_fields', models.BooleanField(default=True, help_text='Include rendered title/message in payload body.')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Extra HTTP headers to send with webhook requests.')),
                ('timeout_seconds', models.PositiveIntegerField(default=5, help_text='Request timeout per webhook call.')),
                ('enabled', models.BooleanField(default=True)),
                ('subscribed_events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, help_text='List of notification event keys this endpoint subscribes to. Empty = all.', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-app'), ('sms', 'SMS'), ('ws', 'WebSocket'), ('sse', 'Server-Sent Events'), ('push', 'Push'), ('webhook', 'Webhook'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('system', 'System'), ('whatsapp', 'WhatsApp')], default='webhook', help_text='Logical channel represented by this endpoint.', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_webhooks', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_webhooks', to='websites.website')),
            ],
            options={
                'verbose_name': 'Notification Webhook Endpoint',
                'verbose_name_plural': 'Notification Webhook Endpoints',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'website', 'name')},
            },
        ),
    ]
