# Generated by Django 5.2.2 on 2026-05-28 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('bounce_hard', 'Hard Bounce'), ('bounce_soft', 'Soft Bounce'), ('complaint', 'Spam Complaint'), ('unsubscribe', 'Unsubscribe'), ('manual', 'Manual')], default='bounce_hard', max_length=20)),
                ('provider', models.CharField(blank=True, help_text="Provider that reported this e.g. 'sendgrid', 'ses'", max_length=50)),
                ('provider_event_id', models.CharField(blank=True, help_text='Provider-side event ID for tracing.', max_length=256)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw webhook payload for audit.')),
                ('suppressed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
                'db_table': 'notif_email_suppression',
            },
        ),
        migrations.CreateModel(
            name='ProviderWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, help_text="e.g. 'sendgrid', 'ses', 'mailgun'", max_length=50)),
                ('event_type', models.CharField(db_index=True, help_text="Provider event type e.g. 'bounce', 'complaint', 'delivered'", max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('provider_event_id', models.CharField(blank=True, max_length=256)),
                ('raw_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored — event type not actionable')], db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Provider Webhook Event',
                'verbose_name_plural': 'Provider Webhook Events',
                'db_table': 'notif_provider_webhook_event',
                'indexes': [models.Index(fields=['status', 'received_at'], name='notif_provi_status_e5c5d6_idx'), models.Index(fields=['provider', 'event_type'], name='notif_provi_provide_caf0e4_idx')],
            },
        ),
    ]
