# Generated by Django 5.0.14 on 2025-12-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0003_add_notification_webhooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplatePerformance',
        ),
        migrations.DeleteModel(
            name='TemplateUsage',
        ),
    ]
