# Generated by Django 5.2.2 on 2026-05-31 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0003_emailsuppression_providerwebhookevent'),
        ('websites', '0004_add_website_branding_and_payment_disclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsuserstatus',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_statuses', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='usernotificationmeta',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_meta', to='websites.website'),
        ),
    ]
