# Generated by Django 5.2.2 on 2026-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0004_allow_null_website_on_notification_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('payment', 'Payment'), ('compensation', 'Compensation'), ('wallet', 'Wallet'), ('writer', 'Writer'), ('account', 'Account'), ('ticket', 'Ticket'), ('file', 'File'), ('loyalty', 'Loyalty'), ('referral', 'Referral'), ('communication_message', 'Communicatin Message'), ('class', 'Class'), ('system', 'System'), ('info', 'Info')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationdigest',
            name='category',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('compensation', 'Compensation'), ('wallet', 'Wallet'), ('writer', 'Writer'), ('account', 'Account'), ('ticket', 'Ticket'), ('file', 'File'), ('loyalty', 'Loyalty'), ('referral', 'Referral'), ('communication_message', 'Communicatin Message'), ('class', 'Class'), ('system', 'System'), ('info', 'Info')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='category',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('payment', 'Payment'), ('compensation', 'Compensation'), ('wallet', 'Wallet'), ('writer', 'Writer'), ('account', 'Account'), ('ticket', 'Ticket'), ('file', 'File'), ('loyalty', 'Loyalty'), ('referral', 'Referral'), ('communication_message', 'Communicatin Message'), ('class', 'Class'), ('system', 'System'), ('info', 'Info')], help_text="Grouping category e.g. 'order', 'payment', 'account'", max_length=100),
        ),
    ]
