# Generated by Django 5.0.14 on 2025-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0004_delete_templateperformance_delete_templateusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=100)),
                ('template_type', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField(default=0)),
                ('render_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('avg_render_time', models.FloatField(default=0.0)),
                ('min_render_time', models.FloatField(default=0.0)),
                ('max_render_time', models.FloatField(default=0.0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_key', 'date'], name='notificatio_event_k_7bf650_idx'), models.Index(fields=['channel', 'date'], name='notificatio_channel_e1dcbd_idx'), models.Index(fields=['website_id', 'date'], name='notificatio_website_360bf8_idx')],
                'unique_together': {('event_key', 'template_type', 'channel', 'website_id', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='TemplateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=100)),
                ('template_type', models.CharField(choices=[('class_based', 'Class Based'), ('database', 'Database'), ('generic', 'Generic'), ('emergency', 'Emergency')], max_length=20)),
                ('template_version', models.CharField(default='v1.0', max_length=20)),
                ('channel', models.CharField(db_index=True, max_length=20)),
                ('website_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('render_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('total_render_time', models.FloatField(default=0.0)),
                ('avg_render_time', models.FloatField(default=0.0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_key', 'template_type'], name='notificatio_event_k_9c868e_idx'), models.Index(fields=['channel', 'website_id'], name='notificatio_channel_3de8a9_idx'), models.Index(fields=['last_used'], name='notificatio_last_us_85ff56_idx')],
                'unique_together': {('event_key', 'template_type', 'template_version', 'channel', 'website_id', 'locale')},
            },
        ),
    ]
