# Generated by Django 5.0.14 on 2026-01-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_system', '0005_templateperformance_templateusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplatePerformance',
        ),
        migrations.DeleteModel(
            name='TemplateUsage',
        ),
    ]
