# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('probation', 'Probation'), ('blacklist', 'Blacklist'), ('suspension', 'Suspension')], db_index=True, max_length=10)),
                ('reason', models.TextField(help_text='Why should this decision be reconsidered?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True, default='', help_text='Internal notes from the reviewing superadmin.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist_type', models.CharField(choices=[('user', 'User Account'), ('email', 'Email Address'), ('ip', 'IP Address')], db_index=True, default='user', max_length=10)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_blacklisted', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Blacklist Record',
                'verbose_name_plural': 'Blacklist Records',
            },
        ),
        migrations.CreateModel(
            name='SuperadminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_manage', 'User Management'), ('payment', 'Payment Override'), ('report_access', 'Report Access'), ('settings_change', 'Settings Modification'), ('promotion', 'User Promotion / Demotion'), ('suspension', 'User Suspension'), ('reactivation', 'User Reactivation'), ('probation', 'User Probation'), ('blacklist', 'User Blacklisting'), ('blacklist_lifted', 'Blacklist Lifted'), ('dispute_resolution', 'Dispute Resolution'), ('appeal_approved', 'Appeal Approved'), ('appeal_rejected', 'Appeal Rejected'), ('admin_tracking', 'Admin Tracking'), ('override', 'System Override'), ('impersonation', 'User Impersonation')], db_index=True, max_length=30)),
                ('action', models.CharField(max_length=255)),
                ('action_details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Superadmin Log',
                'verbose_name_plural': 'Superadmin Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuperadminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_payments', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_modify_settings', models.BooleanField(default=True)),
                ('can_promote_users', models.BooleanField(default=True)),
                ('can_suspend_users', models.BooleanField(default=True)),
                ('can_blacklist_users', models.BooleanField(default=True)),
                ('can_resolve_disputes', models.BooleanField(default=True)),
                ('can_override_payments', models.BooleanField(default=True)),
                ('can_track_admins', models.BooleanField(default=True)),
                ('can_impersonate_users', models.BooleanField(default=False, help_text='Can use security app impersonation. Requires separate approval.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Superadmin Profile',
                'verbose_name_plural': 'Superadmin Profiles',
            },
        ),
    ]
