# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='websites.website'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='blacklisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide blacklist.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='websites.website'),
        ),
        migrations.AddField(
            model_name='superadminlog',
            name='superadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superadminlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User the action was performed on, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_log_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superadminlog',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status', 'submitted_at'], name='superadmin__status_8fc120_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['user', 'status'], name='superadmin__user_id_e9e18e_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['blacklist_type', 'is_active'], name='superadmin__blackli_257856_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['email'], name='superadmin__email_181887_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['ip_address'], name='superadmin__ip_addr_6216c6_idx'),
        ),
        migrations.AddIndex(
            model_name='superadminlog',
            index=models.Index(fields=['superadmin', 'timestamp'], name='superadmin__superad_3c4e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='superadminlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='superadmin__action__474950_idx'),
        ),
        migrations.AddIndex(
            model_name='superadminlog',
            index=models.Index(fields=['target_user', 'timestamp'], name='superadmin__target__228523_idx'),
        ),
    ]
