# Generated by Django 5.2.2 on 2026-06-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_checklists', '0001_initial'),
        ('websites', '0009_add_wagtail_site_to_website'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qachecklistresult',
            new_name='qa_checklis_order_i_6b9915_idx',
            old_name='qa_result_order_reviewer_idx',
        ),
        migrations.AlterField(
            model_name='qachecklistitem',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Blocking — reviewer cannot pass without checking this.'),
        ),
        migrations.AlterField(
            model_name='qachecklistresult',
            name='checked_items',
            field=models.JSONField(default=list, help_text='List of QAChecklistItem PKs that passed.'),
        ),
        migrations.AlterField(
            model_name='qachecklisttemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Automatically attached to new QA review tasks.'),
        ),
        migrations.AlterField(
            model_name='qachecklisttemplate',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_checklist_templates', to='websites.website'),
        ),
    ]
