# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('embedding', models.JSONField(help_text='Vector as a list of floats')),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('source_text_hash', models.CharField(help_text='SHA-256 of the text that produced this embedding', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='ContentPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('page_slug', models.CharField(blank=True, max_length=255)),
                ('gsc_clicks_30d', models.PositiveIntegerField(default=0)),
                ('gsc_impressions_30d', models.PositiveIntegerField(default=0)),
                ('gsc_avg_position_30d', models.FloatField(default=0.0)),
                ('gsc_avg_ctr_30d', models.FloatField(default=0.0)),
                ('ga4_page_views_30d', models.PositiveIntegerField(default=0)),
                ('ga4_sessions_30d', models.PositiveIntegerField(default=0)),
                ('ga4_avg_engagement_30d', models.FloatField(default=0.0)),
                ('internal_conversions_30d', models.PositiveIntegerField(default=0)),
                ('attributed_revenue_30d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gsc_clicks_90d', models.PositiveIntegerField(default=0)),
                ('ga4_page_views_90d', models.PositiveIntegerField(default=0)),
                ('clicks_delta_pct', models.FloatField(default=0.0, help_text='Percentage change in clicks vs previous 30 days')),
                ('position_delta', models.FloatField(default=0.0, help_text='Change in avg position (positive = worsened)')),
                ('ai_overview_appearances_30d', models.PositiveIntegerField(default=0)),
                ('diagnosis', models.CharField(choices=[('healthy', 'Healthy'), ('low_ctr', 'High impressions, low CTR — rewrite title/meta'), ('low_engagement', 'High CTR, low engagement — page over-promised'), ('no_conversion_path', 'Traffic but no conversions — add CTAs'), ('declining_position', 'Position declining — refresh content'), ('not_visible', 'No impressions — check indexation')], default='healthy', max_length=30)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='wagtailcore.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'gsc_clicks_30d'], name='cms_intelli_site_id_a10974_idx'), models.Index(fields=['site', 'internal_conversions_30d'], name='cms_intelli_site_id_52e0b8_idx'), models.Index(fields=['site', 'attributed_revenue_30d'], name='cms_intelli_site_id_d4a799_idx'), models.Index(fields=['site', 'diagnosis'], name='cms_intelli_site_id_db1fbc_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='ConversionAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attribution_model', models.CharField(choices=[('first_touch', 'First touch'), ('last_touch', 'Last touch'), ('linear', 'Linear'), ('position_based', 'Position-based (40/40/20)')], max_length=20)),
                ('credit_share', models.FloatField(help_text='0.0 to 1.0 — fraction of credit assigned')),
                ('attributed_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('path_position', models.PositiveSmallIntegerField(help_text='1 = first page visited, n = last before conversion')),
                ('path_length', models.PositiveSmallIntegerField(help_text='Total pages in the conversion path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_attributions', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'attribution_model'], name='cms_intelli_content_30a824_idx')],
                'unique_together': {('order', 'content_type', 'object_id', 'attribution_model')},
            },
        ),
        migrations.CreateModel(
            name='FreshnessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('alert_type', models.CharField(choices=[('age_threshold', 'Age threshold exceeded'), ('position_decline', 'Search position declined'), ('click_decline', 'Click traffic declined'), ('engagement_decline', 'Engagement declined'), ('editor_flagged', 'Manually flagged by editor'), ('topic_event', 'External topic event')], max_length=30)),
                ('severity', models.PositiveSmallIntegerField(default=3, help_text='1 (low) to 5 (critical). Severity 3+ triggers notifications.')),
                ('detail', models.JSONField(default=dict, help_text='Numbers backing the alert, e.g., {"old_position": 4.2, "new_position": 11.8, "delta": 7.6}')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('', 'Unresolved'), ('updated', 'Content updated'), ('dismissed', 'Dismissed as not actionable'), ('archived', 'Content archived'), ('rewritten', 'Rewritten from scratch'), ('auto_resolved', 'Condition resolved itself')], max_length=20)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshness_alerts', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-severity', '-raised_at'],
                'indexes': [models.Index(fields=['site', 'resolved_at'], name='cms_intelli_site_id_5e84d8_idx'), models.Index(fields=['content_type', 'object_id', 'resolved_at'], name='cms_intelli_content_fa8aff_idx'), models.Index(fields=['severity', 'resolved_at'], name='cms_intelli_severit_2db706_idx')],
            },
        ),
        migrations.CreateModel(
            name='GA4DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('channel', models.CharField(db_index=True, help_text='sessionDefaultChannelGroup: organic, direct, referral, social, paid', max_length=100)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('engaged_sessions', models.PositiveIntegerField(default=0)),
                ('avg_engagement_seconds', models.FloatField(default=0.0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('resolved_page_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_page_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_metrics', to='wagtailcore.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'date'], name='cms_intelli_site_id_fd645e_idx'), models.Index(fields=['site', 'page_path', 'date'], name='cms_intelli_site_id_4d7033_idx')],
                'unique_together': {('site', 'date', 'page_path', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='GSCDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('query', models.CharField(max_length=500)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('appeared_in_ai_overview', models.BooleanField(default=False)),
                ('resolved_page_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_page_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_metrics', to='wagtailcore.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'date'], name='cms_intelli_site_id_e645f3_idx'), models.Index(fields=['site', 'page_path', 'date'], name='cms_intelli_site_id_8e1772_idx'), models.Index(fields=['resolved_page_content_type', 'resolved_page_object_id', 'date'], name='cms_intelli_resolve_ffbe8f_idx')],
                'unique_together': {('site', 'date', 'page_path', 'query')},
            },
        ),
    ]
