# Generated by Django 5.2.2 on 2026-05-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_intelligence', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('gsc', 'GSC ingestion'), ('ga4', 'GA4 ingestion'), ('freshness', 'Freshness scanner'), ('snapshot', 'Performance snapshots'), ('attribution', 'Conversion attribution'), ('embeddings', 'Embedding generation')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial — some sites failed'), ('failed', 'Failed'), ('skipped', 'Skipped — no config')], default='success', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(blank=True, help_text='Null = platform-wide task (e.g. embeddings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['task', '-ran_at'], name='cms_intelli_task_596508_idx'), models.Index(fields=['site', 'task', '-ran_at'], name='cms_intelli_site_id_547d24_idx')],
            },
        ),
    ]
