# Generated by Django 5.2.2 on 2026-06-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_intelligence', '0002_add_task_sync_log'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('organic_search', 'Organic Search (Google, Bing)'), ('paid_search', 'Paid Search (Google Ads, Bing Ads)'), ('social', 'Social Media (Facebook, Instagram, TikTok)'), ('email', 'Email Campaign'), ('referral', 'Referral / Partner'), ('direct', 'Direct / Brand'), ('affiliate', 'Affiliate'), ('custom', 'Custom UTM match')], db_index=True, max_length=30)),
                ('utm_source', models.CharField(blank=True, help_text='Match exact utm_source value (leave blank = any)', max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('hero_headline', models.CharField(blank=True, help_text='Overrides the default hero headline for this persona', max_length=200)),
                ('hero_subheadline', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, help_text="CTA button label override (e.g. 'Claim your 10% off')", max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('trust_badge', models.CharField(blank=True, help_text="Short trust line shown below the CTA (e.g. 'Used by 12,000+ students')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Higher = checked first. First matching active rule wins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalization_rules', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-priority', 'persona'],
                'indexes': [models.Index(fields=['site', 'persona', 'is_active'], name='cms_intelli_site_id_9d1ae3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('results_count', models.PositiveSmallIntegerField(default=0)),
                ('top_result_url', models.CharField(blank=True, max_length=500)),
                ('top_result_title', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'created_at'], name='cms_intelli_site_id_e9fec7_idx'), models.Index(fields=['site', 'query'], name='cms_intelli_site_id_bacb2d_idx')],
            },
        ),
    ]
