# Generated by Django 5.0.14 on 2025-11-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_payments_management', '0006_add_invoice_fields'),
    ]

    operations = [
    ]
