# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('attachment_download', 'Attachment download (email-gated)'), ('new_subscriber', 'New subscriber signup'), ('order_complete', 'Order completed'), ('inactivity', 'Subscriber inactivity (no opens in 90 days)')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_sequences', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title', max_length=255)),
                ('subject_line', models.CharField(max_length=200)),
                ('preview_text', models.CharField(blank=True, help_text='Preview text shown in email clients', max_length=200)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('list', 11), ('quote', 13), ('callout', 15), ('faq', 18), ('cta', 22), ('internal_link', 26), ('attachment', 31), ('divider', 32), ('video', 34), ('sources', 39), ('related_posts', 43), ('code', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('cms_core.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Required for accessibility and SEO (max 125 chars)', 'max_length': 125, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bulleted', 'Bulleted'), ('numbered', 'Numbered')]}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.ListBlock', (9,), {'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('style', 8), ('items', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 13: ('wagtail.blocks.StructBlock', [[('text', 12), ('attribution', 6)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning'), ('important', 'Important')]}), 15: ('wagtail.blocks.StructBlock', [[('style', 14), ('text', 9)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 500}), 17: ('wagtail.blocks.RichTextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('question', 16), ('answer', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 20: ('wagtail.blocks.URLBlock', (), {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 22: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('style', 21)]], {}), 23: ('wagtail.blocks.PageChooserBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': "Override the page's title for this link", 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('page', 23), ('custom_title', 24), ('custom_description', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms_attachments.Attachment',), {}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('card', 'Card with preview'), ('list', 'Compact list item'), ('hero', 'Large hero card'), ('button', 'Simple download button')]}), 29: ('wagtail.blocks.CharBlock', (), {'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Download Now', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('attachment', 27), ('display_style', 28), ('custom_title', 29), ('custom_cta_text', 30)]], {}), 32: ('cms_core.blocks.DividerBlock', (), {}), 33: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo URL'}), 34: ('wagtail.blocks.StructBlock', [[('url', 33), ('caption', 6)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Articles Consulted', 'max_length': 100}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 16), ('url', 20), ('author', 6), ('publication', 6), ('year', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'max_num': 30, 'min_num': 1}), 39: ('wagtail.blocks.StructBlock', [[('heading', 35), ('sources', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'default': 'Related Articles', 'max_length': 100}), 41: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cms_blog.BlogPostPage']}), 42: ('wagtail.blocks.ListBlock', (41,), {'max_num': 5}), 43: ('wagtail.blocks.StructBlock', [[('heading', 40), ('posts', 42)]], {}), 44: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('apa', 'APA Citation Sample')]}), 45: ('wagtail.blocks.TextBlock', (), {}), 46: ('wagtail.blocks.StructBlock', [[('language', 44), ('code', 45), ('caption', 6)]], {})})),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('subject_line_b', models.CharField(blank=True, help_text='Variant B subject line for A/B testing (blank = no test)', max_length=200)),
                ('ab_split_percentage', models.PositiveSmallIntegerField(default=50, help_text='Percentage of recipients who get variant B')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_send_date', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('complaint_count', models.PositiveIntegerField(default=0)),
                ('unsubscribe_count', models.PositiveIntegerField(default=0)),
                ('subject_a_open_rate', models.FloatField(default=0.0)),
                ('subject_b_open_rate', models.FloatField(default=0.0)),
                ('winning_subject', models.CharField(blank=True, max_length=1)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('conversion_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cms_newsletters.newsletter')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_categories', to='wagtailcore.site')),
            ],
            options={
                'verbose_name_plural': 'Subscriber Categories',
                'ordering': ['name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly digest'), ('monthly', 'Monthly digest'), ('instant', 'Every new post')], default='weekly', max_length=20)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('attachment_gate', 'Email-gated attachment download'), ('blog_form', 'Blog signup form'), ('order_optin', 'Order completion opt-in'), ('manual', 'Manual / admin import'), ('import', 'Bulk import')], default='blog_form', max_length=30)),
                ('source_detail', models.CharField(blank=True, help_text='Which attachment, blog post, or import batch led to this signup', max_length=255)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, choices=[('too_frequent', 'Too frequent'), ('not_relevant', 'Not relevant'), ('never_subscribed', 'Never subscribed'), ('other', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='wagtailcore.site')),
                ('categories', models.ManyToManyField(blank=True, related_name='subscribers', to='cms_newsletters.subscribercategory')),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Only send to subscribers of this category (blank = all)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_newsletters.subscribercategory'),
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField()),
                ('delay_days', models.PositiveSmallIntegerField(help_text='Days after trigger (or previous step) to send this email')),
                ('subject_line', models.CharField(max_length=200)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('list', 11), ('quote', 13), ('callout', 15), ('faq', 18), ('cta', 22), ('internal_link', 26), ('attachment', 31), ('divider', 32), ('video', 34), ('sources', 39), ('related_posts', 43), ('code', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('cms_core.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Required for accessibility and SEO (max 125 chars)', 'max_length': 125, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bulleted', 'Bulleted'), ('numbered', 'Numbered')]}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.ListBlock', (9,), {'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('style', 8), ('items', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 13: ('wagtail.blocks.StructBlock', [[('text', 12), ('attribution', 6)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning'), ('important', 'Important')]}), 15: ('wagtail.blocks.StructBlock', [[('style', 14), ('text', 9)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 500}), 17: ('wagtail.blocks.RichTextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('question', 16), ('answer', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 20: ('wagtail.blocks.URLBlock', (), {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 22: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('style', 21)]], {}), 23: ('wagtail.blocks.PageChooserBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': "Override the page's title for this link", 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('page', 23), ('custom_title', 24), ('custom_description', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms_attachments.Attachment',), {}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('card', 'Card with preview'), ('list', 'Compact list item'), ('hero', 'Large hero card'), ('button', 'Simple download button')]}), 29: ('wagtail.blocks.CharBlock', (), {'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Download Now', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('attachment', 27), ('display_style', 28), ('custom_title', 29), ('custom_cta_text', 30)]], {}), 32: ('cms_core.blocks.DividerBlock', (), {}), 33: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo URL'}), 34: ('wagtail.blocks.StructBlock', [[('url', 33), ('caption', 6)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Articles Consulted', 'max_length': 100}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 16), ('url', 20), ('author', 6), ('publication', 6), ('year', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'max_num': 30, 'min_num': 1}), 39: ('wagtail.blocks.StructBlock', [[('heading', 35), ('sources', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'default': 'Related Articles', 'max_length': 100}), 41: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cms_blog.BlogPostPage']}), 42: ('wagtail.blocks.ListBlock', (41,), {'max_num': 5}), 43: ('wagtail.blocks.StructBlock', [[('heading', 40), ('posts', 42)]], {}), 44: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('apa', 'APA Citation Sample')]}), 45: ('wagtail.blocks.TextBlock', (), {}), 46: ('wagtail.blocks.StructBlock', [[('language', 44), ('code', 45), ('caption', 6)]], {})})),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cms_newsletters.automationsequence')),
            ],
            options={
                'ordering': ['sequence', 'step_order'],
                'unique_together': {('sequence', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='NewsletterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained (spam)'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('link_url', models.URLField(blank=True)),
                ('subject_variant', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cms_newsletters.newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_events', to='cms_newsletters.subscriber')),
            ],
            options={
                'indexes': [models.Index(fields=['newsletter', 'event_type'], name='cms_newslet_newslet_d2a820_idx'), models.Index(fields=['subscriber', 'created_at'], name='cms_newslet_subscri_8e1aa4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('next_send_at', models.DateTimeField(blank=True, help_text='When the next email in the sequence fires', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cms_newsletters.automationsequence')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_enrollments', to='cms_newsletters.subscriber')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_send_at'], name='cms_newslet_status_08f878_idx')],
                'unique_together': {('subscriber', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['site', 'is_active'], name='cms_newslet_site_id_b6154a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['site', 'source'], name='cms_newslet_site_id_7992d5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['email'], name='cms_newslet_email_61cb5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('site', 'email')},
        ),
    ]
