# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'News'), ('update', 'System Update'), ('maintenance', 'Maintenance'), ('promotion', 'Promotion'), ('general', 'General')], default='general', help_text='Category of the announcement', max_length=50)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the announcement', null=True, upload_to='announcements/')),
                ('read_more_url', models.URLField(blank=True, help_text="Optional URL for 'Read More' link", null=True)),
                ('view_count', models.IntegerField(default=0, help_text='Total number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When the user viewed the announcement')),
                ('time_spent', models.IntegerField(blank=True, help_text='Time spent viewing in seconds', null=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether user acknowledged the announcement')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the user acknowledged the announcement', null=True)),
            ],
            options={
                'verbose_name': 'Announcement View',
                'verbose_name_plural': 'Announcement Views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
