# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('notifications_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='broadcast',
            field=models.OneToOneField(blank=True, help_text='Linked broadcast notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='notifications_system.broadcastnotification'),
        ),
        migrations.AddField(
            model_name='announcementview',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='announcements.announcement'),
        ),
    ]
