# Generated by Django 5.0.14 on 2026-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('notifications_system', '0007_templateperformance_templateusage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['broadcast'], name='announcemen_broadca_4f8ade_idx'),
        ),
    ]
