# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', '-created_at'], name='announcemen_categor_f8a7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='announcemen_created_da46df_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['broadcast'], name='announcemen_broadca_4f8ade_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['user', 'announcement'], name='announcemen_user_id_591cec_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['announcement', 'viewed_at'], name='announcemen_announc_1fb2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['user', 'viewed_at'], name='announcemen_user_id_7abf11_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['announcement', 'acknowledged'], name='announcemen_announc_82128b_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['user', 'acknowledged'], name='announcemen_user_id_a8563c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementview',
            unique_together={('user', 'announcement')},
        ),
    ]
