# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0002_initial'),
        ('loyalty_management', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbadge',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_badge', to='websites.website'),
        ),
        migrations.AddField(
            model_name='loyaltypointsconversionconfig',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points_conversion_config', to='websites.website'),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='website',
            field=models.ForeignKey(help_text='Website this tier is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='websites.website'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='client',
            field=models.ForeignKey(help_text='Client associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='client_management.clientprofile'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions_for_website', to='websites.website'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_achieveable', to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='clientbadge',
            unique_together={('client', 'badge_name')},
        ),
    ]
