# Generated by Django 5.0.14 on 2025-11-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='default_payment_schedule',
            field=models.CharField(choices=[('bi-weekly', 'Bi-Weekly (Every 2 weeks)'), ('monthly', 'Monthly')], default='bi-weekly', help_text='Default payment schedule for new writers', max_length=20),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='manual_payment_requests_enabled',
            field=models.BooleanField(default=True, help_text='Allow writers to request manual payments outside of scheduled dates'),
        ),
    ]
