# Generated by Django 5.2.2 on 2026-05-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websiteactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=24)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=24)),
                ('accent_color', models.CharField(default='#14b8a6', max_length=24)),
                ('homepage_headline', models.CharField(blank=True, max_length=255)),
                ('homepage_subheadline', models.TextField(blank=True)),
                ('trust_claims', models.JSONField(blank=True, default=list)),
                ('footer_disclaimer', models.TextField(blank=True)),
                ('payment_processor_name', models.CharField(blank=True, help_text="Display name of the payment processor shown to clients, e.g. 'OrderBridge Payments'", max_length=120)),
                ('payment_statement_descriptor', models.CharField(blank=True, help_text="Exact string clients will see on their card statement, e.g. 'ORDERBRIDGE PAYMENTS'", max_length=22)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_branding', to='websites.website')),
            ],
            options={
                'verbose_name': 'Website Branding',
                'verbose_name_plural': 'Website Branding',
            },
        ),
    ]
