# Generated by Django 5.0.14 on 2025-12-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_add_tenant_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='websitetermsacceptance',
            new_name='websites_we_website_e63d85_idx',
            old_name='websites_we_website__idx',
        ),
        migrations.RenameIndex(
            model_name='websitetermsacceptance',
            new_name='websites_we_website_de2180_idx',
            old_name='websites_we_website_1b56c4_idx',
        ),
    ]
