# Generated by Django 5.2.2 on 2026-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_payment_disclosure_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitebranding',
            name='social_facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook page URL'),
        ),
        migrations.AddField(
            model_name='websitebranding',
            name='social_instagram_url',
            field=models.URLField(blank=True, help_text='Full Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='websitebranding',
            name='social_linkedin_url',
            field=models.URLField(blank=True, help_text='Full LinkedIn page URL'),
        ),
        migrations.AddField(
            model_name='websitebranding',
            name='social_tiktok_url',
            field=models.URLField(blank=True, help_text='Full TikTok profile URL'),
        ),
        migrations.AddField(
            model_name='websitebranding',
            name='social_twitter_url',
            field=models.URLField(blank=True, help_text='Full Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='websitebranding',
            name='social_youtube_url',
            field=models.URLField(blank=True, help_text='Full YouTube channel URL'),
        ),
        migrations.DeleteModel(
            name='WebsiteActionLog',
        ),
    ]
