# Generated by Django 5.0.14 on 2025-12-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_writer_acknowledgment_message_review_reminders'),
        ('websites', '0006_enhance_file_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='guest_block_urgent_before_hours',
            field=models.PositiveIntegerField(default=12, help_text='Disallow guest checkout for deadlines sooner than this many hours.'),
        ),
        migrations.AddField(
            model_name='website',
            name='guest_magic_link_ttl_hours',
            field=models.PositiveIntegerField(default=72, help_text='Lifetime of guest magic-link access tokens in hours.'),
        ),
        migrations.AddField(
            model_name='website',
            name='guest_max_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total price allowed for guest orders. Leave blank for no explicit cap.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='guest_requires_email_verification',
            field=models.BooleanField(default=True, help_text='Require guests to verify email before creating an order'),
        ),
        migrations.CreateModel(
            name='GuestAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Hashed value of the raw guest access token.', max_length=128, unique=True)),
                ('scope', models.CharField(choices=[('order', 'Single Order'), ('dashboard', 'Guest Dashboard')], default='order', help_text='Controls what the guest session can access.', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When this token stops being valid.')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was last redeemed (for rotation / auditing).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address that initiated this token.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-agent string for additional auditing / anomaly detection.', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Optional: limit this token to a single order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_tokens', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_tokens', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_tokens', to='websites.website')),
            ],
            options={
                'indexes': [models.Index(fields=['website', 'user'], name='websites_gu_website_029b81_idx'), models.Index(fields=['website', 'order'], name='websites_gu_website_e29b95_idx'), models.Index(fields=['expires_at'], name='websites_gu_expires_7156e5_idx')],
            },
        ),
    ]
