# Generated by Django 5.2.2 on 2026-06-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('websites', '0008_add_earning_mode_to_writer_level_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='wagtail_site',
            field=models.OneToOneField(blank=True, help_text='Linked Wagtail Site for CMS content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website', to='wagtailcore.site'),
        ),
        migrations.CreateModel(
            name='WebsiteNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche_type', models.CharField(choices=[('general_academic', 'General Academic'), ('nursing', 'Nursing'), ('medical', 'Medical'), ('business', 'Business'), ('stem', 'STEM')], default='general_academic', max_length=64)),
                ('service_catalog', models.JSONField(blank=True, default=list)),
                ('subject_catalog', models.JSONField(blank=True, default=list)),
                ('order_form_defaults', models.JSONField(blank=True, default=dict)),
                ('seo_defaults', models.JSONField(blank=True, default=dict)),
                ('writer_pool_rules', models.JSONField(blank=True, default=dict)),
                ('pricing_defaults', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='niche', to='websites.website')),
            ],
            options={
                'verbose_name': 'Website Niche',
                'verbose_name_plural': 'Website Niches',
            },
        ),
    ]
