# Generated by Django 5.2.2 on 2026-06-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_add_wagtail_site_to_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_settings', to='websites.website'),
        ),
    ]
