# Generated by Django 5.2.2 on 2026-06-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_website_settings_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='portal_url',
            field=models.URLField(blank=True, default='', help_text='Client portal URL for this site (e.g., https://app.gradecrest.com). Used as the Stripe success/cancel redirect base URL.'),
        ),
    ]
