# Generated by Django 5.0.14 on 2025-12-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_create_website_integration_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReviewLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_site_name', models.CharField(help_text='Name of the review site (e.g., TrustPilot, Google Reviews, Yelp)', max_length=100)),
                ('review_url', models.URLField(help_text='URL to the review page/profile on the external site')),
                ('review_type', models.CharField(choices=[('website', 'Website Review'), ('order', 'Order Review'), ('writer', 'Writer Review'), ('general', 'General Review')], default='general', help_text='Type of review this link is for', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review link is currently active and should be shown to clients')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this link (lower numbers first)')),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions for clients', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='Optional icon/logo URL for the review site', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Review Link',
                'verbose_name_plural': 'External Review Links',
                'ordering': ['display_order', 'review_site_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='websiteintegrationconfig',
            new_name='websites_we_website_e0e993_idx',
            old_name='websites_we_website_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='websiteintegrationconfig',
            new_name='websites_we_website_68bdd4_idx',
            old_name='websites_we_website_456def_idx',
        ),
        migrations.AddField(
            model_name='externalreviewlink',
            name='website',
            field=models.ForeignKey(help_text='Website this review link belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='external_review_links', to='websites.website'),
        ),
    ]
