# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_files', '0003_initial'),
        ('orders', '0002_initial'),
        ('support_management', '0001_initial'),
        ('tickets', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faqmanagement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='support_management.faqcategory'),
        ),
        migrations.AddField(
            model_name='faqmanagement',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faqmanagement',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentissuelog',
            name='escalated_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_payment_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentissuelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_issues', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentissuelog',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_payment_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='related_dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='support_staff',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportavailability',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportdashboard',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_dashboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportglobalaccess',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_global_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessageaccess',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='message_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportorderfilemanagement',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_actions', to='order_files.orderfile'),
        ),
        migrations.AddField(
            model_name='supportorderfilemanagement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_file_management', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportorderfilemanagement',
            name='support_staff',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_order_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportordermanagement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_order_management', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportordermanagement',
            name='support_staff',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_profiles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='supportpermission',
            name='support_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='support_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='supportactionlog',
            name='support_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='disputeresolutionlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='supportworkloadtracker',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='workload_tracker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerperformancelog',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_performance_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerperformancelog',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
