# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_management', '0001_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('support_management', '0001_initial'),
        ('tickets', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disputemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeresolutionlog',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_log', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faqmanagement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='support_management.faqcategory'),
        ),
        migrations.AddField(
            model_name='faqmanagement',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faqmanagement',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['support', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='escalated_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_escalated_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_disputes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='other_party',
            field=models.ForeignKey(help_text='The other party in the dispute', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='raised_by',
            field=models.ForeignKey(help_text='User who raised the dispute (client or writer)', on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['support', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_order_disputes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_management.orderdispute'),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentissuelog',
            name='escalated_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_payment_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentissuelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_issues', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentissuelog',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_payment_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='related_dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='supportactivitylog',
            name='support_staff',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportavailability',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportdashboard',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_dashboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportglobalaccess',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_global_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessageaccess',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='message_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportorderfilemanagement',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_actions', to='files_management.fileattachment'),
        ),
        migrations.AddField(
            model_name='supportorderfilemanagement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_file_management', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportorderfilemanagement',
            name='support_staff',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_order_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportordermanagement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_order_management', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportordermanagement',
            name='support_staff',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_profiles', to='websites.website'),
        ),
        migrations.AddField(
            model_name='supportpermission',
            name='support_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='support_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='supportactionlog',
            name='support_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='disputeresolutionlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to='support_management.supportprofile'),
        ),
        migrations.AddField(
            model_name='supportworkloadtracker',
            name='support_staff',
            field=models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='workload_tracker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerperformancelog',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_performance_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerperformancelog',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['order', 'status'], name='support_man_order_i_0bf712_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['raised_by', 'status'], name='support_man_raised__9635d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['assigned_to', 'status'], name='support_man_assigne_51f3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['status', 'priority'], name='support_man_status_e0500a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['sla_breached', 'actual_resolution_time'], name='support_man_sla_bre_8ee5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['assigned_to', 'sla_breached'], name='support_man_assigne_f366ef_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['status', 'expected_resolution_time'], name='support_man_status_2be7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['expected_resolution_time'], name='support_man_expecte_ccd5d0_idx'),
        ),
    ]
