# Generated by Django 5.2.2 on 2026-06-17 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeWriterResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_response', to='support_management.orderdispute')),
                ('writer', models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_formal_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Writer Response',
                'verbose_name_plural': 'Dispute Writer Responses',
            },
        ),
    ]
