# Generated by Django 5.0.14 on 2025-12-21 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderdraft_orderpreset_revisionrequest'),
        ('support_management', '0004_rename_support_man_order_i_idx_support_man_order_i_0bf712_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdisputesla',
            options={'ordering': ['-expected_resolution_time'], 'verbose_name': 'Order/Dispute SLA', 'verbose_name_plural': 'Order/Dispute SLAs'},
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='breach_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes past deadline if breached (cached for performance)', null=True),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='breach_notified_at',
            field=models.DateTimeField(blank=True, help_text='When breach notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='email_alert_sent',
            field=models.BooleanField(default=False, help_text='Whether email alert was sent'),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('warning', 'Warning (Approaching Deadline)'), ('breached', 'Breached'), ('resolved', 'Resolved')], default='on_track', help_text='Current SLA status', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='time_remaining_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes remaining until deadline (cached for performance)', null=True),
        ),
        migrations.AddField(
            model_name='orderdisputesla',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='When warning was sent (before breach)', null=True),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['sla_breached', 'actual_resolution_time'], name='support_man_sla_bre_8ee5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['assigned_to', 'sla_breached'], name='support_man_assigne_f366ef_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['status', 'expected_resolution_time'], name='support_man_status_2be7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdisputesla',
            index=models.Index(fields=['expected_resolution_time'], name='support_man_expecte_ccd5d0_idx'),
        ),
    ]
