# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=32)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_client_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('first_order_only', models.BooleanField(default=False)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('first_order', 'First order'), ('holiday', 'Holiday'), ('loyalty', 'Loyalty'), ('referral', 'Referral'), ('campaign', 'Campaign'), ('spend_tier', 'Spend tier'), ('system', 'System')], default='manual', max_length=32)),
                ('is_campaign_managed', models.BooleanField(default=True, help_text='If true, campaign activation/deactivation controls this discount.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscountConversionEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('viewed', 'Viewed'), ('previewed', 'Previewed'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('removed', 'Removed'), ('paid', 'Paid'), ('expired_at_checkout', 'Expired at checkout')], max_length=40)),
                ('payable_type', models.CharField(blank=True, choices=[('order', 'Order'), ('special_order', 'Special order'), ('class_order', 'Class order')], max_length=40)),
                ('payable_id', models.CharField(blank=True, max_length=64)),
                ('discount_code', models.CharField(blank=True, max_length=64)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_manual_codes', models.BooleanField(default=True)),
                ('auto_apply_first_order_discount', models.BooleanField(default=True)),
                ('allow_code_to_replace_first_order', models.BooleanField(default=True)),
                ('auto_apply_best_discount', models.BooleanField(default=True)),
                ('allow_discounts_on_orders', models.BooleanField(default=True)),
                ('allow_discounts_on_special_orders', models.BooleanField(default=True)),
                ('allow_discounts_on_class_bundles', models.BooleanField(default=True)),
                ('require_admin_approval_for_campaigns', models.BooleanField(default=False)),
                ('notify_admins_on_large_discount', models.BooleanField(default=True)),
                ('large_discount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscountSpendTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('minimum_lifetime_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-minimum_lifetime_spend',),
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_type', models.CharField(choices=[('order', 'Order'), ('special_order', 'Special order'), ('class_order', 'Class order')], max_length=40)),
                ('payable_id', models.CharField(max_length=64)),
                ('discount_code', models.CharField(max_length=64)),
                ('discount_type', models.CharField(max_length=32)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('origin', models.CharField(max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-applied_at',),
            },
        ),
        migrations.CreateModel(
            name='FirstOrderDiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], default='percentage', max_length=32)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('applies_to_orders', models.BooleanField(default=True)),
                ('applies_to_special_orders', models.BooleanField(default=True)),
                ('applies_to_class_bundles', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
