# Generated by Django 5.0.14 on 2025-10-29 09:36

import discounts.validators.code_format_validator
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(help_text='Unique discount code', max_length=32, unique=True, validators=[discounts.validators.code_format_validator.CodeFormatValidator()])),
                ('description', models.TextField(blank=True, help_text='Description of the discount', null=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=20)),
                ('origin_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('system', 'System Generated'), ('client', 'Client Specific'), ('promo', 'Promotional Campaign')], default='manual', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('applies_to_first_order_only', models.BooleanField(default=False)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_general', models.BooleanField(default=True)),
                ('has_tiers', models.BooleanField(default=False)),
                ('stackable', models.BooleanField(default=False)),
                ('stacking_priority', models.PositiveIntegerField(default=0)),
                ('max_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_stackable_uses_per_customer', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the discount is currently active')),
                ('is_expired', models.BooleanField(default=False, help_text='Indicates if the discount has expired')),
                ('is_archived', models.BooleanField(default=False, help_text='Indicates if the discount is archived and not available for use')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the discount is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the discount was soft-deleted', null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_stackable_discounts', models.PositiveIntegerField(default=1, help_text='Maximum number of discount codes that can be applied to a single order.')),
                ('enable_stacking', models.BooleanField(default=True)),
                ('enable_hints', models.BooleanField(default=True)),
                ('discount_threshold', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum order total required (after applying the first discount) to allow stacking additional discounts.', max_digits=10)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=30.0, help_text='Maximum total discount percent allowed per order.', max_digits=5)),
                ('allow_stack_across_events', models.BooleanField(default=False, help_text='Allow stacking discount codes from different promotional campaigns on the same order.')),
                ('promotional_campaign_discount_active', models.BooleanField(default=True, help_text='Is the promotional campaign discount active?')),
                ('promotional_campaign_discount_value', models.DecimalField(decimal_places=2, default=10.0, help_text='Value of promotional campaign discount in percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the discount config was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
            ],
            options={
                'verbose_name': 'Discount Configuration',
                'verbose_name_plural': 'Discount Configurations',
            },
        ),
        migrations.CreateModel(
            name='DiscountStackingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority of this discount stack (lower number = higher priority)')),
            ],
            options={
                'verbose_name': 'Discount Stacking Rule',
                'verbose_name_plural': 'Discount Stacking Rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(decimal_places=2, help_text='Minimum order value to activate this tier.', max_digits=10)),
                ('percent_off', models.DecimalField(decimal_places=2, help_text='Percentage discount for this tier.', max_digits=5)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum absolute discount this tier can apply.', max_digits=10, null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Tiers with higher priority override lower ones if multiple match.')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this tier will not be considered.')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional start date/time when this tier becomes active.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional end date/time after which this tier is inactive.', null=True)),
            ],
            options={
                'verbose_name': 'Discount Tier',
                'verbose_name_plural': 'Discount Tiers',
                'ordering': ['-priority', '-min_order_value'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Event name (e.g., Black Friday, Christmas Sale)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the promotional campaign', null=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug for URL or admin filtering', null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When the  promotional campaign starts')),
                ('end_date', models.DateTimeField(help_text='When the promotional campaign ends')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promotional campaign is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the campaign is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the campaign was soft-deleted', null=True)),
                ('campaign_type', models.CharField(blank=True, help_text="Optional type (e.g. 'email-blast', 'referral', 'flash-sale')", max_length=50, null=True)),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
            },
        ),
    ]
