# Generated by Django 5.2.2 on 2026-06-21 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discount_soft_delete_fields'),
        ('websites', '0009_add_wagtail_site_to_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePromoDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('banner_strip', 'Banner strip'), ('countdown_banner', 'Countdown banner'), ('popup', 'Popup')], default='banner_strip', max_length=32)),
                ('color_scheme', models.CharField(choices=[('brand', 'Brand (default)'), ('dark', 'Dark'), ('warm', 'Warm / amber')], default='brand', max_length=16)),
                ('badge_text', models.CharField(blank=True, default='', help_text='Short label shown before the headline, e.g. "Flash sale" or "Limited time".', max_length=40)),
                ('headline', models.CharField(max_length=120)),
                ('subtext', models.CharField(blank=True, default='', max_length=200)),
                ('cta_label', models.CharField(default='Order now', max_length=60)),
                ('cta_url', models.CharField(default='/order', max_length=255)),
                ('discount_code', models.CharField(blank=True, default='', help_text='Discount code shown to visitors (optional).', max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Toggle off to hide without deleting.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site promo display',
                'verbose_name_plural': 'Site promo displays',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_website_deleted_at_idx',
        ),
        migrations.AddField(
            model_name='sitepromodisplay',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional — links this display to a discount campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_displays', to='discounts.promotionalcampaign'),
        ),
        migrations.AddField(
            model_name='sitepromodisplay',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_displays_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepromodisplay',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_displays', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='sitepromodisplay',
            index=models.Index(fields=['website', 'is_active', 'starts_at'], name='discounts_s_website_1a9af7_idx'),
        ),
        migrations.AddIndex(
            model_name='sitepromodisplay',
            index=models.Index(fields=['website', 'ends_at'], name='discounts_s_website_879879_idx'),
        ),
    ]
