# Generated by Django 5.0.14 on 2025-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_configs', '0003_change_preferred_writer_config_to_website_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferredwriterconfig',
            options={'ordering': ['website']},
        ),
        migrations.AlterField(
            model_name='preferredwriterconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether preferred writer option is enabled for this website'),
        ),
        migrations.AlterField(
            model_name='preferredwriterconfig',
            name='preferred_writer_cost',
            field=models.DecimalField(decimal_places=2, help_text='Extra cost (in USD) for selecting a preferred writer (applies to all writers)', max_digits=10),
        ),
    ]
