# Generated by Django 6.0.5 on 2026-05-28 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_id', models.UUIDField(db_index=True)),
                ('previous_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=30)),
                ('new_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=30)),
                ('previous_visibility', models.CharField(choices=[('public', 'Public'), ('shadowed', 'Shadowed'), ('internal', 'Internal'), ('removed', 'Removed'), ('under_review', 'Under Review')], max_length=30)),
                ('new_visibility', models.CharField(choices=[('public', 'Public'), ('shadowed', 'Shadowed'), ('internal', 'Internal'), ('removed', 'Removed'), ('under_review', 'Under Review')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('moderator_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField(db_index=True)),
                ('target_type', models.CharField(choices=[('order', 'Order'), ('special_order', 'Special Order'), ('class_order', 'Class Order'), ('website', 'Website')], db_index=True, max_length=40)),
                ('target_id', models.UUIDField(db_index=True)),
                ('writer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('rating_payload', models.JSONField(blank=True, default=dict)),
                ('moderation_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('shadowed', 'Shadowed'), ('internal', 'Internal'), ('removed', 'Removed'), ('under_review', 'Under Review')], db_index=True, default='under_review', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('moderated_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='reviews_sys_target__9271b6_idx'), models.Index(fields=['writer_id', 'visibility'], name='reviews_sys_writer__726f1e_idx'), models.Index(fields=['target_type', 'visibility'], name='reviews_sys_target__d19720_idx')],
            },
        ),
    ]
