# Generated by Django 5.2.2 on 2026-06-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_system', '0002_writerreview_websitereview_orderreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderreview',
            new_name='reviews_sys_writer__d83a2f_idx',
            old_name='reviews_or_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='orderreview',
            new_name='reviews_sys_website_102f79_idx',
            old_name='reviews_or_website_idx',
        ),
        migrations.RenameIndex(
            model_name='websitereview',
            new_name='reviews_sys_website_2f8706_idx',
            old_name='reviews_wsr_website_idx',
        ),
        migrations.RenameIndex(
            model_name='writerreview',
            new_name='reviews_sys_writer__b580cd_idx',
            old_name='reviews_wr_writer_idx',
        ),
        migrations.RenameIndex(
            model_name='writerreview',
            new_name='reviews_sys_website_8f8b3a_idx',
            old_name='reviews_wr_website_idx',
        ),
    ]
