# Generated by Django 5.0.14 on 2026-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_system', '0002_add_writer_review_indexes'),
        ('reviews_system', '0003_alter_orderreview_reviewer_and_more'),
    ]

    operations = [
    ]
