# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications_system', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_acknowledgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastacknowledgement',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_acknowledgements', to='websites.website'),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='broadcastacknowledgement',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='notifications_system.broadcastnotification'),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='notifications_system.broadcastnotification'),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_overrides_by_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastoverride',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_overrides', to='websites.website'),
        ),
        migrations.AddField(
            model_name='channelpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_preferences', to='websites.website'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.website'),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventnotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventnotificationpreference',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='globalnotificationsystemsettings',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_notification_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='groupnotificationprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='The user receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications_system.notification'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationdigestqueue',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='notifications_system.notificationdigest'),
        ),
        migrations.AddField(
            model_name='notificationdigestqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdigestqueue',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='website',
            field=models.ForeignKey(blank=True, help_text='The website this event is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationeventoverride',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Scope override to a specific website or leave null for global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_event_overrides', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications_system.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='users',
            field=models.ManyToManyField(help_text='Users who are part of this notification group.', related_name='notification_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='websites.website'),
        ),
        migrations.AddField(
            model_name='groupnotificationprofile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications_system.notificationgroup'),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications_system.notificationgroup'),
        ),
        migrations.AddField(
            model_name='notificationgroupprofile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='notificationgroupprofile',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Directly assigned users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationgroupprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='notifications_system.notificationgroup'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications_system.notification'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(help_text='The user whose preferences are being managed.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreferencegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreferencegroup',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='profile_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications_system.notificationpreferencegroup'),
        ),
        migrations.AddField(
            model_name='notificationpreferenceprofile',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='base_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications_system.notificationprofile'),
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='user',
            field=models.ForeignKey(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='profile',
            field=models.ForeignKey(help_text='The notification profile applied to this preference.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='notifications_system.notificationprofile'),
        ),
        migrations.AddField(
            model_name='notificationgroupprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications_system.notificationprofile'),
        ),
        migrations.AddField(
            model_name='notificationsuserstatus',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='notifications_system.notification'),
        ),
        migrations.AddField(
            model_name='notificationsuserstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications_system.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outbox',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.website'),
        ),
        migrations.AddField(
            model_name='rolenotificationpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='templateperformance',
            index=models.Index(fields=['event_key', 'date'], name='notificatio_event_k_7bf650_idx'),
        ),
        migrations.AddIndex(
            model_name='templateperformance',
            index=models.Index(fields=['channel', 'date'], name='notificatio_channel_e1dcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='templateperformance',
            index=models.Index(fields=['website_id', 'date'], name='notificatio_website_360bf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateperformance',
            unique_together={('event_key', 'template_type', 'channel', 'website_id', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='templateusage',
            index=models.Index(fields=['event_key', 'template_type'], name='notificatio_event_k_9c868e_idx'),
        ),
        migrations.AddIndex(
            model_name='templateusage',
            index=models.Index(fields=['channel', 'website_id'], name='notificatio_channel_3de8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='templateusage',
            index=models.Index(fields=['last_used'], name='notificatio_last_us_85ff56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateusage',
            unique_together={('event_key', 'template_type', 'template_version', 'channel', 'website_id', 'locale')},
        ),
        migrations.AddField(
            model_name='usernotificationmeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_meta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preferences', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notificationeventpreference',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_preferences', to='notifications_system.usernotificationpreference'),
        ),
        migrations.AddField(
            model_name='channelpreference',
            name='user_pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_prefs', to='notifications_system.usernotificationpreference'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_system_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['website', 'event_type'], name='broadcast_n_website_e4e148_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['-created_at'], name='broadcast_n_created_cd3a2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastnotification',
            unique_together={('website', 'title', 'event_type')},
        ),
        migrations.AddIndex(
            model_name='broadcastacknowledgement',
            index=models.Index(fields=['user', 'broadcast'], name='notificatio_user_id_be1b48_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastacknowledgement',
            index=models.Index(fields=['website'], name='notificatio_website_d85873_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastacknowledgement',
            unique_together={('user', 'broadcast')},
        ),
        migrations.AddIndex(
            model_name='broadcastoverride',
            index=models.Index(fields=['website', 'broadcast', 'user', 'role'], name='notificatio_website_56b0e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastoverride',
            unique_together={('website', 'broadcast', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'channel'], name='notif_deliv_status_4b00c5_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['user', 'website'], name='notif_deliv_user_id_32d9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['event_key'], name='notif_deliv_event_k_193a0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventnotificationpreference',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='globalnotificationsystemsettings',
            unique_together={('website',)},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['website', 'user', 'type', 'is_read'], name='notificatio_website_b57672_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_adb823_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_1fd826_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivered_at'], name='notificatio_deliver_1f5a68_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_digest', 'digest_group'], name='notificatio_is_dige_de555b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_0210bb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_b433a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('website', 'user', 'type', 'title', 'message')},
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['user', 'website', 'notification'], name='notificatio_user_id_e174ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together={('user', 'website', 'notification', 'channel')},
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['user', 'event_key', 'scheduled_for'], name='notificatio_user_id_269136_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdigest',
            constraint=models.UniqueConstraint(fields=('user', 'event_key', 'scheduled_for'), name='unique_user_event_scheduled'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationdigest',
            unique_together={('user', 'event_key', 'scheduled_for')},
        ),
        migrations.AddIndex(
            model_name='notificationdigestqueue',
            index=models.Index(fields=['user', 'timestamp'], name='notificatio_user_id_67a5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigestqueue',
            index=models.Index(fields=['event_key', 'timestamp'], name='notificatio_event_k_3e8afe_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigestqueue',
            index=models.Index(fields=['website', 'timestamp'], name='notificatio_website_1b9940_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationeventoverride',
            unique_together={('website', 'event_key')},
        ),
        migrations.AlterUniqueTogether(
            name='groupnotificationprofile',
            unique_together={('website', 'group')},
        ),
        migrations.AddIndex(
            model_name='notificationprofile',
            index=models.Index(fields=['name'], name='notificatio_name_1ed2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprofile',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_db1f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['website', 'user'], name='notificatio_website_0aca6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['event'], name='notificatio_event_17373e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['channel'], name='notificatio_channel_3043cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('website', 'user', 'event', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroupprofile',
            unique_together={('website', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationsuserstatus',
            unique_together={('user', 'notification')},
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['channel', 'locale'], name='notif_templ_channel_065aa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('event', 'website', 'channel', 'locale', 'version')},
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['processed_at'], name='notif_outbo_process_1ceffb_idx'),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['event_key'], name='notif_outbo_event_k_41481d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolenotificationpreference',
            unique_together={('role', 'website')},
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('website', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationeventpreference',
            unique_together={('user', 'event', 'website')},
        ),
        migrations.AlterUniqueTogether(
            name='channelpreference',
            unique_together={('website', 'user_pref', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationsettings',
            unique_together={('website', 'user')},
        ),
    ]
