# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('captured', 'Captured'), ('released', 'Released'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='Business reference, e.g. order ref or payment ref.', max_length=128)),
                ('reason', models.TextField(blank=True, default='')),
                ('wallet_reference', models.CharField(blank=True, default='', max_length=64)),
                ('payment_intent_reference', models.CharField(blank=True, default='', max_length=128)),
                ('related_object_type', models.CharField(blank=True, default='', help_text='Related business model, e.g. Order, Dispute.', max_length=128)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hold Record',
                'verbose_name_plural': 'Hold Records',
                'db_table': 'ledger_hold_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(help_text='Stable human readable entry reference.', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('entry_type', models.CharField(choices=[('client_wallet_top_up', 'Client Wallet Top Up'), ('client_wallet_spend', 'Client Wallet Spend'), ('client_wallet_support_credit', 'Client Wallet Support Credit'), ('client_wallet_support_debit', 'Client Wallet Support Debit'), ('client_wallet_refund', 'Client Wallet Refund'), ('client_wallet_tip_deduction', 'Client Wallet Tip Deduction'), ('external_payment_capture', 'External Payment Capture'), ('external_refund', 'External Refund'), ('payment_reversal', 'Payment Reversal'), ('payment_fee', 'Payment Fee'), ('gateway_settlement', 'Gateway Settlement'), ('gateway_reconciliation_adjustment', 'Gateway Reconciliation Adjustment'), ('tip_settlement', 'Tip Settlement'), ('order_payment', 'Order Payment'), ('order_installment_payment', 'Order Installment Payment'), ('special_order_deposit', 'Special Order Deposit'), ('special_order_installment', 'Special Order Installment'), ('class_bundle_deposit', 'Class Bundle Deposit'), ('class_bundle_installment', 'Class Bundle Installment'), ('class_payment', 'Class Payment'), ('writer_earning_accrual', 'Writer Earning Accrual'), ('writer_payout', 'Writer Payout'), ('writer_bonus', 'Writer Bonus'), ('writer_fine', 'Writer Fine'), ('writer_tip_credit', 'Writer Tip Credit'), ('writer_manual_increase', 'Writer Manual Increase'), ('writer_manual_decrease', 'Writer Manual Decrease'), ('writer_earning_recovery', 'Writer Earning Recovery'), ('writer_earning_restoration', 'Writer Earning Restoration'), ('writer_recovery_applied_to_payout', 'Writer Recovery Applied To Payout'), ('dispute_hold', 'Dispute Hold'), ('dispute_release', 'Dispute Release'), ('dispute_reversal', 'Dispute Reversal'), ('reversal', 'Reversal'), ('manual_adjustment', 'Manual Adjustment')], max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('currency', models.CharField(default='USD', help_text='ISO currency code for all lines in this entry.', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', help_text='Business reference such as payment ref or order ref.', max_length=128)),
                ('source_app', models.CharField(blank=True, choices=[('orders', 'Orders'), ('tips', 'Tips'), ('special_orders', 'Special Orders'), ('class_management', 'Class Management'), ('payment_processor', 'Payment Processor'), ('wallets', 'Wallets'), ('refunds', 'Refunds'), ('disputes', 'Disputes'), ('fines', 'Fines'), ('writer_payments', 'Writer Compensation'), ('admin', 'Admin'), ('system', 'System')], default='', max_length=64)),
                ('source_model', models.CharField(blank=True, default='', help_text='Source model name, e.g. OrderPayment or Refund.', max_length=128)),
                ('source_object_id', models.CharField(blank=True, default='', help_text='Primary key of the source business object.', max_length=64)),
                ('external_reference', models.CharField(blank=True, default='', help_text='Gateway/provider reference when applicable.', max_length=255)),
                ('payment_intent_reference', models.CharField(blank=True, default='', help_text='Reference to the central payment intent when applicable.', max_length=128)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry takes financial effect.')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'ledger_journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('wallet_reference', models.CharField(blank=True, default='', max_length=64)),
                ('payment_intent_reference', models.CharField(blank=True, default='', max_length=128)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=128)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'db_table': 'ledger_journal_lines',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable internal account code, e.g. PLATFORM_CASH.', max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(help_text='Human friendly ledger account name.', max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('clearing', 'Clearing'), ('control', 'Control')], max_length=20)),
                ('currency', models.CharField(default='USD', help_text='ISO currency code, e.g. KES, USD.', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_system_account', models.BooleanField(default=False, help_text='Whether this account is platform controlled.')),
                ('allows_negative', models.BooleanField(default=False, help_text='Whether balances on this account may go negative.')),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Ledger Accounts',
                'db_table': 'ledger_accounts',
                'ordering': ['website_id', 'account_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('matched', 'Matched'), ('partially_matched', 'Partially Matched'), ('mismatched', 'Mismatched'), ('resolved', 'Resolved')], default='unreconciled', max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, default='', help_text='Internal business reference, e.g. payment or refund ref.', max_length=128)),
                ('external_reference', models.CharField(blank=True, default='', help_text='Gateway or provider reference.', max_length=255)),
                ('payment_intent_reference', models.CharField(blank=True, default='', max_length=128)),
                ('source_app', models.CharField(blank=True, default='', help_text='Originating app name, e.g. payments, refunds, payouts.', max_length=64)),
                ('source_model', models.CharField(blank=True, default='', max_length=128)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('mismatch_reason', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Record',
                'verbose_name_plural': 'Reconciliation Records',
                'db_table': 'ledger_reconciliation_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Computed balance at snapshot time.', max_digits=14)),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this snapshot was taken.')),
                ('reference', models.CharField(blank=True, default='', help_text='Optional reference (e.g. daily_close, reconciliation_run).', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance_snapshots', to='websites.website')),
            ],
            options={
                'verbose_name': 'Account Balance Snapshot',
                'verbose_name_plural': 'Account Balance Snapshots',
                'db_table': 'ledger_account_balance_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
