# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holdrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holdrecord',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_holds', to='websites.website'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, help_text='Original entry that this entry reverses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='websites.website'),
        ),
        migrations.AddField(
            model_name='holdrecord',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Optional originating journal entry for this hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hold_records', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='websites.website'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='ledger.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='holdrecord',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hold_records', to='ledger.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='accountbalancesnapshot',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='ledger.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ledger_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_reconciliations', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'entry_type'], name='ledger_jour_website_08fe6b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'status'], name='ledger_jour_website_5eb019_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'currency'], name='ledger_jour_website_4d301e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'reference'], name='ledger_jour_website_ee659b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'source_app'], name='ledger_jour_website_1f5d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'source_model', 'source_object_id'], name='ledger_jour_website_342b35_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'external_reference'], name='ledger_jour_website_e2a1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'payment_intent_reference'], name='ledger_jour_website_68d1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'effective_at'], name='ledger_jour_website_28ac18_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['website', 'posted_at'], name='ledger_jour_website_ff57e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['website', 'code'], name='ledger_acco_website_1736f0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['website', 'account_type'], name='ledger_acco_website_2b804b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['website', 'status'], name='ledger_acco_website_72a88a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['website', 'is_system_account'], name='ledger_acco_website_0f966c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ledgeraccount',
            unique_together={('website', 'code')},
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'journal_entry'], name='ledger_jour_website_d3f17f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'ledger_account'], name='ledger_jour_website_1dabec_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'entry_side'], name='ledger_jour_website_467c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'currency'], name='ledger_jour_website_b1b001_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'user'], name='ledger_jour_website_ea145a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'wallet_reference'], name='ledger_jour_website_60a948_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'payment_intent_reference'], name='ledger_jour_website_57a375_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['website', 'related_object_type', 'related_object_id'], name='ledger_jour_website_f55bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'status'], name='ledger_hold_website_a46375_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'ledger_account'], name='ledger_hold_website_c043f1_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'user'], name='ledger_hold_website_7473fc_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'wallet_reference'], name='ledger_hold_website_a336e1_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'payment_intent_reference'], name='ledger_hold_website_3e59ea_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'reference'], name='ledger_hold_website_38f8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'related_object_type', 'related_object_id'], name='ledger_hold_website_7ae9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='holdrecord',
            index=models.Index(fields=['website', 'expires_at'], name='ledger_hold_website_330b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['website', 'ledger_account'], name='ledger_acco_website_e82041_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['website', 'currency'], name='ledger_acco_website_b25460_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['website', 'snapshot_date'], name='ledger_acco_website_9a423a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['website', 'reference'], name='ledger_acco_website_40085f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'status'], name='ledger_reco_website_5ae0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'currency'], name='ledger_reco_website_db9c96_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'reference'], name='ledger_reco_website_3e12b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'external_reference'], name='ledger_reco_website_76339f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'payment_intent_reference'], name='ledger_reco_website_6def25_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'source_app'], name='ledger_reco_website_4c9c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'source_model', 'source_object_id'], name='ledger_reco_website_7cc285_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'reconciled_at'], name='ledger_reco_website_2e1ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['website', 'resolved_at'], name='ledger_reco_website_0ce038_idx'),
        ),
    ]
