# Generated by Django 6.0.5 on 2026-05-28 09:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('payable_object_id', models.PositiveBigIntegerField()),
                ('allocation_type', models.CharField(choices=[('wallet', 'Wallet'), ('external_payment', 'External Payment')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('applied', 'Applied'), ('released', 'Released'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_dispute_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], default='open', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('order', 'Order'), ('special_order', 'Special Order'), ('class_purchase', 'Class Purchase'), ('bundle_purchase', 'Bundle Purchase'), ('wallet_top_up', 'Wallet Top Up'), ('tip', 'Tip'), ('invoice', 'Invoice'), ('extra_order_charge', 'Extra Order Charge'), ('manual_billing', 'Manual Billing'), ('billing_payment_request', 'Billing Payment Request')], max_length=32)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe')], max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='created', max_length=32)),
                ('application_status', models.CharField(choices=[('not_applied', 'Not Applied'), ('applying', 'Applying'), ('applied', 'Applied'), ('application_failed', 'Application Failed')], default='not_applied', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payable_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_checkout_url', models.URLField(blank=True, default='')),
                ('provider_client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('provider_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('application_attempts', models.PositiveIntegerField(default=0)),
                ('application_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_refund_id', models.CharField(blank=True, default='', max_length=128)),
                ('destination', models.CharField(choices=[('original_method', 'Original Method'), ('wallet', 'Wallet')], default='original_method', max_length=32)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='requested', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('authorization', 'Authorization'), ('capture', 'Capture'), ('charge', 'Charge'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('reversal', 'Reversal'), ('webhook_event', 'Webhook Event'), ('manual_confirmation', 'Manual Confirmation'), ('verification', 'Verification')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProviderWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('signature_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
    ]
