# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments_processor', '0002_initial'),
        ('wallets', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='wallet_hold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocation', to='wallets.wallethold'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_disputes', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payable_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='wallet_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='wallets.wallethold'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments_processor.paymentintent'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='payments_processor.paymentintent'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments_processor.paymentintent'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments_processor.paymentintent'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments_processor.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments_processor.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='providerwebhookevent',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments_processor.paymentintent'),
        ),
        migrations.AddField(
            model_name='providerwebhookevent',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_webhook_events', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['website', 'reference'], name='payments_pr_website_d0e0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider', 'provider_intent_id'], name='payments_pr_provide_9b392b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status'], name='payments_pr_status_923f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['application_status'], name='payments_pr_applica_73292e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['purpose'], name='payments_pr_purpose_f28d29_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['website', 'client', 'created_at'], name='payments_pr_website_a98311_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='ppi_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__gte', Decimal('0.00'))), name='ppi_amount_refunded_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['website', 'customer', 'created_at'], name='payments_pr_website_eb9802_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['allocation_type', 'status'], name='payments_pr_allocat_034701_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payable_content_type', 'payable_object_id'], name='payments_pr_payable_86aca6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['website', 'payment_intent', 'created_at'], name='payments_pr_website_078417_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'provider_event_id'], name='payments_pr_provide_b72483_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'provider_transaction_id'], name='payments_pr_provide_10df9d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payments_pr_status_fd1cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['kind'], name='payments_pr_kind_2c9e56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['website', 'payment_intent', 'requested_at'], name='payments_pr_website_41cb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['provider', 'provider_refund_id'], name='payments_pr_provide_f632f8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['status'], name='payments_pr_status_eeb946_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['website', 'payment_intent', 'opened_at'], name='payments_pr_website_2ebf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['status'], name='payments_pr_status_4648b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentdispute',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_dispute_id'), name='ppd_unique_provider_dispute'),
        ),
        migrations.AddIndex(
            model_name='providerwebhookevent',
            index=models.Index(fields=['provider', 'event_type'], name='payments_pr_provide_c890e8_idx'),
        ),
        migrations.AddIndex(
            model_name='providerwebhookevent',
            index=models.Index(fields=['processing_status'], name='payments_pr_process_b6a669_idx'),
        ),
        migrations.AddIndex(
            model_name='providerwebhookevent',
            index=models.Index(fields=['payment_intent'], name='payments_pr_payment_9f6542_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='ppwe_unique_provider_event'),
        ),
    ]
