# Generated by Django 5.2.2 on 2026-06-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_processor', '0005_paymentrefund_applied_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentrefund',
            name='ppr_payment_intent_applied_at_idx',
        ),
    ]
