# Generated by Django 5.2.2 on 2026-06-22 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_processor', '0006_remove_paymentrefund_ppr_payment_intent_applied_at_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_attempts', models.PositiveSmallIntegerField(default=3, help_text='How many times a failed webhook delivery is retried.')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30, help_text='Maximum seconds to wait for a webhook endpoint to respond.')),
                ('signature_verification_enabled', models.BooleanField(default=True, help_text='Verify HMAC signatures on inbound webhook payloads.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Config',
            },
        ),
    ]
