# Generated by Django 5.2.2 on 2026-06-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_processor', '0007_add_webhook_config'),
        ('websites', '0011_add_portal_url_to_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='stripe', help_text="Provider name — must match a registered provider key (e.g. 'stripe').", max_length=32)),
                ('webhook_endpoint', models.CharField(default='/api/payments/webhooks/stripe/', help_text='Full path registered in the Stripe dashboard for this site, e.g. /api/payments/webhooks/stripe/', max_length=255)),
                ('callback_base_url', models.URLField(blank=True, default='', help_text='Base URL Stripe redirects clients to after checkout (e.g. https://app.gradecrest.com). Leave blank to fall back to Website.root_url.', max_length=255)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive gateways fall back to the platform default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_config_updates', to=settings.AUTH_USER_MODEL)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_config', to='websites.website')),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
            },
        ),
        migrations.CreateModel(
            name='PaymentNotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Finance team' or 'CEO'.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_notification_email_creations', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notification_emails', to='websites.website')),
            ],
            options={
                'verbose_name': 'Payment Notification Email',
                'verbose_name_plural': 'Payment Notification Emails',
                'ordering': ['website__name', 'email'],
                'unique_together': {('website', 'email')},
            },
        ),
    ]
