# Generated by Django 6.0.5 on 2026-05-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_blog', '0001_initial'),
        ('cms_service_pages', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogServiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('inline_natural', 'Inline natural link in body text'), ('inline_card', 'Inline call-out card mid-article'), ('end_cta', 'CTA block at end of post'), ('sidebar', 'Sticky sidebar callout'), ('after_intro', 'Soft mention after introduction')], max_length=30)),
                ('cta_text', models.CharField(help_text="The pitch text for this specific route, e.g., 'Need a custom care plan written by an RN? See our service →'", max_length=200)),
                ('is_primary_route', models.BooleanField(default=False, help_text='Is this the main conversion route for this blog post?')),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Times this link was rendered on a page view')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Times this link was clicked')),
                ('attributed_conversions', models.PositiveIntegerField(default=0, help_text='Orders attributed to this link')),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_routes', to='cms_blog.blogpostpage')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sources', to='cms_service_pages.servicepage')),
            ],
            options={
                'ordering': ['-is_primary_route', '-clicks'],
                'indexes': [models.Index(fields=['blog_post', 'service_page'], name='cms_content_blog_po_1684ca_idx'), models.Index(fields=['service_page', 'clicks'], name='cms_content_service_5d40ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Nursing Care Plans', 'APA Essay Writing'", max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_keywords', models.JSONField(blank=True, default=list, help_text='e.g., ["nursing care plan", "care plan template", "nursing care plan example"]')),
                ('spoke_count', models.PositiveIntegerField(default=0)),
                ('avg_gsc_position', models.FloatField(default=0.0)),
                ('total_clicks_30d', models.PositiveIntegerField(default=0)),
                ('total_conversions_30d', models.PositiveIntegerField(default=0)),
                ('attributed_revenue_30d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub_post', models.ForeignKey(blank=True, help_text='The flagship/comprehensive guide for this topic cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs_for', to='cms_blog.blogpostpage')),
                ('service_page', models.OneToOneField(help_text='The service page this pillar funnels traffic toward', on_delete=django.db.models.deletion.CASCADE, related_name='pillar', to='cms_service_pages.servicepage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pillars', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['-attributed_revenue_30d', 'name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('related', 'Related — same broad topic'), ('prerequisite', 'Prerequisite — read this first'), ('deepdive', 'Deep Dive — more detail on this aspect'), ('example', 'Example — concrete instance of the concept')], default='related', max_length=20)),
                ('strength', models.FloatField(default=0.7, help_text='0.0 to 1.0 — how relevant is this link?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='cms_blog.blogpostpage')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='cms_blog.blogpostpage')),
            ],
            options={
                'ordering': ['-strength'],
                'unique_together': {('from_post', 'to_post')},
            },
        ),
    ]
