# Generated by Django 5.1.5 on 2025-01-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the ticket.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the issue.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('awaiting_response', 'Awaiting Response')], default='open', help_text='Current status of the ticket.', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('payment', 'Payment Issues'), ('technical', 'Technical Support'), ('feedback', 'Feedback'), ('order', 'Order Issues')], default='general', help_text='Category of the ticket.', max_length=20)),
                ('is_escalated', models.BooleanField(default=False, help_text='Indicates if the ticket is escalated.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the ticket was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the ticket was last updated.')),
                ('created_by', models.ForeignKey(help_text='The user who created this ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, help_text='The user this ticket is directed to (admin/support only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_received', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='The website this ticket is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the message.')),
                ('is_internal', models.BooleanField(default=False, help_text='Indicates if this is an internal message (admins/support only).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this message was sent.')),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='The ticket this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
