# Generated by Django 5.1.5 on 2025-02-04 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('websites', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The admin/support user assigned to this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='website',
            field=models.ForeignKey(help_text='The website this ticket is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(help_text='The ticket this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='The ticket this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketstatistics',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stats', to='websites.website'),
        ),
    ]
