# Generated by Django 5.0.14 on 2025-10-29 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACCESS', 'Access')], help_text='Short name of the action performed.', max_length=10)),
                ('target', models.CharField(blank=True, help_text="Target model, e.g., 'orders.Order'.", max_length=200)),
                ('target_id', models.PositiveBigIntegerField(blank=True, help_text='Primary key of the target object.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional structured metadata about the action.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed.', null=True)),
                ('changes', models.JSONField(blank=True, help_text="What changed: {field: {'from': old, 'to': new}}.", null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string of the actor’s client.', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the audit log entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time the audit log entry was last updated.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the action occurred.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or comments about the action.')),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebhookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('webhook_url', models.URLField()),
                ('event', models.CharField(max_length=50)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('fallback_icon', models.URLField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
