# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_logging', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='webhookauditlog',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='webhookauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_user_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['actor', 'target', 'target_id'], name='audit_loggi_actor_i_c59e88_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action'], name='audit_loggi_action_269de5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['timestamp'], name='audit_loggi_timesta_7c5164_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookauditlog',
            index=models.Index(fields=['user'], name='audit_loggi_user_id_e8336a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookauditlog',
            index=models.Index(fields=['event'], name='audit_loggi_event_e7a565_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookauditlog',
            index=models.Index(fields=['was_successful'], name='audit_loggi_was_suc_5aa6dc_idx'),
        ),
    ]
