# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('order_configs', '0002_initial'),
        ('orders', '0001_initial'),
        ('pricing_configs', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedbacks', to='websites.website'),
        ),
        migrations.AddField(
            model_name='deadlinechangelog',
            name='changed_by',
            field=models.ForeignKey(help_text='User who changed the deadline.', on_delete=django.db.models.deletion.CASCADE, related_name='deadline_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadlinechangelog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_change_log', to='websites.website'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(blank=True, help_text='The user who raised the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dispute', to='websites.website'),
        ),
        migrations.AddField(
            model_name='disputewriterresponse',
            name='dispute',
            field=models.ForeignKey(help_text='The dispute being responded to.', on_delete=django.db.models.deletion.CASCADE, related_name='writer_responses_to_disputes', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='disputewriterresponse',
            name='responded_by',
            field=models.ForeignKey(help_text='The writer responding to the dispute.', limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_writer_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputewriterresponse',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_writer_response', to='websites.website'),
        ),
        migrations.AddField(
            model_name='order',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text='The academic level required.', null=True, on_delete=django.db.models.deletion.PROTECT, to='order_configs.academiclevel'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, help_text='The writer assigned to this order.', limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_writer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The client who placed this order.Leave blank for admin-created orders.', limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed the order.', limit_choices_to={'role__in': ['writer', 'editor', 'support', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='english_type',
            field=models.ForeignKey(blank=True, help_text='Preferred English style for the paper.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.englishtype'),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_services',
            field=models.ManyToManyField(blank=True, help_text='Additional services requested.', related_name='orders', to='pricing_configs.additionalservice'),
        ),
        migrations.AddField(
            model_name='order',
            name='formatting_style',
            field=models.ForeignKey(blank=True, help_text='The formatting style required.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.formattingandcitationstyle'),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_type',
            field=models.ForeignKey(help_text='The type of paper requested.', on_delete=django.db.models.deletion.PROTECT, to='order_configs.papertype'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_writer',
            field=models.ForeignKey(blank=True, help_text='Preferred writer for this order.', limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_order',
            field=models.ForeignKey(blank=True, help_text='Reference to the previous order this one follows up on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='The subject of the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.subject'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_work',
            field=models.ForeignKey(blank=True, help_text='The type of work requested.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.typeofwork'),
        ),
        migrations.AddField(
            model_name='order',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='websites.website'),
        ),
        migrations.AddField(
            model_name='order',
            name='writer_deadline_percentage',
            field=models.ForeignKey(blank=True, help_text='The Deadline the Writer sees', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_configs.writerdeadlineconfig'),
        ),
        migrations.AddField(
            model_name='order',
            name='writer_level',
            field=models.ForeignKey(blank=True, help_text='Selected writer quality level. eg. Standard, Premium.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing_configs.writerleveloptionconfig'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(help_text='The order associated with this dispute.', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deadlinechangelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpricingsnapshot',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_snapshot', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertransitionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordertransitionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferredwriterresponse',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='preferredwriterresponse',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_writer_decline_response', to='websites.website'),
        ),
        migrations.AddField(
            model_name='preferredwriterresponse',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_writer_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='preferred_writer',
            field=models.ForeignKey(blank=True, help_text='Optional preferred writer requested by the client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_reassignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin or system user who processed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignmentrequest',
            name='requester',
            field=models.ForeignKey(help_text='The actual user who made the request.', on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_logs_for_website', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='order',
            field=models.ForeignKey(help_text='The order associated with this progress log.', on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_progress', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='writer',
            field=models.ForeignKey(help_text='The writer associated with this progress log.', limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerreassignmentlog',
            name='new_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_gained', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerreassignmentlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='writerreassignmentlog',
            name='previous_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_lost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerreassignmentlog',
            name='reassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='writerrequest',
            name='requested_by_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writerrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_deadline_pages_request', to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='disputewriterresponse',
            unique_together={('dispute', 'responded_by')},
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['order', 'expires_at'], name='orders_orde_order_i_8ec5bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrequest',
            unique_together={('order', 'writer')},
        ),
        migrations.AlterUniqueTogether(
            name='writerprogress',
            unique_together={('writer', 'order', 'timestamp')},
        ),
    ]
