# Generated by Django 5.1.5 on 2025-01-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='admin_extended_deadline',
            field=models.DateTimeField(blank=True, help_text='If set, admin has manually extended the deadline.', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='writer_responded',
            field=models.BooleanField(default=False, help_text='Indicates whether the writer has responded to the dispute.'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(blank=True, help_text='The user who raised the dispute (admin, client, editor, support, superadmin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisputeWriterResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text="Writer's response or clarification.")),
                ('response_file', models.FileField(blank=True, help_text='Optional file upload for revised work.', null=True, upload_to='dispute_responses/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of response.')),
                ('dispute', models.ForeignKey(help_text='The dispute being responded to.', on_delete=django.db.models.deletion.CASCADE, related_name='writer_responses', to='orders.dispute')),
                ('responded_by', models.ForeignKey(help_text='The writer responding to the dispute.', limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_writer_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
