# Generated by Django 5.1.5 on 2025-01-29 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dispute_admin_extended_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='resolution_outcome',
            field=models.CharField(blank=True, choices=[('writer_wins', 'Writer Wins'), ('client_wins', 'Client Wins'), ('extend_deadline', 'Extend Deadline'), ('reassign', 'Reassign Order')], help_text='Outcome of the dispute resolution.', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='disputewriterresponse',
            unique_together={('dispute', 'responded_by')},
        ),
    ]
