# Generated by Django 5.1.6 on 2025-02-22 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='writerprogress',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='writerprogress',
            name='text_description',
            field=models.TextField(blank=True, help_text='Optional update details.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='writerprogress',
            unique_together={('writer', 'order', 'timestamp')},
        ),
        migrations.DeleteModel(
            name='FailedPayment',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
