# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_users', to='websites.website'),
        ),
        migrations.AddField(
            model_name='deletionsettings',
            name='website',
            field=models.ForeignKey(help_text='The website this deletion setting is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_settings', to='websites.website'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(help_text='The user whose email is being verified.', on_delete=django.db.models.deletion.CASCADE, related_name='user_email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='website',
            field=models.ForeignKey(help_text='The website this email verification is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_update_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(help_text='The user whose activity is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='users_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='website',
            field=models.ForeignKey(help_text='The website where the activity took place.', on_delete=django.db.models.deletion.CASCADE, related_name='website_activities', to='websites.website'),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='user',
            field=models.ForeignKey(help_text='The user whose action is being logged.', on_delete=django.db.models.deletion.CASCADE, related_name='users_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='website',
            field=models.ForeignKey(help_text='The website this audit log is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='user',
            field=models.ForeignKey(help_text='The user who has given consent.', on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='website',
            field=models.ForeignKey(help_text='The website this user consent is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to='websites.website'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(help_text='The user this permission is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='website',
            field=models.ForeignKey(help_text='The website this user permission is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='wbsite_user_permissions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_main_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.ForeignKey(blank=True, help_text='The website this user is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites_users_profiles', to='websites.website'),
        ),
    ]
