# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications_system', '0002_initial'),
        ('users', '0004_make_auditlog_website_nullable'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='website',
            field=models.ForeignKey(blank=True, help_text='The website this audit log is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['website'], name='users_user_website_9666be_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended'], name='users_user_is_susp_7493fe_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_blacklisted'], name='users_user_is_blac_9aa51c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_on_probation'], name='users_user_is_on_p_b00107_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='users_user_last_lo_5f84ec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['website', 'role'], name='users_user_website_c72345_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_suspended'], name='users_user_role_dc2e92_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['website', 'is_active'], name='users_user_website_fe6358_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'date_joined'], name='users_user_role_e20d41_idx'),
        ),
    ]
