# Generated by Django 5.0.14 on 2025-12-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_privacy_models'),
        ('users', '0005_alter_user_options_alter_userauditlog_website_and_more'),
    ]

    operations = [
    ]
