# Generated by Django 5.0.14 on 2025-12-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_profile_changes_privacy'),
        ('websites', '0007_website_guest_block_urgent_before_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('blog_posts', 'Blog Post Updates'), ('coupon_updates', 'Coupon Updates'), ('marketing_messages', 'Marketing Messages'), ('unread_messages', 'Unread Messages'), ('transactional_messages', 'Transactional Messages'), ('notifications', 'Notifications'), ('order_updates', 'Order Updates'), ('promotional_offers', 'Promotional Offers'), ('product_updates', 'Product Updates'), ('security_alerts', 'Security Alerts'), ('account_updates', 'Account Updates')], help_text='Type of subscription.', max_length=50)),
                ('is_subscribed', models.BooleanField(default=True, help_text='Whether the client is currently subscribed.')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the client first subscribed.')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the client unsubscribed, if applicable.', null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='When the last message of this type was sent.', null=True)),
                ('preferred_channels', models.JSONField(blank=True, default=list, help_text='Preferred delivery channels for this subscription type.')),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('monthly', 'Monthly Digest')], default='immediate', help_text='How frequently to receive messages.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Subscription',
                'verbose_name_plural': 'Client Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_subscriptions_enabled', models.BooleanField(default=True, help_text='Master switch for all subscriptions.')),
                ('marketing_consent', models.BooleanField(default=False, help_text='Consent to receive marketing communications.')),
                ('marketing_consent_date', models.DateTimeField(blank=True, help_text='When marketing consent was given.', null=True)),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email delivery.')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS delivery.')),
                ('push_enabled', models.BooleanField(default=False, help_text='Enable push notifications.')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications.')),
                ('dnd_enabled', models.BooleanField(default=False, help_text='Enable do-not-disturb hours.')),
                ('dnd_start_hour', models.PositiveSmallIntegerField(default=22, help_text='Do-not-disturb start hour (0-23).')),
                ('dnd_end_hour', models.PositiveSmallIntegerField(default=6, help_text='Do-not-disturb end hour (0-23).')),
                ('transactional_enabled', models.BooleanField(default=True, help_text='Transactional messages (cannot be disabled).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Preference',
                'verbose_name_plural': 'Subscription Preferences',
            },
        ),
        migrations.RenameIndex(
            model_name='clientprivacysettings',
            new_name='users_clien_user_id_1333ba_idx',
            old_name='users_client_user_website_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='users_dataa_user_id_32aa9b_idx',
            old_name='users_dataa_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='users_dataa_accesse_9a50d5_idx',
            old_name='users_dataa_access_idx',
        ),
        migrations.RenameIndex(
            model_name='loginalertpreference',
            new_name='users_login_user_id_35f491_idx',
            old_name='users_logina_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='penname',
            new_name='users_penna_user_id_9ad171_idx',
            old_name='users_penname_user_website_active_idx',
        ),
        migrations.RenameIndex(
            model_name='penname',
            new_name='users_penna_pen_nam_0f8993_idx',
            old_name='users_penname_pen_name_idx',
        ),
        migrations.RenameIndex(
            model_name='profilechangerequest',
            new_name='users_profi_user_id_62f1e4_idx',
            old_name='users_profil_user_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='profilechangerequest',
            new_name='users_profi_website_007916_idx',
            old_name='users_profil_website_status_idx',
        ),
        migrations.RenameIndex(
            model_name='profilechangerequest',
            new_name='users_profi_change__321534_idx',
            old_name='users_profil_change_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='writeravatarupload',
            new_name='users_write_user_id_027fc3_idx',
            old_name='users_writer_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='writeravatarupload',
            new_name='users_write_website_3a13cd_idx',
            old_name='users_writer_website_status_idx',
        ),
        migrations.RenameIndex(
            model_name='writerprivacysettings',
            new_name='users_write_user_id_09726a_idx',
            old_name='users_writer_user_website_idx',
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='user',
            field=models.ForeignKey(help_text='The client user who has this subscription.', limit_choices_to={'role__in': ['client', 'customer']}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='website',
            field=models.ForeignKey(help_text='The website this subscription is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='client_subscriptions', to='websites.website'),
        ),
        migrations.AddField(
            model_name='subscriptionpreference',
            name='user',
            field=models.OneToOneField(help_text='The client user.', limit_choices_to={'role__in': ['client', 'customer']}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpreference',
            name='website',
            field=models.ForeignKey(help_text='The website these preferences are for.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_preferences', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['user', 'website'], name='users_clien_user_id_f88d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['subscription_type', 'is_subscribed'], name='users_clien_subscri_af6fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['is_subscribed'], name='users_clien_is_subs_d52290_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientsubscription',
            unique_together={('user', 'website', 'subscription_type')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpreference',
            unique_together={('user', 'website')},
        ),
    ]
