# Generated by Django 5.0.14 on 2025-12-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clientsubscription_subscriptionpreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeravatarupload',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='writeravatarupload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='writeravatarupload',
            name='website',
        ),
        migrations.DeleteModel(
            name='ProfileChangeRequest',
        ),
        migrations.DeleteModel(
            name='WriterAvatarUpload',
        ),
    ]
