# Generated by Django 5.0.14 on 2025-12-21 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_writeravatarupload_approved_by_and_more'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('bio', 'Bio'), ('avatar', 'Avatar'), ('pen_name', 'Pen Name'), ('other', 'Other')], help_text='Type of profile change', max_length=50)),
                ('current_value', models.TextField(blank=True, help_text='Current value of the field being changed')),
                ('requested_value', models.TextField(help_text='Requested new value')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the request was approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the change was completed', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profile_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting profile change', on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to='websites.website')),
            ],
            options={
                'verbose_name': 'Profile Change Request',
                'verbose_name_plural': 'Profile Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='users_profi_user_id_62f1e4_idx'), models.Index(fields=['website', 'status'], name='users_profi_website_007916_idx'), models.Index(fields=['change_type', 'status'], name='users_profi_change__321534_idx')],
            },
        ),
        migrations.CreateModel(
            name='WriterAvatarUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_file', models.ImageField(help_text='Uploaded avatar file', upload_to='writer_avatars/pending/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_avatars', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Writer uploading the avatar', on_delete=django.db.models.deletion.CASCADE, related_name='avatar_uploads', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='avatar_uploads', to='websites.website')),
            ],
            options={
                'verbose_name': 'Writer Avatar Upload',
                'verbose_name_plural': 'Writer Avatar Uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_write_user_id_027fc3_idx'), models.Index(fields=['website', 'status'], name='users_write_website_3a13cd_idx')],
            },
        ),
    ]
