# Generated by Django 5.0.14 on 2025-12-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profilechangerequest_writeravatarupload'),
        ('websites', '0008_set_guest_checkout_safe_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('profile_update', 'Profile Update'), ('email_change', 'Email Change'), ('role_change', 'Role Change'), ('website_change', 'Website Change'), ('username_change', 'Username Change'), ('name_change', 'Name Change'), ('phone_change', 'Phone Number Change'), ('bio_change', 'Bio Change'), ('avatar_change', 'Avatar Change'), ('pen_name_change', 'Pen Name Change (Writers)'), ('other', 'Other')], help_text='Type of edit request', max_length=50)),
                ('field_changes', models.JSONField(help_text='Dictionary of field changes: {field: {old: value, new: value}}')),
                ('reason', models.TextField(blank=True, help_text="User's reason for the change request")),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by User')], default='pending', help_text='Current status of the request', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's notes or rejection reason")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the request was completed (approved/rejected)', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting the edit', on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website context', on_delete=django.db.models.deletion.CASCADE, related_name='user_edit_requests', to='websites.website')),
            ],
            options={
                'verbose_name': 'User Edit Request',
                'verbose_name_plural': 'User Edit Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='users_usere_user_id_0824c1_idx'), models.Index(fields=['website', 'status'], name='users_usere_website_2007af_idx'), models.Index(fields=['request_type', 'status'], name='users_usere_request_4bb02e_idx'), models.Index(fields=['status', '-created_at'], name='users_usere_status_3f8d84_idx')],
            },
        ),
    ]
