# Generated by Django 6.0.5 on 2026-05-28 08:38

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('bio', models.TextField(help_text='Public biography — displayed on author profile page')),
                ('credentials', models.CharField(blank=True, help_text="Displayed credentials, e.g. 'MSN, RN, CCRN'", max_length=255)),
                ('degrees', models.JSONField(blank=True, default=list, help_text='List of degrees: [{"degree": "MSN", "institution": "Johns Hopkins", "year": 2018, "verified": true}]')),
                ('licenses', models.JSONField(blank=True, default=list, help_text='List of professional licenses: [{"license": "RN", "state": "MD", "number": "R12345", "expires": "2027-06"}]')),
                ('areas_of_expertise', models.CharField(blank=True, help_text="Comma-separated areas, e.g. 'Pediatric Nursing, Care Plans, EBP'", max_length=500)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, help_text='Years of professional experience', null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID identifier, e.g. 0000-0002-1825-0097', max_length=50)),
                ('google_scholar_url', models.URLField(blank=True)),
                ('personal_website', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('senior_writer', 'Senior Writer'), ('editor', 'Editor'), ('subject_matter_expert', 'Subject Matter Expert'), ('clinical_reviewer', 'Clinical Reviewer')], default='writer', max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('show_publicly', models.BooleanField(default=True, help_text='Show on the public author index page')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='wagtailcore.site')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('site', 'slug')},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_page', to='cms_authors.author')),
            ],
            options={
                'verbose_name': 'Author Profile Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
