# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_authors', '0001_initial'),
        ('cms_service_pages', '0001_initial'),
        ('files_management', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_categories', to='wagtailcore.site')),
            ],
            options={
                'verbose_name_plural': 'Attachment Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('attachment_type', models.CharField(choices=[('sample_essay', 'Sample Essay/Paper'), ('template', 'Template (fillable)'), ('outline', 'Outline/Structure'), ('rubric', 'Rubric/Grading Guide'), ('checklist', 'Checklist'), ('worksheet', 'Worksheet/Exercise'), ('cheat_sheet', 'Cheat Sheet/Quick Reference'), ('guide', 'Comprehensive Guide'), ('infographic', 'Infographic'), ('study_guide', 'Study Guide'), ('reference_list', 'Reference List/Bibliography'), ('citation_examples', 'Citation Examples (APA/MLA/etc)'), ('formatting_guide', 'Formatting Guide'), ('case_study_template', 'Case Study Template'), ('research_proposal_template', 'Research Proposal Template'), ('thesis_template', 'Thesis/Dissertation Template'), ('care_plan_template', 'Nursing Care Plan Template'), ('soap_note_template', 'SOAP Note Template'), ('other', 'Other')], default='template', max_length=50)),
                ('file_format', models.CharField(blank=True, max_length=20)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('academic_level', models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate/Masters'), ('phd', 'PhD/Doctoral'), ('professional', 'Professional'), ('general', 'General/All Levels')], default='general', max_length=30)),
                ('subject_area', models.CharField(blank=True, help_text='e.g., Nursing, Business, Psychology', max_length=100)),
                ('formatting_style', models.CharField(choices=[('apa7', 'APA 7th Edition'), ('apa6', 'APA 6th Edition'), ('mla9', 'MLA 9th Edition'), ('chicago', 'Chicago/Turabian'), ('harvard', 'Harvard'), ('ieee', 'IEEE'), ('ama', 'AMA'), ('vancouver', 'Vancouver'), ('na', 'Not Applicable')], default='na', max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0, help_text='For sample essays/papers')),
                ('gate_type', models.CharField(choices=[('free', 'Free — no requirement'), ('email', 'Requires email signup'), ('account', 'Requires user account'), ('customer', 'Requires past order'), ('paid', 'Premium — paid only')], default='free', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Only for 'paid' gate type", max_digits=10, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('schema_type', models.CharField(choices=[('DigitalDocument', 'Digital Document'), ('LearningResource', 'Learning Resource'), ('CreativeWork', 'Creative Work')], default='DigitalDocument', max_length=30)),
                ('author_credentials', models.CharField(blank=True, help_text="e.g., 'MSN, RN, 10 years nursing education'", max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='Reviewed by editor, confirmed high quality')),
                ('is_featured', models.BooleanField(default=False)),
                ('average_rating', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('email_capture_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0, help_text='Downloads that led to orders')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_date', models.DateField(blank=True, help_text='When to review for accuracy (e.g., APA 6 → APA 7 transitions)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cms_authors.author')),
                ('managed_file', models.ForeignKey(blank=True, help_text='The actual downloadable file', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachment_uses', to='files_management.managedfile')),
                ('preview_file', models.ForeignKey(blank=True, help_text='Preview image or first-page thumbnail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_previews', to='files_management.managedfile')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cms_service_pages.servicepage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wagtailcore.site')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='cms_attachments.attachment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cms_attachments.attachmentcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-download_count', '-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AttachmentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Captured email if gated by email', max_length=254)),
                ('source_page_url', models.URLField(blank=True, help_text='The page the user was on when they clicked download')),
                ('referrer', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('converted_to_order', models.BooleanField(default=False)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='cms_attachments.attachment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='landing_page', to='cms_attachments.attachment')),
            ],
            options={
                'verbose_name': 'Attachment Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AttachmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cms_attachments.attachment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailGatedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_newsletter', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=1)),
                ('last_download', models.DateTimeField(auto_now=True)),
                ('converted', models.BooleanField(default=False)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_captures', to='cms_attachments.attachment')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_captures', to='wagtailcore.site')),
            ],
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['site', 'status', 'attachment_type'], name='cms_attachm_site_id_2d0abd_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['site', 'category', 'status'], name='cms_attachm_site_id_5a3fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['download_count'], name='cms_attachm_downloa_1af620_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('site', 'slug')},
        ),
        migrations.AddIndex(
            model_name='attachmentdownload',
            index=models.Index(fields=['attachment', 'created_at'], name='cms_attachm_attachm_181d76_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentdownload',
            index=models.Index(fields=['email'], name='cms_attachm_email_834b11_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachmentrating',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('attachment', 'user'), name='unique_attachment_rating_per_user'),
        ),
        migrations.AddIndex(
            model_name='emailgatedaccess',
            index=models.Index(fields=['site', 'email'], name='cms_attachm_site_id_c89679_idx'),
        ),
        migrations.AddIndex(
            model_name='emailgatedaccess',
            index=models.Index(fields=['site', 'converted'], name='cms_attachm_site_id_d2302b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailgatedaccess',
            unique_together={('site', 'email')},
        ),
    ]
