# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_rename_orders_order_status_idx_orders_orde_status_c6dd84_idx_and_more'),
        ('special_orders', '0003_installmentpayment_payment_record_and_more'),
        ('websites', '0001_initial'),
        ('writer_management', '0007_orderdispute_writerautoranking_writermessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOrderBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=2, help_text='Bonus amount for the special order.', max_digits=12)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('special_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_management_bonuses', to='special_orders.specialorder')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_order_bonuses', to='writer_management.writerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount.', max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus amount added.', max_digits=12)),
                ('fines', models.DecimalField(decimal_places=2, default=0.0, help_text='Any fines deducted.', max_digits=12)),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, help_text='Tips received from clients.', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Blocked', 'Blocked'), ('Delayed', 'Delayed'), ('Voided', 'Voided')], default='Pending', help_text='Payment status based on order conditions.', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, help_text='The order related to this payment.', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('special_order', models.ForeignKey(blank=True, help_text='The special order related to this payment.', null=True, on_delete=django.db.models.deletion.CASCADE, to='special_orders.specialorder')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_payment_management_payments', to='websites.website')),
                ('writer', models.ForeignKey(help_text='Writer receiving the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_management_payments', to='writer_management.writerprofile')),
            ],
            options={
                'unique_together': {('writer', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WriterPaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, help_text='Amount adjusted (positive or negative).', max_digits=12)),
                ('reason', models.TextField(help_text='Reason for adjustment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='Admin making the adjustment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_adjustments', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer_payment', models.ForeignKey(help_text='Payment entry being adjusted.', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='writer_payments_management.writerpayment')),
            ],
        ),
        migrations.CreateModel(
            name='WriterPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Requested payout amount.', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Payout request status.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
                ('writer', models.ForeignKey(help_text='Writer requesting the payout.', on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='writer_management.writerprofile')),
            ],
        ),
    ]
