# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0002_initial'),
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_d0cfbe_idx'),
        ('special_orders', '0002_initial'),
        ('websites', '0001_initial'),
        ('writer_compensation', '0001_initial'),
        ('writer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentrequest',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='advancerecovery',
            name='advance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='writer_compensation.advancepaymentrequest'),
        ),
        migrations.AddField(
            model_name='compensationadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_compensation_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensation_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationadjustment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_adjustments', to='websites.website'),
        ),
        migrations.AddField(
            model_name='compensationadjustment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_adjustments', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='related_event',
            field=models.ForeignKey(blank=True, help_text='Reversal or adjustment link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_events', to='websites.website'),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_events', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='compensationadjustment',
            name='related_financial_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='compensationeventlink',
            name='financial_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='compensationeventlink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_event_links', to='websites.website'),
        ),
        migrations.AddField(
            model_name='compensationstatetransitionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationstatetransitionlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transition_logs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='correctionevent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AddField(
            model_name='correctionevent',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='deferredsettlementitem',
            name='deferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_payment_deferrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deferredsettlementitem',
            name='financial_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='exposureledger',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_ledgers', to='websites.website'),
        ),
        migrations.AddField(
            model_name='exposureledger',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_ledgers', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='financialeventitem',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_items', to='class_management.classorder'),
        ),
        migrations.AddField(
            model_name='financialeventitem',
            name='compensation_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='financialeventitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='financialeventitem',
            name='special_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_items', to='special_orders.specialorder'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['key', 'scope'], name='writer_comp_key_b8a7af_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('key', 'scope'), name='unique_idempotency_key_scope'),
        ),
        migrations.AddField(
            model_name='milestonebonus',
            name='compensation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='milestonebonus',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_bonus_records', to='writer_management.writerprofile'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(fields=('event_type', 'payload_hash'), name='uniq_outbox_event_type_payload'),
        ),
        migrations.AddField(
            model_name='paymentwindow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_writer_payment_windows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentwindow',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writer_payment_windows', to='websites.website'),
        ),
        migrations.AddField(
            model_name='deferredsettlementitem',
            name='from_payment_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_deferrals', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='deferredsettlementitem',
            name='to_payment_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_deferrals', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='payment_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='related_window',
            field=models.ForeignKey(blank=True, help_text='Set when this event corrects something in a prior closed window. The event itself lives in the current open window.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_events', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='advancepaymentrequest',
            name='payment_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payout_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='payment_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payout_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches', to='websites.website'),
        ),
        migrations.AddField(
            model_name='payoutclearance',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payout_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutclearance',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_clearances', to='websites.website'),
        ),
        migrations.AddField(
            model_name='payoutreconciliationreport',
            name='payout_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_reports', to='writer_compensation.payoutbatch'),
        ),
        migrations.AddField(
            model_name='payoutreconciliationreport',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_reconciliation_reports', to='websites.website'),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='writer_compensation.payoutbatch'),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payout_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payout_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_records', to='websites.website'),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_records', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='payoutclearance',
            name='payout_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='writer_compensation.payoutrecord'),
        ),
        migrations.AddField(
            model_name='performancebonussnapshot',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_bonus_snapshots', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='ratecardsnapshot',
            name='order',
            field=models.OneToOneField(help_text='The order this snapshot was captured for. OneToOne — one snapshot per order, always.', on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_snapshot', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ratecardsnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='ratecardsnapshot',
            name='writer',
            field=models.ForeignKey(help_text='The writer this rate card applied to.', on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_snapshots', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='compensation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='referred_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_referral_bonuses', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_records', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='reputationreward',
            name='compensation_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_reward', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='reputationreward',
            name='performance_metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_rewards', to='writer_management.writerperformancemetrics'),
        ),
        migrations.AddField(
            model_name='reputationreward',
            name='performance_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_rewards', to='writer_management.writerperformancesnapshot'),
        ),
        migrations.AddField(
            model_name='reputationreward',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_rewards', to='websites.website'),
        ),
        migrations.AddField(
            model_name='reputationreward',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_rewards', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='retentionbonus',
            name='compensation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='retentionbonus',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_bonus_records', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='reversalchain',
            name='original_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_origins', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='reversalchain',
            name='reversal_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_targets', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='reversalchain',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_chains', to='websites.website'),
        ),
        migrations.AddField(
            model_name='rewardanalyticssnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_analytics_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='rewardrule',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='websites.website'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='financial_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_writer_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='payment_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_settlement_periods', to='websites.website'),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_periods', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='settlement_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='writer_compensation.settlementperiod'),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='settlement_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_records', to='writer_compensation.settlementperiod'),
        ),
        migrations.AddField(
            model_name='compensationevent',
            name='settlement_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to='writer_compensation.settlementperiod'),
        ),
        migrations.AddField(
            model_name='advancerecovery',
            name='settlement_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_recoveries', to='writer_compensation.settlementperiod'),
        ),
        migrations.AddField(
            model_name='settlementrulesnapshot',
            name='settlement_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_snapshot', to='writer_compensation.settlementperiod'),
        ),
        migrations.AddField(
            model_name='settlementrulesnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_rule_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerbalancesnapshot',
            name='payment_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_snapshots', to='writer_compensation.paymentwindow'),
        ),
        migrations.AddField(
            model_name='writerbalancesnapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_balance_snapshots', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerbalancesnapshot',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='compensation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='writerbonus',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerpayoutpreference',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writer_payout_preferences', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerpayoutpreference',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_preferences', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerreputationbonus',
            name='compensation_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_bonus', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='writerreputationbonus',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_bonuses', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerreputationbonus',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_bonuses', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writerreward',
            name='compensation_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_reward', to='writer_compensation.compensationevent'),
        ),
        migrations.AddField(
            model_name='writerreward',
            name='reward_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_rewards', to='writer_compensation.rewardrule'),
        ),
        migrations.AddField(
            model_name='writerreward',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_writer_rewards', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writerreward',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rewards', to='writer_management.writerprofile'),
        ),
        migrations.AddField(
            model_name='writertrustscore',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_trust_scores', to='websites.website'),
        ),
        migrations.AddField(
            model_name='writertrustscore',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='writer_management.writerprofile'),
        ),
        migrations.AddIndex(
            model_name='compensationadjustment',
            index=models.Index(fields=['writer', 'adjustment_type'], name='writer_comp_writer__2e24ef_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationadjustment',
            index=models.Index(fields=['website', 'writer'], name='writer_comp_website_c89f10_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationeventlink',
            index=models.Index(fields=['content_type', 'object_id'], name='writer_comp_content_85335e_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationeventlink',
            index=models.Index(fields=['financial_event'], name='writer_comp_financi_4048f3_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationstatetransitionlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='writer_comp_entity__1307c8_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationstatetransitionlog',
            index=models.Index(fields=['from_state', 'to_state'], name='writer_comp_from_st_55290a_idx'),
        ),
        migrations.AddIndex(
            model_name='exposureledger',
            index=models.Index(fields=['writer'], name='writer_comp_writer__4acc1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exposureledger',
            unique_together={('website', 'writer')},
        ),
        migrations.AddIndex(
            model_name='financialeventitem',
            index=models.Index(fields=['item_type'], name='writer_comp_item_ty_ab9c66_idx'),
        ),
        migrations.AddIndex(
            model_name='financialeventitem',
            index=models.Index(fields=['compensation_event'], name='writer_comp_compens_324dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='milestonebonus',
            index=models.Index(fields=['writer', 'milestone'], name='writer_mile_writer__9c7f16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestonebonus',
            unique_together={('writer', 'milestone')},
        ),
        migrations.AddIndex(
            model_name='paymentwindow',
            index=models.Index(fields=['website', 'status'], name='writer_comp_website_727d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwindow',
            index=models.Index(fields=['cycle_type'], name='writer_comp_cycle_t_e967ea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwindow',
            index=models.Index(fields=['website', 'start_date', 'end_date'], name='writer_comp_website_8a9858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentwindow',
            unique_together={('website', 'start_date', 'cycle_type')},
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['website', 'status'], name='writer_comp_website_7e5610_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['payment_window'], name='writer_comp_payment_fd5ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='performancebonussnapshot',
            index=models.Index(fields=['writer', 'order_id'], name='writer_perf_writer__6331df_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecardsnapshot',
            index=models.Index(fields=['writer', 'snapshotted_at'], name='rate_snapshot_writer_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecardsnapshot',
            index=models.Index(fields=['website', 'snapshotted_at'], name='rate_snapshot_site_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratecardsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('base_pay_per_page__gte', Decimal('0.00'))), name='rate_snapshot_base_page_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ratecardsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('urgent_multiplier__gte', Decimal('1.00'))), name='rate_snapshot_urgency_multiplier_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ratecardsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('tip_percentage__gte', Decimal('0.00')), ('tip_percentage__lte', Decimal('100.00'))), name='rate_snapshot_tip_pct_range'),
        ),
        migrations.AddIndex(
            model_name='referralbonus',
            index=models.Index(fields=['referrer', 'referred_writer'], name='writer_refe_referre_39eab0_idx'),
        ),
        migrations.AddIndex(
            model_name='referralbonus',
            index=models.Index(fields=['order'], name='writer_refe_order_i_aecc51_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationreward',
            index=models.Index(fields=['website', 'writer'], name='rep_reward_site_writer_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationreward',
            index=models.Index(fields=['reward_reason', 'awarded_at'], name='rep_reward_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='reputationreward',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='rep_reward_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='retentionbonus',
            index=models.Index(fields=['writer', 'month'], name='writer_rete_writer__6bd267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retentionbonus',
            unique_together={('writer', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='rewardanalyticssnapshot',
            unique_together={('website', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['website', 'is_active'], name='reward_rule_active_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['website', 'rule_type', 'is_active'], name='reward_rule_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.UniqueConstraint(fields=('website', 'slug'), name='unique_reward_rule_slug_per_website'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.CheckConstraint(condition=models.Q(('reward_amount__gte', Decimal('0.00'))), name='reward_rule_reward_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_avg_rating__isnull', True), models.Q(('minimum_avg_rating__gte', Decimal('0.00')), ('minimum_avg_rating__lte', Decimal('5.00'))), _connector='OR'), name='reward_rule_avg_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_percentile_rank__isnull', True), models.Q(('minimum_percentile_rank__gte', Decimal('0.00')), ('minimum_percentile_rank__lte', Decimal('100.00'))), _connector='OR'), name='reward_rule_percentile_range'),
        ),
        migrations.AddIndex(
            model_name='settlementperiod',
            index=models.Index(fields=['website', 'status'], name='writer_comp_website_4bbdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementperiod',
            index=models.Index(fields=['writer', 'payment_window'], name='writer_comp_writer__2a3e66_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementperiod',
            index=models.Index(fields=['payment_window', 'status'], name='writer_comp_payment_12fd8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settlementperiod',
            unique_together={('writer', 'payment_window')},
        ),
        migrations.AlterUniqueTogether(
            name='settlementitem',
            unique_together={('settlement_period', 'financial_event')},
        ),
        migrations.AddIndex(
            model_name='payoutrecord',
            index=models.Index(fields=['batch', 'status'], name='writer_comp_batch_i_c997f2_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrecord',
            index=models.Index(fields=['writer', 'status'], name='writer_comp_writer__b8e4f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payoutrecord',
            unique_together={('batch', 'writer')},
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['website', 'writer'], name='writer_comp_website_0029e8_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['writer', 'payment_window'], name='writer_comp_writer__6f9ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['writer', 'status'], name='writer_comp_writer__b27219_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['event_type', 'status'], name='writer_comp_event_t_cc307f_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['created_at'], name='writer_comp_created_f3fc36_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['source_type', 'source_id'], name='writer_comp_source__170469_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['website', 'writer', 'created_at'], name='writer_comp_website_ee4e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationevent',
            index=models.Index(fields=['website', 'writer', 'status', 'settlement_period'], name='comp_evt_settle_idx'),
        ),
        migrations.AddConstraint(
            model_name='compensationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('website', 'writer', 'idempotency_key'), name='unique_compensation_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='compensationevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('0.00')), _negated=True), name='compensation_event_amount_non_zero'),
        ),
        migrations.AddIndex(
            model_name='writerbalancesnapshot',
            index=models.Index(fields=['writer', 'captured_at'], name='writer_comp_writer__a0e8af_idx'),
        ),
        migrations.AddIndex(
            model_name='writerbalancesnapshot',
            index=models.Index(fields=['website', 'writer'], name='writer_comp_website_935860_idx'),
        ),
        migrations.AddIndex(
            model_name='writerbonus',
            index=models.Index(fields=['writer', 'bonus_type'], name='writer_bonu_writer__889560_idx'),
        ),
        migrations.AddIndex(
            model_name='writerbonus',
            index=models.Index(fields=['idempotency_key'], name='writer_bonu_idempot_a82989_idx'),
        ),
        migrations.AddIndex(
            model_name='writerbonus',
            index=models.Index(fields=['created_at'], name='writer_bonu_created_9ba6cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writerpayoutpreference',
            unique_together={('website', 'writer')},
        ),
        migrations.AddIndex(
            model_name='writerreputationbonus',
            index=models.Index(fields=['writer', 'awarded_at'], name='rep_bonus_writer_time_idx'),
        ),
        migrations.AddIndex(
            model_name='writerreputationbonus',
            index=models.Index(fields=['tier', 'awarded_at'], name='rep_bonus_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='writerreward',
            index=models.Index(fields=['website', 'writer'], name='writer_reward_writer_idx'),
        ),
        migrations.AddIndex(
            model_name='writerreward',
            index=models.Index(fields=['website', 'status'], name='writer_reward_status_idx'),
        ),
        migrations.AddIndex(
            model_name='writerreward',
            index=models.Index(fields=['writer', 'issued_at'], name='writer_reward_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='writerreward',
            index=models.Index(fields=['reward_rule', 'issued_at'], name='writer_reward_rule_idx'),
        ),
        migrations.AddConstraint(
            model_name='writerreward',
            constraint=models.CheckConstraint(condition=models.Q(('reward_amount__gte', Decimal('0.00'))), name='writer_reward_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='writerreward',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__isnull', True), models.Q(('average_rating__gte', Decimal('0.00')), ('average_rating__lte', Decimal('5.00'))), _connector='OR'), name='writer_reward_avg_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='writerreward',
            constraint=models.CheckConstraint(condition=models.Q(('percentile_rank__isnull', True), models.Q(('percentile_rank__gte', Decimal('0.00')), ('percentile_rank__lte', Decimal('100.00'))), _connector='OR'), name='writer_reward_percentile_range'),
        ),
        migrations.AddConstraint(
            model_name='writerreward',
            constraint=models.CheckConstraint(condition=models.Q(('composite_score__isnull', True), ('composite_score__gte', Decimal('0.00')), _connector='OR'), name='writer_reward_composite_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='writerreward',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__isnull', True), ('period_end__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='writer_reward_period_valid'),
        ),
        migrations.AddIndex(
            model_name='writertrustscore',
            index=models.Index(fields=['website', 'score'], name='trust_site_score_idx'),
        ),
        migrations.AddIndex(
            model_name='writertrustscore',
            index=models.Index(fields=['website', 'percentile_rank'], name='trust_percentile_idx'),
        ),
        migrations.AddConstraint(
            model_name='writertrustscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', Decimal('0.00')), ('score__lte', Decimal('100.00'))), name='writer_trust_score_range'),
        ),
    ]
