# Generated by Django 5.2.2 on 2026-07-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_compensation', '0003_alter_payoutclearance_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerpayoutpreference',
            name='cycle_type',
            field=models.CharField(choices=[('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='BIWEEKLY', max_length=16),
        ),
    ]
