# Generated by Django 5.0.14 on 2025-12-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number for this config')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('config_data', models.JSONField(help_text='Complete snapshot of configuration at this version')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('restored', 'Restored')], default='updated', help_text='Type of change that created this version', max_length=20)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of what changed in this version', null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, help_text='List of field names that were changed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this version', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current active version')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_versions_created', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, help_text='Previous version (for version chain)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='core.configversion')),
            ],
            options={
                'verbose_name': 'Configuration Version',
                'verbose_name_plural': 'Configuration Versions',
                'ordering': ['-version_number', '-created_at'],
                'indexes': [
                    models.Index(fields=['content_type', 'object_id'], name='core_config_content_887fc9_idx'),
                    models.Index(fields=['content_type', 'object_id', 'version_number'], name='core_config_content_6ad913_idx'),
                    models.Index(fields=['created_at'], name='core_config_created_a29433_idx')
                ],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
