# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.CharField(help_text="Unique identifier for this card (e.g., 'total_orders', 'total_revenue')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Card title/label', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Card description or help text')),
                ('icon', models.CharField(default='📊', help_text='Emoji or icon identifier', max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('indigo', 'Indigo'), ('teal', 'Teal')], default='blue', help_text='Card color theme', max_length=20)),
                ('data_source', models.CharField(help_text="API endpoint or data source path (e.g., 'dashboardData.total_orders')", max_length=200)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percentage', 'Percentage'), ('text', 'Text')], default='number', help_text='Type of data to display', max_length=20)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="List of roles that can see this card (e.g., ['admin', 'superadmin'])")),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is active')),
                ('badge_text', models.CharField(blank=True, help_text="Badge text to show in card footer (e.g., 'All time', 'Last 30 days')", max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration (formatting options, calculations, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Card Configuration',
                'verbose_name_plural': 'Dashboard Card Configurations',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFontConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default="'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", help_text='CSS font-family value', max_length=100)),
                ('font_url', models.URLField(blank=True, help_text='URL to load font from (e.g., Google Fonts)')),
                ('base_font_size', models.CharField(default='16px', help_text='Base font size', max_length=20)),
                ('card_value_font_size', models.CharField(default='clamp(24px, 3vw, 32px)', help_text='Card value font size (CSS clamp or fixed)', max_length=50)),
                ('card_label_font_size', models.CharField(default='13px', help_text='Card label font size', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Font Configuration',
                'verbose_name_plural': 'Dashboard Font Configurations',
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number for this config')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('config_data', models.JSONField(help_text='Complete snapshot of configuration at this version')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('restored', 'Restored')], default='updated', help_text='Type of change that created this version', max_length=20)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of what changed in this version', null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, help_text='List of field names that were changed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this version', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current active version')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Configuration Version',
                'verbose_name_plural': 'Configuration Versions',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
    ]
