# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configversion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configversion',
            name='previous_version',
            field=models.ForeignKey(blank=True, help_text='Previous version (for version chain)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='core.configversion'),
        ),
        migrations.AddField(
            model_name='dashboardcardconfig',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website-specific card (null = all websites)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='websites.website'),
        ),
        migrations.AddField(
            model_name='dashboardfontconfig',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Website-specific font config (null = default for all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_fonts', to='websites.website'),
        ),
        migrations.AddIndex(
            model_name='configversion',
            index=models.Index(fields=['content_type', 'object_id'], name='core_config_content_887fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='configversion',
            index=models.Index(fields=['content_type', 'object_id', 'version_number'], name='core_config_content_6ad913_idx'),
        ),
        migrations.AddIndex(
            model_name='configversion',
            index=models.Index(fields=['created_at'], name='core_config_created_a29433_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configversion',
            unique_together={('content_type', 'object_id', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='dashboardcardconfig',
            index=models.Index(fields=['card_key', 'is_active'], name='core_dashbo_card_ke_1faf74_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardcardconfig',
            index=models.Index(fields=['website', 'is_active'], name='core_dashbo_website_58e9d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardfontconfig',
            unique_together={('website',)},
        ),
    ]
