# Generated by Django 5.0.14 on 2025-12-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_config_version_only'),
        ('websites', '0011_add_external_review_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.CharField(help_text="Unique identifier for this card (e.g., 'total_orders', 'total_revenue')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Card title/label', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Card description or help text')),
                ('icon', models.CharField(default='📊', help_text='Emoji or icon identifier', max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('indigo', 'Indigo'), ('teal', 'Teal')], default='blue', help_text='Card color theme', max_length=20)),
                ('data_source', models.CharField(help_text="API endpoint or data source path (e.g., 'dashboardData.total_orders')", max_length=200)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percentage', 'Percentage'), ('text', 'Text')], default='number', help_text='Type of data to display', max_length=20)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="List of roles that can see this card (e.g., ['admin', 'superadmin'])")),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is active')),
                ('badge_text', models.CharField(blank=True, help_text="Badge text to show in card footer (e.g., 'All time', 'Last 30 days')", max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration (formatting options, calculations, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(blank=True, help_text='Website-specific card (null = all websites)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='websites.website')),
            ],
            options={
                'verbose_name': 'Dashboard Card Configuration',
                'verbose_name_plural': 'Dashboard Card Configurations',
                'ordering': ['position', 'title'],
                'indexes': [models.Index(fields=['card_key', 'is_active'], name='core_dashbo_card_ke_1faf74_idx'), models.Index(fields=['website', 'is_active'], name='core_dashbo_website_58e9d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardFontConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default="'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", help_text='CSS font-family value', max_length=100)),
                ('font_url', models.URLField(blank=True, help_text='URL to load font from (e.g., Google Fonts)')),
                ('base_font_size', models.CharField(default='16px', help_text='Base font size', max_length=20)),
                ('card_value_font_size', models.CharField(default='clamp(24px, 3vw, 32px)', help_text='Card value font size (CSS clamp or fixed)', max_length=50)),
                ('card_label_font_size', models.CharField(default='13px', help_text='Card label font size', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(blank=True, help_text='Website-specific font config (null = default for all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_fonts', to='websites.website')),
            ],
            options={
                'verbose_name': 'Dashboard Font Configuration',
                'verbose_name_plural': 'Dashboard Font Configurations',
                'unique_together': {('website',)},
            },
        ),
    ]
