# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('client', 'Client'), ('writer', 'Writer')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='websites.website')),
            ],
            options={
                'db_table': 'wallets_wallet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('funding', 'Funding'), ('referral_bonus', 'Referral Bonus'), ('loyalty_conversion', 'Loyalty Conversion'), ('order_payment', 'Order Payment'), ('order_refund', 'Order Refund'), ('earning', 'Earning'), ('bonus', 'Bonus'), ('penalty', 'Penalty'), ('fine', 'Fine'), ('deduction', 'Deduction'), ('admin_adjustment', 'Admin Adjustment'), ('admin_credit', 'Admin Credit'), ('admin_debit', 'Admin Debit'), ('hold', 'Hold'), ('hold_release', 'Hold Release'), ('hold_capture', 'Hold Capture'), ('payout_reserve', 'Payout Reserve'), ('payout_release', 'Payout Release'), ('payout_settled', 'Payout Settled'), ('writer_earning', 'Writer Earning')], max_length=50)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='posted', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet_entries', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='ledger.journalentry')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallets.wallet')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_entries', to='websites.website')),
            ],
            options={
                'db_table': 'wallets_wallet_entry',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WalletHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('captured', 'Captured'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet_holds', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='wallets.wallet')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_holds', to='websites.website')),
            ],
            options={
                'db_table': 'wallets_wallet_hold',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['website', 'owner_user'], name='wallets_wal_website_8c798d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_type', 'status'], name='wallets_wal_wallet__6d8efb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='wallets_wal_currenc_7dd088_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('website', 'owner_user', 'wallet_type', 'currency'), name='wallets_unique_wallet_per_owner_type_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallets_available_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('pending_balance__gte', 0)), name='wallets_pending_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_credited__gte', 0)), name='wallets_total_credited_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_debited__gte', 0)), name='wallets_total_debited_gte_0'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['website', 'wallet'], name='wallets_wal_website_e46a00_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['entry_type', 'status'], name='wallets_wal_entry_t_160e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallets_wal_referen_3b6229_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['created_at'], name='wallets_wal_created_7878ce_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['website', 'wallet'], name='wallets_wal_website_beee0f_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['status'], name='wallets_wal_status_df5466_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallets_wal_referen_b61218_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['expires_at'], name='wallets_wal_expires_273b09_idx'),
        ),
    ]
