# Generated by Django 5.2.2 on 2026-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletentry_client_disclosure_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletentry',
            name='disclosure_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
