# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0001_initial'),
        ('wallet', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classbundle',
            name='client',
            field=models.ForeignKey(help_text='Client who bought the bundle', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classbundleconfig',
            name='website',
            field=models.ForeignKey(help_text='Website this config applies to', on_delete=django.db.models.deletion.CASCADE, related_name='class_configs', to='websites.website'),
        ),
        migrations.AddField(
            model_name='classbundle',
            name='config',
            field=models.ForeignKey(help_text='Base pricing config used', on_delete=django.db.models.deletion.PROTECT, to='class_management.classbundleconfig'),
        ),
        migrations.AddField(
            model_name='classdurationoption',
            name='website',
            field=models.ForeignKey(help_text='Website-specific duration choice', on_delete=django.db.models.deletion.CASCADE, related_name='duration_options', to='websites.website'),
        ),
        migrations.AddField(
            model_name='classbundleconfig',
            name='duration',
            field=models.ForeignKey(help_text='Target class duration option', on_delete=django.db.models.deletion.PROTECT, to='class_management.classdurationoption'),
        ),
        migrations.AddField(
            model_name='classinstallment',
            name='class_bundle',
            field=models.ForeignKey(help_text='Target class bundle', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='class_management.classbundle'),
        ),
        migrations.AddField(
            model_name='classinstallment',
            name='paid_by',
            field=models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classpurchase',
            name='bundle',
            field=models.ForeignKey(help_text='Target class bundle', on_delete=django.db.models.deletion.PROTECT, to='class_management.classbundle'),
        ),
        migrations.AddField(
            model_name='classpurchase',
            name='client',
            field=models.ForeignKey(help_text='Purchasing user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expressclass',
            name='client',
            field=models.ForeignKey(help_text='Client booking the express class', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_purchase',
            field=models.ForeignKey(blank=True, help_text='Purchase tied to this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_management.classpurchase'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='User wallet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_management_wallet_transactions', to='wallet.wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='classdurationoption',
            unique_together={('website', 'class_code')},
        ),
        migrations.AlterUniqueTogether(
            name='classbundleconfig',
            unique_together={('duration', 'level', 'bundle_size')},
        ),
    ]
