# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField(help_text='Points deducted for this redemption')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the redemption request', max_length=20)),
                ('fulfillment_code', models.CharField(blank=True, help_text='Generated code/voucher for fulfillment (e.g., discount code)', max_length=100, null=True)),
                ('fulfillment_details', models.JSONField(blank=True, default=dict, help_text='Additional fulfillment details (e.g., tracking number, delivery address)')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Redemption Request',
                'verbose_name_plural': 'Redemption Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(help_text="Name of the badge (e.g., 'Top Spender').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Details about why this badge was awarded.', null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, help_text='When this badge was awarded.')),
                ('client', models.ForeignKey(help_text='Client who earned this badge.', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='client_management.clientprofile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_badges', to='websites.website')),
            ],
            options={
                'verbose_name': 'Client Badge',
                'verbose_name_plural': 'Client Badges',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('points_issued', 'Points Issued Over Time'), ('redemptions_trend', 'Redemptions Trend'), ('tier_distribution', 'Loyalty Tier Distribution'), ('top_redemptions', 'Top Redemption Items'), ('engagement_rate', 'Client Engagement Rate'), ('points_balance', 'Total Points Balance'), ('conversion_rate', 'Points to Wallet Conversion')], help_text='Type of widget to display', max_length=50)),
                ('title', models.CharField(help_text='Widget title', max_length=200)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display position on dashboard')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether widget is visible')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget configuration (chart type, date range, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='websites.website')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointsConversionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=Decimal('0.1'), help_text='Number of loyalty points earned per dollar spent.', max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Rate at which loyalty points are converted to wallet balance.', max_digits=5)),
                ('min_conversion_points', models.PositiveIntegerField(default=100, help_text='Minimum number of points required for conversion.')),
                ('max_conversion_limit', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Maximum limit for conversion in wallet balance.', max_digits=12)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether loyalty points conversion is currently enabled.')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points_conversion_config', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the loyalty tier (e.g., Bronze, Silver, Gold).', max_length=50, unique=True)),
                ('threshold', models.PositiveIntegerField(help_text='Minimum points required to qualify for this tier.')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for clients in this tier.', max_digits=4)),
                ('perks', models.TextField(blank=True, help_text='Additional perks or benefits for this tier.', null=True)),
                ('website', models.ForeignKey(help_text='Website this tier is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='websites.website')),
            ],
            options={
                'verbose_name': 'Loyalty Tier',
                'verbose_name_plural': 'Loyalty Tiers',
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Number of points added, redeemed, or deducted.')),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('redeem', 'Redeem'), ('deduct', 'Deduct')], default='add', help_text='Type of transaction (add, redeem, deduct).', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the loyalty transaction.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the transaction was recorded.')),
                ('client', models.ForeignKey(help_text='Client associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='client_management.clientprofile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions_for_website', to='websites.website')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the milestone (e.g., 'First $100 Spent').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Details about the milestone.', null=True)),
                ('target_type', models.CharField(choices=[('total_spent', 'Total Spent'), ('loyalty_points', 'Loyalty Points'), ('orders_placed', 'Orders Placed')], help_text='Type of milestone (e.g., total spent, loyalty points).', max_length=50)),
                ('target_value', models.PositiveIntegerField(help_text='Value the client must achieve to earn this milestone.')),
                ('reward_points', models.PositiveIntegerField(default=0, help_text='Loyalty points rewarded upon achieving this milestone.Set to 0 for no reward.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this milestone was created.')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_achieveable', to='websites.website')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['target_value'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Discounts', 'Products', 'Services')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this redemption category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active for redemptions')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order for categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_categories', to='websites.website')),
            ],
            options={
                'verbose_name': 'Redemption Category',
                'verbose_name_plural': 'Redemption Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the redemption item (e.g., '$10 Discount', 'Free Writing Service')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what the client receives')),
                ('points_required', models.PositiveIntegerField(help_text='Number of loyalty points required for redemption')),
                ('redemption_type', models.CharField(choices=[('discount', 'Discount Code'), ('cash', 'Cash/Wallet Credit'), ('product', 'Physical Product'), ('service', 'Service Credit'), ('voucher', 'Voucher/Code')], default='discount', help_text='Type of redemption item', max_length=20)),
                ('discount_code', models.CharField(blank=True, help_text='Discount code to generate/apply (for discount type)', max_length=50, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount in dollars (for discount/cash types)', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (for discount type)', max_digits=5, null=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text='Available stock (None = unlimited)', null=True)),
                ('total_redemptions', models.PositiveIntegerField(default=0, help_text='Total number of times this item has been redeemed')),
                ('max_per_client', models.PositiveIntegerField(default=1, help_text='Maximum times a single client can redeem this item')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is available for redemption')),
                ('image_url', models.URLField(blank=True, help_text='Image URL for the redemption item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this redemption item belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='loyalty_management.redemptioncategory')),
                ('min_tier_level', models.ForeignKey(blank=True, help_text='Minimum loyalty tier required to redeem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_items_requiring_tier', to='loyalty_management.loyaltytier')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_items', to='websites.website')),
            ],
            options={
                'verbose_name': 'Redemption Item',
                'verbose_name_plural': 'Redemption Items',
                'ordering': ['category', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_active_clients', models.PositiveIntegerField(default=0, help_text='Total clients with loyalty points')),
                ('total_points_issued', models.PositiveIntegerField(default=0, help_text='Total points issued in period')),
                ('total_points_redeemed', models.PositiveIntegerField(default=0, help_text='Total points redeemed in period')),
                ('total_points_balance', models.PositiveIntegerField(default=0, help_text='Total outstanding points balance')),
                ('total_redemptions', models.PositiveIntegerField(default=0, help_text='Total number of redemptions')),
                ('total_redemption_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of redemptions (in points)', max_digits=12)),
                ('bronze_count', models.PositiveIntegerField(default=0)),
                ('silver_count', models.PositiveIntegerField(default=0)),
                ('gold_count', models.PositiveIntegerField(default=0)),
                ('platinum_count', models.PositiveIntegerField(default=0)),
                ('active_redemptions_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of active clients who redeemed', max_digits=5)),
                ('average_points_per_client', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_analytics', to='websites.website')),
                ('most_popular_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_as_popular', to='loyalty_management.redemptionitem')),
            ],
            options={
                'verbose_name': 'Loyalty Analytics',
                'verbose_name_plural': 'Loyalty Analytics',
                'ordering': ['-date_to', '-date_from'],
            },
        ),
    ]
