# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0002_initial'),
        ('loyalty_management', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this redemption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='client_management.clientprofile'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, help_text='Admin who fulfilled this redemption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='loyalty_management.redemptionitem'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='redemption_request',
            field=models.ForeignKey(blank=True, help_text='Associated redemption request if this is a redemption transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty_management.redemptionrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='clientbadge',
            unique_together={('client', 'badge_name', 'website')},
        ),
        migrations.AddConstraint(
            model_name='redemptioncategory',
            constraint=models.UniqueConstraint(fields=('website', 'name'), name='unique_category_per_website'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyanalytics',
            constraint=models.UniqueConstraint(fields=('website', 'date_from', 'date_to'), name='unique_analytics_per_website_date_range'),
        ),
    ]
