# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_add_default_registration_id'),
        ('loyalty_management', '0005_add_min_tier_level'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardwidget',
            options={'ordering': ['position', 'title'], 'verbose_name': 'Dashboard Widget', 'verbose_name_plural': 'Dashboard Widgets'},
        ),
        migrations.AlterModelOptions(
            name='redemptionitem',
            options={'ordering': ['category', 'points_required'], 'verbose_name': 'Redemption Item', 'verbose_name_plural': 'Redemption Items'},
        ),
        migrations.AlterUniqueTogether(
            name='clientbadge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='redemptionitem',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display position on dashboard'),
        ),
        migrations.AlterField(
            model_name='clientbadge',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_badges', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Widget configuration (chart type, date range, etc.)'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether widget is visible'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='title',
            field=models.CharField(help_text='Widget title', max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('points_issued', 'Points Issued Over Time'), ('redemptions_trend', 'Redemptions Trend'), ('tier_distribution', 'Loyalty Tier Distribution'), ('top_redemptions', 'Top Redemption Items'), ('engagement_rate', 'Client Engagement Rate'), ('points_balance', 'Total Points Balance'), ('conversion_rate', 'Points to Wallet Conversion')], help_text='Type of widget to display', max_length=50),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='redemption_request',
            field=models.ForeignKey(blank=True, help_text='Associated redemption request if this is a redemption transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty_management.redemptionrequest'),
        ),
        migrations.AlterField(
            model_name='redemptionitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Available stock (None = unlimited)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientbadge',
            unique_together={('client', 'badge_name', 'website')},
        ),
    ]
