# Generated by Django 5.0.14 on 2025-10-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0001_initial'),
        ('discounts', '0001_initial'),
        ('order_payments_management', '0001_initial'),
        ('orders', '0001_initial'),
        ('special_orders', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_payments', to='websites.website'),
        ),
        migrations.AddField(
            model_name='classbundlepurchase',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bundles_payments', to='class_management.classbundle'),
        ),
        migrations.AddField(
            model_name='classbundlepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='failedpayment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='failedpayment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_order_payments', to='websites.website'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_payments', to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='websites.website'),
        ),
        migrations.AddField(
            model_name='failedpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_payments', to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_dispute', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='order_payments_management.invoice'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_log', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_notification', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='order_payments_management.invoice'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='order_payments_management.paymentrecord'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='order_payments_management.paymentrecord'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='order_payments_management.paymentrecord'),
        ),
        migrations.AddField(
            model_name='classbundlepurchase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_purchase', to='order_payments_management.paymentrecord'),
        ),
        migrations.AddField(
            model_name='paymentremindersettings',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin who last updated the settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminder_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentremindersettings',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_reminders', to='websites.website'),
        ),
        migrations.AddField(
            model_name='paymentsupportingdocument',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='order_payments_management.invoice'),
        ),
        migrations.AddField(
            model_name='paymentsupportingdocument',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof_uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptdeliverylog',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='order_payments_management.paymentreceipt'),
        ),
        migrations.AddField(
            model_name='refund',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_refund', to='websites.website'),
        ),
        migrations.AddField(
            model_name='requestpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='requestpayment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests_order', to='websites.website'),
        ),
        migrations.AddField(
            model_name='specialorderpayment',
            name='special_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_for_special_orders', to='special_orders.specialorder'),
        ),
        migrations.AddField(
            model_name='specialorderpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='splitpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_payments', to='order_payments_management.orderpayment'),
        ),
        migrations.AddField(
            model_name='splitpayment',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_order_payments', to='websites.website'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
