# Generated by Django 5.0.14 on 2025-11-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_payments_management', '0005_discountusage_and_more'),
    ]

    operations = [
    ]
