# Generated by Django 5.0.14 on 2025-11-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payments_management', '0010_discountusage_alter_invoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('succeeded', 'Succeeded'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('standard', 'Standard Order'), ('predefined_special', 'Predefined Special Order'), ('estimated_special', 'Estimated Special Order'), ('special_installment', 'Special Order Installment'), ('class_payment', 'Class Payment'), ('wallet_loading', 'Wallet Loading/Top-up'), ('tip', 'Tip Payment'), ('invoice', 'Standalone Invoice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('succeeded', 'Succeeded'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('under_review', 'Under Review')], default='pending', help_text='Current payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.CharField(choices=[('standard', 'Standard Order'), ('predefined_special', 'Predefined Special Order'), ('estimated_special', 'Estimated Special Order'), ('special_installment', 'Special Order Installment'), ('class_payment', 'Class Payment'), ('wallet_loading', 'Wallet Loading/Top-up'), ('tip', 'Tip Payment'), ('invoice', 'Standalone Invoice')], help_text='The payment being made', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('succeeded', 'Succeeded'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('under_review', 'Under Review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_management_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='order_payments_management.orderpayment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payment_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialorderpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('succeeded', 'Succeeded'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('under_review', 'Under Review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('succeeded', 'Succeeded'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('under_review', 'Under Review')], max_length=20),
        ),
    ]
