# Generated by Django 5.0.14 on 2026-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payments_management', '0012_merge_20260106_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_payment_link',
            field=models.URLField(blank=True, help_text='Optional custom payment link (overrides default generated link if set)', max_length=500, null=True),
        ),
    ]
