# Generated by Django 5.2.2 on 2026-06-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_fe_website_bbedf9_idx',
            old_name='feedback_re_website_status_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_fe_website_0704e6_idx',
            old_name='feedback_re_surface_status_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_fe_request_2163a2_idx',
            old_name='feedback_re_requester_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_fe_status_686ac9_idx',
            old_name='feedback_re_status_category_idx',
        ),
    ]
